### ISSUE TITLE
handleSnapshotRequest reason sometimes passed in as "undefined"

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#1006]
### Analysis

The object passed into handleSnapshotRequest detailed the height, width and reason for the snapshot sometimes has the reason as undefined. Example below:

{ height: 720, width: 1280, reason: undefined }
{ height: 720, width: 1280, reason: 0 }
{ height: 720, width: 1280, reason: 0 }
{ height: 720, width: 1280, reason: undefined }
{ height: 720, width: 1280, reason: 0 }
{ height: 720, width: 1280, reason: 0 }
{ height: 720, width: 1280, reason: undefined }
{ height: 720, width: 1280, reason: 0 }
{ height: 720, width: 1280, reason: undefined }
{ height: 720, width: 1280, reason: 0 }
{ height: 720, width: 1280, reason: undefined }
{ height: 720, width: 1280, reason: 0 }

### Expected Behavior

handleSnapshotRequest object should not have an undefined value

### Steps To Reproduce

....

### Logs

```markdown
....
```

### Configuration

```json
...
```

### Environment

- OS:
- Software: HAP 0.11.1
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by Supereg** [comment]
This is expected as this field is optional as the Home Hub will not always provide the value. HAP-NodeJS just forwards what the HomeKit client sends.
