### ISSUE TITLE
`updateCharacteristic` won't work after `Client connection closed`

### ISSUE THREAD

**Issue by kovapatrik** [homebridge/HAP-NodeJS#1031]
### Current Situation

I have the following plugin to control BlueAir Air Purifiers: https://github.com/kovapatrik/homebridge-blueair-purifier/tree/develop

Controlling devices is based on a cloud API, so it's not local communication. The problem is that if I try to turn on or off the device as soon as I open the Home app, it works, but if I wait a short time, then it simply won't respond (like when try to turn it on, it will stay in `Turning on...` state and it will never be `On`).

I've enabled HAP debug mode: after I get the `Client connection closed` in the logs, I experience the issue I just described. Before that, it works as it's expected. I don't know if this is a bug or not, so I raised it as a question.

### Logs

```markdown
I've attached the log file (I've commented on what happens when, and also it's logged out by the plugin when the `Active` state is accessed or set) and a screen recording of the Home app. (when I'm doing circles with the cursor in the recording, I'm just waiting for the disconnect to happen)
```

### Configuration

```json
-
```

### Environment

- OS: Ubuntu Jammy Jellyfish (22.04.3 LTS) - RPi OS Lite
- Software: Homebridge in Docker (homebridge/homebridge:latest, 1.8.0)
- Node: v18.19.0
- npm: 10.2.3

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

https://github.com/homebridge/HAP-NodeJS/assets/44952801/f0fa1bac-9db7-483e-afbd-53a04a6dbf9d

[log.txt](https://github.com/homebridge/HAP-NodeJS/files/15204900/log.txt)

**Comment by NorthernMan54** [comment]
After looking at your logs and video, and am wondering if this behaviour is triggered by your lack of a home hub.  Or it is something from your device

If you look at the logs, the home app, registers your fan for events ( 2024-05-03T20:20:19.289Z ), which sets up a constant socket connection between the Home app and HAP-NodeJS, then at ( 2024-05-03T20:20:32.209Z ) the home app closes the connection......

Is your iOS device running a beta version or something

**Comment by kovapatrik** [comment]
I can try with a Homepod, my main home has one attached, I've just used another home for developing plugins.

I'm running stable macOS on my MacBook and stable iOS on my iPhone.

**Comment by kovapatrik** [comment]
I also had an idea that maybe the `onGet` method gets called after the reconnect so the Home app receives the original value first, not the updated one thus it's stuck on `Turning on...` but I'm not sure how this is handled.

**Comment by NorthernMan54** [comment]
If your using updateCharateristic to update device state no need to use the onGet method.

**Comment by kovapatrik** [comment]
Adding the accessory to the Home where I have a Homepod indeed worked, but why is this necessary or how can I change the code for this to not happen if someone doesn't have a home hub setup?

**Comment by kovapatrik** [comment]
Or is it common for cloud API based plugins to work like this?

**Comment by NorthernMan54** [comment]
The cloud API for your device isn't part of this, but it is a behaviour of the Apple HomeKit environment.  I would assume that almost 100% of HomeKit users have a home hub, and it is an exception where people don't.

**Comment by kovapatrik** [comment]
Ah, yeah, you are right.

I presume the official Homekit devices are using local APIs in all cases, so the protocol is not prepared to have a delay when getting the state of the device (like waiting for the answer of the cloud API).

Thanks for the help!

**Comment by NorthernMan54** [comment]
In this scenario the local interface is between the HomeApp / Home Hub and Hap-NodeJS, and the cloud API to the device doesn't come into the equation.

Good luck with your plugin

**Comment by kovapatrik** [comment]
So if I understand correctly, the problem is not with the cloud API but with the HomeKit Air Purifier service itself. Or did I misunderstand it?

**Comment by NorthernMan54** [comment]
As adding a home hub to your setup resolved it, it appears to be with HomeKit
