### ISSUE TITLE
lib v1.x.x adding any accessory HomeKit Error

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#1069]
### Analysis

I had migrated my code to use the hap-nodes lib and not rely on core.js. Things have been working fine up until v1.x.x of the library released. When adding ANY accessory, Home app reports "Accessory is out of compliance"

### Expected Behavior

Things should remain the same between library versions

### Steps To Reproduce

Just raising first to see any idea/suggestions on direct to investigate 

### Logs

```markdown
..
```

### Configuration

```json
..
```

### Environment

- OS: Ubuntu 
- Software:
- Node: 18.19.1
- npm: 9.0.2

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
Can you share your GitHub repo, and a method of reproducing the error?  Am thinking your accessory is missing something or composed of services in a combination HomeKit doesn’t support.

**Comment by n0rt0nthec4t** [comment]
The weird part is I can install v0.12.2 of hap-nodes and things work perfectly fine.. install v1.1.0 and no working

Repo https://github.com/n0rt0nthec4t/Nest_accfactory

**Comment by NorthernMan54** [comment]
Well cloned it, ran npm install, then

node Nest_accfactory.js

/Users/sgracey/Code/Nest_accfactory/nexusstreamer.js:12
var protoBuf = require("pbf");  // Proto buffer
               ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/sgracey/Code/Nest_accfactory/node_modules/pbf/index.js from /Users/sgracey/Code/Nest_accfactory/nexusstreamer.js not supported.
Instead change the require of index.js in /Users/sgracey/Code/Nest_accfactory/nexusstreamer.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/sgracey/Code/Nest_accfactory/nexusstreamer.js:12:16)
Pinkman:Nest_accfactory sgracey$ node -v
v20.12.2

Also as I don't have a Nest device, I won't be able to configure one.

My working theory on what is happening, is that with HAP-NodeJS 1.0, we removed a bunch of deprecated service and characteristic HomeKit definitions, and your code is attempting to use one and it is causing the accessory to not be constructed correctly.

I did a quick scan, and spotted this one, which was removed -         this.batteryService = this.HomeKitAccessory.addService(HAP.Service.BatteryService, "", 1);

Try removing this and trying again

**Comment by n0rt0nthec4t** [comment]
Yep, I picked those errors up (the pdf library went ES only, so have to peg it back a 3.3.0). Didn't realised BatteryServcie got depreciated, but not big. Hmm.. not sure then

Also notice that you dont use .setPrimaryService against the accessory

Used to be eg: this.HomeKitAccessory.setPrimaryService(this.temperatureService);

Now need todo this this.temperatureService.setPrimaryService();

Ok, might have something todo with my custom Eve characteristics and services created.. need to look

current sources

https://github.com/n0rt0nthec4t/Nest_accfactory/tree/alpha

**Comment by donavanbecker** [comment]
`BatteryService` was replaced by `Battery` a while ago.

**Comment by hjdhjd** [comment]
> `BatteryService` was replaced by `Battery` a while ago.

Like several years. 😄

My recommendations, for what they’re worth @n0rt0nthec4t:

1. Make sure you’re not using long-deprecated services/methods/values (BatteryService is one but there are a few others out there).
2. Future-proofing: use ES Modules. We’re moving in this direction more and more as we strive to continue to modernize and evolve HAP-NodeJS capabilities.
3. Stylistic: shift away from callbacks and toward async/await and Promises when-needed.
4. Requirements: Node 18 is the minimum supported version of HAP-NodeJS (I noticed your package.json supports Node 17) - one of the more subtle changes in HAP-NodeJS is a requirement of Node 18 or beyond. The reason for this is primarily because Unicode support in Node 18 is needed for a more complete HAP implementation.

**Comment by n0rt0nthec4t** [comment]
Ok, found what caused my issue. Narrowed down the the custom characteristics and the permissions. Previously had defined the perms as "HAP.Characteristic.Perms.WRITE" or "HAP.Characteristic.Perms.READ". I had thought fixing to "HAP.Perms.WRITE" or "HAP.Perms.READ" was correct.. 

Appears WRITE and READ depreciated and use  PAIRED_WRITE and PAIRED_READ now

**Comment by n0rt0nthec4t** [comment]
> 2. Future-proofing: use ES Modules. We’re moving in this direction more and more as we strive to continue to modernize and evolve HAP-NodeJS capabilities.
> 3. Stylistic: shift away from callbacks and toward async/await and Promises when-needed.
> 4. Requirements: Node 18 is the minimum supported version of HAP-NodeJS (I noticed your package.json supports Node 17) - one of the more subtle changes in HAP-NodeJS is a requirement of Node 18 or beyond. The reason for this is primarily because Unicode support in Node 18 is needed for a more complete HAP implementation.

@hjdhjd Thanks for the tips. Guess I need to learn about ES modules :-D and look what todo with callbacks. Yep, noted the change to use node >= 18 and updated package.json for it. Hope we leave it at 18 atm due to issues when building on docker nodejs for any version above 18 on armv7 etc

**Comment by hjdhjd** [comment]
> > 2. Future-proofing: use ES Modules. We’re moving in this direction more and more as we strive to continue to modernize and evolve HAP-NodeJS capabilities.
> > 3. Stylistic: shift away from callbacks and toward async/await and Promises when-needed.
> > 4. Requirements: Node 18 is the minimum supported version of HAP-NodeJS (I noticed your package.json supports Node 17) - one of the more subtle changes in HAP-NodeJS is a requirement of Node 18 or beyond. The reason for this is primarily because Unicode support in Node 18 is needed for a more complete HAP implementation.
> 
> @hjdhjd Thanks for the tips. Guess I need to learn about ES modules :-D and look what todo with callbacks. Yep, noted the change to use node >= 18 and updated package.json for it. Hope we leave it at 18 atm due to issues when building on docker nodejs for any version above 18 on armv7 etc

Our aim is always to support the LTS versions of Node…Node 18 will be good roughly through mid-2025 (you can check here: https://nodejs.org/en/about/previous-releases).

async/await/Promises…lots of good/quick tutorials out there too (TypeScript as well). It’s a great adventure!
