### ISSUE TITLE
Don't understand why I can't use a colon ( : ) in a ConfiguredName with Homebridge 2.0

### ISSUE THREAD

**Issue by dacarson** [homebridge/HAP-NodeJS#1079]
### Current Situation

I am migrating a plugin to HomeBridge 2.0 and I now get a warnings for ConfigureName title.  I am using Configured to express unsupported characteristics in the Home app, to allow automations.
With the weather-plus plugin, you can set up automations to trigger under certain conditions, a typical one is windspeed. If the windspeed is above a configured threshold, the occupancy sensor turns on. The current value of the windspeed is provided as the name of the sensor, an Occupancy Sensor to be exact. It is in the form "Wind speed: 0 mph". 
It seems that having a colon in the middle of a string is no longer allowed, it is not alphanumeric. But I don't understand why a colon can't be included in the string.
Some sites say alphanumeric can sometimes include @ # * &, some other sites say @ (“at” sign), $ (dollar sign), # (pound sign). 
If I can't use a colon, are there any special characters I can use as a delimiter?

### Logs

```markdown
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Wind Speed: 2.15 mph'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Wind Dir: NW'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('UV Index: null'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Air Pressure: 1014.49 hPa'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends wit
```

### Configuration

```json
{
    "units": "us",
    "interval": 1,
    "stations": [
        {
            "nameNow": "KPTPeppertree",
            "service": "weatherunderground",
            "key": "xx",
            "stationId": "KTNKINGS343",
            "language": "en",
            "compatibility": "home",
            "conditionCategory": "simple",
            "now": true,
            "extraHumidity": false,
            "hidden": [
                "Air Pressure",
                "Cloud Cover",
                "Condition",
                "Condition Category",
                "Dew Point",
                "Forecast Day",
                "Humidity",
                "Observation Station",
                "Observation Time",
                "Ozone",
                "Rain",
                "Rain 1h",
                "Rain Day",
                "Rain Chance",
                "Snow",
                "Solar Radiation",
                "Sunrise Time",
                "Sunset Time",
                "Temperature Min",
                "Temperature Apparent",
                "UV Index",
                "Visibility",
                "Wind Direction",
                "Wind Speed Max"
            ],
            "thresholdWindSpeed": 5
        }
    ],
    "platform": "WeatherPlus"
}
```

### Environment

- OS: Debian GNU/Linux Bookworm (12)
- Software: v2.0.0-beta.23
- Node: v20.18.0
- npm: 10.8.2

### Process Supervisor

hb-service

### Additional Context

Plugin is hosted here: https://github.com/naofireblade/homebridge-weather-plus

**Comment by hjdhjd** [comment]
Asked and answered several times, but for posterity:

https://developer.apple.com/design/human-interface-guidelines/homekit#Help-people-choose-useful-names

> Check that the names people provide follow HomeKit naming rules. If your app lets people rename services, make sure that the new names follow the rules. (The system-provided setup flow automatically checks the original names.) If people enter a name that breaks one or more rules, briefly explain the problem and suggest some alternative names that work. Here are the rules:
> * Use only alphanumeric, space, and apostrophe characters.
> * Start and end with an alphabetic or numeric character.
> * Don’t include emojis.

Don't blame us, we're just the plumbers. 😄

**Comment by dacarson** [comment]
Do we know what exactly is considered "alphanumeric"? They say in the second bullet that it must start and end with alphabetic or numeric character, rather than saying it must start and end with an alphanumeric character. Which implies to me that "alphanumeric" means more than just alphabetic and numeric characters.

**Comment by hjdhjd** [comment]
It's not, and alphanumeric means exactly what it says. The ~second~ first bullet clearly and unequivocally sates what the valid domain of characters are.

As much as you (or I!) may not want it to be, your feedback here is better directed to Apple. You're welcome to file a radar with Apple and request clarification or a change to their rules. We are just abiding by them. I'm not thrilled with them either. 😄

Closing this out as the question has been answered.

Added for reference: [Apple's definition of alphanumeric](https://developer.apple.com/documentation/foundation/characterset/1779632-alphanumerics)

>Returns a character set containing the characters in Unicode General Categories L*, M*, and N*.

**Comment by dacarson** [comment]
I tried using the character from the Lm category that falls under Unicode General Category L*, the (ː) (Modifier Letter Triangular Colon), and I am still getting an error. From what I can tell it is considered a part of the Apple's definition of alphanumeric.

**Comment by hjdhjd** [comment]
> I tried using the character from the Lm category that falls under Unicode General Category L*, the (ː) (Modifier Letter Triangular Colon), and I am still getting an error. From what I can tell it is considered a part of the Apple's definition of alphanumeric.

Great catch. Will ensure it more fully reflects the above cohesively in an upcoming update. I think that's a miss on my part!

**Comment by dacarson** [comment]
Thanks! FWIW, i was also seeing if I could use roman numerals, from Nl category that falls under N* and they also failed. 
I am using this site for reference: https://www.unicode.org/Public/UNIDATA/UnicodeData.txt 
It has the characters and their categories.
