### ISSUE TITLE
Prefix Debuggers

### ISSUE THREAD

**Issue by desvdp** [homebridge/HAP-NodeJS#126]
Regarding the use of the "debug" library: Would it be possible to prefix the debugger in such the messages can be easily filtered (very handy when embedding this library) 
###### lib/HAPServer.js :1

var debug = require('debug')('HAPNodeJS:HAPServer');
###### lib/util/eventedhttp.js :1

var debug = require('debug')('HAPNodeJS:EventedHTTPServer');
###### lib/Accessory.js :1

var debug = require('debug')('HAPNodeJS:Accessory');

small change no need for pull requests I guess ...
##### Reference:

https://www.npmjs.com/package/debug#conventions

> ##### Conventions
> 
> If you're using this in one or more of your libraries, you should use the name of your library so that developers may toggle debugging as desired without guessing names. If you have more than one debuggers you should prefix them with your library name and use ":" to separate features. For example  "bodyParser" from Connect would then be "connect:bodyParser".

Thanks.

**Comment by Supereg** [comment]
This change was incorporated into the latest beta version and be part of the future 0.7.0 release.
