### ISSUE TITLE
Ports 

### ISSUE THREAD

**Issue by volschin** [homebridge/HAP-NodeJS#131]
In eventedhttp.js a port is hardcoded, that prevents to run more than one instance of homebridge on a machine.

``` javascript
var PortAllocator = {
  initialPort: 54826, // first port to use; subsequent ports will increment from this
  portsInUse: {}, // sparse array of ports in use
```

Is there a technical reason to have this as fixed port or could it be made configurable?

My intention is to run a more productive and a test homebridge on one machine.
I found that problems with a bridge device need to remove all other devices or reset of complete homekit necessary. Having more than 50 devices this makes me not lucky.

**Comment by nriley** [comment]
Even if there is only one copy of HAP-NodeJS running it is possible for one of the ports to already be in use (in my case it is VMware NAT).  eventedhttp.js should check if the port is in use by another process prior to trying to listen.

**Comment by snowdd1** [comment]
I was thinking of having the eventedhttpserver check for the availbility of te port, as in the node server documentation at https://nodejs.org/docs/latest/api/net.html#net_server_listen_port_hostname_backlog_callback

**Comment by snowdd1** [comment]
@nriley : I think your approach doesn't do much better: "A port value of zero will assign a random port." is said in the documentation. I think that random is only slightly better than incremental without checking for the error element. I'll try a pull request for @KhaosT  based on the documentation example linked in mylast post

**Comment by nriley** [comment]
Good point, I did not realize the OS does not check if the port was in use.  What a mess.  http://stackoverflow.com/questions/9901043/

**Comment by snowdd1** [comment]
I wrecked my local git clone so I cannot produce a pull request right now. Yo might want to try the following:

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/util/eventedhttp.js#L125 :
````JavaScript
  this._httpServer.listen(this._httpPort);
  this._httpServer.on('error'), this._onHttpServerError.bind(this);
````

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/util/eventedhttp.js#L193 insert:
````JavaScript
EventedHTTPServerConnection.prototype._onHttpServerError = function(e){
	  // we got an error during opening of the port?
	  if (e.code === 'EADDRINUSE') {
		  debug("Port [%s] in use, trying next port", this._httpPort);
		  this._httpPort = PortAllocator.allocatePort();
		  //retry: 
		  this._httpServer.listen(this._httpPort);
	  }
}
````
It is supposed to be iterative until a free port has been found, but might take to Long with the callbacks. I do not have a testing Scenario right now.

**Comment by justme-1968** [comment]
i don't know about node but in 'conventional' socket programming using 0 as the port in bind means that you will get a random but free port. so this is the right way to go.

**Comment by nriley** [comment]
OK, I revised my pull request to actually check for ports in use.  I still don't use the PortAllocator given it just duplicates the functionality of letting the OS allocate the port (as @justme-1968 mentions).  I tested it by having it try an already-in-use port first, then port 0 and it seemed to work fine:

```
  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer [fe80::18f8:5463:3464:872a] New connection from client +1s
  EventedHTTPServer [fe80::18f8:5463:3464:872a] HTTP server error: listen EADDRINUSE :::51826 +1ms
  EventedHTTPServer [fe80::18f8:5463:3464:872a] HTTP server listening on port 53236 +0ms
  EventedHTTPServer [::ffff:192.168.0.9] New connection from client +4ms
  EventedHTTPServer [::ffff:192.168.0.9] HTTP server error: listen EADDRINUSE :::51826 +0ms
  EventedHTTPServer [::ffff:192.168.0.9] HTTP server listening on port 53238 +0ms
```
