### ISSUE TITLE
Error: dns service error: unknown

### ISSUE THREAD

**Issue by ghost** [homebridge/HAP-NodeJS#132]
Hi,

I try to run node Core.js and i got dns service error. What to do?

![untitled](https://cloud.githubusercontent.com/assets/10205046/9928154/c6359c92-5d2c-11e5-801e-07dc55b0fa5e.png)

**Comment by mvahanen** [comment]
I found this: https://github.com/KhaosT/HAP-NodeJS/issues/47
and there is comment:
"@jeffhuys can you try to replace Advertiser.js with contents from here? https://gist.github.com/KhaosT/d1f617230f619bf64e71"

I'll do that but now i got new error..

marbo@ubuntuu:~/HAP-NodeJS$ node Core.js 
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: TemperatureSensor_accessory.js
Parsing accessory: Thermostat_accessory.js
Err1
[TypeError: argument 8 must be an integer (port)]
Err1
[TypeError: argument 8 must be an integer (port)]
Err1
[TypeError: argument 8 must be an integer (port)]
Err1
[TypeError: argument 8 must be an integer (port)]
Err1
[TypeError: argument 8 must be an integer (port)]
Err1
[TypeError: argument 8 must be an integer (port)]
Err2
[TypeError: Cannot read property 'start' of undefined]
Err2
[TypeError: Cannot read property 'start' of undefined]
Err2
[TypeError: Cannot read property 'start' of undefined]
Err2
[TypeError: Cannot read property 'start' of undefined]
Err2
[TypeError: Cannot read property 'start' of undefined]
Err2
[TypeError: Cannot read property 'start' of undefined]

**Comment by kstaniek** [comment]
I'm facing the 'Error: dns service error: unknown' issue. Any hint how to solve it?

Here is my Docker file:

```
FROM nodered/node-red-docker

USER root
RUN apt-get update && \
    apt-get install -y \
    apt-utils \
    python \
    build-essential \
    make \
    g++ \
    libavahi-compat-libdnssd-dev \
    libnss-mdns

RUN sed -i "s/#enable-dbus=yes/enable-dbus=no/g" /etc/avahi/avahi-daemon.conf
RUN service avahi-daemon start

RUN npm install mdns
RUN npm install node-red-contrib-homekit

#CMD ["npm", "start", "--", "--userDir", "/data"]
```

**Comment by chabad360** [comment]
my error got rooted down to `lib/util/eventedhttp.js:65:10`

**Comment by Supereg** [comment]
The error referenced refers to a library which is not used anymore. So closing this issue.
