### ISSUE TITLE
allow one service without a subtype if using multiple identical services

### ISSUE THREAD

**Issue by justme-1968** [homebridge/HAP-NodeJS#133]
the check for existing subtypes in Accessory.prototype.addService will fail if the first service is added without a subtype and the second with a subtype as existing.subtype.toString() will fail.

i think it would be nice to be able to add the first service without a subtype as at this point it might not be know if there are more services added later.

existing.subtype should probably be a default like empty string if it is not defined.

not sure if this was clear ...

**Comment by snowdd1** [comment]
You can just ALWAYS put the distinctive name as the subtype to be sure. Subtypes, as I understood, never do harm to anything, as long as they are unique.
