### ISSUE TITLE
Help , To add Accessory

### ISSUE THREAD

**Issue by massinegro204** [homebridge/HAP-NodeJS#139]
I read in this guide
https://github.com/KhaosT/HAP-NodeJS/wiki/Adding-Multiple-Accessories
but if I try to add one, spite change the username , this is not on the list
But the username has a specific procedure to be able to assign ?
I 'm trying to dublicate Light_accessory.js but i have this problems . I would like a little help , thanks

**Comment by KhaosT** [comment]
What's the problem you encountered when duplicates Light_accessory.js? There are several changes to this project in the past few months and the wiki may no longer valid...

**Comment by kajaba** [comment]
I have also a problem duplicating light accessory. I change username but after node Core.js I got this error:

Error: dns service error: name conflict
    at new Advertisement (/home/pi/hap/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/home/pi/hap/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/home/pi/hap/lib/Advertiser.js:43:30)
    at Accessory._onListening (/home/pi/hap/lib/Accessory.js:352:20)

**Comment by Rollonat** [comment]
i got the same error

**Comment by CorentinCo** [comment]
I got the same error too, I duplicate an accessory but now I get this error.

**Comment by jamesabruce** [comment]
I managed to fix this by also making this line unique:

```var light = exports.accessory = new Accessory('Light', lightUUID);```

for example:

```var light = exports.accessory = new Accessory('Office Light', lightUUID);```

(in addition to the object name, the UUID, and the MAC address/username, though those might not all be neccessary)
