### ISSUE TITLE
Window/Window Covering Profile issue regarding position state

### ISSUE THREAD

**Issue by christofferbrask** [homebridge/HAP-NodeJS#142]
I have succesfully made a Window + Window Covering accessory. I can add the devices to eve app, use the functionality, the problem I have is the "Position State", which always says closing (the initial value is 0) / (1 indicates Opening and 2 indicates Stopped).

But why doesn't Position State change as I change the Target positon to xx %? 

I thought it might be something with supportevents, I have set as true but I didn't change anything. 

Do I need to add something more in the Target positon/Position State brackets to change the value in Position State when setting a Target positon?

**Comment by cflurin** [comment]
@supermax45 You have to handle it yourself. You might have a look [here](https://github.com/cflurin/homebridge-shims/blob/master/FhemWindowCovering.js)

But  I really don't see the benefit of this characteristic.

**Comment by peadard** [comment]
@supermax45 would you possibly be able to share your code? I too am trying to create a window covering device but Siri has never co-operated "sorry I could not find any devices this time" etc. I could also add position state to mine to test . Thanks

**Comment by supermax45** [comment]
https://www.dropbox.com/s/elr73m8jwkuty2q/Window_accessory.js?dl=0
https://www.dropbox.com/s/w6vkmams58sdess/WindowCovering_accessory.js?dl=0

Maybe it's easier to help me now. 

@cflurin i have tried your link but got an error at " this.Characteristic.CurrentPosition.setProps( { minStep: 5 });" 

Is there no way to implement it in my application?

**Comment by cflurin** [comment]
@supermax45 I'm not sure I unterstand you. You asked for "Position State"

Using the new API - which I recomned you - you have to define a service:

```javascript
...
function FhemWindowCovering(log, config) {
...
  this.Characteristic = {};
  this.currentValue = {};
...
FhemWindowCovering.prototype = {
...
  getServices: function() {
...
    var FhemWindowCoveringService = new Service.WindowCovering();
...
    this.Characteristic.PositionState = FhemWindowCoveringService
      .getCharacteristic(Characteristic.PositionState)
      .on('get', this.getPositionState.bind(this));
      
    // The value property of PositionState must be one of the following:
    // Characteristic.PositionState.DECREASING = 0;
    // Characteristic.PositionState.INCREASING = 1;
    // Characteristic.PositionState.STOPPED = 2;
    this.currentValue.PositionState = Characteristic.PositionState.STOPPED;
```

and define:
```javascript
  getPositionState: function(callback) {
...
```
Take a look at the FhemWindowCovering.js for more details.

**Comment by supermax45** [comment]
And would using the new API be any better? 

Are you saying that it's impossible to change position state in my application if target position value is changed?

**Comment by cflurin** [comment]
Sure you can change the position state in your application, e.g. setting the target position the motor will start in one direction (set DECREASING or INCREASING) , at the end you can set STOPPED. As I said I didn't implement this because I don't see any advantage.

I only use the new homebridge API.

**Comment by supermax45** [comment]
Can you give a example of how to implement it in the window example? :)
https://www.dropbox.com/s/elr73m8jwkuty2q/Window_accessory.js?dl=0
Initial value is set to 2 = Stopped
The ideal scenario is tapping in eve app, setting a target value and see that position state changes from stopped to opening and maybe after 1 sec go back to stopped. 

Decreasing target position change stopped to closing and back to stopped.

I am a bit confused about what exactly the execute("Window", "Current Position", value); etc.

Sry for being a noob, but I have never worked javascript/json before.

**Comment by cflurin** [comment]
Just now I'm quite busy. You can start using the new API with a simple shims like
FakeOutlet.js on my repo, you also find the corresponding config-fake.json.
You should also install the latest homebridge. If you are using a RPi, take a look [here](https://github.com/cflurin/homebridge-shims/wiki/Minimalist-Homebridge-on-a-Raspberry-Pi)

**Comment by supermax45** [comment]
Your FakeOutlet doesn't work. I have both tried on my current homebridge folder I have used succesfully with Hyperion TV backlight, but then trying to add Fake-Homebridge it never give me a chance to type password, same happens in the newest version of Homebridge.

**Comment by cflurin** [comment]
Hmm, It works perfectly with EVE :smile:

![fakeoutlet2](https://cloud.githubusercontent.com/assets/5056710/10241973/927e0020-68ed-11e5-8807-9349edfc2eb0.jpg)

**Comment by supermax45** [comment]
Do you know what could be wrong? I see the Fake Homebridge fine in Eve but after tapping it, it never ask for a setup code..

**Comment by cflurin** [comment]
Please don't post ```Your FakeOutlet doesn't work.``` It isn't really motivating me to help you. Well probably it's an issue with the repeating tests you've done.
Try to rename the username in config.json
from:
```javascript
        "username": "CC:22:3D:E3:CE:30",
```
to:
```javascript
        "username": "CC:22:3D:E3:CE:31",
```

and restart homebridge

**Comment by supermax45** [comment]
Already tried that..

**Comment by supermax45** [comment]
@cflurin sry for the "Your FakeOutlet doesn't work" i should had added "for me"

Im back to trying a new api for HAP-NODEjs following the examples lock, temperatur sensor and lightbulb.

Would you maybe look at my code and tell if it look's okay? It's just the most basic for now.

Sadly i can't the accesorry in console after running node Core.js :(

**Comment by Maxmudjon** [comment]
https://www.dropbox.com/s/sy6b30xihxuadkk/FakeWindow_accesory.js?dl=0
can not download

**Comment by lisergio** [comment]
can you upload the accessory again please?

**Comment by lisergio** [comment]
thanks

**Comment by n0rt0nthec4t** [comment]
Could you share you window covering accessory again?

**Comment by lisergio** [comment]
look at my example, it helps you anyway
https://lisergio.wordpress.com/2017/09/18/accesorio-persiana-compatible-con-homekit/
