### ISSUE TITLE
Smartlock lock / unlocked / open

### ISSUE THREAD

**Issue by sd8rdb** [homebridge/HAP-NodeJS#149]
Hi,

for the lock accessoires, I can see UNSECURED (e.g. door is unlocked), SECURED (e.g. door is locked). But there there are models/doors available where you also can open the door. Means you have to use the key to enter the door. 

Means the door can also not be entered while the lock is in unsecured mode. 

So a another command is necessary: "open"

How can this be implemented? Is it available with Homekit?

BR

**Comment by KhaosT** [comment]
There is a door service (https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1454)

**Comment by justme-1968** [comment]
you can add a TargetDoorState to the LockMechanism service. from get just return TargetDoorState.CLOSED and from the set you can send an open to the smart lock and create a timeout to push TargetDoorState.CLOSED back to homekit after 500ms or so. this will result in the open button in eve always be pressable.
