### ISSUE TITLE
npm install error for openwrt mips cross compilation

### ISSUE THREAD

**Issue by venche** [homebridge/HAP-NodeJS#157]
Hi,

 I am porting HAP-NodeJs to opwrt mips

 every thing went well but while npm install its giving an error as follows

gyp: Undefined variable openssl_config_path in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-50-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /tmp/HAP-NodeJS_MIPS/node_modules/srp/node_modules/bignum
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

i got installed all the modules except srp inside node_modules,below is the list of modules got installed
curve25519  debug  ed25519  mdns  node-persist  simple-plist

I am new to nodejs iam not familiar with can any body help  me out

**Comment by venche** [comment]
sorry its openwrt mips

**Comment by KhaosT** [comment]
You need to install OpenSSL on the system first.

**Comment by venche** [comment]
Thank u for ur replay khaost ,

I installed openssl on my host system  & in cross compile environment.

if iam correct srp is dependent on bignum package where the  openssl_config_path is not defined in the binding.gyp for the mips architecture(this is cause of error is there any way to fix it).

if iam compiling srp for arm its working fine

**Comment by benwwchen** [comment]
@venche Did you solve the problem? How to fix it?
