### ISSUE TITLE
Light_accessory doesn't show up on iphone after a while

### ISSUE THREAD

**Issue by fredsco** [homebridge/HAP-NodeJS#164]
After a while my lights can't connect anymore, home kit won't see them. After restarting the pi the problem still occurs. example accessory like fans are always shown. What I have to do get the lights back is remove HAP-NodeJS and install it again but again after 3 hours the problem comes back :-1: 

What I find strange is that this problem is only occurring with lights.

**Comment by KhaosT** [comment]
Given is problem only occurs after a while and only with specific accessory, are you sure your implementation of light accessory always returns valid values for characteristics? HomeKit will block/remove the accessory if it returns something out of the compliance.
