### ISSUE TITLE
Returning the current state of device/appliance

### ISSUE THREAD

**Issue by shawnlobo96** [homebridge/HAP-NodeJS#175]
How can I return the current state of the device say garage door such that when i ask siri it returns the current state! the garage door can return its state with the help of magnetic switches.  Would appreciate if someone could guide me with the python code (if needed). 

I'm using a raspberry pi 2.

**Comment by KhaosT** [comment]
I assume your garage door uses HTTP API, if so, you can setup a timer to periodically query the state of the garage door and invoke Characteristic.setValue() with the actual garage door state.

**Comment by anal-probe** [comment]
I have the same issue. Try to invoke Characteristic.setValue(), but this fires event 'set' which send data to device. is there any way to avoid firing 'set'?

**Comment by cflurin** [comment]
@anal-probe: you can set the context: 
```
setValue(value, null, context);
```
context can be a string like "from whatever". Add:
```
if (typeof(context) !== "from whatever")
```
in your set function. Take a look [here](https://github.com/cflurin/homebridge-punt) for a practical use.

**Comment by anal-probe** [comment]
Thanks, this works
