### ISSUE TITLE
HAP-Nodejs on openwrt

### ISSUE THREAD

**Issue by venche** [homebridge/HAP-NodeJS#177]
Hi

I trying to port HAP-Nodejs to the openwrt platform but not succed at.I am not able to pair the accessory as the HAP-Nodejs is crashing can somebody help me out what is going on attachaing the error for reference

Platfrom:openwrt(mips)
![screenshot from 2015-12-09 18 13 55](https://cloud.githubusercontent.com/assets/15050374/11685907/9bcc9dae-9ea2-11e5-9780-71951a8fb8fa.png)

**Comment by KhaosT** [comment]
it looks you're close to finish the port. If possible, can you add some code above [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/HAPServer.js#L362) to print out the values of outputKey, clientUsername and clientLTPK?

**Comment by venche** [comment]
here is the screen shot after adding logs, but strangely its not the same place all the times it failing.attaching all those screen shots for reference.Is there any endian dependency for HAP nodejs, my system is bigedian is it creating problem?


![screenshot from 2015-12-14 12 09 07](https://cloud.githubusercontent.com/assets/15050374/11774581/920131a0-a25c-11e5-969e-d004bed4c7a8.png)
![screenshot from 2015-12-14 11 50 17](https://cloud.githubusercontent.com/assets/15050374/11774592/9cf72d8a-a25c-11e5-8f05-b024d1ce364e.png)
![screenshot from 2015-12-14 11 41 35](https://cloud.githubusercontent.com/assets/15050374/11774596/a77fd6d0-a25c-11e5-9e94-fae0b50cb780.png)

**Comment by KhaosT** [comment]
HomeKit uses little endian and in the process of writing this I didn't consider the case of big endian (although it should work). I noticed pair-setup succeed without issue so the encryption part should be working fine... Can you print out ``clientLTPK`` at [here](https://github.com/KhaosT/HAP-NodeJS/blob/c2c03deff9c0048a9362ceb8852d3dca9ffc188d/lib/HAPServer.js#L362) and ``clientPublicKey`` at [here](https://github.com/KhaosT/HAP-NodeJS/blob/c2c03deff9c0048a9362ceb8852d3dca9ffc188d/lib/HAPServer.js#L538) and see if it's the same?

**Comment by venche** [comment]
append the logs at  Client %s provided an invalid signature but not able to reproduce this message the below is the loginfo
![screenshot from 2015-12-14 15 47 13](https://cloud.githubusercontent.com/assets/15050374/11779622/71576e12-a282-11e5-9b13-67ba6aec6d53.png)

**Comment by benwwchen** [comment]
@venche Could you please help me with cross compiling the mdns dependency on mips openwrt? I cross compiled everything without errors with `npm --arch=mipsel install` but when I tried running it, it gives this error:
```
/mnt/sda1/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
          ^
Error: File not found
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/sda1/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
By the way, at the beginning I got `dns_sd.h/libdns_sd.so` missing errors when installing mdns, so I find them in `staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/root-ramips/usr/` and copy them to the `include` and `lib` folder in `staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/`. Then npm can install it without errors.
Should I install something else on the device itself or did I install mdns wrongly?

**Comment by benwwchen** [comment]
I finally cross compiled and got it running on my mipsel(little endien) machine. But it couldn't pair:
```
#DEBUG=* node BridgedCore.js
HAP-NodeJS starting...
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: TemperatureSensor_accessory.js
Parsing accessory: Thermostat_accessory.js
  Accessory [Node Bridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Node Bridge] Creating new IdentifierCache +47ms
  EventedHTTPServer Server listening on port 51826 +225ms
  EventedHTTPServer [192.168.1.205] New connection from client +2m
  EventedHTTPServer [192.168.1.205] HTTP server listening on port 58728 +7ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +89ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-setup +3ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair step 1/5 +28ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +203ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +17s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-setup +3ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair step 2/5 +11ms
  HAPServer [CC:22:3D:E3:CE:F6] Error while checking pincode: client did not use the same password +541ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +10ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +9s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-setup +2ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair step 1/5 +7ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +131ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +173ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-setup +2ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair step 2/5 +6ms
  HAPServer [CC:22:3D:E3:CE:F6] Error while checking pincode: client did not use the same password +639ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +4ms
```
When I cross compiled bignum, I added the `openssl_config_path` for `mipsel` in binding.gyp to `elf`/ `mipsel` / `mips`but none of them works.

Could you please tell me how to debug it?
