### ISSUE TITLE
Rediscovering devices after removing them in HMCatalog

### ISSUE THREAD

**Issue by j4k3** [homebridge/HAP-NodeJS#192]
First of all, sorry for asking this stupid question here that seems to be a HomeKit problem, not a HAP-NodeJS one, but I'm out of ideas what to do to solve it:

I've restarted Core.js after a bunch of edits on an accessory and it worked nicely after that. To refresh some readonly values, such as the device and manufacturer name, I deleted the accessory from my home, only to find out, that the device isn't listed under "Add devices". And sure enough, after I delete a device from the accessories list, I can never find again. Not even on other devices or the simulator. I'm sure this can't be as its intended to work, right?

What can I do to connect to the device again? Ive already tried deleting my HomeKit data, via the privacy settings but that doesn't help. The same devices are still missing from the list.
I also tried changing the devices identity by fiddling with the lightUUID and device name values, but that doesn't help either.

**edit**
_Okay, I just 'solved' the problem myself by flushing the content of the persist folder. So it actually is an issue with HAP-Nodejs, just to point that out. It seems that the cached data here prevents the device from being rediscovered again after it is deleted from the HomeKit data._

**Comment by ahnyerkeester** [comment]
Actually, this isn't a fault in HAP-NodeJS, this is how it is supposed to work. HomeKit only lets you add the device once. The correct method is to clear the persist folder.

Anyone know if you have to restart HAP-NodeJS once the folder is clear?
