### ISSUE TITLE
Fail on Waiting for callback(); in Characteristic.on('set') or ('get')

### ISSUE THREAD

**Issue by antonbrams** [homebridge/HAP-NodeJS#206]
Hi, Guys!

I have here some issue :) ive builded a TimeCapsule Object that control Netatalk and Mounted Disks a la TimeCapsule. If i try to get TimeCapsule state, my Homekit hangs on because my TimeCapsule needs a bit time to check, if it running. Or if i switch my TimeCapsule off, it needs time to unmount disk and get Netatalk down... Where can i set the longer timeout, that my Homekit will not crash?

```
Device
    .addService(Service.Switch, TimeCapsule.alias, TimeCapsule.alias)
    .getCharacteristic(Characteristic.On)
    .on('set', function(value, callback) {

        TimeCapsule.on('set', value, function () {
                console.log(TimeCapsule.alias +' is set to '+ (value? 'ON': 'OFF'));
                callback();
        });
    })
    .on('get', function(callback) {

        TimeCapsule.on('get', function (value) {
                console.log(TimeCapsule.alias +' is '+ (value? 'ON': 'OFF'));
                callback(null, value);
        });
    });
```

Thanks :)

**Comment by KhaosT** [comment]
@antonkluev How long are you talking about?

**Comment by antonkluev** [comment]
ca. 10 seconds... maybe more

**Comment by KhaosT** [comment]
@antonkluev HomeKit should allow up to 60s for accessory to handle a request and HomeKit should not crash when read request timeout. Where do you see it crashes?

**Comment by antonkluev** [comment]
for example here

    ```
.on('set', function(value, callback) {

        TimeCapsule.on('set', value, function () {
                console.log(TimeCapsule.alias +' is set to '+ (value? 'ON': 'OFF'));
                callback();
        });
    })
```

If i switch it on - my Harddrive will powered up -> accelerate -> mounted -> and start Netatalk. It takes ca. 10 - 30 seconds. But in this time my Homekit app shows no information about all accessories until i wait a long time or gonna restart HAP. But this "callback();" must block only this switcher, not the whole app ))

**Comment by KhaosT** [comment]
That's strange, does this happen in all HomeKit apps or just a specific one?

**Comment by antonkluev** [comment]
I think that it depends not on iphone app, because after wifi and app restart on my iphone, devices are not responsible also... The problem is in server.

**Comment by KhaosT** [comment]
I'm not really sure how this happens since I wasn't able to reproduce the problem by disabling the invocation of the callback() in "get" event.

**Comment by antonkluev** [comment]
I will try to make a video next days of that issue :)

**Comment by fahrvergnuugen** [comment]
@antonkluev does the node process terminate?

I had this problem but it was because I was accidentally using the same callback twice, which happened because I had bound my get handler twice by mistake. This raised an exception and ended the node process.

**Comment by snowdd1** [comment]
Just wondering: You are binding the "set" event of the TimeCapsule to a function to return the value, but you do that if the "set" event of the characteristic is fired? Or am I missing crucial parts of the code?
I would assume that a "set" event is meant to send commands to your device, and not to start listening for events that your device code might be firing (later, it seems)?

**Comment by antonkluev** [comment]
**fahrvergnuugen**, ive tryed it again and it works,,, i thing i had an issue with double call of callback(); but fixed it accedentialy )) 

**snowdd1**, i use node.js for controlling a timecapsule and inside of timecapsulescript i use exec, it can takes time to fire an event and get "echo" back as callbackfunction... here in pseudocode

```
var state = function (value) {
    // here is eventualy my callback of homekit
};
exec({check my timecapsule state}, function (error, echo, stderr) {
    state(echo.contains('running') == true? true: false); 
});
```

but now it works.. once again, as fahrvergnuugen said, double call of callback is not good ^^
