### ISSUE TITLE
The accessory sent an invalid response. Pleas try again.

### ISSUE THREAD

**Issue by stevenshizzle** [homebridge/HAP-NodeJS#219]
The Garage control in the "Eve" application gives error "The accessory sent an invalid response. Please try again". I even removed my customized GarageDoorOpener accessory, cleared out the /persist directory, removed the accessory from HomeKit, and added it again and I still have this issue.

Any thoughts on what might be causing this or how to see what is being sent to HomeKit that might be causing the response to be invalid?

**Comment by KhaosT** [comment]
I guess Eve is doing its own characteristic validation. I'd suggest you use a different HomeKit app and see what's the actual value HomeKit is receiving

**Comment by KhaosT** [comment]
Or enable the debug logging so we can see what's the value by adding "DEBUG=*" before node

**Comment by stevenshizzle** [comment]
It was the iPhone application. I used Apple’s HMCatalog app and had not issue.  Thank you.
On 21-Feb-2016, at 19:43, Khaos Tian <notifications@github.com> wrote:

Or enable the debug logging so we can see what's the value by adding "DEBUG=*" before node
