### ISSUE TITLE
what ist Characteristic.Category

### ISSUE THREAD

**Issue by justme-1968** [homebridge/HAP-NodeJS#220]
does anyone know what Characteristic.Category is supposed to do? are there any defined values?

thanks
 andre

**Comment by KhaosT** [comment]
It's used for iOS to tell HomeKit app the type of the accessory (https://developer.apple.com/library/prerelease/ios/releasenotes/General/iOS90APIDiffs/Objective-C/HomeKit.html HMAccessory.category)

**Comment by justme-1968** [comment]
but why? i mean the possible values are the same as the service types. at least most of them. the only distinct ones that would make sense are bridge and fan. what am i missing?

anyway. should the possible types not be added as defined values in HomeKitTypes.js ?

**Comment by Supereg** [comment]
This categories are used mainly for the icon in the pairing screen. It describes the main use of the accessory (remember a accessory can have multiple services).
