### ISSUE TITLE
HAP-NodeJS etnernet Arduino

### ISSUE THREAD

**Issue by Ramzes177** [homebridge/HAP-NodeJS#225]
Hi,
tell me how to organize a two-way communication between the Arduino and Raspberry through etnernet that would send and receive answer
Thank you

**Comment by legotheboss** [comment]
You could try HTTP GET and HTTP POST.

**Comment by desvdp** [comment]
If you're alluding to using ethernet between the Arduino and RPi I see two options:
- either your Arduino is a Yun (-like) device
- or you're be using an ethernet shield, similar to this one https://www.sparkfun.com/products/11166

In both cases you could choose to use MQTT: 
- for the Yun see here: https://blog.adafruit.com/2015/09/01/adafruit-mqtt-arduino-library-now-with-arduino-yun-example/
- in the case of the ethernet shield, see here: http://m2mio.tumblr.com/post/30048662088/a-simple-example-arduino-mqtt-m2mio

Hope this get you started, remember Google is your friend !
