### ISSUE TITLE
allowInsecureRequest for put method

### ISSUE THREAD

**Issue by PaulWieland** [homebridge/HAP-NodeJS#232]
I have an external script that sends commands to homebridge via an _http put_ request. I set `allowInsecureRequest = true` on [line 82 of HAPServer.js](https://github.com/KhaosT/HAP-NodeJS/blob/917877d52cffd3e600ee8014f56979126514d2ad/lib/HAPServer.js#L82), but the _put_ fails with an _http 401_ error.

It seems that `if (!this.allowInsecureRequest && !session.encryption) {` is missing from [line 940](https://github.com/KhaosT/HAP-NodeJS/blob/917877d52cffd3e600ee8014f56979126514d2ad/lib/HAPServer.js#L940). If I comment this block out, my script works.

**Comment by KhaosT** [comment]
For write, an extra layer of security is added to prevent unauthorized writes. Please add "authorization" header to your HTTP request with accessory PIN as content. Eg: "Authorization: 031-45-154"

**Comment by k1979** [comment]
Hi,
I try to do same thing.

I set **this.allowInsecureRequest = true;** in HAPServer.js, and add authorization header like
curl -X PUT http://localhost:PORT/characteristics --header "Content-Type:Application/json" --header **"authorization:031-45-154"** --data "{\"characteristics\":[{\"aid\":3,\"iid\":10,\"value\":1}]}".
But still it returns {"status":-70401}.

Is "an extra layer" you wrote  [line 885](https://github.com/KhaosT/HAP-NodeJS/blob/917877d52cffd3e600ee8014f56979126514d2ad/lib/HAPServer.js#L885), right?

If I comment this block out, it works.

I don't know why this line doesn't work.
I think if I set this.allowInsecureRequest = true; , it should return no error.

**Comment by KhaosT** [comment]
take a look at [here](https://github.com/nfarina/homebridge/issues/506#issuecomment-261673712)

**Comment by k1979** [comment]
@KhaosT 

Thank you for your very quick reply.

Yeah, I read that issue thread and tried the code `curl -X PUT http://localhost:PORT/characteristics --header "Content-Type:Application/json" --header "authorization:031-45-154" --data "{"characteristics":[{"aid":xx,"iid":xx,"value":x}]}"`.

I think that if I set `this.allowInsecureRequest = true;` in HAPServer.js line82, HAPServer.js line885 should not return 401 error(I'm completely noob with  programming so I might misinterpret...).

HAPServer.js line 885-890 are

```
   if (!this.allowInsecureRequest && !session.encryption) {
     response.writeHead(401, {"Content-Type": "application/hap+json"});
     response.end(JSON.stringify({status:HAPServer.Status.INSUFFICIENT_PRIVILEGES}));
 
     return;
}
```

If I comment this block out, I can change the accessory's status from that script.

**Comment by KhaosT** [comment]
Changing that to true should be sufficient. I'm not sure why it's not working for you. Maybe it's the module cache? After changing the variable, run it and then kill it and re-start again and see if it make a difference.

**Comment by k1979** [comment]
I tried

HAPServer.js line 885

```
HAPServer.prototype._handleCharacteristics = function(request, response, session, events, requestData) {

  this.allowInsecureRequest = true;

  if (!this.allowInsecureRequest && !session.encryption) {
    response.writeHead(401, {"Content-Type": "application/hap+json"});
    response.end(JSON.stringify({status:HAPServer.Status.INSUFFICIENT_PRIVILEGES}));

    return;
  }
```
It worked.


```
HAPServer.prototype._handleCharacteristics = function(request, response, session, events, requestData) {

  this.allowInsecureRequest = false;

  if (!this.allowInsecureRequest && !session.encryption) {
    response.writeHead(401, {"Content-Type": "application/hap+json"});
    response.end(JSON.stringify({status:HAPServer.Status.INSUFFICIENT_PRIVILEGES}));

    return;
  }
```
It returns 401 error.


They are as expected but if I change at line 82
```
function HAPServer(accessoryInfo, relayServer) {
  this.accessoryInfo = accessoryInfo; 
  this.allowInsecureRequest = true;
```
it doesn't work.
I think it doesn't apply to line 885?
