### ISSUE TITLE
Control via ICLOUD

### ISSUE THREAD

**Issue by Ramzes177** [homebridge/HAP-NodeJS#234]
Hi
After installing the NAP-NODEJS device perfectly controlled via LTE, but now control some reason stopped working.
What could be the reason?
The code itself does not change anything.

**Comment by legotheboss** [comment]
Remove the persist folder and check. Do you have an Apple TV in your setup?

**Comment by Ramzes177** [comment]
Ok, I check and delete. Before, Apple TV has 4 generations, but it not set in any of the software for HomeKit

**Comment by legotheboss** [comment]
You need an Apple TV for remote control of HomeKit devices...

**Comment by Ramzes177** [comment]
What is necessary for this program to install?
How to do it?

**Comment by Ramzes177** [comment]
I can not get to remotely control lights. HELP

**Comment by timoschilling** [comment]
@Ramzes177 you need to log in into iCloud with the same account as on your iPhone, then it should work.

**Comment by legotheboss** [comment]
@Ramzes177 Make sure you have iCloud Keychain enabled on your iPhone
