### ISSUE TITLE
update status on HAP Server

### ISSUE THREAD

**Issue by chrigu1981** [homebridge/HAP-NodeJS#235]
Hello,

it's not an issue but i need your help. everything works fine with HAP Server but i want also to trigger some lights (ESP8266) with my PHP Server but how can i update the state on the HAP Server that the light switched on/off?

thank you for your help
christian

**Comment by dircm** [comment]
I would use the lightweight MQTT communication and write a client in your HAPnode that listens for events from your 8266.

I'm using https://www.npmjs.com/package/mqtt on my RPI, there are many good ones around..

**Comment by chrigu1981** [comment]
ok i made it like this in the accessory at the end:

client.on('message', function(topic, message) {
	console.log(String(message));
	if(String(message) == "SwitchedOn"){
		LIVINGROOM.powerOn = 1;
		console.log("value is on");
	}else if(String(message) == "SwitchedOff"){
		LIVINGROOM.powerOn = false;
		console.log("value is off");
	}
});

i publish a second message on the same topic with either SwitchedOn or SwitchedOff

**Comment by dodekeract** [comment]
@chrigu1981 You can use [this](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to improve readability.

**Comment by chrigu1981** [comment]
thx
