### ISSUE TITLE
HAP-NodeJS + Location possible?

### ISSUE THREAD

**Issue by shawnlobo96** [homebridge/HAP-NodeJS#240]
I was wondering if it is possible to use the iOS devices' location to create triggers. Or does it require to be connected to the iCloud service using an Apple TV?

**Comment by fahrvergnuugen** [comment]
Triggers are standard functionality in HomeKit, and they include geofences as an event type.

**Comment by michbeck100** [comment]
Geofencing must be supported by the used HomeKit app on your iOS device. This is not a feature of HAP-NodeJS

**Comment by shawnlobo96** [comment]
Could you suggest any apps that support this feature.

**Comment by justme-1968** [comment]
eve does for example

**Comment by legotheboss** [comment]
HMCatalog works @shawnlobo96

**Comment by PatchworkBoy** [comment]
Eve, Hesperus, Home...

**Comment by PatchworkBoy** [comment]
Lutron, Ecobee...

**Comment by PatchworkBoy** [comment]
And yes, you do also need an AppleTv3 or better, OR an iPad (with Bluetooth turned on) on the same LAN as your homebridge, signed in to the same iCloud account.
