### ISSUE TITLE
Fake lock accessory

### ISSUE THREAD

**Issue by franklindee** [homebridge/HAP-NodeJS#243]
hi will you be so kind to write the lock_accessory.js that basically when we ask to unlock the door it runs the followin python script? 

cmd.run('sudo python /home/pi/HAP-NodeJS/python/lock.py');

the lock.py should be like this:

import RPi.GPIO as GPIO
from time import sleep
GPIO.setmode(GPIO.BOARD)
GPIO.setup(26, GPIO.OUT)
GPIO.output(26, GPIO.HIGH)
GPIO.output(26, GPIO.LOW)
sleep(1)
GPIO.output(26, GPIO.HIGH)
GPIO.cleanup()

after the scipt running i would like that it change back the status to SECURED

with the locking function no action is required

i need to use this script for an electronic locking gate in my villas

let me know thaks for the help

**Comment by KhaosT** [comment]
I can point out where should you modify but I'll not re-write the code for you.
You can learn how to execute shell script in node.js at [here](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback).
To have the lock run something when iOS sends the command, you can try to modify [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/Lock_accessory.js#L10).

**Comment by franklindee** [comment]
Hi i've tried to do this 

 if (value == Characteristic.LockTargetState.UNSECURED) {
      FAKE_LOCK.unlock();{
    ** cmd.run('sudo python /home/pi/HAP-NodeJS/python/lock.py');**
     }
      callback(); // Our fake Lock is synchronous - this value has been successfully set
      
      // now we want to set our lock's "actual state" to be unsecured so it shows as unlocked in iOS apps
      lock
        .getService(Service.LockMechanism)
        .setCharacteristic(Characteristic.LockCurrentState, Characteristic.LockCurrentState.UNSECURED);
    }
    else if (value == Characteristic.LockTargetState.SECURED) {
      FAKE_LOCK.lock();
      callback(); // Our fake Lock is synchronous - this value has been successfully set
      
      // now we want to set our lock's "actual state" to be locked so it shows as open in iOS apps
      lock
        .getService(Service.LockMechanism)
        .setCharacteristic(Characteristic.LockCurrentState, Characteristic.LockCurrentState.SECURED);
    }
  });

do you think will work?

thank you
