### ISSUE TITLE
different accessory

### ISSUE THREAD

**Issue by marcgrc** [homebridge/HAP-NodeJS#248]
Good morning everybody,
Thank for the great work. I write from italy.
I have a question.
If i want to open two different garage door whit a different Siri name, what can i do ?
I try to created two different file s whit garage door open accessory whit the different Siri name . For exsample: one have garage name and one have basculant name. 
When i speck whit a different name the door opened in same Times.  
It ' s possibile to created two different accessory??
Help me thanks very mutch.﻿

**Comment by fadriPi** [comment]
I'm looking for the same solution. I have 3 Garages which i want to open with Siri and 3 different names. I tried to copy the default garage accessory and renamed it. In the file i changed the display name and the username. But when i start core.js the created accessory won't start.

any ideas?
Thanks for support.

**Comment by legotheboss** [comment]
Can you share your garage door opener accessory file? You might need to change the UDID

**Comment by fadriPi** [comment]
Here the files i created for Garage2 and Garage3.
[Garage2and3.zip](https://github.com/KhaosT/HAP-NodeJS/files/314470/Garage2and3.zip)

Thanks for your help.

**Comment by legotheboss** [comment]
I created new files for you. I see you use my tutorials 👍 

[GarageDoorOpener2](https://gist.github.com/legotheboss/4e160fdeadbbecd7ad22b5cefefa876e)
[GarageDoorOpener3](https://gist.github.com/legotheboss/f6ff3bebe9e1a06bcf31d5b563b6761e)

**Comment by marcgrc** [comment]
Thank you very very mutch 👌👌👍🏻👍🏻

Inviato da iPhone

**Comment by fadriPi** [comment]
Thank you too! great work. 
Now it will parsing the additional doors.

now i have another problem. on iphone i use the app "eve". when i add the first garage door and call it garage door one then siri will open it without any failure and says "garage one is open".
when i add the second door and call it garage door two then siri only says "the garage doors are open" and open both doors.

what app do you use? have you any idea what's the problem? 
when i manually open the doors with the button it will work correctly. it must be a app-error?

Thanks for support. very nice tutorial at all.

**Comment by marcgrc** [comment]
thank you for great work.i have same problem.

Date: Wed, 15 Jun 2016 11:53:02 -0700

**Comment by fadriPi** [comment]
I was testing it on "Insteon+" and "myHome+" with the same error. Then I renamed the doors to "Garage One" and "Garage Door Two" for testing but nothing changed. Siri shows the correct names on the screen.

**Comment by legotheboss** [comment]
To ease this in my situation, I created two scenes for each garage I have:
 
"Open Garage Door X" and "Close Garage Door X"

I just configured the scene to open or close the corresponding garage. Im not sure about the apps you are using, but the app I use allowed me to configure these scenes. When I tell Siri Open Garage Door X, it would execute the corresponding scene. I've been doing this for months now.

**Comment by fadriPi** [comment]
I found the problem. 
When i say "garage X open" (in german) siri will understand the command but open both garages.
I have to say "Open Garage X" then it works correctly. the problem was behind the screen. :)

thanks again!

**Comment by G0lexiy** [comment]
Legotheboss,
Great job on your tutorials! First garage with sensor works great! When I tried your tutorial to create second garage door file, my homekit app does not see the second garage door opener as an option when I tap 'add accessory'
Any suggestions?
I even copied the second garage file from the above coments, still did not work.

**Comment by G0lexiy** [comment]
Legotheboss,
Great job on your tutorials! First garage with sensor works great! When I tried your tutorial to create second garage door file, my homekit app does not see the second garage door opener as an option when I tap 'add accessory'
Any suggestions?
I even copied the second garage file from the above coments, still did not work.

**Comment by G0lexiy** [comment]
file:///home/pi/Temp%20copies/GarageDoorOpener_accessory
