### ISSUE TITLE
How to reuse a mqtt connection?

### ISSUE THREAD

**Issue by codmpm** [homebridge/HAP-NodeJS#252]
Hi,

first, thanks for your work. I was flashed 10 minutes ago as I comanded Siri to switch on my living room light. I'm fairly new to nodejs but as a full-time web developer I know JavaScript itself. So my problem is simply the structure I think.

Can anyone tell me how to reuse a mqtt-connection through different accessories? 
I have many sensors and actuators which work over mqtt but I don't want to open an new mqtt connection for every accessory or put everything in one file.

Maybe someone of you got it working or has a good starting point to improve my understanding.

Thanks and cheers,
Patrik

**Comment by PatchworkBoy** [comment]
Install Domoticz, let Domoticz index all your MQTT devices, use homebridge-edomoticz plugin and homebridge to shunt it all out to Siri via HAP-NodeJS (part of Homebridge)? 

    On Saturday, 11 June 2016, 12:44, Patrik Mayer <notifications@github.com> wrote:
 

 Hi,first, thanks for your work. I was flashed 10 minutes ago as I comanded Siri to switch on my living room light. I'm fairly new to nodejs but as a full-time web developer I know JavaScript itself. So my problem is simply the structure I think.Can anyone tell me how to reuse a mqtt-connection through different accessories? 
I have many sensors and actuators which work over mqtt but I don't want to open an new mqtt connection for every accessory or put everything in one file.Maybe someone of you got it working or has a good starting point to improve my understanding.Thanks and cheers,
Patrik—

**Comment by codmpm** [comment]
Hey,

thanks for that fast reply. That could be a very interessting way. 

Currently I run openHAB with homegear to controll many Homematic and MAX! devices. The goal is to bring all these devices to mqtt via homegear but I'm not there yet.

I will have a look into the domoticz-plugin to get my head around how to reuse a mqtt-connection.

Cheers,
Patrik

**Comment by PatchworkBoy** [comment]
It does if you look into the MQTT-integration branch.

**Comment by hobbyquaker** [comment]
perhaps this is something for you: https://github.com/hobbyquaker/homekit2mqtt
