### ISSUE TITLE
wiringPiSetup: must be root

### ISSUE THREAD

**Issue by sevenfoxes** [homebridge/HAP-NodeJS#257]
I'm running into an issue where every time I ask siri if my door is open it tells me that she can't find a garage door at this time. So I ran the debug while asking and found that it appears to crash for not having appropriate permissions. do you know what might be going wrong?

Opening and closing the door works fine. It also correctly indicates in my app if it's open or closed.

```
  Accessory [Garage Door Opener] Processing characteristic set: [{"aid":1,"iid":9,"ev":true},{"aid":1,"iid":10,"ev":true}] +6ms
  Accessory [Garage Door Opener] Registering Characteristic "BlaBla" for events +3ms
  Accessory [Garage Door Opener] Registering Characteristic "BlaBla" for events +3ms
  EventedHTTPServer [::ffff:10.0.1.32] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:10.0.1.32] HTTP request: /characteristics?id=1.9 +26s
  HAPServer [3C:5A:3D:EE:5E:FA] HAP Request: GET /characteristics?id=1.9 +4ms
  Accessory [Garage Door Opener] Getting value for Characteristic "BlaBla" +32ms
Read:
wiringPiSetup: Must be root. (Did you forget sudo?)
pi@garage:~/HAP-NodeJS $ which node
/home/pi/.nvm/versions/node/v6.2.2/bin/node
```

**Comment by KhaosT** [comment]
@sevenfoxes looks like the package you used to perform read (wiringPi) needs the root permission to perform correctly. You can try to run hap-nodejs with root or use a different GPIO package...
