### ISSUE TITLE
Service.LightSensor broken?

### ISSUE THREAD

**Issue by FlorianWendelborn** [homebridge/HAP-NodeJS#260]
``` javascript
this
    .addService(Service.TemperatureSensor)
    .getCharacteristic(Characteristic.CurrentTemperature)
    .on('get', callback => {
        callback(null, findSensor(this.device.id).getStatus().data);
    });
```

This code breaks, as soon as I change `TemperatureSensor` to `LightSensor` and `CurrentTemperature` to `CurrentAmbientLightLevel`.

`.data` is an integer with a value of about 40.

Am I missing something or is this broken?

The iOS 10 public beta 1 `Home` App just shows the data as `(null)`.

**Comment by Qonstrukt** [comment]
I can confirm this issue, with Hesperus, or even the HMCatalog app from Apple there doesn't seem to be a problem. So it seems to me like a bug in the Home app of iOS 10.

**Comment by warloofer** [comment]
I have it working with mqtt, but in a test mode (fixed light level value).

Here is the file:
https://github.com/warloofer/samples/blob/master/LightSensor_accessory.js

The problem I have with LightSensor in the HomeKit deffault ios app, is the automation tab.

I have created a virtual MotionSensor and LightSensor (both with fixed value), with the only purpose of check the automation. The automation triggered when a sensor detects something only works with the MotionSensor. LightSensor doesn't appear here.

¿Do anyone has the same problem?
