### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Ramzes177** [homebridge/HAP-NodeJS#267]
Good afternoon,
There is a switch that includes \ turns off the light after hap-nodejs through MQTT
you must enter obychnvy switch
how to organize feedback to the js side that would change the status if you use a switch?
tell me how to implement a feedback

**Comment by ThaNerd** [comment]
Was looking for the same information :-)

**Comment by snowdd1** [comment]
See here: https://github.com/KhaosT/HAP-NodeJS/issues/175
