### ISSUE TITLE
Secant Cardio Interface

### ISSUE THREAD

**Issue by JPCoollink** [homebridge/HAP-NodeJS#274]
Hi,
I own a Secant Cardio domotic kit in my house.
I would like to used this HAP server to interface with my cardio using the available RS-232 interface that allow to control my cardio. 
I would create separate HAP accessories for each of my lights and device controlled by the cardio.
The only thing i am not sure how to do is where to host the serial port server that will send and received the command from my different HAP accesories?
Is there some example for that?
Thanks
JP

**Comment by legotheboss** [comment]
Take a look at this node package and see if it can work for you: https://www.npmjs.com/package/serial-node
