### ISSUE TITLE
Shutter/blinds positioning 

### ISSUE THREAD

**Issue by nunofgs** [homebridge/HAP-NodeJS#277]
I'm using homebridge to control my Fibaro rollershutter which is capable of precise positioning. 

Is it possible to get a characteristic for the garagedoor (that's what my device is mapped to) that allows me to tell Siri to "close my shutter to 30%" or "open my shutter half-way"?

**Comment by justme-1968** [comment]
the standard garage door service has only open and closed states.

just try to add the CurrentPosition and TargetPosition characteristics.

i will depend on the app you use if the controls will be visible. i don't know if they will work with siri.

**Comment by nunofgs** [comment]
@justme-1968: looks like I already had what I needed. There is a service called "WindowCovering" which does exactly what I want.

The only issue is that the open/close characteristics don't show up. Would love some help with that issue.

FWIW here's the PR I submitted with the working service: https://github.com/home-assistant/homebridge-homeassistant/pull/34

**Comment by justme-1968** [comment]
it depends on the app which characteristics are displayed. eve for example displays most of them. insteon+ is quite restrictive. even for the 'normal' default services and characteristics.

my window blinds work without problems in eve, siri and the home app but insteon does not work. i think it is one of the worst homekit apps.

**Comment by nunofgs** [comment]
Thanks for the tip. You were so right. The eve app displays up and down buttons correctly!
