### ISSUE TITLE
Can't add accessories after installing in RPi3 (using iOS9 or iOS10)

### ISSUE THREAD

**Issue by pplucky** [homebridge/HAP-NodeJS#282]
First of all, thanks in advance for your patience with my noobness ;-)

So my setup is a Raspbian Jessie in an RPi3, 2 iOS devices (one with iOS 9.0.2 and another one with iOS 10.0.1), and after following the instructions in this [video](https://www.youtube.com/watch?v=93J-tavDG6o), I did not manage to add any accessory either with Home app (in iOS 10) or Eve (iOS 9 or iOS 10).

When running BridgeCore.js, I get the following:
pi@strongswanpi3:~/HAP-NodeJS $ sudo DEBUG=\* node BridgedCore.js
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
HAP-NodeJS starting...
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: TemperatureSensor_accessory.js
Parsing accessory: Thermostat_accessory.js
  EventedHTTPServer Server listening on port 51826 +0ms

If I try to: 'curl http://127.0.0.1:51826/accessories', it shows:
  EventedHTTPServer [::ffff:127.0.0.1] New connection from client +5m
  EventedHTTPServer [::ffff:127.0.0.1] HTTP server listening on port 43218 +4ms
  EventedHTTPServer [::ffff:127.0.0.1] HTTP request: /accessories +34ms
  HAPServer [CC:15:3D:E3:CE:F6] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:127.0.0.1] HTTP Response is finished +20ms
  EventedHTTPServer [::ffff:127.0.0.1] Client connection closed +9ms
  EventedHTTPServer [::ffff:127.0.0.1] HTTP connection was closed +5ms
  EventedHTTPServer [::ffff:127.0.0.1] HTTP server was closed +2ms

Also tried deleting persistent folder and changing default username in BridgeCore.js, but no good. 

Still then, I'm not able to get any of the pre-configured accessories in HAP-NodeJS to appear in iOS apps. 

Is there anything else I might try to get this to work?

**Comment by murch1** [comment]
On your iOS device, go to Settings > HomeKit. Press Edit, then delete the home file. You should then be able to go back in to your HomeKit app and repair everything again.
