### ISSUE TITLE
How to make Siri throw errors

### ISSUE THREAD

**Issue by macsee** [homebridge/HAP-NodeJS#293]
Hi, 
I'm very new at using HAP-Node. I have recently start playing with the Fake Light accessory and I was wondering how can I capture errors and make Siri throw them. For instance,  I'm using a Raspberry Pi 3 as server for the HAP-Node Core which controls an arduino switch via Wi-Fi. I'd like to know whether this device is available or not . As far as I could see, my device only appears as unavailable when the server is not running (Core.js), however, if the server is running and my device is disconnected, Siri sees my device as available and turns it on or off as usual. My question is : if there is a way to notify the Server which devices are available and which are not? I can capture errors from my device but how can I tell to Siri that an error has ocurred? 
Great work by the way! Congrats!

Cheers!
Maxi

**Comment by sembsa** [comment]
Move you HAP folder to home folder

**Comment by macsee** [comment]
Ok. It was and it is already in there. But, I don't understand how this would help me to tell Siri when something is wrong.

**Comment by sembsa** [comment]
It's not possible because you don't set Siri command. If your iPhone not connect to RPi, when Siri talk for you This device is not available.

**Comment by PatchworkBoy** [comment]
The Pi needs to set the device as unreachable when it can't connect to the Arduino. HomeKit doesn't poll devices in such a way - you need to do that at the bridge.

**Comment by PatchworkBoy** [comment]
(See this.reachable in lib/Accessory.js)

**Comment by macsee** [comment]
Great! Now we are talking about! Thanks! I'll take a look.

Cheers!

**Comment by PatchworkBoy** [comment]
Have a look at homebridge and it's platform plugins for examples - many reflect realtime status etc utilising MQTT and other methods. Majority of the code in these will work directly with HAP-NodeJS.

**Comment by PatchworkBoy** [comment]
( https://github.com/search?q=homebridge- )

**Comment by macsee** [comment]
Ok. I will. Thanks!
