### ISSUE TITLE
Changing a switch state when pressed

### ISSUE THREAD

**Issue by ARogerson** [homebridge/HAP-NodeJS#309]
Hi,

This may have been answered already but I was not able to find anything, so if it was sorry.

I have implemented UPB switches using HAP-NodeJS and everything is working well. The next task is to change the state of the switch in Homekit when a switch is pressed manually. UPB provides a event message that contains the details of the event that can be decoded and then used to set the state of the appropriate switch in HAP-NodeJS. My question is how do I do this and where would the code be? The event needs to be decoded first then the appropriate switch state would need to be changed. 

**Update:** The way in which I communicate with UPB is through an RS232 interface module so the events are sent when the switch is pressed and I already know how to decode the message. I am just thinking that the event handler needs to be in the main code and not in the switch code since it could happen at any time. I think at one time KNX was supported in a similar way but that was a while back and the code structure has changed since then. Just looking for pointers as this is the last part of my implementation.

I have a true HomeKit switch that works in the way I want it to so I am sure it is possible.

Thanks in advance for any pointers.

Andy

**Comment by marcgrc** [comment]
Hi I would like to implement accessory light so that switch status is changed to Homekit when a switch is manually pressed.
A solution could be adaptable as for the garage sensor, in input on the gpio of raspberry with wirinpi.
Someone has solutions to create this accessory?
thank you
