### ISSUE TITLE
How to trigger a HomeKit Event with a physical button connected to the raspberry?

### ISSUE THREAD

**Issue by mrcsmxms** [homebridge/HAP-NodeJS#311]
hello.
i can control my nightstand light via HomeKit and a physical button connected to my raspberry.
but when i press the button (toggles GPIO status) it wont change the status in HomeKit. 

the button simply executes a python script that directly controls the GPIO state. i want to add a command to this script to change the status in HomeKit too.

**Comment by snowdd1** [comment]
Try `Characteristic.setValue()`
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L150

**Comment by mrcsmxms** [comment]
that looks complicated. I'll do my best to read me through all the comments.  do i need to execute the whole js-file ? I'm a total noob in js sorry :(

**Comment by cflurin** [comment]
One "easy way" is to use node-red (preinstalled on jessie) and homebridge-mqtt.
https://github.com/cflurin/homebridge-mqtt.
If you don't know node-red, mqtt, you'll probably have to invest a couple of hours.
But as soon as you have installed and learned how to use node-red and mqtt you'll be able to do almost everything.

**Comment by exsilium** [comment]
@mrcsmxms An example how to use the `setValue()` call. I have a impulse type of button which I set back to "off" state after a timer has expired. Hope this helps to clarify how to use the `setValue()` call on an on/off characteristic.

https://github.com/exsilium/homebridge-xbee/blob/master/index.js#L60

**Comment by marcgrc** [comment]
Hi I would like to implement accessory light so that switch status is changed to Homekit when a switch is manually pressed.
A solution could be adaptable as for the garage sensor, in input on the gpio of raspberry with wirinpi.
Someone has solutions to create this accessory?
thank you

**Comment by exsilium** [comment]
@marcgrc Maybe I'm missing a bit on what you would like to achieve but I think reading back the switch state depends more on your specific actuator, how it is wired or how it reports back a state.

For example, if you are using a RPi and the switch is wired physically to your board, you can just detect the pin change at the GPIO and `setValue()` of the switch based on that change.

Another example, when you are using some more sophisticated switch like a ZigBee enabled one - they tend to send the state change information via a `0x0a` Report attributes cmd frame that you would need to read back via serial and similarly set the value of the switch based on the frame received.

Altough both examples are very different when it comes to physically interacting with the switch, from HomeKit point of view they both are based on @snowdd1 answer to use `Characteristic.setValue()` to set the state to whatever the physical device tends to be.

**Comment by marcgrc** [comment]
Thank you for the reply.
I want to give input to the lamp in the raspberry when I push the wall switch by intercepting the electrical wires that, before coming to the relays, pass from the acs712 module which will return the input lamp to the lamp in the raspberry.
I do not know how to upgrade
 The light accessory to make it change was all homekit.
Could you send me a script that I clen in my light accessory ??
I would be grateful to you

**Comment by Tkg8455** [comment]
Hello everyone,
This is what I'm trying to do. Bu there is no information about what margrc try to do.
Can you help us?

**Comment by Tkg8455** [comment]
I continue searches. If anyone find a solution. Please show us a way to solution.
I hope  someone finds
