### ISSUE TITLE
Event handler advice

### ISSUE THREAD

**Issue by ARogerson** [homebridge/HAP-NodeJS#316]
Ok, got no replies to my previous question so lets try a different approach.

Where in the code would I put an event handler to capture notifications that come in on an RS232 port. Once they come in I will decode the message and then update the state of the specific device.

Regards,

Andy

**Comment by snowdd1** [comment]
Write an event handler that has access to the characteristics object. When your event is caught update characteristic with setValue()

**Comment by Samfox2** [comment]
Is there a way to change/set a value of a homekit device "from outside" with a simple python/shell script? I think this is what is missing - an universal interface...

**Comment by legotheboss** [comment]
@Samfox2 You can have the accessory file read a specific file. When the value in the file changes, it could trigger a change. I implemented a similar system in one of my accessories.

```
setInterval(function() {
  wpi.setup('phys');
  sensorReading = wpi.digitalRead(12);
  sensorReading = Number(sensorReading);
  if (sensorReading == '1'){
    newStatus = false;
  }
  if (sensorReading == '0'){
    newStatus = true;
  }

  if(newStatus != GARAGE_DOOR.opened){
    GARAGE_DOOR.opened = newStatus;
    garage
      .getService(Service.GarageDoorOpener)
      .setCharacteristic(Characteristic.CurrentDoorState, !GARAGE_DOOR.opened);
  }
}, 1000);
```

**Comment by Samfox2** [comment]
The charme would be that polling would be unnecessary.

**Comment by snowdd1** [comment]
Access to hap-nodejs is denied in default mode. You can change that in the code: 
See https://github.com/KhaosT/HAP-NodeJS/issues/232

**Comment by Samfox2** [comment]
Wow, this is exactly what I was looking for. Could you please explain how to use this function? Is there a code snippet anywhere? I'd like to extend my  [doorbell accessory](https://github.com/Samfox2/homebridge-doorbell) to respond to commands from outside (a script call/json request) so that a message is fired as soon as the bell button is pressed. At this time it is hardcoded to the "identify" command.

**Comment by Kosta-Github** [comment]
maybe a dumb question: for updating values in characteristics should one use `setCharacteristic()` (as above) of `getCharacteristic().setValue()` (as seen most of the time)?
```
garage
    .getService(Service.GarageDoorOpener)
    .setCharacteristic(Characteristic.CurrentDoorState, !GARAGE_DOOR.opened);
```
vs.
```
garage
    .getService(Service.GarageDoorOpener)
    .getCharacteristic(Characteristic.CurrentDoorState)
    .setValue(!GARAGE_DOOR.opened);
```
Is that equivalent or has one method an advantage over the other?
