### ISSUE TITLE
Two topic client.subscribe MQTT

### ISSUE THREAD

**Issue by Ramzes177** [homebridge/HAP-NodeJS#326]
Good afternoon,
Tell me how to get information from two different topics?
For example:
1 - The temperature
2 - Switch status

These messages come from all topics
`client.on('message', function(topic, message) {
  //console.log(parseFloat(message));

  MTemperature = parseFloat(message);
});`

**Comment by iCarl** [comment]
On the same accessory?

**Comment by iCarl** [comment]
See https://www.grahl.ch/2016/07/09/wemos-d1-mini-dht-homekit-setup/

**Comment by Ramzes177** [comment]
Yes, the same accessory

**Comment by Ramzes177** [comment]
I went this way

client.on('connect', () => {
	client.subscribe('MedisanaTemperature')
	client.subscribe('LightStatus')
})

client.on('message', function(topic, message) {
	var strTopic = String(topic);
	var strMessage = String(message);
	console.log("Received '" + strMessage + "' on '" + strTopic + "'");
	if(topic == 'MedisanaTemperature') {
		MTemperature = parseFloat(message);
		console.log ("TemperatureSensor = " + MTemperature);
	}
	
	if
	(strTopic == "LightStatus") {
		strLightStatus = parseFloat(message);
		console.log ("Status = " + strLightStatus);
	}
})

like works
