### ISSUE TITLE
Negative Temperature

### ISSUE THREAD

**Issue by Fafex** [homebridge/HAP-NodeJS#331]
Hello,

I've created a Temperature accessory for my home automation system. It should read current temperature from a txt file (that's a way I prefer). Every time the temperature goes below zero, every iOS app throws an error and refuses to show the temperature. I already changed minValue in both my accessory and in HomeKitTypes.js

Here's the part that reads temperature from my *_accessory.js

```
},{
    	cType: types.CURRENT_TEMPERATURE_CTYPE,
    	onRead: function(callback) {
    		console.log("Reading temperature outside");
    		fs = require('fs')
			fs.readFile('/home/username/hktmp.txt', 'utf8', function (err,data) {
  				if (err) {
    			        return console.log(err);
 					}
 				console.log(data);
 				var inttemp = parseFloat(data);
				console.log(inttemp)
  				callback(inttemp);
  			})
    	},
    	perms: ["pr","ev"],
		format: "float",
		initialValue: 24,
		supportEvents: false,
		supportBonjour: false,
		minValue: -100,
		maxValue: 100,
		manfDescription: "Temperature"
	},{
```

Console log, after parseFloat, throws out a correct value of negative temperature.

And the fragment I changed in HomeKitTypes.js

```
Characteristic.CurrentTemperature = function() {
  Characteristic.call(this, 'Current Temperature', '00000011-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    unit: Characteristic.Units.CELSIUS,
    maxValue: 100,
    minValue: -100,
    minStep: 0.1,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};
```

Any idea what else can be going wrong here?

**Comment by TheNoim** [comment]
For me it is simply working to change the min value to -100

**Comment by Fafex** [comment]
Okay, so I've take a look at @TheNoim commit and my file was the same. So I've rewritten my _accessory.js file. It now reads temperature from a sensor through Domoticz API and parse the response with RegExp. It looks like this:

```
var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var request = require("request");

// here's a fake temperature sensor device that we'll expose to HomeKit
var FAKE_SENSOR = {
  getTemperature: function() { 
    console.log("Getting the current temperature!");
    request("http://10.0.1.1:8080/json.htm?type=devices&rid=xxx", function(error, response, body) {
    				var regtemplate = new RegExp(/-?\d+\.\d+/g);
    				var regtemp= body.match(regtemplate);
    				console.log('RegExp result:');
    				console.log(regtemp[5]);
				var floattemp = parseFloat(regtemp[5]);
				console.log('called back:');
				console.log(floattemp)
				FAKE_SENSOR.currentTemperature = floattemp;
    				return FAKE_SENSOR.floattemp;
    		});
  }
}


// Generate a consistent UUID for our Temperature Sensor Accessory that will remain the same
// even when restarting our server. We use the `uuid.generate` helper function to create
// a deterministic UUID based on an arbitrary "namespace" and the string "temperature-sensor".
var sensorUUID = uuid.generate('hap-nodejs:accessories:temperature-sensor');

// This is the Accessory that we'll return to HAP-NodeJS that represents our fake lock.
var sensor = exports.accessory = new Accessory('Test Temperature Sensor', sensorUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
sensor.username = "C1:5D:3A:AE:5D:FA";
sensor.pincode = "031-45-154";

// Add the actual TemperatureSensor Service.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKitTypes.js`
sensor
  .addService(Service.TemperatureSensor)
  .getCharacteristic(Characteristic.CurrentTemperature)
  .on('get', function(callback) {
    
    // return our current value
    callback(FAKE_SENSOR.getTemperature());
  });

// randomize our temperature reading every 3 seconds
setInterval(function() {
  
  FAKE_SENSOR.getTemperature();
  
  // update the characteristic value so interested iOS devices can get notified
  sensor
    .getService(Service.TemperatureSensor)
    .setCharacteristic(Characteristic.CurrentTemperature, FAKE_SENSOR.currentTemperature);
  
}, 3000);
```


Negative temperatures shows fine now, but there's another issue. When I open any of my HomeKit apps, the temperature is at minValue until the request is finished and temperature is updated to the correct value. It creates a problem when I'm asking Siri for the specific temperature. She always answers with minimal value. Is there maybe a way to force the HomeKit protocol to wait for request result?

**Comment by snowdd1** [comment]
Your `getTemperatur()` method starts an async process with a callback, you expect the answer is already there when you call the `on('get', function() {...} )` callback.  
However, your value is **never RETURNED** as the line   
`return FAKE_SENSOR.floattemp;` is in a routine that doesn't take the return value anywhere.  

Accidentally it works sometimes because you set `FAKE_SENSOR.currentTemperature = floattemp` in your routine that is taken later on by `.setCharacteristic(Characteristic.CurrentTemperature, FAKE_SENSOR.currentTemperature);` if there was a `get` event sometimes before.

Please read some material about async calls and callbacks in JavaScript.  
http://callbackhell.com/
