### ISSUE TITLE
Siri sending an invalid response

### ISSUE THREAD

**Issue by legotheboss** [homebridge/HAP-NodeJS#335]
Currently have a Garage Door setup through HAP-NodeJS. I have been lately noticing that when I query Siri the status of my door, it says "Opening" or "Closing" instead of saying Closed or Open. However, the Home app shows the correct status. I tried making a generic garage with the HomeKit Accessory Simulator and experienced the same problem. Anyone else having this problem? I am on iOS 10.2 but have had the issue on iOS 10 as well.

**Comment by snowdd1** [comment]
*Home* does not use **PositionState**, it just compares **TargetPositionState** and **CurrentPositionState** AFAIK.  Cross check with *Elgato Eve* app.  
Same with window covering.

**Comment by legotheboss** [comment]
@snowdd1 EVE shows the correct status. I tried a few other HomeKit apps and they also showed the correct status. Only Siri seems to be telling me the wrong status.

**Comment by snowdd1** [comment]
I just checked with mine, and it told me *"one garage door is open and the other is closed"* so it's not a General Siri issue - though my Siri is configured to speak German, not English.

**Comment by legotheboss** [comment]
@snowdd1 @snowdd1 [This]("https://github.com/legotheboss/YouTube-files/blob/master/Garage%20Solution/Sensor/GarageDoorOpener_accessory(wired).js") is my accessory file. Do you spot anything that would cause this to be a problem?

**Comment by snowdd1** [comment]
Ad hoc, I cannot see anything wrong. What status does hap-nodejs print in the log for the answer to Siri's query?

**Comment by dwightpro** [comment]
Same situation. This just suddenly started happening. Target and Current always match up but Siri gets the wrong response. Parsed through the code and can't identify the problem. Home app shows proper value.

**Comment by legotheboss** [comment]
@dwightpro This might be a bug with Siri on the recent iOS 10 releases or even a bigger bug with HomeKit.

**Comment by jonny772** [comment]
Had a similar issue using a light with HAP-NodeJS. Spent a while troubleshooting and found that for POWER_STATE_CTYPE it'll return a 1 or 0 unless you use Siri where it starts returning "true" or "false".

Maybe it's something similar, using iOS 10.

**Comment by dwightpro** [comment]
This issue resolved itself for us a few weeks after it was reported. I'm assuming it was a server side change to Siri's responses.
