### ISSUE TITLE
WEB Control Panel for HAP

### ISSUE THREAD

**Issue by sszczep** [homebridge/HAP-NodeJS#353]
Hi. Has anyone succeeded making web control panel to control some lights? Can you share some of your ideas? I was thinking about linking it to MQTT. Thanks for responses!

**Comment by Maxmudjon** [comment]
http://majordomo.smartliving.ru/Main/HomePage
it can help you

**Comment by OczkoSX** [comment]
I would prefer something made just by me

**Comment by Maxmudjon** [comment]
http://majordomohome.com/Main/FAQ

**Comment by OczkoSX** [comment]
I think you don't get it. I want to sync HAP-NodeJS with WWW page and maybe my own app for iP to gain access home-away (I don't have Apple TV nor iPad)

**Comment by Maxmudjon** [comment]
you want to access your apps

**Comment by OczkoSX** [comment]
But I don't want an external app. I'd like to build something on my own...

**Comment by oriolism** [comment]
Maybe this?

https://home-assistant.io

**Comment by KhaosT** [comment]
@OczkoSX take a look at [this](https://github.com/nfarina/homebridge/issues/506#issuecomment-261704140), for hap-nodejs itself, you need to make changes to [publish](https://github.com/KhaosT/HAP-NodeJS/blob/master/BridgedCore.js#L38) and allow it to be accessed insecurely.

**Comment by OczkoSX** [comment]
But how can i change value of variable in one of my accessories?

**Comment by KhaosT** [comment]
@OczkoSX pass the right aid and iid and then it will change to the value you passed in

**Comment by OczkoSX** [comment]
So it will call for example this function just as it would be a command from Siri? 
'  acc.getCharacteristic(Characteristic.On)
  .on('set', function(value, callback){});' 

If yes - cool!

**Comment by KhaosT** [comment]
Yep
