### ISSUE TITLE
Error Creating Accessory

### ISSUE THREAD

**Issue by TheBearF8** [homebridge/HAP-NodeJS#365]
I'm getting the following when running  node Core.js   or node BridgedCore.js

0c6d6ec3-0d2f-4423-ba3c-51557f0a785a
/root/HAP-NodeJS/lib/Accessory.js:128
    if (existing.UUID === service.UUID) {
                                 ^

TypeError: Cannot read property 'UUID' of undefined
    at Accessory.addService (/root/HAP-NodeJS/lib/Accessory.js:128:34)
    at Object.<anonymous> (/root/HAP-NodeJS/accessories/TTI_Irrigation_accessory.js:166:4)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)

Here is my accessory.js   UUID lines

// Generate a consistent UUID for our Lock Accessory that will remain the same even when
// restarting our server. We use the `uuid.generate` helper function to create a deterministic
// UUID based on an arbitrary "namespace" and the word "lock".
var systemUUID = uuid.generate('hap-nodejs:accessories:tti_sys');

console.log(systemUUID);
// This is the Accessory that we'll return to HAP-NodeJS that represents our fake lock.

var system = exports.accessory = new Accessory('Irrigation System', systemUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
system.username = "E3:3E:3A:EE:32:12";
system.pincode = "031-45-154";

Where did I go wrong?  I have tried many strings after the :accessories: portion and still same result

Thanks in advance

**Comment by KhaosT** [comment]
It's complaining at ``/root/HAP-NodeJS/accessories/TTI_Irrigation_accessory.js`` line 166. What's the service you're trying to add?

**Comment by TheBearF8** [comment]
thanks for the quick reply

// We can see the complete list of Services and Characteristics in `lib/gen/HomeKitTypes.js`
system
  .addService(Service.IrrigationSystem, "Irrigation System") // services exposed to the user should have "names" like "Fake Light" for us
  .getCharacteristic(Characteristic.LockTargetState)
  .on('set', function(value, callback) {



.addService is line 166

**Comment by KhaosT** [comment]
Err... the original ``Service.Lightbulb`` is not magic, it's defined at [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2849). To define your own service, you'll need to define it before trying to add it in that way. For how to define custom service/characteristic, please check [this example](https://github.com/devbobo/homebridge-lifx-lan/blob/master/index.js#L45).
