### ISSUE TITLE
How do you get rid of "Error: dns service error: unknown"

### ISSUE THREAD

**Issue by chabad360** [homebridge/HAP-NodeJS#367]
I had started working with HAP-NodeJS, and after finally getting node to run I was met with this ugly error:
```
/home/user/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: unknown
    at new Advertisement (/home/user/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/home/user/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/home/user/HAP-NodeJS/lib/Advertiser.js:43:30)
    at Accessory._onListening (/home/user/HAP-NodeJS/lib/Accessory.js:539:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._onListening (/home/user/HAP-NodeJS/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:188:7)
    at EventedHTTPServer.<anonymous> (/home/user/HAP-NodeJS/lib/util/eventedhttp.js:65:10)
```
The thing is, even after I reinstalled HAP-NodeJS and reinstalled all of its dependencies, it still gave me that error, so now what do I do?

I'm using the windows subsystem for linux (look it up) on windows 10 x64, but I don't think it affects anything as it is apparent from other open issues that other people have had this problem as well (I'm just putting it on top).

**Comment by tjhorner** [comment]
I am having this error too on the exact same setup, the Windows Linux Subsystem. I think Windows's networking might be breaking this, as the subsystem is still in beta...

**Comment by caasiu** [comment]
update `node-persist` to version 2.0.7 solve the `dns service error: unknown` Error
but have another error:
```
/HAP-NodeJS/lib/model/IdentifierCache.js:37
  var value = this._cache[key];
                         ^
TypeError: Cannot read property 'a1fafdd1-bad1-4d6b-98f6-a2b76a15adcf|nextIID' of undefined
```

npm => 4.1.1
node => 7.4.0
node-gyp => 3.5.0
avahi installed
@KhaosT please tell me how to fix this?

Thanks

**Comment by KhaosT** [comment]
lol it's not ``node-persist`` 2.0.7 solves the problem, instead it's the software crashes before reaching the place it throw the dns service error. HAP-NodeJS currently only work with ``node-persist`` 0.0.8~11 so you may need to downgrade it back. For the dns service error, please make sure avahi daemon is running correctly on the machine.

**Comment by caasiu** [comment]
sorry @KhaosT , it's my mistake.
I don't enable my avahi daemon. 
Thanks for your great help

**Comment by chabad360** [comment]
Avahi doesnt want to turn on in wsl...

**Comment by neophob** [comment]
you need to install apple bonjour sdk to run this package on windows

**Comment by chabad360** [comment]
and after I do that...
