### ISSUE TITLE
TargetTemperature range to small

### ISSUE THREAD

**Issue by luc-ass** [homebridge/HAP-NodeJS#372]
Hi there, would it be possible to make the range for target temperature bigger? Right now it is between 10 an 38 °C but some features of my heating system cause target temperature to be set much lower. When this happens the accessory is ignored by homebridge/HomeKit.

I would rather set the rage from 0 to 50 °C (although no one would actually use it). 

If this is not possible, can I change the range within my plugin manually?

Thanks a lot in advance!

**Comment by Kosta-Github** [comment]
the same is true for the `CurrentTemperature` value: right now the range is `0` to `100` celsius, but for an outside sensor you definitely want to have values below `0`...
see: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L643
my suggestion use a range of `-100.0` to `+100.0`...

**Comment by KhaosT** [comment]
Those values are pulled from Apple's HomeKit Accessory Simulator. I can manually change those but the ideal way is for developer to set the characteristic's min/maxValue to the proper value the actual device can handle. Is there a reason why you want me to change the default value?

**Comment by KhaosT** [comment]
Ah miss the second part, to change it from plugin, you can either do that during [characteristic initialization](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L52) or invoke [setProps](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L108) to update the value. Please be aware that you may need to remove the accessory and pair with it again in order for that to take effect.

**Comment by Kosta-Github** [comment]
oh, I wasn't aware about the fact, that I can also alter those `min`/`max` values myself, once added to an accessory... thanks for the hint.
