### ISSUE TITLE
Accessories disappearing & missing in Add Accessory screen

### ISSUE THREAD

**Issue by Shifter147** [homebridge/HAP-NodeJS#384]
Hello all! 

I encountered a strange problem with my HAP-NodeJS running on my RPI.
It runs on boot because I added it to the /etc/rc.local and set it as executed.  

It worked fine the past few days, I added some sonoff and lights. I also added some scenes to test stuff. This all worked fine! And than suddenly the scenes didn't work anymore and the accessoires where unresponsive. 

So I thought, lets remove all the accessories, reboot the PRI and start over. After removing all the accessories, only 3 out of the 8 accessories came back to the "adding" screen. I can't find out why the rest is missing. 

1) I have tried te remove the persist folder. This didn't help.
2) Tried a lot of reboots, hard and soft. Also didn't help. 
3) Reset my router, also didn't help
4) Deleted my entire Home from the Homekit app, also didn't help... 
5) I killed the node from the auto startup and ran the node Core.js manual via ssh. And strangely than all my accessories are visible in the homekit app. After rebooting they are gone again and only 3 show again.

I don't know where I have to search for or what causes this symptoms. 

So I hope someone can help me with this!

**Comment by Shifter147** [comment]
Ok, i tried a few more things to source my problem, but still can't figure it out. 

1) I reinstalled HAP-NodeJS, this didn't fix the problem. 
2) Tried a different method of start on boot, also didn't solve the problem

The thing that worked is changing the username (mac address like) of every accessory. Now all my accessories show up again. I looks like there are some remains of the "old" not working accessories somewhere on the raspberry. 

I would really like to know where this behaviour comes from. Or how i can prevent this in the future. 

Hope someone with some more expertise can react :D

**Comment by pairughdocks** [comment]
Try to change the username of the items by a digit or so. I had a similar issue and this worked for me.

**Comment by Shifter147** [comment]
I tried, but this did not help... Does anybody knows how to solve this. Can't find a solution for this and therefore can't use Homekit anymore :( :(

**Comment by OczkoSX** [comment]
Haven't you fixed it by changing username? Why not using bridgedCore?

Wysłane z iPhone'a

Dnia 02.05.2017 o godz. 22:03 Shifter147 <notifications@github.com> napisał(a):

**Comment by Shifter147** [comment]
Thanks for you comment OczkoSX, 

I changed my forever startup to BridgedCore.js and this indeed works. 
But i would like to learn what went wrong with starting Core.js. Is there some extra explanation for this behaviour?

**Comment by OczkoSX** [comment]
I had similar problems. These are the steps I were doing and they worked:
- close all Node instances
- remove persist folder
- change username and uuid of all accessories (if using Core instead of Bridge)
- remove all accessories and bridges from iPhone
- launch HAP
- if it still doesn't work, reboot iPhone 
And that's all

Wysłane z iPhone'a

Dnia 06.05.2017 o godz. 10:40 Shifter147 <notifications@github.com> napisał(a):
