### ISSUE TITLE
Thermostat Accessoriy with MQTT 

### ISSUE THREAD

**Issue by Maxmudjon** [homebridge/HAP-NodeJS#387]
[Thermostat_MQTT_Accessoriy.txt](https://github.com/KhaosT/HAP-NodeJS/files/705705/Thermostat_MQTT_Accessoriy.txt)

**Comment by Maxmudjon** [comment]
Maybe someone will need ))

**Comment by JustAmaze** [comment]
Thank you so much Maxmudjon. Do you have any better way to update the status of the accessories without interval function?
