### ISSUE TITLE
Optional Characteristic in air quality sensor do not appear

### ISSUE THREAD

**Issue by Nero5023** [homebridge/HAP-NodeJS#390]
I want add the optional Characteristics like PM2.5 Density and PM10 Density to the air quality sensor. I have already set the required characteristics and add the optional characteristics to sensor, but in homekit app it only shows the air quality, I can't find PM2.5 Density and PM10 Density.

This is my core code 
``` JavaScript
sensor
  .addService(Service.AirQualitySensor, "Air quality Sensor")
  .getCharacteristic(Characteristic.AirQuality)
  .on('get', function(callback) {
    callback(null, AIRQUALITY_SENSOR.aqi);
  });

sensor
  .getService(Service.AirQualitySensor)
  .addCharacteristic(Characteristic.PM2_5Density)
  .on('get', function(callback) {
    // AIRQUALITY_SENSOR.getStatus()
    callback(null, AIRQUALITY_SENSOR.pm2_5Density);
  });

sensor
  .getService(Service.AirQualitySensor)
  .addCharacteristic(Characteristic.PM10Density)
  .on('get', function(callback) {
    callback(null, AIRQUALITY_SENSOR.pm10Density);
  });

setInterval(function() {
  AIRQUALITY_SENSOR.ramdomizeQuality();
  // update the characteristic value so interested iOS devices can get notified
  sensor
    .getService(Service.AirQualitySensor)
    .setCharacteristic(Characteristic.AirQuality, AIRQUALITY_SENSOR.aqi);
  sensor
    .getService(Service.AirQualitySensor)
    .setCharacteristic(Characteristic.PM2_5Density, AIRQUALITY_SENSOR.pm2_5Density);
  console.log("Set");
  sensor
    .getService(Service.AirQualitySensor)
    .setCharacteristic(Characteristic.PM10Density, AIRQUALITY_SENSOR.pm10Density);
}, 3000);
```
This is the screen shoot

![img_4588](https://cloud.githubusercontent.com/assets/11721990/21989271/3f9a5e9a-dc45-11e6-8cd9-df0d58bbee73.png)
![img_4587](https://cloud.githubusercontent.com/assets/11721990/21989272/4146279c-dc45-11e6-8139-8f21cbee2815.png)

**Comment by Maxmudjon** [comment]
deleted accessory program add the newly
then it will be shown


![photo1204279221268236](https://cloud.githubusercontent.com/assets/23142922/21989453/c3916608-dc2c-11e6-8bcf-b91c8e27074d.jpg)

**Comment by Maxmudjon** [comment]
AirQualitySensor
  .addService(Service.AirQualitySensor, ismi2)
  .getCharacteristic(Characteristic.AirQuality)
  .on('get', function(callback) {    
    callback(null, SENSOR.getQuality());
  });

AirQualitySensor
  .getService(Service.AirQualitySensor)
  .getCharacteristic(Characteristic.AirParticulateDensity)
  .on('get', function(callback) {    
    callback(null, SENSOR.Density());
  });

AirQualitySensor
  .getService(Service.AirQualitySensor)
  .getCharacteristic(Characteristic.AirParticulateSize)
  .on('get', function(callback) {    
    callback(null, SENSOR.Size());
  });

AirQualitySensor
  .getService(Service.AirQualitySensor)
  .getCharacteristic(Characteristic.StatusLowBattery)
  .on('get', function(callback) {
    callback(null, SENSOR.Battery());
  });

**Comment by Nero5023** [comment]
It works but your code should be like this for `Characteristic.StatusLowBattery`, `Characteristic. AirParticulateSize `,  `Characteristic.AirParticulateDensity`
``` JavaScript
AirQualitySensor
  .getService(Service.AirQualitySensor)
  .addCharacteristic(Characteristic.AirParticulateDensity)
  .on('get', function(callback) {
    callback(null, SENSOR.Density());
  });
```
It should be `addCharacteristic`

Also, what if I want to add two or more AirParticulateDensity, what should I do.
Right now I change the AirParticulateDensity and size every 3 seconds, is any other good ways?

**Comment by Korcsog** [comment]
@Nero5023 The Home app can't show some type of Characteristic value (at the moment, maybe later it will show), but the Elgato Eve app display the values!
![img_4212](https://cloud.githubusercontent.com/assets/19993757/23584385/8708b066-0160-11e7-8065-dadba4a142fe.PNG)
