### ISSUE TITLE
Differentiating HomeKit request origins

### ISSUE THREAD

**Issue by justin-vt** [homebridge/HAP-NodeJS#393]
Does HomeKit or HAP expose any sort of unique identifier corresponding to the device that originates the request? Since automations are shared between invited guests of a home, it seems like a lost opportunity if we can't pass this information along and fire discrete actions based on whether, for example, a _particular_ iPhone device "arrives home".

A 3rd party app like Locative can do this with per-device HTTP push triggers, but it would be nice if we could do it all within HomeKit.

**Comment by KhaosT** [comment]
HAP doesn't identify user's individual iOS devices. Technically you can identify which user by public key but that's not something reliable due to the existence of remote access.

**Comment by justin-vt** [comment]
Thanks! 

Is that public key something that HAP-NodeJS picks up on? Perhaps it could be combined with other contextual factors to become a more reliable identifier.

**Comment by KhaosT** [comment]
It's picked up but I don't think it's exposed to other components. If you need I can try to put that in characteristic r/w context.

**Comment by justin-vt** [comment]
That would be awesome. Out of curiosity, is this the clientPublicKey you see in the _handlePairVerifyX() methods? I dumped clientUsername also, but that doesn't seem to correspond to any of iOS devices. Although I did see my Apple TV pop up there (I think?)

**Comment by KhaosT** [comment]
Yup, it's a UUID generated by HomeKit on iOS. It remains the same for all iOS devices under the same iCloud account. So technically you can use that to identify which user send the command I guess.

**Comment by justin-vt** [comment]
Any more thoughts on how you might expose this in a characteristic? I'm having a hard time wrapping my head around where to access this, since it is outside the context of an accessory or specific service -- would it be available as a property of every service?

**Comment by KhaosT** [comment]
Probably just put the uuid in the context of [`set`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L32) event

**Comment by justin-vt** [comment]
Ah, yes! I see. That would be brilliant!

**Comment by justin-vt** [comment]
I think I have this working in principle. It looks like `M5Packet[HAPServer.Types.USERNAME]` is what we're looking for. I've verified that my iPad and iPhone generate the same value, and my wife's iPad generates a different one (different iCloud account, but same HomeKit home.)

I added an additional parameter to `set-characteristics` event (as with `sessionID`) and then I'm stuffing it into the context in the Characteristic `setValue() `function. I can then pull it out of the context in my homebridge plugin.

Out of curiosity, do you know what this username value actually is? It looks like it's an sha1 hash of something, but I'm not sure what. I can dump the values using debug statements, but it would be cool to be able to derive it directly from an iCloud account.

Amazing work with these handlePairVerify() methods, by the way -- once I dug into them I saw miraculous it was that you were able to reverse engineer the pairing process.

**Comment by rodorgas** [comment]
Hey @justin-vt nice work! I'm also interested on this issue, could you share your code?

**Comment by justme-1968** [comment]
ist this username the same if a device is used local or remotely via a homekit hub? i.e. does it really identify the device the request is originating from or just the 'last hop' in the chain.

**Comment by jpditto** [comment]
@rodorgas, here's my HAP-NodeJS patch for v4.22. I haven't updated it since 4.22 unfortunately (if it ain't broke, don't fix it!), but you can get the gist of it and roll a new patch. 

@justme-1968 the ID seems to remain consistent when remote vs. local, but it's a bit fickle, mine seems to have changed with my upgrade to iPhone 7 and/or iOS11. I need to follow up on that.

[justin-vt-hap-no-js-lib-4.22.patch.txt](https://github.com/KhaosT/HAP-NodeJS/files/1441671/justin-vt-hap-no-js-lib-4.22.patch.txt)

**Comment by jpditto** [comment]
Here's the patch against the current 0.4.36 version of HAP-nodejs. I can confirm it working - I see my wife's 33 digit identifier in Indigo when I turn on the light with her iPad, and my own when I turn on the light with my iPhone.

Good news @justme-1968 .. it looks like the identifier is in fact the same as it was 6 months ago, and it's unique to the device, homekit hub or not. I think it's bound to the Apple ID, because it's the same whether I use my iPad or iPhone. 

[justin-vt-hap-no-js-lib-4.36.patch.txt](https://github.com/KhaosT/HAP-NodeJS/files/1442538/justin-vt-hap-no-js-lib-4.36.patch.txt)

**Comment by ebaauw** [comment]
Cool.  Could you also derive this way whether the user is an Administrator for the home?  See https://github.com/nfarina/homebridge/issues/1389.

**Comment by jpditto** [comment]
Well, since I know which of our two IDs is the administrator, I can make rules based on that ;-) .. but I'm unaware of anything we can put in the context that indicates whether the client is an administrator or not. Maybe @khaosT would know.

**Comment by KhaosT** [comment]
@jpditto HomeKit provides information about whether or not a UUID is admin of the home when it adds the key. However, we are not saving it at any place so it's lost...

**Comment by jpditto** [comment]
@khatosT could I pass it along like I'm doing with client ID? See HAPServer.js in my patch:
```
    }.bind(this)), false, session.sessionID, session.encryption.clientUsername); // clientUsername added by justin-vt
```
I just don't know what is available other than clientUsername...

**Comment by jpditto** [comment]
Ugh, I just now realized I've been posting from my work account. justin-vt = jpditto ;-)

**Comment by KhaosT** [comment]
No, the problem is those information already lost in current version and there is no way to recover it.

**Comment by justin-vt** [comment]
There we go, back to normal. Sorry, @ebaauw sounds like we can't pass that along unless it's made available.
