### ISSUE TITLE
Error: listen EADDRINUSE :::51826

### ISSUE THREAD

**Issue by StefanMeGit** [homebridge/HAP-NodeJS#395]
Since today i got an new error... absolutely no idea where is it coming from. 

`HAP-NodeJS starting...
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: MotionSensor_accessory.js
Parsing accessory: Outlet_accessory.js
Parsing accessory: TemperatureSensor_accessory.js
Parsing accessory: Thermostat_accessory.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/home/pi/HAP-NodeJS/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/home/pi/HAP-NodeJS/lib/HAPServer.js:158:20)
    at Accessory.publish (/home/pi/HAP-NodeJS/lib/Accessory.js:496:16)
    at /home/pi/HAP-NodeJS/Core.js:32:13
    at Array.forEach (native)`

**Comment by heuels** [comment]
Hey, @StefanMeGit. I'm almost certain it means you already have HAP-NodeJS running on your machine. Look in your running processes for PID of `node Core.js` and then `kill -9 PID` it.

**Comment by elmotard** [comment]
Hello, @StefanMeGit. I managed to solve this problem. You need to change the `port ` of your JavaScript file of executing.
The port that you used maybe use by an other application.

PS: Sorry if I make mistakes in English, I'm a french.

**Comment by Maxmudjon** [comment]
terminal: killall node

**Comment by shrawan2015** [comment]
In addition to @heuels answer:- 

ps aux | grep node

shrawans         62831   0.0  0.0  2433828   1852 s004  S+    2:32PM   0:00.00 grep node
shrawans         62684   0.0  0.2  3069196  18176 s005  T     2:23PM   0:00.29 node BridgedCore.js
shrawans         62507   0.0  0.4  3183972  34220   ??  S     2:12PM   


kill -9 PID

Note: PID is second column in above result.

**Comment by thifabri** [comment]
Hi all,

I have the same problem here and i have no idea to solve it. I use just one instance and I don't have a automatic process to start the homebridge.

I can execute the homebridge perfectly only one time. If I need stop and restart the homebridge occurred this issue. So, I need reboot the RBP and start the service again.

How can I solve it?

Best,
Thiago

**Comment by kjetisve** [comment]
This is also true for me. Is it because I am using _forever_? Tried changing the port in Core.js, but no luck.
