### ISSUE TITLE
Garagaedoor with bluetooth

### ISSUE THREAD

**Issue by ddilbaz** [homebridge/HAP-NodeJS#396]
Hello
I connected the bluetooth to the garage door with "Open Sesame". I turn it on and off with the Apple app. How can I make Homekit feature on this product.

**Comment by heuels** [comment]
Hello, @ddilbaz. 

Is [this](https://www.mygarageopener.com/) your garage door opener? Unfortunately there are no detailed specifications available for the protocol Open Sesame uses, apart from the obvious Bluetooth 4.0 and I was unable to failed to find any open library that supports it. 
So, I'm afraid that it's not easily achieved: one would need to sniff the traffic between iOS/Android app and the devce itself.

**Comment by ddilbaz** [comment]
Hello # @heuels 
When I scan the Bluetooth product, the following results appear:

on -> stateChange: poweredOn
on -> scanStart
on -> discover: {"id":"cd6bd9c44227","address":"cd:6b:d9:c4:42:27","addressType":"random","connectable":true,"advertisement":{"localName":"4623A10703\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","txPowerLevel":0,"manufacturerData":{"type":"Buffer","data":[76,0,2,21,87,112,0,0,162,135,17,228,141,93,0,2,165,213,197,27,18,15,41,207,203,75]},"serviceData":[],"serviceUuids":["fff0"],"solicitationServiceUuids":[],"serviceSolicitationUuids":[]},"rssi":-85,"state":"disconnected"}
on -> scanStop
on -> connect
on -> RSSI update -84
on -> peripheral services discovered {"uuid":"1800","name":"Generic Access","type":"org.bluetooth.service.generic_access","includedServiceUuids":null},{"uuid":"1801","name":"Generic Attribute","type":"org.bluetooth.service.generic_attribute","includedServiceUuids":null},{"uuid":"180a","name":"Device Information","type":"org.bluetooth.service.device_information","includedServiceUuids":null},{"uuid":"fff0","name":null,"type":null,"includedServiceUuids":null},{"uuid":"ff70","name":null,"type":null,"includedServiceUuids":null},{"uuid":"1802","name":"Immediate Alert","type":"org.bluetooth.service.immediate_alert","includedServiceUuids":null},{"uuid":"ff30","name":null,"type":null,"includedServiceUuids":null},{"uuid":"ff60","name":null,"type":null,"includedServiceUuids":null},{"uuid":"1804","name":"Tx Power","type":"org.bluetooth.service.tx_power","includedServiceUuids":null},{"uuid":"ff80","name":null,"type":null,"includedServiceUuids":null},{"uuid":"ff40","name":null,"type":null,"includedServiceUuids":null},{"uuid":"180f","name":"Battery Service","type":"org.bluetooth.service.battery_service","includedServiceUuids":null},{"uuid":"1530","name":null,"type":null,"includedServiceUuids":null}
on -> service included services discovered
on -> service characteristics discovered {"uuid":"2a00","name":"Device Name","type":"org.bluetooth.characteristic.gap.device_name","properties":["read"]},{"uuid":"2a01","name":"Appearance","type":"org.bluetooth.characteristic.gap.appearance","properties":["read"]},{"uuid":"2a04","name":"Peripheral Preferred Connection Parameters","type":"org.bluetooth.characteristic.gap.peripheral_preferred_connection_parameters","properties":["read"]}
on -> characteristic read 4623A10703 false
<Buffer 34 36 32 33 41 31 30 37 30 33 00 00 00 00 00 00 00 00>
on -> disconnet

**Comment by heuels** [comment]
@ddilbaz Please see [this](https://learn.adafruit.com/reverse-engineering-a-bluetooth-low-energy-light-bulb/sniff-protocol) article from Adafruit about reverse-engineering a Bluetooth Low Energy light bulb, it may get you started.
