### ISSUE TITLE
I can connect many camera in HAP-NodeJS ?

### ISSUE THREAD

**Issue by Maxmudjon** [homebridge/HAP-NodeJS#399]
and how can I set up separately ?
I would like to like this 

// Publish the camera on the local network.
cameraAccessory.publish({
  username: "EC:22:3D:D3:CE:CE",
  port: 51062,
  pincode: "000-00-000",
  category: Accessory.Categories.CAMERA,
  ipsi: "rtsp://192.168.1.115/live1.264?user=abs&passwd=123"
}, true);

**Comment by heuels** [comment]
Hello, @Maxmudjon.

I believe you have already read [the Wiki article about IP Camera support](https://github.com/KhaosT/HAP-NodeJS/wiki/IP-Camera). 
In order to connect several cameras I would run separate instances of `Core.js`, one for each camera.

**Comment by utya1988** [comment]
hello, @heuels 
how can i run separate instances of CameraCore.js one for each camera.
Thanks

**Comment by OczkoSX** [comment]
Write simple manager and run multiple forever instances. The easiest way.

Wysłane z iPhone'a

Dnia 16.03.2017 o godz. 19:03 utya1988 <notifications@github.com> napisał(a):
