### ISSUE TITLE
Pairing stops after step 1 on iOS 10.3 beta

### ISSUE THREAD

**Issue by mechdrew** [homebridge/HAP-NodeJS#400]
I have been using HAP-Nodejs on a Raspberry Pi successfully for several months now. I recently tried to add a custom camera to my setup but was unable to complete pairing with the device. Using debug I found that step 1 of the pairing process would show up in the output but after entering the pin code it never proceeded, eventually it would time out. I tried updating all of the modules, rebuilding, and even renaming the device, all in vain. As a last resort I deleted my persist cache and removed all devices from the Home app, but now I can't finish pairing with the accessories I previously had working fine. I have even reverted back to only the accessories before this whole problem began with no effect. The only thing I can think of that could be causing the issue is that I am using the iOS 10.3 public beta released last week and that it has somehow broken compatibility.

**Comment by KhaosT** [comment]
I just tried with 10.3 and it's working properly. Please make sure your accessory is returning correct values.

**Comment by Maxmudjon** [comment]
And I also e works perfectly with iOS 10.3 beta 1

**Comment by neophob** [comment]
i tested hap-nodejs on multiple devices. however it looks like sometimes a iphone/hap server combo can be stuck. i cannot discover one device on my iphone (deleted all data i could on iphone and hap server), but the same device can be discovered on another iphone. sounds like a ios bug, where some stalled data exists. someone else discovered a similar issue?
