### ISSUE TITLE
Nothing happend after “node Core.js”

### ISSUE THREAD

**Issue by ghost** [homebridge/HAP-NodeJS#401]
The program stop at “HAP-NodeJS starting…” after “node Core.js” Please help me.

**Comment by heuels** [comment]
Hello, @DTO213. Please clarify, have you changed the default accessory files or added any new ones?

**Comment by DTO213** [comment]
I didn't change anything.I will try to reinstall it.

**Comment by lettierimarco** [comment]
if you didn't changed nothing is correct it doesn't do anything else.
Check on your iphone the app "Home" or if you find devices under HAP bonjour service

**Comment by Supereg** [comment]
The stale bot seems to be bugged, gonna close it from hand as the issue seems stale.
