### ISSUE TITLE
Connection delay of 1 device seems to affect other devices

### ISSUE THREAD

**Issue by gvuyk** [homebridge/HAP-NodeJS#411]
I recently removed one of my devices from the network and noticed that Home app now takes longer to show the status of the other still connected devices

When my server app asks these devices for their status, it uses a timeout of 5 seconds. But if all devices reply within the first 500ms except the disconnected one, the Home app still displays "updating" under each device until those 5 seconds have ellapsed.

Of course the easiest thing to do here is decrease my timeout to 1 second and go get fresh air
But :)
Any ideas? All the devices are under a bridge running on an RPi2

**Comment by snowdd1** [comment]
Which plugin do you use for this? How do you configure the timeout?

**Comment by gvuyk** [comment]
The server uses MQTT ([mcollina/mosca](https://github.com/mcollina/mosca)) to communicate with devices. Each status request sent from the server to a device is bundled with a `requestId` wich the devices use when they reply, this way each time the server receives a response it knows wich request it received a response for, and then executes the right callback (the one from the accesories on('get') ).

I can see on the server logs that all the callbacks are executed except the ones for wich the server didn't get a response (disconnected device) as one would expect. Then, the timeout kicks in 5 seconds later and the remaining callback is executed with an error parameter, and thats when the Home app on the iphone gets updated

If I reconnect the disconnected device, the Home app updates almost instantly
