### ISSUE TITLE
Thermostat_accessory.js  + Temperature Sensor + Relay

### ISSUE THREAD

**Issue by Pollo1990** [homebridge/HAP-NodeJS#416]
It is possible to get it working with a TEMPERATURE SENSOR ( DS18B20 ) and a RELAY attached to the 
electric heaters ?
 
Thank.

**Comment by profesionalTI** [comment]
Yes, is possible, but I can't get enough help on this forum, I'm new on this, The thermostat accessory not work fine, you need to make some setting, but I don't know how.

You can set thermostat to work fine? (what need I do?)

**Comment by dean9** [comment]
In Thermostat_accessory.js, add your code to latch the relay inside the "TARGET_TEMPERATURE_CTYPE" ctype's onUpdate anonymous function.  I use python-shell to get my python scripts executed there (https://www.npmjs.com/package/python-shell).

To get temperature data displayed in the iOS app, I added a separate TemperatureSensor_accessory file. There you can do something like this 

`
setInterval(function() {  
    var j = require('current_temp');
    TEMP.currentTemperature = j.temp;
  
  // update the characteristic value so interested iOS devices can get notified
  sensor
    .getService(Service.TemperatureSensor)
    .setCharacteristic(Characteristic.CurrentTemperature, TEMP.currentTemperature);
  
}, 3000);
`

To grab your latest temperature measurement from a json file every 3 seconds.
