### ISSUE TITLE
Motion sensor notification over apple tv

### ISSUE THREAD

**Issue by rahulmranjith** [homebridge/HAP-NodeJS#418]
I have done all the setup with raspi camera and put sensor and added all those to same room
On sensing a motion the alert is shown with a captured jmage and clicking image takes to live stream 

This works well within WiFi and home network. Once my phone is connected to 4G/ data network

**Comment by rahulmr999** [comment]
the notification alerts works for some time .Then I don't get the notification alert through the mobile data network . 

What could be the issue ?

**Comment by brownad** [comment]
I don't think motion sensor is pushed to outside of wifi. Someone can probably confirm?

**Comment by rahulmr999** [comment]
Hey for me it's working but is inconsistent. It worked for me yesterday whole day but today it's not working 🙂

**Comment by jspv** [comment]
Having very similar experience with Motion Sensor events; inconsistent propagation of MotionDetected state changes and seldom when not locally connected. 

(https://github.com/nfarina/homebridge/issues/1182)

**Comment by rahulmr999** [comment]
Could that be an issue with Apple TV or with the hap Nodejs server we have got ? Any idea ?

**Comment by jspv** [comment]
See linked issue above. It **appears** that my test iOS device unregisters from the MotionDetected event just after registering. Not sure if this is what is really happening or if it's a bug in HAP or homebridge at this point.

**Comment by rahulmr999** [comment]
who should be able to throw some light on this ? without a stable notification mechanism through the internet/mobile data I feel the accessories like the motion sensor/door lock would be of less use . No point in having the notifications work only when at home (:

**Comment by jspv** [comment]
I believe I've tracked much of this to an iOS bug which appears to have been fixed in the 10.3 beta.  For now, I'm working around the bug in my fork by having HAP-NodeJS ignore 'Unregister' requests for the "Motion Detected" characteristic.  Not sure if this might cause other issues, but it's working for me.  
https://github.com/jspv/HAP-NodeJS

**Comment by brownad** [comment]
Still occurs for me even on 10.3 😒

**Comment by NorthernMan54** [comment]
I applied the fix mentioned earlier in this thread to my environment a few weeks ago and it has been stable since.  I would recommend doing the same.

**Comment by brownad** [comment]
Should it be considered to be merged back to this repo then?

**Comment by KhaosT** [comment]
I'm not really sure about this one... Have you guys tried toggling the "Allow Notifications" in Home app for motion sensor? If not, try toggle it off, wait for a few minutes and then toggle it back on.

**Comment by brownad** [comment]
Same need to restart HomeKit to get back to normal until it stops normally a day will do it

**Comment by brownad** [comment]
Correction homebridge not HomeKit 😐

**Comment by simonrb2000** [comment]
I have replace me Accessories.js and HAPServer.js files with the ones from your repo jsvp then restarted homebridge. This hasn't fixed the issue for me. Have I missed something? 

Cheers

**Comment by ebaauw** [comment]
I can confirm that the bug appears in tvOS 10.2.1 and that @jspv's hack works around it.  The bug doesn't appear in iOS 10.3.2.  Consequently, `Motion Detected` events are sent to iOS devices over WiFi, but not to the AppleTV, and therefore not to iOS devices over 4G.

iOS devices connected over WiFi show a Motion Detected notification, but iOS devices connected over 4G generally don't.  However, you might still see the notification on an iOS device connected over 4G, when another iOS device is connected over WiFi and the notification to the WiFi-connected iOS device is synced over iCloud.

HomeKit automations with a condition on `Motion Detected` don't fire on the AppleTV, but they do on an iPad setup as HomeKit Hub.

**Comment by ebaauw** [comment]
As far as I can tell: no change in tvOS 10.2.2.

**Comment by rodhall** [comment]
@jspv how do I implement your fork with Homebridge?

**Comment by NorthernMan54** [comment]
As discovered by @ebaauw this was resolved in tvOS 11, and this issue can be closed.

**Comment by jspv** [comment]
Confirmed on my end as well, no longer any need for the hack.
