### ISSUE TITLE
Service.HeaterCooler is not supported by iOS10

### ISSUE THREAD

**Issue by viatsyshyn** [homebridge/HAP-NodeJS#420]
Hello,

I'm building a small heater controller device based NodeMCU and RasPI. And I've been trying for a while to make Service.HeaterCooler work, but failed. May be somebody had more luck and can advice me on this service.

I use HAP-NodeJS v0.4.21.

**Comment by viatsyshyn** [comment]
Looks like the set of supported Services is small

Apple Docs: [Accessory Service Types](https://developer.apple.com/reference/homekit/hmservice/accessory_service_types)

**Comment by snowdd1** [comment]
That list looks like the first version for ios8, we know that there are much more by now.
