### ISSUE TITLE
Access Through Internet

### ISSUE THREAD

**Issue by vbbalaji** [homebridge/HAP-NodeJS#424]
1. I installed HAP
2. I brough Apple TV 3rd Gen into the network
3. Im able to add Accessories through Homekit and through EVE/Elgato
4. Im able to control the switches from 3 different devices (iphones, ipad). Works like a charm!
5. BUT if I go out of Wifi, Im not able to see/control the devices.

I have kept AppleTV in network and when Im in wifi, I can see the message in Homekit : "AppleTV Connected" under "Home Hubs" screen of "My Home"

When Im out of WiFi and using Verizon 4G it says "AppleTV not responding"

**Comment by NorthernMan54** [comment]
That is a well used configuration, please ensure that you have followed all the troubleshooting steps from Apple for these issues.  Including 2 factor authentication.

**Comment by rahulmr999** [comment]
Try logging out from the icloud in apple tv and in the iphone as well . Sign in again and check.

**Comment by vbbalaji** [comment]
I did. Many times. BTW, I moved the appleTV out of the equation and added an iPad and everything works! I was able to control through iCloud. Mystery is why appleTV wont work!

Anything I can troubleshoot?

**Comment by hbpng** [comment]
Only Apple TV 4th generation able to works remotely

**Comment by justme-1968** [comment]
gen3 also works.

**Comment by vbbalaji** [comment]
@justme-1968 Could you please assist me in debugging this? Im able to get it to work with an iPad but not the AppleTV.

**Comment by NorthernMan54** [comment]
When I ran into a similar issue with homebridge, I tried all the apple troubleshooting steps.  Then I basically reset  everything, and then it just worked afterwards.

And when I say reset, I removed the .homebridge/persist and .homebridge/accessories direct and changed the 'username' in the config file.  And removed everything from Home App, then added again.

**Comment by justme-1968** [comment]
exactly. just one more thing: wait. sometimes it takes a few hours till the apple-tv is reachable after the first login.

**Comment by vbbalaji** [comment]
Interesting thing I noticed when I started doing what you guys mentioned

1. I removed the iPad from being the node
2. I signed out of AppleTV iCloud
3. Now I fired the Home app in my iPhone it said "accessories are not
responding" or something like that

4. I restarted the AppleTV
4. I signed into the AppleTV
5. I restarted the AppleTV again
6. Now I started the home app (again) in my iPhone
It said "AppleTV is not responding"!!

This means its able to "see" the AppleTV as the hub but the darn AppleTV is
not responding!!

I have enabled Key chain in my iphone, my AppleTV has the latest version of
software.

*sigh* this still doesnt work....

**Comment by justme-1968** [comment]
stop the home app, restart homebridge and try again with home. if it still does not work wait for one hour and try again.

**Comment by vbbalaji** [comment]
I dont have homebridge. Im using HAP-NodeJS --> iPad --> Home app on iPhone over internet.

I will restart everything and revert back with feedback. This is the order of switching on Im planning

1. Start RPi
2. Start Node Core.js
3. Start Apple TV
4. Restart iPhone and try from LTE!!

**Comment by vbbalaji** [comment]
Probably this is moot, but apparently Apple has revoked access from older AppleTV. Even though I can see my AppleTV as a "controller" it shows as "Disabled". Probably we should update the documentation to show that you need Newer AppleTV or an iPad Air or above.

**Comment by justme-1968** [comment]
no. apple has not revoked support for Apple TV gen3.

**Comment by maragelis** [comment]
You have to enable two factor authentication for homekit to work. Go into your icloud settings on an ios device and enable two factor, then logout of all your devices and login again. I was battling this for days.
One other thing. If you had two factor enabled (through apple web) go into your account settings and disable it, then enable it on ios.
