### ISSUE TITLE
pressure sensor

### ISSUE THREAD

**Issue by blacklykich** [homebridge/HAP-NodeJS#430]
i want to add air pressure sensor but i didnt find it in homekittypes

**Comment by justme-1968** [comment]
there is no default service class for this at the moment. you have to use a custom one and a custom characteristic for this.

have a look here: https://gist.github.com/gomfunkel/b1a046d729757120907c 

this shows the uuids that elgato uses and eve recognizes.

**Comment by mrose17** [comment]
@blacklykich - take a look at https://github.com/homespun/hap-nodejs-community-types/blob/master/types.js#L345

**Comment by mrose17** [comment]
which includes those definitions and others...
