### ISSUE TITLE
Momentary push button?

### ISSUE THREAD

**Issue by sszczep** [homebridge/HAP-NodeJS#439]
Hi. Are there any buttons in Homekit? I'd like to press it once in app and it would call a function in my node function. I was thinking about making regular switch and then set timeout to flip it off, but maybe there is a better solution. Thanks in advance

**Comment by KhaosT** [comment]
For trigger you have [this](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L3145)

**Comment by OczkoSX** [comment]
[https://github.com/KhaosT/HAP-NodeJS/issues/134#issuecomment-248993321](url)

I don't have a physical button. I want to send impulses from home app

**Comment by OczkoSX** [comment]
Or maybe you will find a better way of handling this. My LEDs have different modes and i'd like to switch between them. I was thinking about a button to switch them one by one.

**Comment by OczkoSX** [comment]
`var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;

var state = false;

var accUUID = uuid.generate('hap-nodejs:accessories:switch');

var acc = exports.accessory = new Accessory("Switch", accUUID);

function unFlip() {
  console.log("Unflipping...");
  state = false;

  acc.getService(Service.Switch)
    .getCharacteristic(Characteristic.On)
    .updateValue(state);
}

acc.username = "1A:AA:AA:AA:AA:AA";
acc.pincode = "031-45-154";

acc.on('identify', function(paired, callback) {
  console.log("Identify switch");
  callback();
});

acc.addService(Service.Switch, "Switch")
  .getCharacteristic(Characteristic.On)
  .on('get', function(callback) {
    console.log("The current state is %s", state ? "on" : "off");
    callback(null, state);
  })
  .on('set', function(value, callback) {
    console.log("The switch has been flipped");
    state = value;
    if(value) setTimeout(unFlip, 100);
    callback();
  });
`

I made something like that to make it act as a button.
