### ISSUE TITLE
Dynamic changing name of accessory

### ISSUE THREAD

**Issue by sszczep** [homebridge/HAP-NodeJS#440]
Hi. Is it possible to change the name of accessory using a function? I'd like to change it every 10 secs

**Comment by KhaosT** [comment]
Nope, once the accessory is paired, user has to change accessory name from HomeKit side.

Best Wishes,
Tian

**Comment by OczkoSX** [comment]
Hmm, but is it somehow possible to make something like a label/state indicator? I'm changing modes using switch and would like to know what is the currently mode using Home app.

**Comment by kajaba** [comment]
Thats what Home app does for you.. Just name your accessory and based on accessory type the Home app shows the state of the accessory.
