### ISSUE TITLE
mdns cross-compile(MIPS) for OpenWrt success but run BridgeCore failed

### ISSUE THREAD

**Issue by js-john** [homebridge/HAP-NodeJS#442]
Terminal logs:

john@john-Parallels-Virtual-Platform:~/Desktop/sdk/HAP-NodeJS$ sudo npm install  --arch=mips mdns
npm WARN package.json curve25519@1.0.0 No repository field.
npm http GET https://registry.npmjs.org/mdns
npm http 304 https://registry.npmjs.org/mdns
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings

> mdns@2.3.3 install /home/john/Desktop/sdk/HAP-NodeJS/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/john/Desktop/sdk/HAP-NodeJS/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_update_record.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
  COPY Release/dns_sd_bindings.node
make: Leaving directory '/home/john/Desktop/sdk/HAP-NodeJS/node_modules/mdns/build'
mdns@2.3.3 node_modules/mdns
├── bindings@1.2.1
└── nan@2.3.5

**Then I compress the HAP-NodeJS folder and copy it to the router, then extract on the router**

**run node BridgedCore.js failed**

root@OpenWrt:/mnt/sda/homekit/HAP-NodeJS# node BridgedCore.js 
node: '/mnt/sda/homekit/HAP-NodeJS/node_modules/mdns/build/Release/dns_sd_bindings.node' is not an ELF executable for MIPS

/mnt/sda/homekit/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
          ^
Error: File not found
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/sda/homekit/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
root@OpenWrt:/mnt/sda/homekit/HAP-NodeJS# 
root@OpenWrt:/mnt/sda/homekit/HAP-NodeJS# npm -v
-ash: npm: not found
root@OpenWrt:/mnt/sda/homekit/HAP-NodeJS# node -v
v0.10.17
root@OpenWrt:/mnt/sda/homekit/HAP-NodeJS# vim test.js        # console.log('hello world')
root@OpenWrt:/mnt/sda/homekit/HAP-NodeJS# node test.js 
hello world

**Comment by neophob** [comment]
might be a bit OT, but I think replacing mdns with https://github.com/watson/bonjour might simplify compiling HAP significant.

**Comment by imReker** [comment]
You may need the OpenWRT toolchain to cross compile.

[dns_sd_bindings.zip](https://github.com/KhaosT/HAP-NodeJS/files/1652244/dns_sd_bindings.zip) This is for MT7620A and works fine.
