### ISSUE TITLE
Home doesn't show any accessory

### ISSUE THREAD

**Issue by Supersimo88** [homebridge/HAP-NodeJS#444]
I did a clean installation, it worked smoothlybefore and now I can't see anye accessories on the phone.
During the pairing process does not show anything, I tried both with Core and with BridgedCore but nothing has changed, activating the debug I see nothing like the iphone does not communicate with the HAPNode server itself that is on the raspberry, of course i'm on the same network.

DEBUG:
pi@raspberrypi:~/HAP-NodeJS $ sudo DEBUG=* node Core.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
  AccessoryLoader Parsing accessory: Fan_accessory.js +0ms
  AccessoryLoader Parsing accessory: GarageDoorOpener_accessory.js +336ms
  AccessoryLoader Parsing accessory: Light_accessory.js +169ms
  AccessoryLoader Parsing accessory: Lock_accessory.js +94ms
  AccessoryLoader Parsing accessory: MotionSensor_accessory.js +66ms
  AccessoryLoader Parsing accessory: Outlet_accessory.js +104ms
  AccessoryLoader Parsing accessory: TemperatureSensor_accessory.js +54ms
  AccessoryLoader Parsing accessory: Thermostat_accessory.js +80ms
  EventedHTTPServer Server listening on port 51826 +906ms
  EventedHTTPServer Server listening on port 51827 +147ms
  EventedHTTPServer Server listening on port 51828 +94ms
  EventedHTTPServer Server listening on port 51829 +68ms
  EventedHTTPServer Server listening on port 51830 +83ms
  EventedHTTPServer Server listening on port 51831 +69ms
  EventedHTTPServer Server listening on port 51832 +80ms
  EventedHTTPServer Server listening on port 51833 +81ms

**Comment by OczkoSX** [comment]
- close all Node instances
- remove persist folder
- change username and uuid of all accessories (if using Core instead of Bridge)
- remove all accessories and bridges from iPhone
- launch HAP
- if it still doesn't work, reboot iPhone
