### ISSUE TITLE
Multiple function device in single _accessory.js

### ISSUE THREAD

**Issue by Shifter147** [homebridge/HAP-NodeJS#445]
Hello all! 

I'm sorry to post this here because it is not an issue. But i have no knowledge of a forum where Hap-NodeJS is widely discussed. 

I'm currently working an a room sensor powered by an esp8266 which includes the following functions:
- Temperature
- Humidity
- Movement 
- Air Quality
- C02 values
- Light intensity
- Smoke detection

The hardware side and Arduino software side of the projects works and ik can send all the data via MQTT. Now i only have to make the software for the HAP-NodeJS side. This is where my experience lags a bit.... 

Is it possible to make a single _accessory.js file for my roomsensor? I don't know how ik can include al this function into a single file because there are multiple devices and i have to choose the correct device type  . I have only made (changed software) some lights, switches and a fan. But these devices all have 1 device type instead of 7. 

Im still learning to program software and I hope someone can push me in the right direction.

Thank you in advance! :)

**Comment by NorthernMan54** [comment]
This might be easier if you used homebridge instead of hap-nodejs, there are a lot of existing integrations and examples of what you are looking to make.

Also, if you look around I think there is also an esp8266 code base floating around that directly talks to HomeKit, vastly simplifying your software build. 

https://github.com/HomeACcessoryKid/ESP8266-HomeKit

**Comment by Shifter147** [comment]
I know it will be easier to use homebridge. But i would like to know if it is even possible to do in HAP-NodeJS. I don't know if Homekit allows a single device with 7 functions. 

Will look at the link you provided. Thanks!

**Comment by OczkoSX** [comment]
You can make multiple accessories in one file. You just need to change the file name from _accessory to _accfactory and do some changes with modules export. Then you can simply connect to a Mqtt broker

**Comment by snowdd1** [comment]
May I point to https://github.com/KhaosT/HAP-NodeJS/issues/429#issuecomment-294282419 for multiple accessories.  

However, I think you are talking about **functions** (which are called `services` in Homekit) and AFAIK each accessory can have quite a lot of services (I guess another place for Apple's magical 99 limit). But if you want to have multiple services of the same type in one device you need to give them a distinct subtype in the constructor.
