### ISSUE TITLE
How do you link it with a MQTT server or any other server for that matter? 

### ISSUE THREAD

**Issue by zohairshafi** [homebridge/HAP-NodeJS#448]
Hello, I'm a bit of a novice in this field, and was wondering if anyone could help me out with connecting the HAP-NodeJS app with an MQTT server. Im using an ESP-8266 for the hardware side, and can't figure out how to broadcast to the ESP-8266 from my Raspberry Pi running HAP-NodeJS with the relevant data from the output of running 'node Core.js'. 

Thanks in advance!

**Comment by OczkoSX** [comment]
You need a mqtt broker. Than you simply connect to the broker from your accessory file (Look for NPM MQTT)

**Comment by zohairshafi** [comment]
That's it? Thanks a lot! 
So i ran npm install mqtt and I've got it installed. 

Will this server now run whenever HAP-Nodejs runs? 

Also, is there any way to confirm that my MQTT server is up and running? 

Thank you again!

**Comment by OczkoSX** [comment]
You need an external broker (server). Look for mosquito 

Wysłane z iPhone'a

Dnia 22.05.2017 o godz. 15:47 Zohair Shafi <notifications@github.com> napisał(a):

**Comment by zohairshafi** [comment]
Thank you!
Mosquitto is to check if the broker I installed via 'npm install mqtt' is working, yes?

**Comment by OczkoSX** [comment]
No. You need to set up a mqtt server on mosquito. You connect to this server using mqtt from npm. Find some tuts about connecting esp to rpi using mqtt. There are a lot of them 

Wysłane z iPhone'a

Dnia 22.05.2017 o godz. 16:15 Zohair Shafi <notifications@github.com> napisał(a):

**Comment by zohairshafi** [comment]
Alright, thank you so much!

**Comment by davea** [comment]
Check out [homekit2mqtt](https://github.com/hobbyquaker/homekit2mqtt) too, it's super simple to bridge between HAP and MQTT.

**Comment by zohairshafi** [comment]
Will do, thank you!
