### ISSUE TITLE
Speaker accessory

### ISSUE THREAD

**Issue by AlessandroFerri** [homebridge/HAP-NodeJS#452]
Hi to all,
I would like to create a homekit accessory for a loudspeaker. I have tried with failure to create it, and I tried it in several ways. I wonder if it is possible to have an example of accessory type Speaker_accessory.js that works.

Thanks for help.

**Comment by piejanssens** [comment]
@KhaosT Is this possible at all? Have a HomeKit accessory that allows controlling volumne/muting?
I'm also looking for an example, but I'm reading a lot of confusing things about speaker in HomeKit.

**Comment by ebaauw** [comment]
Yes, my [homebridge-zp](https://github.com/ebaauw/homebridge-zp) plugin for Sonos has been offering that for years.  While defined by Apple, neither the Apple Home app nor Siri recognise the Speaker service, nor the Volume and Mute characteristics, but they work fine with other HomeKit apps.  If you want to control the volume from Siri, you might want to use the Brightness or Rotation Speed characteristic instead, see the `”service”` config.json key in homebridge-zp.

**Comment by piejanssens** [comment]
@ebaauw As you might have guessed, being able to control the volume of my amp with Siri is the only reason I'm interested in this. Your plugin looks like a great solution! However I'm using NodeRed with the node-red-contrib-homekit module (devices are controlled via OH bindings over MQTT). I don't see how I can apply the same method there (yet). 
If I would use a Lightbulg with Brightness characteristic, that would not allow me to control it by natural langauage as in "Turn volume up" right?

**Comment by ebaauw** [comment]
If you name the lightbulb “volume” you can say “set volume to 10%”.  Unfortunately, Siri will also change the volume if you say “set living room lights to 50%” (assuming the speaker lightbulb is in the living room).
