### ISSUE TITLE
Update status on iOS after curl request

### ISSUE THREAD

**Issue by p3ntium** [homebridge/HAP-NodeJS#458]
Hello:
I'm trying to update the accessory status after the switch on or off via curl.
I.E: I do the following request:

`curl -X PUT http://localhost:51829/characteristics --header "Content-Type:Application/json" --header "Authorization: 000-02-012" --data "{\"characteristics\":[{\"aid\":1,\"iid\":9,\"value\":1}]}" `

And works fine, it updates the value in the HAP server but it's not updated on the phone.
How can I force an update for the phone in order to get the new state?

I'll try with the characteristic.updateValue function unsuccessfully...

Thanks!
Fran

**Comment by p3ntium** [comment]
Seems that the updateValue function is deprecated, right?

**Comment by TheNoim** [comment]
Update value on ios device:
```javascript
your_accessory
.getService(Service.YOUR_SERVICE)
.updateCharacteristic(Characteristic.YOUR_CHARACTERISTIC, VALUE);
```

**Comment by p3ntium** [comment]
Hi TheNoim:
I've tested by I writing this (I've forced the value to 1 for the test):

```
lightAccessory
  .getService(Service.Lightbulb)
  .updateCharacteristic(Characteristic.On, 1);
```

... at the end of my accessory file, but nothing happens on the iOS side.

What's wrong?


Thanks in advance.
