### ISSUE TITLE
Identify any known UUID for Voltage

### ISSUE THREAD

**Issue by jsmeyers** [homebridge/HAP-NodeJS#466]
I'm trying to add some characteristics such as the actual input voltage to a device to an accessory. I have found a updated CommunityTypes https://github.com/homespun/hap-nodejs-community-types, I can't get the Volts value to display in Home, Hesperus, or Eve(which the UUID is based on their products). I was wondering if anyone had luck exposing Volts as a value i any of these apps.

**Comment by justme-1968** [comment]
i have no problem displaying the voltage, power, current and energy characteristics in eve.

**Comment by jsmeyers** [comment]
Can you point me to a accessory service that I can reference ?

**Comment by mrose17** [comment]
https://github.com/homespun/homebridge-accessory-neurio/blob/master/index.js#L106

**Comment by jsmeyers** [comment]
I've noticed if I add the CommunityTypes.Volts to a Battery Service or Contact Sensor it won't display in Eve or Hesperus, but If I add a Outlet Service it works as expected.

**Comment by mrose17** [comment]
the problem is that neither of those accessory types has a voltage characteristic associated with it, so it doesn't "really" get added.

you can define new services that inherit from those two and also include the new characteristics...
