### ISSUE TITLE
Running 2 instances of HAP-NodeJS

### ISSUE THREAD

**Issue by KillSwitchSIG** [homebridge/HAP-NodeJS#471]
Hi 
I'm running 2 instances of HAP-NodeJS through Homebridge and node-red-contrib-homekit.

There seems to be port conflicts etc in running 2 instances at the same time on the same server(RaspberryPi). Example of issues are my iOS device cannot pair properly and also get "No response" from the accessories. 

Looking at the HAP-NodeJS code:
In Core.JS:
`var targetPort = 51826;`
In BridgedCore.JS:
`  username: "CC:22:3D:E3:CE:F6",`
`  port: 51826,`
`  pincode: "031-45-154",`

Can I know what should be different and what can stay the same? I tried changing the ports from 51826 to 52826 and also tried changing the pincode, but it's not working. Do I also need to change the username?
What other pincode values and username values can I try?

**Comment by mschm** [comment]
Cannot say much about Homebridge, but when you configure the Accessory in Node-RED, do you leave the Port field empty? Because if you do, a free port should be assigned automatically, so that conflicts are avoided. I recommend to leave Port, Username and Pincode at default in Node-RED.
