### ISSUE TITLE
Help ! blind accessory don't update state (Thanks)

### ISSUE THREAD

**Issue by lisergio** [homebridge/HAP-NodeJS#475]
Hi again! I work in a blind accessory... 
The accessory connects to a esp8266 and works properly, up and down.
The value of the position is saved in a variable called "Blind1Position" sent by the esp8266.
But I do not get the accessory update the position ... when starting the app is always low (position 0), and changing the value of the position, esp8266 responds well moving the blind, but the app always puts "opening..."

I have tried to put the CurrentPosition and CurrentState values inside their services, but they do not run.
CurrentPosition is a int value ( 0 - 100 )
CurrentState is a int value ( 0=close , 1 = open and 2 = stop)
it is right?

https://www.dropbox.com/s/8e2xdpdvc52j7lb/icono.png?dl=0

The code:

var Blind1Position=0;
var Blind1State=0;
var Blind1Target=0;
// MQTT Setup
var mqtt = require('mqtt');
console.log("Connecting to MQTT broker...");
var mqtt = require('mqtt');
var options = {
  port: 1883,
  host: '192.168.0.56',
  clientId: 'blind1'
};
var client = mqtt.connect(options);
console.log("Blind 1 Connected to MQTT broker");
client.subscribe('blind1posicion');
client.on('message', function(topic, message) {
console.log(parseFloat(message));
Blind1Position = parseInt(message);
});

var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var exec = require('child_process').exec;
var ServiceName="MoveBlinds1";

var sensorUUID = uuid.generate('hap-nodejs:accessories:move1');
var blind1 = exports.accessory = new Accessory('Move Blinds 1', sensorUUID);
blind1.username = "99:34:CC:5A:13:2B";
blind1.pincode = "031-45-154";

blind1.getService(Service.AccessoryInformation)
.setCharacteristic(Characteristic.Manufacturer, "Lisergio")
.setCharacteristic(Characteristic.Model, "Blinds")
.setCharacteristic(Characteristic.SerialNumber, "00001");

blind1.on('identify', function(paired, callback) {
  callback();
});

blind1.addService(Service.WindowCovering,ServiceName)
  .getCharacteristic(Characteristic.CurrentPosition)
  .on('set', function(callback) {
// return our current value
//  callback(null,Blind1Position);
  });

blind1.getService(Service.WindowCovering)
  .getCharacteristic(Characteristic.PositionState)
  .on('get',function(callback){
//      callback(null,Blind1State);
  });

blind1.getService(Service.WindowCovering)
  .getCharacteristic(Characteristic.TargetPosition)
  .on('set',function(val, callback){
        client.publish('blind1',String(val));
        Blind1Target=val;
        callback(null,Blind1Target);
  });

**Comment by sokarovski** [comment]
Have you tried

```javascript
blind1.getService(Service.WindowCovering)
.getCharacteristic(Characteristic.CurrentPosition)
.updateValue(Blind1Position);
```

???

**Comment by lisergio** [comment]
Thanks! don´t work, give me a error, but I try your first option in a interval function and works!!!

setInterval(function() {
blind1.getService(Service.WindowCovering)
        .getCharacteristic(Characteristic.CurrentPosition)
        .updateValue(Blind1Position);
},500);

https://www.dropbox.com/s/33u9m4raawlurqj/icon2.png?dl=0

thanks again!!!

Now to work on the accessory with the esp8266!

**Comment by sokarovski** [comment]
@lisergio it's better to use events rather than pull the data with interval. I think i found the error and updated my code. Can you try again?

**Comment by lisergio** [comment]
Works fine!
thanks!!

**Comment by Korcsog** [comment]
@lisergio Will you upload the Arduino code into your website? I'm still working on the same project, but gave up few months ago 😄

**Comment by lisergio** [comment]
I'm still working on the accessory with the esp8266, to control the position using hall sensors.
When I have the system working, I will upload it to my blog.

**Comment by Korcsog** [comment]
@lisergio Using the hall sensors for the up/down state or you measuring the RPM speed?

**Comment by lisergio** [comment]
The idea is to count the steps from the closed position to the open position and map the measurement between 0 and 100 to send or receive the information.

**Comment by lisergio** [comment]
I update the code, and now, update the position if you move manually the blind, using push button ...

var Blind1Position=0;
var Blind1Target=0;;
var Dato=0;
// MQTT Setup
var mqtt = require('mqtt');
console.log("Connecting to MQTT broker...");
var mqtt = require('mqtt');
var options = {
port: 1883,
host: '192.168.0.56',
clientId: 'blind1'
};
var client = mqtt.connect(options);
console.log("Blind 1 Connected to MQTT broker");
client.subscribe('blind1posicion');
client.on('message', function(topic, message) {
    console.log(parseInt(message));
    Dato=parseInt(message);

if (Dato>=200){
Blind1Target=(Dato-200);
updateTarget(Blind1Target);
}
else{
   Blind1Position=Dato;
   updateBlind(Blind1Position);
}

});

var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var exec = require('child_process').exec;
var ServiceName="Persiana1";

var sensorUUID = uuid.generate('hap-nodejs:accessories:move1');
var blind1 = exports.accessory = new Accessory('Persiana 1', sensorUUID);
blind1.username = "69:34:CC:5A:13:2B";
blind1.pincode = "031-45-154";

blind1.getService(Service.AccessoryInformation)
.setCharacteristic(Characteristic.Manufacturer, "Lisergio")
.setCharacteristic(Characteristic.Model, "Blinds")
.setCharacteristic(Characteristic.SerialNumber, "00001");

blind1.on('identify', function(paired, callback) {
callback();
});

blind1.addService(Service.WindowCovering,ServiceName)
    .getCharacteristic(Characteristic.CurrentPosition)
    .on('get', function(callback) {
        //iOS will want to know whats the current Blind1Position when it opens the HomeKit App
        //So here we send it to iOS
        callback(null, Blind1Position)
    })

var updateBlind = function(toPosition) {
    //Update the value to the iOS when the client tells us it's changing
    blind1.getService(Service.WindowCovering)
        .getCharacteristic(Characteristic.CurrentPosition)
        .updateValue(toPosition);
}

var updateTarget = function(toPosition) {
    //Update the value to the iOS when the client tells us it's changing
    blind1.getService(Service.WindowCovering)
        .getCharacteristic(Characteristic.TargetPosition)
        .updateValue(toPosition);
}


blind1.getService(Service.WindowCovering)
    .getCharacteristic(Characteristic.TargetPosition)
    .on('get', function(callback) {
        //Tell the iOS whats the current target initaly when you open the HomeKit App
        callback(null, Blind1Target);
    })
    .on('set',function(val, callback){
        //iOS tells the client that target needs to be changed
        client.publish('blind1',String(val));
        Blind1Target=val;
        callback(null);
    });

**Comment by Korcsog** [comment]
Cool!!
This was my idea too, mount a sensor on the blind motor and measure the rotation but can't figured it out so I hope you have a working solution for that soon.

**Comment by Korcsog** [comment]
@lisergio Which sensor did you use?

**Comment by lisergio** [comment]
Hall sensor

**Comment by lisergio** [comment]
In a few days, i post the code and the hardware in my blog, and in my github repo

**Comment by lisergio** [comment]
Hi again!
The complet project of blind accessory.
https://lisergio.wordpress.com/2017/09/18/accesorio-persiana-compatible-con-homekit/

**Comment by MoniCris** [comment]
Thank you so much for sharing this. I'm working too at the same project. I was thinking to use 2 sensors (up and down) but I got a mess with all between 0 and 100%. The hall sensor is great idea. 
Thank you again.
