### ISSUE TITLE
Props Formats Bool

### ISSUE THREAD

**Issue by NebzHB** [homebridge/HAP-NodeJS#477]
Hi,

it's not clear for me if Bool Characteristics do need Boolean javascript value ? do i have to send true/false as a javascript Boolean, does it need 0 and 1 ?

BR's

Nebz

**Comment by sokarovski** [comment]
I just scrolled through the code it looks like there is only type checking for different integer lengths. I tested the data that the server sends and for boolean it sends exactly what you pass. I've tested it with true/false and 1/0 and it works ok so iOS app knows how to handle. Be careful not to send string "1" and "0"

**Comment by NebzHB** [comment]
ok thanks, shouldn't HAP-NodeJS sanatize that before sending ?

**Comment by pdlove** [comment]
As of PR #489 HAP-NodeJS will sanitize. If Javascript recognizes that your value is the same as true then it will return true. it uses (==) instead of (===) to make sure it catches all equivalencies of true.
