### ISSUE TITLE
hap over wan

### ISSUE THREAD

**Issue by eduardocanton** [homebridge/HAP-NodeJS#479]
Hello,

I connect the HAP in LAN mode without problem, buy if I go out my home, I loss my wifi connection and don´t work.

Is it possible use it by WAN?, what is the port for foward?

thank you

**Comment by Korcsog** [comment]
For remote connection you need an Apple TV as HomeKit hub!

**Comment by x43x61x69** [comment]
Actually it is possible w/o AppleTV or an iPad. You need a VPN connection to your home LAN, then run a DNS proxy that bridges the HAP mDNS info to your VPN subnet.
