### ISSUE TITLE
HAP-NodeJS don't start

### ISSUE THREAD

**Issue by HaTe87** [homebridge/HAP-NodeJS#482]
hi.
i follow the guide, but when i run sudo node Core.js it retuns that:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
/home/pi/HAP-NodeJS/lib/Service.js:101
    if (!this.linkedServices.includes(newLinkedService))
                             ^

TypeError: this.linkedServices.includes is not a function
    at Service.addLinkedService (/home/pi/HAP-NodeJS/lib/Service.js:101:30)
    at Object.<anonymous> (/home/pi/HAP-NodeJS/accessories/AirConditioner_accessory.js:83:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/pi/HAP-NodeJS/lib/AccessoryLoader.js:33:29
    at Array.forEach (native)

can anyone help me?

**Comment by pdlove** [comment]
I thought I commented last night... the problem is that your version of node is too old. You must have at least version 6 to use this. I recommend using the newest version.

**Comment by HaTe87** [comment]
i use that wget http://node-arm.herokuapp.com/node_latest_armhf.deb

**Comment by pdlove** [comment]
What version is it? ‘node -v’

**Comment by HaTe87** [comment]
v4.2.1

**Comment by pdlove** [comment]
Check out the page here on how to get a newer version on Raspberry Pi: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#install-node

**Comment by HaTe87** [comment]
i have do that:
https://nodejs.org/dist/latest/node-v8.4.0-linux-armv7l.tar.gz
tar -xvf node-v8.4.0-linux-armv7l.tar.gz
cd node-v8.4.0-linux-armv7l
sudo cp -R * /usr/local/

**Comment by pdlove** [comment]
That should make it so that `node -v` returns v8.4.0

**Comment by HaTe87** [comment]
sure!
but now i have a new problem .
i need to command the fan with an on / off and i do not understand what i have to change and how and where to attach the relay pin

**Comment by pdlove** [comment]
That will be beyond my current expertise to help with.  You might take a look at how it's done in one of the homebridge plugins: https://github.com/rsg98/homebridge-gpio-wpi2
Or maybe someone else on this thread can chime in how they handle it.

**Comment by HaTe87** [comment]
i'm going to studying it... thanks a lot

**Comment by oddwires** [comment]
Chiming in with an alternate approach...

[I use 433MHz RC transmitter and standard power sockets for the hardware](https://github.com/oddwires/alarm-system)

![image](https://github.com/oddwires/alarm-system/wiki/images/IMG_9001.png)

And for the software I have a custom service running to handle the low level stuff, so...
- To change the device state I write to file input.txt
- To read back the device state I read from file status.txt

example Fan_accessory.js...

```
var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var fs = require('fs');

// here's a GENERIC fan device that we'll expose to HomeKit
var GENERIC_Fan01 = {
  powerOn: false,
  setPowerOn: function(on) { 
    console.log("Turning the Fan fan %s", on ? "On" : "Off");
    if (on) {
            fs.appendFile("/var/www/data/input.txt", "Siri:iPhone:rcon swtch:5:On\n", function(err) {       
               if(err) { return console.log(err); }
               console.log("Fan fan on Success");
               }); 
            } else {
            fs.appendFile("/var/www/data/input.txt", "Siri:iPhone:rcon swtch:5:Off\n", function(err) {       
               if(err) { return console.log(err); }
               console.log("Fan fan off Success");
               });
            }
  },
}

// Generate a consistent UUID for our light Accessory that will remain the same even when
// restarting our server. We use the `uuid.generate` helper function to create a deterministic
// UUID based on an arbitrary "namespace" and the word "fan01".
var fanUUID01 = uuid.generate('hap-nodejs:accessories:fan01');

// This is the Accessory that we'll return to HAP-NodeJS that represents our GENERIC fan.
var fan01 = exports.accessory = new Accessory('Fan', fanUUID01);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
fan01.username = "fa:3c:ed:5a:1a:0d";
fan01.pincode = "031-45-154";
fan01.displayName = "Fan";

// set some basic properties (these values are arbitrary and setting them is optional)
fan01
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "oddwires.co.uk")
  .setCharacteristic(Characteristic.Model, "Ver 1.0")
  .setCharacteristic(Characteristic.SerialNumber, "Handset 27, Button 4");

// Add the actual outlet Service and listen for change events from iOS.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKitTypes.js`
fan01
  .addService(Service.Fan, "Fan") // services exposed to the user should have "names" like "GENERIC Fan" for us
  .getCharacteristic(Characteristic.On)
  .on('set', function(value, callback) {
    GENERIC_Fan01.setPowerOn(value);
    callback(); // Our GENERIC fan is synchronous - this value has been successfully set
  });

// We want to intercept requests for our current power state so we can query the hardware itself instead of
// allowing HAP-NodeJS to return the cached Characteristic.value.
fan01
  .getService(Service.Fan)
  .getCharacteristic(Characteristic.On)
  .on('get', function(callback) {
    // this event is emitted when you ask Siri directly whether your fan is on or not. you might query
    // the fan hardware itself to find this out, then call the callback. But if you take longer than a
    // few seconds to respond, Siri will give up.
   var err = null; // in case there were any problems
    fs.readFile("/var/www/data/status.txt", 'utf8', function(err, data) {
        if(err) { return console.log(err); }
        var lines = data.split('\n');
        for(var i = 0; i < lines.length; i++){
            if ((lines[i].indexOf("rcon") !=-1) && (lines[i].indexOf("Fan") !=-1)) {
            // falls through here when we have found the line for this device in the status file
            // console.log(lines[i]);
               var values = lines[i].split(':');
               // read the actual status of the accessory from the file
               console.log(values[5]);
               if (values[5].indexOf("On") !=-1) { 
                    console.log("Current status: on");
                    GENERIC_Fan01.powerOn = true;
                    callback(err, true);
                } else {
                    console.log("Current status: off");
                    GENERIC_Fan01.powerOn = false;
                    callback(err, false);
                }
            }
        }
    });
 `});```

**Comment by pdlove** [comment]
I'm thinking you could use a Raspberry Pi Zero W with this module to do it pretty easily: https://www.amazon.com/RobotDyn-controller-control-Arduino-Raspberry/dp/B072K9P7KH/ref=pd_sbs_328_6
Just need to turn it on with Characteristic.On and control the PWM output with Characteristic.FanSpeed.

**Comment by TeraJaQ** [comment]
http://www.fargionconsulting.com/apple-homekit-server-su-raspberry-pi/
in this link is reported an updated guide to install on a rasberry pi
