### ISSUE TITLE
Validation function enhanced

### ISSUE THREAD

**Issue by NebzHB** [homebridge/HAP-NodeJS#496]
Hi,

i have several ideas i'm implementing in my plugin for value validation :

1. min/max validation
[https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L246](url)
with the new validate function, if the value outbound the minValue or the maxValue, the value is limited to the min/max... but that min/max value is never validated and could be wrong... those may be parseInt or parseFloat too
-> maybe validate the min/max value on setProps ? or when assigning to the value ?
(eg : homebridge crash if maxValue="100" (a string) and the value is 300)

2. uint ... u is for unsigned
maybe a Math.abs() could be usefull to clean the value from any minus it could have.

3. bool
i transform any boolean like value into boolean with that function :
```
function toBool(val) {
	if (val == 'false' || val == '0') {
		return false;
	} else {
		return Boolean(val);
	}
}
```
could be nice here : [https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L219](url)

4. float and int (and uint)
parseFloat and parseInt could be sure the value is a Float or an INT before sending

5. a way to avoid the null or undefined value to be sent
something like if(!val) val = default value

for reference, here is my sanitizing function, i use it before the commit with the validation on your side because i import data from a Jeedom plateform (and value may be diverse) (i know yours is better for certains points, but a merge of the two is even more validated ;))
```
// -- sanitizeValue
// -- Desc : limit the value to the min and max characteristic + round the float to the same precision than the minStep
// -- Params --
// -- currentValue : value to prepare
// -- characteristic : characteristic containing the props
// -- Return : prepared value
function sanitizeValue(currentValue,characteristic) {
	let val=0;
	switch(characteristic.props.format) {
			case "uint8" :
			case "uint16":
			case "uint32" :
			case "uint64" :
				val = parseInt(currentValue);
				val = Math.abs(val); // unsigned
				if(!val) val = 0;
				if(characteristic.props.minValue != null && characteristic.props.minValue != undefined && val < parseInt(characteristic.props.minValue)) val = parseInt(characteristic.props.minValue);
				if(characteristic.props.maxValue != null && characteristic.props.maxValue != undefined && val > parseInt(characteristic.props.maxValue)) val = parseInt(characteristic.props.maxValue);		
			break;
			case "int" :
				val = parseInt(currentValue);
				if(!val) val = 0;
				if(characteristic.props.minValue != null && characteristic.props.minValue != undefined && val < parseInt(characteristic.props.minValue)) val = parseInt(characteristic.props.minValue);
				if(characteristic.props.maxValue != null && characteristic.props.maxValue != undefined && val > parseInt(characteristic.props.maxValue)) val = parseInt(characteristic.props.maxValue);	
			break;
			case "float" :
				val = minStepRound(parseFloat(currentValue),characteristic);
				if(!val) val = 0.0;
				if(characteristic.props.minValue != null && characteristic.props.minValue != undefined && val < parseFloat(characteristic.props.minValue)) val = parseFloat(characteristic.props.minValue);
				if(characteristic.props.maxValue != null && characteristic.props.maxValue != undefined && val > parseFloat(characteristic.props.maxValue)) val = parseFloat(characteristic.props.maxValue);	
			break;
			case "bool" :
				val = toBool(currentValue);
				if(!val) val = false;
			break;
			case "string" :
			case "tlv8" :
				val = currentValue.toString();
				if(!val) val = '';
			break;
	}
	return val;
}

// -- minStepRound
// -- Desc : round the value to the same precision than the minStep
// -- Params --
// -- val : value to round
// -- characteristic : characteristic containing the props
// -- Return : rounded value
function minStepRound(val,characteristic) {
	if(characteristic.props.minStep == null || characteristic.props.minStep == undefined) {
		characteristic.props.minStep = 1;
	}
	let prec = (characteristic.props.minStep.toString().split('.')[1] || []).length;
	if(val) {
		val = val * Math.pow(10, prec);
		val = Math.round(val); // round to the minStep precision
		val = val / Math.pow(10, prec);
	}
	return val;
}

// -- toBool
// -- Desc : transform to boolean a value
// -- Params --
// -- value : value to convert into boolean
// -- Return : boolean value
function toBool(val) {
	if (val == 'false' || val == '0') {
		return false;
	} else {
		return Boolean(val);
	}
}

```

thank you for reading

**Comment by snowdd1** [comment]
What about the indexed values for int and uint8? Or did I miss these checks in your examples?

**Comment by pdlove** [comment]
BTW, thank you @NebzHB for pointing out the parseInt and parseFloat. I didn't think to do that since I was performing math on the value but it'll help prevent crashes.

**Comment by NebzHB** [comment]
@snowdd1 : no, as said in my comment, i did that sanitizing before the indexed value came out, and i didn't add it as the validation function do it right
@pdlove : it would be interesting to do that on min and max or on setprops too ... i did have a crash because the minValue was set to "0" for a INT.

For the CurrentAmbientLightLevel, my users had crashes because the captor get a 0 value, so the min value is set but it seems that 0.0001 is not get or rounded (even if there is no minStep value) and so it's set to 0 and it crash homebridge too (No Response)

**Comment by pdlove** [comment]
@NebzHB The validate function does min/max validation. If you set the value less than the minimum, it stores the minimum and more than the maximum is set to the maximum. I've tried to make it impossible for a developer to freak out HomeKit on IOS by passing bad values. I know that it can't be that solid, but I think it's pretty close. 
On the issue your users have had with CurrentAmbientLightLevel, is that with the current version? I may need to add a default minStep to floats of something like 0.00000001 to make sure that it DOESN'T try to round the value.

**Comment by NebzHB** [comment]
not really... it does validate the value against the min/max... but the min max are not validated themselves during setprops... as in my exemple, if the min max are set to a "0" string, and the value is -45 (int), the validation will set "0" into an INTEGER ... and homebridge crashes !
