### ISSUE TITLE
Listen to events

### ISSUE THREAD

**Issue by mortocks** [homebridge/HAP-NodeJS#497]
Are there any example or documentation on how to trigger custom events from a hap-nodejs server? Looking at adding socket.io events when home bridge events trigger to add a web ui interface. Any help would be appreciated.

**Comment by renssies** [comment]
As far as I know, calling `setCharacteristic()` causes the bridge to send out a notification to the controllers (your device/home hub).

I've used this for motion and contact sensors using Homebridge and it triggers home automation almost instantly.

**Comment by a-x-** [comment]
Is it respond to iOS HomeKit status and UI view?

In other words, can HAP-NodeJS send hardware status change to HomeKit app runned on Apple Device?

For example: 
- presence sensor, 
- physical light switcher with a feedback

**Comment by a-x-** [comment]
As I can see here: https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/MotionSensor_accessory.js
Sensor cannot trigger update. Who triggers updates here? Is HomeKit polles state with an interval? Know anybody what the interval?

My problem: I have an light with a lot of controllers (ifttt, button, HomeKit, voice) and HomeKit does not update its status

**Comment by NorthernMan54** [comment]
Your light / device should send the status changes as an event if you want semi real time updates.  Otherwise, the home app refreshes on its own schedule, roughly when you change rooms or open/close the app

**Comment by a-x-** [comment]
Thank you, @NorthernMan54 

Can you help to achieve it?:
> Your light / device should send the status changes as an event

Doc link or code snippet will be such helpful

**Comment by NorthernMan54** [comment]
When I’m back home next week, and not limited to Mobile I can give better examples but there are two patterns that can be implemented depending on the device.  First would be the best case where the device generates events that can be passed to hap-nodejs and ultimately the HomeKit.  Second is to implement device polling, and update HomeKit with the current status.   Both of these patterns use the updateValue characteristic interface.  The first updates when a device event occurs, the second when polling occurs.

If you device doesn’t support events ( which Is most ) your stuck with polling, and the inherent lag associated with it.

I use the second pattern with my homebridge plugins that the devices don’t support events and the first with the ones that do.  My homebridge-dht does polling, while homebridge-heyu uses device events.

**Comment by a-x-** [comment]
I had not got answer though...
