### ISSUE TITLE
pairedClients suddenly empty. All devices unreachable

### ISSUE THREAD

**Issue by thexperiments** [homebridge/HAP-NodeJS#501]
Hi,
I'm using HAP-NodeJS via the pimatic-hap plugin and it worked great for quite some time...

However it stoped working once and after finding no other solution I removed the AcessoryInfo file and set everything up from scratch.

This worked for about 30 minutes and then stopped working. Since then I multiple times to get it working again and tried every fix I could find. Nothing did work. After some minutes everything stopped working again...

Today I wanted to tackle this once and for all and took a fresh look.
I saw that it didn't seem to go past the pairing step und thus I checked the "pairedClients" within AcessoryInfo.XXXX.json was empty!

Sadly I don't have any additional logs at the moment but maybe anybody has an idea what could cause the flush of the paired devices.

One thing is suspect could have to do with this is that I also have an apple TV for remote access and a delay of some minutes could have to do with the iPhone which is used to set up the system syncing the keychain and the apple tv doing the same and then trying to authenticate with the hap nodejs server...

**Comment by themainframe** [comment]
I too ran into this issue today - did you ever find a solution, @thexperiments ?
