### ISSUE TITLE
Garage Door set off after time 

### ISSUE THREAD

**Issue by massinegro204** [homebridge/HAP-NodeJS#505]
Hi, i am trying to set a time limit on the open state of the garage accessory .But not having much experience with the programming i am looking for help for now i did this .. any help i ask you to give thanks in advance

`var state = false

function unFlip() {
  console.log("Unflipping...");
state = false
GARAGE_DOOR.close();
    garage
        .getService(Service.GarageDoorOpener)
        .setCharacteristic(Characteristic.CurrentDoorState, Characteristic.CurrentDoorState.CLOSED);
       GARAGE_DOOR .opened = false
}`

and in 

`var GARAGE_DOOR = {

  opened: false,
  open: function() {
    console.log("Opening the Garage!");
    cmd.run('sudo python /home/pi/HAP-NodeJS/python/0x20/led-65.py');
   setTimeout(unFlip, 10000)
 },
  close: function() {
    console.log("Closing the Garage!");
    cmd.run('sudo python /home/pi/HAP-NodeJS/python/0x20/led-65OFF.py');
    GARAGE_DOOR.opened = false;
  },
  identify: function() {
    console.log("Identify the Garage");
  }
};`

**Comment by robertlarue** [comment]
I had a similar issue with a Garage Door that automatically closes after a specified timeout. I created a new accessory to do just that. Perhaps it will help you?
[https://github.com/robertlarue/HAP-NodeJs-Accessories/blob/master/GarageDoorAutoClose_accessory.js](https://github.com/robertlarue/HAP-NodeJs-Accessories/blob/master/GarageDoorAutoClose_accessory.js)
