### ISSUE TITLE
Switches Aqara

### ISSUE THREAD

**Issue by Ramzes177** [homebridge/HAP-NodeJS#513]
Good afternoon,
Maybe HAP-NodeJS will connect the switches Aqara?

**Comment by Korcsog** [comment]
@Ramzes177  If you can modify the firmware ( e.g.: with MQTT support like this : https://github.com/monster1025/aqara-mqtt), the answer is yes. It will connect with HAP using an MQTT server and mqtt npm package. Same thing with the Sonoff Touch switches.

**Comment by ebaauw** [comment]
The Xiaomi Aqara switches communicate over ZigBee.  If you connect them to a [deCONZ gateway](https://github.com/dresden-elektronik/deconz-rest-plugin), [homebridge-hue](https://github.com/ebaauw/homebridge-hue) exposes them to HomeKit.  Note that currently we support the smart wireless switches; the in-wall switches are work in progress (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/165).
