### ISSUE TITLE
DHT 22 is not defined

### ISSUE THREAD

**Issue by Timetogetstarted** [homebridge/HAP-NodeJS#518]
HI
When I run "Core.js"

I get this error 

pi@raspberrypi:~/HAP-NodeJS $ node Core.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
/home/pi/HAP-NodeJS/accessories/SonoffHumidity_accessory.js:14
var sensorType = DHT22;
                 ^

ReferenceError: DHT22 is not defined
    at Object.<anonymous> (/home/pi/HAP-NodeJS/accessories/SonoffHumidity_accessory.js:14:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/pi/HAP-NodeJS/lib/AccessoryLoader.js:33:29
    at Array.forEach (native)
    at Object.loadDirectory (/home/pi/HAP-NodeJS/lib/AccessoryLoader.js:28:23)

Can someone tell me what have i done wrong?
Many Thanks in advance.

**Comment by marcgrc** [comment]
try to change var sensorType = DHT22; in  var sensorType = 'DHT22';

**Comment by Timetogetstarted** [comment]
Hi marcgrc 
I'm a newbie. So, can you tell me a bit more about how to do it?
Thanks

**Comment by Timetogetstarted** [comment]
var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var mqtt = require('mqtt');
var mqttMSG = 0;


var name = "Sonoff Humidity Sensor"; //accessory name
var sonoffUUID = "hap-nodejs:accessories:sonoff:Humidity:" + name; //change this to your preferences
var sonoffUsername = "1C:3C:3A:4E:5E:FF";
var MQTT_NAME = 'bedroomlights'; //MQTT topic that was set on the Sonoff firmware
var MQTT_IP = 'localhost'; //change this if your MQTT broker is different
var sensorType = DHT22;

var options = {
  port: 1883,
  host: MQTT_IP,
//  username: 'pi', //enable only if you have authentication on your MQTT broker
//  password: 'raspberry', //enable only if you have authentication on your MQTT broker
  clientId: MQTT_NAME+'HumiHAP'
};
var sonoffTopic = 'cmnd/'+MQTT_NAME+'/status';
var client = mqtt.connect(options);

client.on('connect', function () {
  client.subscribe('stat/'+MQTT_NAME+'/STATUS10')
});

var sonoffObject = {
  CurrentRelativeHumidity: 99,
  getReadings: function() {
    client.publish(sonoffTopic, '10');
  },
  identify: function() {
    console.log(name + " Identified!");
  }
}

var sonoffHumi = exports.accessory = new Accessory(name, uuid.generate(sonoffUUID));

sonoffHumi.username = sonoffUsername;
sonoffHumi.pincode = "031-45-154";

// listen for the "identify" event for this Accessory
sonoffHumi.on('identify', function(paired, callback) {
  sonoffObject.identify();
  callback();
});

sonoffHumi
  .addService(Service.HumiditySensor)
  .getCharacteristic(Characteristic.CurrentRelativeHumidity)
  .on('get', function(callback) {
    // return our current value
    callback(null, sonoffObject.CurrentRelativeHumidity);
  });

  client.on('message', function(topic, message) {
  //  console.log(message.toString());
    message = message.toString();
    mqttMSG = JSON.parse(message);
  //  console.log(mqttMSG.StatusSNS.DHT22.Humidity);
    sonoffObject.CurrentRelativeHumidity = mqttMSG.StatusSNS.sensorType.Humidity;
  });

setInterval(function() {

  sonoffObject.getReadings();

  sonoffHumi
    .getService(Service.HumiditySensor)
    .setCharacteristic(Characteristic.CurrentRelativeHumidity, sonoffObject.CurrentRelativeHumidity);

}, 30000);

**Comment by marcgrc** [comment]
1) where you find the line    var sensorType = DHT22; change in var sensorType = 'DHT22';

**Comment by Timetogetstarted** [comment]
Hi 
It worked. Thank you.
Now its running.
But now there is a new issue.
In the Home app in phone, when I try to add the temperature sensor, its giving an error message saying "Couldn't add Sonoff Temperature Sensor   Home couldn't connect to this accessory. "

**Comment by marcgrc** [comment]
mmmm i don't know
