### ISSUE TITLE
Light_accessory.js  return of light status

### ISSUE THREAD

**Issue by marcgrc** [homebridge/HAP-NodeJS#519]
does anyone have an idea to give a return to the state of light? off or on when i turn off or turn on with a switch?

**Comment by slss** [comment]
according to light accessory example:

> // To inform HomeKit about changes occurred outside of HomeKit (like user physically turn on the light)
// Please use Characteristic.updateValue
// 
// lightAccessory
//   .getService(Service.Lightbulb)
//   .getCharacteristic(Characteristic.On)
//   .updateValue(true);

**Comment by BertanStar** [comment]
Thanks! It helped me too...
