### ISSUE TITLE
Guide on how to install on a Mac?

### ISSUE THREAD

**Issue by jat80** [homebridge/HAP-NodeJS#522]
Hi there,

I run this currently on my raspberry pi 3 but would like to run it on my always on Mac mini.  My Mac mini also has homebridge on it but was told that as long as the port for homebridge and HAP-NodeJS are different  they will be fine running on the same machine.

I would like to know if there is any guide on how to install HAP-NodeJS on a Mac anywhere that someone can point me too please?

Thanks.

**Comment by rasiquiz** [comment]
Just download the files from Github. Open the Core.js or BridgedCore.js and change the port to a different one than your Homebridge. Then open the folder in Terminal and type "node BridgedCode.js" or "node Code.js" and the service will start and should be available on your devices. The pin for the bridge is inside BridgedCore.js or in Core.js (where you have to type your own). If you want it to start at when booting the computer then there are plenty of guides on how to do that around the web fx. https://www.npmjs.com/package/node-autostart
