### ISSUE TITLE
Vent Device Type

### ISSUE THREAD

**Issue by bassrock** [homebridge/HAP-NodeJS#524]
I am looking at a way to add Keen Home to HomeBridge. Is there such thing as a Vent Device type? It operates like a dimmer bulb and also has a temperature sensor in it.

I'd like to work on adding this https://github.com/sibartlett/homebridge-wink3 but can't seem the best device type to add it as.

**Comment by volschin** [comment]
Have you taken a look at the Fanv2 or the HeaterCooler Service?

**Comment by bassrock** [comment]
Yea, but they both have power on states, the vents are more just open or close.

**Comment by jvmahon** [comment]
How about the Slat service?
