### ISSUE TITLE
the accessory not run as a service at startup

### ISSUE THREAD

**Issue by AlessandroFerri** [homebridge/HAP-NodeJS#526]
I try to start the service of my accessory at the boot of the raspberry, but it does not appear in my iPad, but if it run with the command from the terminal it appears on my iPad. These steps:

1) to start at boot
```
sudo nano \lib\systemd\system\hap.service

[Unit]
Description=HapSone accessory
After=ble.service               # Requires the mysql service to run first

[Service]
ExecStart=/usr/bin/node /home/pi/HAP/Core.js
#WorkingDirectory=/opt/nodeserver   # Required on some systems
Restart=always
RestartSec=5                        # Restart service after 5 seconds if node service crashes
StandardOutput=syslog               # Output to syslog
StandardError=syslog                # Output to syslog
SyslogIdentifier=nodejs-example
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target

sudo systemctl enable hap.service
sudo systemctl start hap.service
```
the service run and is active but accessory not appear in my iPad. No error from monitor.

2) run from command:
`sudo node /HAP/Core.js`
accessory appear in my iPad.

I try to remove the directory \persist but nothing is happening.

can anyone help me?

**Comment by volschin** [comment]
You should better wait for the network target.

**Comment by AlessandroFerri** [comment]
I have waited enough for the network target, so it is true that if I stop the service with
`sudo systemctl stop hap.service`
and run again with the command:
`sudo node /HAP/Core.js`
 my accessory immediately appears from the iPad, if I run "CTRL ^ C" and run the service again
`sudo systemctl start hap.service`
I do not see it.
But I must say that initially my accessory had appeared, I have paired the accessory on my iPad. Next I removed the accessory from my iPad and now I do not see it anymore. I only see it from terminal after running:
`sudo node /HAP/Core.js`
after delete the \persist directory, but not if it running from service.
Everything looks like I did not reset something.

Anyway, how can I see journal and how and with which user do I have to start the service?

**Comment by AlessandroFerri** [comment]
Another information yet. If I remove the \persist directory and run the command:
`sudo node /HAP/Core.js`
a new \persist directory was created.
If I remove the \persist directory and run the command:
`sudo systemctl start hap.service`
no new \persist directory was created.
Why?
