### ISSUE TITLE
Remote Homekit Access

### ISSUE THREAD

**Issue by greenchapter** [homebridge/HAP-NodeJS#527]
Everything is working well in my own Wi-Fi, is it Possible to get Access from Remote with LTE/4G?

This works with an AppleTV but not with HAP-NodeJS. Any ideas how to get this to work?

**Comment by volschin** [comment]
This is the intended function to be bridged by Apple TV, an iPad stationary in the home network or later the new HomePod.

**Comment by greenchapter** [comment]
There is no way to do that without an Apple TV or an iOS Device?

**Comment by llemtt** [comment]
https://github.com/KhaosT/HAP-NodeJS/issues/337

**Comment by greenchapter** [comment]
Ok this "solution" I have already in mind, but I thought any tooling outside can do the same as iPad oder AppleTV 🙁

**Comment by llemtt** [comment]
Actually I don't know any... :slightly_frowning_face:

Main reason behind is that you need at least access to homekit (hap is not enough) to behave like the iPad/Apple TV bridge, and homekit is currently available only under iOS.
