### ISSUE TITLE
Some MQTT messages are not delivered

### ISSUE THREAD

**Issue by adicrescenzo** [homebridge/HAP-NodeJS#528]
Hi all,

I've a Sonoff Dual switch with the tasmota firmware installed on it. Basically this device has two releay onboard and, via the tasmota firmware, it publish an MQTT message every time that the relay status changes(every relay has it own topic).

I've created two accessory file to map each lamp on HAPNodeJS ([first](https://github.com/adicrescenzo/HAP-NodeJS_Accessories/blob/master/SonoffMQTT_livingRoomFloorLightBig_accessory.js), [second](https://github.com/adicrescenzo/HAP-NodeJS_Accessories/blob/master/SonoffMQTT_livingRoomFloorLightSmall_accessory.js))

The sonoff publish a message every time a relay changes its own status (I debugged with an MQTT client) but, for some reason, the callbacks code of this accessories sometimes are not called. It happens randomly without a specific pattern and I really can't understand the reason.

If I run the accessory file with

> node SonoffMQTT_livingRoomFloorLightBig_accessory.js

without using the Core.js of HAPNodeJS every messages are delivered correctly.

This problem doesn't appear with a Sonoff Basic (that has just one relay) and the accessory code is quite the same.

I really appreciate your help guys, many thanks in advance to everyone would help me.

**Comment by adicrescenzo** [comment]
I solved the issue. The problem is that I was using the same [clientId](https://github.com/adicrescenzo/HAP-NodeJS_Accessories/blob/bca263acb06669b834fafc85fa759a8c89046d4c/SonoffMQTT_livingRoomFloorLightSmall_accessory.js#L19) for both accessories.

Maybe I can do the same thing using just one accessory, can anyone suggest me how to adapt this code in order to export a singole accessory with two lights? I tried to look this [example](https://github.com/KhaosT/HAP-NodeJS/blob/v0.0.2/accessories/KNX_Dimmers_accfactory.js.sample.js) but it's quite complicated. Many thanks in advance

**Comment by OczkoSX** [comment]
I think you are looking for _accfactory suffix. It allows you to export multiple accessories from one js file 

Wysłane z iPhone'a

**Comment by adicrescenzo** [comment]
@OczkoSX exaclty, is there a simple example that I can I look into?
Many thanks.

**Comment by budisek** [comment]
Hello

I want to ask how did you set up two mqtt topics for each relay in sonoff dual? In tasmota web settings there is only one topic name option. 

I have maden two files on HAP-nodeJS directory with two differt topic. I can control the first or the second relay on homekit (when i change the topic) but not both. 

Thanks for your answer.

**Comment by adicrescenzo** [comment]
Hi,

I’ve created two separated files in the HAP-NodeJS directory, each with its own topic.
In this way HomeKit will see the sonoff dual as two single devices and you can control it independently.
Is this what you want or do you need something different?

Regards,
Angelo

**Comment by budisek** [comment]
Thanks for your reply. I know that two files is necessary. But i do not know how to set them up.
Could you please send me your two corrected accessory files for example?

**Comment by adicrescenzo** [comment]
Sure, here you can find the accessories files.
Hope that this could help you, if you need any help don’t hesitate to ask.

Ciao,
Angelo
