### ISSUE TITLE
Defaulting of options when adding accessory

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#549]
I’ve been looking into see if you can programmatically default options for when adding an accessory. For example, a recent accessory I added into HomeKit exposed two items, and camera and a motion sensor. The camera had the option defaulted to add into favourites but the motion sensor didn’t

Is there a way to do this via hap-nodejs?

**Comment by n0rt0nthec4t** [comment]
Any thoughts on this as a follow up?

**Comment by ebaauw** [comment]
No, setting favourites, room and scene assignments, even renaming an already paired accessory can only be done throught the HomeKit API, used by HomeKit apps.  The HomeKit Accessory Protocol (HAP) “only” supports providing accessories.
