### ISSUE TITLE
Air pressure sensor

### ISSUE THREAD

**Issue by unit76** [homebridge/HAP-NodeJS#550]
how to connect Air pressure sensor to HAP-NodeJS?
There are no Air pressure sensor in BridgeTypes.js

**Comment by justme-1968** [comment]
you have to use a custom characteristic.

if you use E863F10F-079E-48FF-8F27-9C2605A29F52 as the uuid eve will display it as air pressure sensor. also see here: https://gist.github.com/gomfunkel/b1a046d729757120907c

**Comment by NorthernMan54** [comment]
And a working example.  Mind you this is a homebridge plugin, but it shows the concept.


https://github.com/NorthernMan54/homebridge-bme280
