### ISSUE TITLE
Can't get HoldPosition characteristic to work in Window/WindowCovering service

### ISSUE THREAD

**Issue by grover** [homebridge/HAP-NodeJS#553]
I'm trying to create a custom accessory that exposes the WindowCovering service. When I add the optional HoldPosition characteristic everything seems to work fine on first glance, however I can't seem to get the characteristic to work.

The home app doesn't show it and Elgatos Eve app shows it with a STOP button, but hitting it doesn't seem to write to the characteristic.

Using HAS I can seemingly reproduce this behavior - I don't see STOP actually writing to the characteristic. Am I missing something? Or is this characteristic somehow incomplete/broken?

Thanks!

**Comment by Supereg** [comment]
I have the same problem when trying to implement the HoldPosition characteristic with the Window service. Everything is registered correctly.
However when trying to hold the windows with voice command Siri herself says that this option is not supported by this accessory.
The characteristic seems broken to me!

**Comment by Supereg** [comment]
@KhaosT are there any informations about this issue or progress made?

**Comment by TheNON75** [comment]
Good morning,

I can confirm that as of now, the HoldPosition still has no effect.
It remains false

Is it planned to be investigated?

thank you in advance
Regards
THN

**Comment by Shaquu** [comment]
@Supereg Please reopen.

**Comment by Shaquu** [comment]
Continuing in #908

**Comment by Supereg** [comment]
For traceability purposes:

The Home App (and Siri) never implemented support for the `HoldPosition` characteristic. Weirdly, every spec to date listed the `HoldPosition` characteristic as required. However, I also already encountered HomeKit certified accessories which do not at all implement the `HoldPosition` characteristic.
Third party apps (like e.g. the Eve app) tend to support the `HoldPosition` characteristic though and controlling it works as expected if implemented correctly.

**Comment by TheNON75** [comment]
Just performed some further tests and can confirm both Siri and Eve.
However Siri can handle “hold curtain”, after a short conversation, hk sends  a new TargetPostion. It is pity there is no counterpart for this in home app, but this is a different thing.
Thanks anyway
