### ISSUE TITLE
Adding a completely custom characteristic to an existing accessory

### ISSUE THREAD

**Issue by legotheboss** [homebridge/HAP-NodeJS#555]
Hey all,

I am currently working on creating a HAP-NodeJS accessory that is an outlet which integrates some power monitoring values(volts, wattage, amps) coming from a sensor. I have found the Elgato Eve characteristics for such values (https://gist.github.com/simont77/3f4d4330fa55b83f8ca96388d9004e7d) but currently am perplexed on how to integrate these into an existing HAP-NodeJS accessory file.

**Comment by simont77** [comment]
Have a look here https://github.com/simont77/fakegato-history. You will find reference to plugins using the custom characteristics.
