### ISSUE TITLE
Block Accessoires for Remote access ?!

### ISSUE THREAD

**Issue by calkoe** [homebridge/HAP-NodeJS#559]
Is they a way to block Accessoires to be controlled from remote ? (e.g. via the iPad/AppleTV bridge).
I don't want to open my Door-Lock by accident from far away.

Thank You!

**Comment by jvmahon** [comment]
You can disable remote access via the Apple TV. Unfortunately, it is an all-or-nothing choice. Hopefully Apple will eventually add something like this (and more granular sharing of devices when you share your Home), but for now , I don't think you can do what you are looking for.

**Comment by NorthernMan54** [comment]
I think this is technically do able with hap-nodejs, but would take some effort.  And is likely to need changes to hap-nodejs but should be feasible.  When your local and Home your phone talks direct to hap-nodejs and when your remote your Home hub talks to hap-nodejs.

You would need to look at having the plugin access the request context, as it would have the source ip of the request. And change behaviour based on source ip.

**Comment by calkoe** [comment]
@jvmahon I know.. but that's don't what I want, I only want to block my DoorLock Accessory from remote access. 

@NorthernMan54 That sounds good, actually I'm processing the HABjs Messages in Node-Red, so it would be simple to block a specific IP-Adress. Which changes I have to do to pass the source IP within the HAP-Context message to Node-Red ? 
(I still think this would be an interesting question for the HomePod too,  I don't want that strangers are able to open my Door lock by whispering to Siri... 👎 )

Thanks for your answers guys!

**Comment by NorthernMan54** [comment]
For changes, I think some research may be needed first.  If you look at the emitter side of the set request in hap-nodejs there is a context and connectionid passed with the event.  The source is may be lurking there.

I would suggest starting there in characteristic.js

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js

**Comment by calkoe** [comment]
<img width="400px" src="https://www.imakeyouintelligent.com/wp-content/uploads/2018/02/2018-02-25_11-34-41.png">
ok, i`am able to pass Values to my Node-Red output.

But I'm not able to access the connectionID variable in the "Characteristic.prototype.toHAP" method because its not passed to it. How can I access "connectionID" to pass it to the Output ? 

Please help me, I really need this :disappointed: :grin:

**Comment by NorthernMan54** [comment]
I took a moment and looked at this further, and you can access the additional data on your listener to the get or set event like this.

IrBlaster.prototype._setState = function(on, callback,value1,value2) {

debug("VALUES",value1.request,value2);

And the output looks like this

  IrBlaster VALUES { request: [Function: bound ],
  encrypt: [Function: bound ],
  decrypt: [Function: bound ],
  close: [Function: bound ],
  keepalive: true,
  '3.10': true,
  '3.11': true } af3e0f3f-24a6-414c-a773-fd5c4a3f1333 

But looking at the values, the source IP did not jump out at me.

**Comment by KhaosT** [comment]
HomeKit includes “remote” in characteristic write if the request if from remote, you can use that to filter.

**Comment by calkoe** [comment]
<img align="right" src="https://www.imakeyouintelligent.com/wp-content/uploads/2018/02/2018-02-26_08-28-35.png" />

@KhaosT where can i Access the "remote characteristic" and output them? 

`this.test2 = JSON.stringify(this);`
`this.test3 = JSON.stringify(hap);`

I this objects in the "Characteristic.prototype.toHAP" Method, theres no "remote" variable.
This is the output I get by sending from Remote (its exactly the same as send from LAN):

**Comment by KhaosT** [comment]
Right now it's not being surfaced in characteristic `set` event context. Try to print data from [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Accessory.js#L802), the `remote` should be in the request.

**Comment by calkoe** [comment]
In my Case `remote`  was always false..

I've try around a little bit and found a solution.
I'm now passing the source IP from the HTTP server through to the Output by done this changes:

<img align="left" width="600px" src="https://www.imakeyouintelligent.com/wp-content/uploads/2018/02/2018-02-26_10-31-08.png" />
<img align="left" width="600px"  src="https://www.imakeyouintelligent.com/wp-content/uploads/2018/02/2018-02-26_10-30-01.png" />
<img align="left" width="600px"  src="https://www.imakeyouintelligent.com/wp-content/uploads/2018/02/2018-02-26_10-30-41.png" />

<img src="https://www.imakeyouintelligent.com/wp-content/uploads/2018/02/2018-02-26_10-41-14.png" />

I hope this will work for me and won't produce any Errors :joy:
@KhaosT & @NorthernMan54 thanks for the Help an this awesome Project!
