### ISSUE TITLE
Hue Tap kind of switch

### ISSUE THREAD

**Issue by svh1985** [homebridge/HAP-NodeJS#563]
Is it possible to create a switch just like the Hue Tap?
Single press, (same icon), 4 subbuttons and set the action on the switch?

I've been looking into difference methods but when I us the regular switch I have to use automation do the actions. With the Hue Tap I can configure the actions on the accessory itself.

![img_1983](https://user-images.githubusercontent.com/5213210/36947653-5eaa34bc-1fcf-11e8-95fd-7f91ba56ef8b.jpg)

![img_1984](https://user-images.githubusercontent.com/5213210/36947647-51475a34-1fcf-11e8-9c02-836f5ac9921c.jpg)

**Comment by svh1985** [comment]
Thanks for your quick response, I'm gonna check if I can build such an accessory. :)

**Comment by Final-Hawk** [comment]
Could i have some example code? thanks
