### ISSUE TITLE
Client IP

### ISSUE THREAD

**Issue by p3ntium** [homebridge/HAP-NodeJS#566]
Hello:
When a notification event occurs, I'm trying to identify the client IP that originates the request. I have notifications from iOS devices, and notifications from localhost. The question is:

From the *_accessory.js code, how can I obtain the IP address of the client that is requesting the set or get characteristic?

I don't know if it understand....

Thanks in advance!
Fran

**Comment by p3ntium** [comment]
I've try by modifying the onHttpServerRequest function from eventedhttp.js and the HAPServer.js unsuccessfully....
Any idea?
Regards

**Comment by calkoe** [comment]
look here #559
