### ISSUE TITLE
iOS 11.3 - Changes

### ISSUE THREAD

**Issue by FlixMa** [homebridge/HAP-NodeJS#576]
In iOS 11.3 they made some changes to HomeKit as stated in the update notes:

> Adds support for software authentication as a new way for developers to create and enable HomeKit-compatible accessories

Does this affect our current projects?
I would say no because it’s “hardware-related”, but has anyone tried it out yet?

Thanks!

**Comment by massinegro204** [comment]
Hello I just wanted to know if this is my problem and FixMa or with iOS 11.3 everything does not work .

**Comment by massinegro204** [comment]
But FlixMa you have all ok ?

**Comment by bluntiless** [comment]
I just updated to iOS 11.3 on iPhone 7 and all accessories are still functioning correctly. ATV4 has also been updated to the latest tvOS. Remote access fully functional also. Must be something your end causing the problem.

**Comment by massinegro204** [comment]
Ok , thanks

**Comment by FlixMa** [comment]
I didn't update yet because of the fear, everything wouldn't anymore.
But if Bluntiless did update and everything seems to be fine. Why not upgrading ;-)

**Comment by massinegro204** [comment]
Ok I confirm that with iOS 11.3 everything works
