### ISSUE TITLE
Why did you replace mdns with bonjour-hap and what about Ed25519 and curve25519?

### ISSUE THREAD

**Issue by Ks89** [homebridge/HAP-NodeJS#586]
@KhaosT 
If it's because mdns doesn't support nodejs 10, version 2.4.x it should be ok right now also with nodejs 10.

Instead, Ed25519 and curve25519 are not maintained. Are there better alternatives with a good support? Searching on npmjs.org I found this library with millions of download / week: `https://www.npmjs.com/package/tweetnacl`

I don't know if it fits well, it's only an idea to try to use libraries with bigger communities.

**Comment by Ks89** [comment]
PS: also node-persist is really old.

I updated HAP-NodeJS on a private branch to node-persist 2 (it is a breaking change for hap-nodejs, because files and structures changes a little bit, but it was quite simple to do), however, right now there is a new major release only with async support here https://github.com/simonlast/node-persist and I thing that it's better to switch to that one.

What do you think?

**Comment by KhaosT** [comment]
The previous mdns library caused a lot of issues because the prequirement on certain platform. Is there a particular reason you want to bring it back?

Last time I checked, tweetnacl lacks certain functionality. I can revisit it when I have some time.

**Comment by KhaosT** [comment]
And for node-persist, the main problem is that I cannot simply upgrade the dependency, otherwise people will lost their home configuration… from what I see, they don’t offer any way to migrate from old version to new version…

**Comment by jvmahon** [comment]
For the node-persist update, I had also looked at this for a project one time. The best I could figure for a migration solution is you would have to have a "transitional" release of software that further includes a one-time utility module that checks if the database is in the "old" node-persist 1.0 format and if it is, it reads the "old" databases using the node-persist 1.0 and re-writes the data to a "new" database using node-persist 3.0 (or whatever later version). I was going to use a new naming convention for the updated database storage file as a way to determine if the database had been updated (e.g., add a version # to the file name). This seems like it would be easy enough, but I ended up not needing to do this for my project. I assume the main value in doing this would be to change to an async database model which I'm assuming helps if there is a lot of reads / writes.  I'm not suggesting this is needed, but am just making the suggestion for future consideration as you indicated a concern over lack of a migration path.

**Comment by Ks89** [comment]
This could be the perfect moment to release hap node 1.0.0 with node persist as breaking change.
If someone discovers a vulnerability or something else, the developer of node persist will fix only the last version, so in that scenario there will be only two solutions (use the vulnerable version and it's unacceptable or force to update everyone). So I think that it's better e to update to 3.x.right know with hap node. 1.0.0 as an excuse. 


Thank u for your interest in tweentnacl. It is also possible to try to ask to their to add the missing feature opening an issue. 

About mdns I haven't specific concerns right now, but I'll try to update my project and I'll update you with the result next week.

**Comment by volschin** [comment]
@Ks89 why do you think curve25519 is not maintained?

**Comment by Ks89** [comment]
DOH! I saw the wrong package, not yours but the original one. Sorry man 👍

**Comment by Ks89** [comment]
I migrated my software to the latest version of hap node without mdns and it seems to be ok. However I changed a little bit 2 or 3 lines of code (I'll investigate in a bettwer way tomorrow about this) . Tomorrow I'll finish my test and I'll add the final result. I want to stress a little bit my server xd

**Comment by Ks89** [comment]
I tried and it seems to be ok, however I replaced "name: advertiseName" with "name: this.accessoryInfo.displayName".
