### ISSUE TITLE
Node CameraCore.js

### ISSUE THREAD

**Issue by raaffq** [homebridge/HAP-NodeJS#590]
Hello , just try to setup motion eye with node cameracore.js + apple home kit

All working ok at motion eye (web) , camera show up at apple home kit , but cant see any picture at apple home kit.
any idea what is wrong?

NodeJS at Raspberry pi 3

thanks ,

**Comment by hoangtuit** [comment]
same issue

**Comment by BjornvanSchie** [comment]
Not sure if you already fixed it, but make sure that the Camera.js in the lib folder is replaced with the custom .js file that is provided with motionEye.

You can accomplish this using the following commands
`cd /home/pi/HAP-NodeJS/lib/`
`sudo mv Camera.js OriginalCamera.bak`
`sudo wget https://goo.gl/VZZMYV -O Camera.js`
