### ISSUE TITLE
Question about HTTP message encryption and splitting

### ISSUE THREAD

**Issue by longkerdandy** [homebridge/HAP-NodeJS#592]
Hi, I'm reading the HAP Specifiction and project's source code, there is somthing I don't understand.
The document says: Each HTTP message is split into frames no larger than 1024 bytes.

- is this mandatory or it's optional? does this means sending multiple responses to a single request?
- the 1024 bytes is http body or http headers included?
- what is the nonce of chacha20-poly1305 used in the encryption, doesn't find any in the document.

**Comment by Supereg** [comment]
HAP specified the following format for a singled frame (unit of transmission)
* 2 bytes: length `n` of encrypted data
* `n` bytes: encrypted data, chunks of the http message
* 16 bytes: auth tag used for authentication by the encryption algorithm to ensure the encrypted data wasn't altered

Each frame begins with a **fixed** size length number. With 2 bytes the maximum number you can represent is 1024 (in hex 0x400). This is were the limit comes from. It is not relevant if the `n` bytes of encrypted data contain a full http request/response. The http response/request is always split into multiple chunks with a maximum size of 1024 bytes, then encrypted and sent over the network. On the other side every frame is decrypted and the data is just appended. 

The [nonce](https://en.wikipedia.org/wiki/Cryptographic_nonce) is a constantly incrementing number which is thrown into the encryption algorithm (it is only used once and then incremented). Every participant counts which nonce is expected for incoming communication. The encrypted data will only be successfully decrypted if the expected nonce was used for encryption/authentication. This measure is used to prevent [replay attacks](https://en.wikipedia.org/wiki/Replay_attack).

I know it's a bit late, but nonetheless I hope I could clear up some of your questions. Feel free to reopen if you have any further questions.
