### ISSUE TITLE
Notification settings not persistent 

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#593]
Been having an issue with the last couple of accessories been coding. After adding to home, and setting say one device to turn off notifications, the setting will be remembered until I either stop  node Core.js or the service where is running. After restarting, the notification setting is turned back on.

Running node v9.10.1, Raspbian stretch

**Comment by n0rt0nthec4t** [comment]
Ok, maybe this part of my code

garageAccessory.publish({username:FAKE_GARAGEDOOR.username, pincode:FAKE_GARAGEDOOR.pincode, category:Accessory.Categories.GARAGE_DOOR_OPENER}, false);
console.log("Setup Code");
qrcode.generate(garageAccessory.setupURI(),{small: true});

Seems by calling the publish method above, this causes the issues.. Had todo this so setupURI() would function.. hrmmm

**Comment by mo22** [comment]
Same issue here - it also affects contact sensors, here the notification settings are reset to disabled after restarting the server.

**Comment by Supereg** [comment]
Could some of you maybe share the minimum required accessory code to reproduce this?
I remember, that I though this had happened to me also.

**Comment by mo22** [comment]
For me it is happening with a very simple example.

System is raspbian, node v10.15.2, hap-nodejs@0.5.6, node-persist@0.0.11

I've also checked if the data in the node-persist folder changes (i.e. using different uuids for each accessory so that HomeKit mistakes the devices for new ones after each restart) but it is unchanged.

```
import * as hap from 'hap-nodejs';

const storage = require('node-persist');
storage.initSync();

let name = 'example bridge';
const bridge = new hap.Bridge(name, hap.uuid.generate(name));
this.bridge.publish({
  port: 51826,
  username: hap.uuid.generate(name).split('-')[4].toUpperCase().match(/../g)!.join(':'),
  pincode: '123-45-678', // combination of mac and pin
  category: hap.Accessory.Categories.BRIDGE,
});

name = 'example accessory';
const accessory = new hap.Accessory(name, hap.uuid.generate(name));

name = 'example service';
let type = hap.Service.GarageDoorOpener;
const service = accessory.addService(type, name);
```

**Comment by Supereg** [comment]
I would assume that you would add the accessory to the bridge(?). Your snippet doesn't do that.
I couldn't reproduce the error on my end.
But looking at the code one problem is that you publish you bridge before you are ready. Try moving the publish after all the accessory and service initialization.

**Comment by mo22** [comment]
Moving publish after addAccessory did the trick.
Thank you very much

**Comment by Supereg** [comment]
Calling publish on a Bridge Accessory before adding Accessory CAN work if done correctly and only in certain circumstances, but nonetheless will produce useless HAP traffic and most likely will lead to undefined behavior and cause issues. So it is always to move it to the end except you really know what you are doing ☺️

**Comment by mo22** [comment]
For me everything was working just fine and as expected except that the notification settings reverted to default each time the bridge was restarted.
