### ISSUE TITLE
dynamically update characteristic props

### ISSUE THREAD

**Issue by llemtt** [homebridge/HAP-NodeJS#596]
Hi, anyone knows how to dynamically change characteristic props, like for instance HIDDEN permission to dynamically hide or show? or if this works at all?

My actual understanding is that props are sent to clients when they issue the /accessories request, is there a way to notify the clients that characteristic props have changed?

**Comment by ebaauw** [comment]
I tried changing permissions (read-only vs read/write) and changing minValue and maxValue dynamically, only to find that HomeKit would hang or kick the accessory.  My conclusion so far is that HomeKit really doesn’t like changing properties.

**Comment by llemtt** [comment]
Regarding read-only vs read-write you can somehow manage that returning a READ_ONLY_CHARACTERISTIC error from your "set" handler, but show/hide would be truly useful.

**Comment by ebaauw** [comment]
> Regarding read-only vs read-write you can somehow manage that returning a READ_ONLY_CHARACTERISTIC error from your "set" handler, but show/hide would be truly useful.

Yes, that’s doable, but I would prefer the HomeKit app to display a read-only control pro-actively, rather than re-actively slapping the user on their wrist.
