### ISSUE TITLE
Optional characteristic settings not remember

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#597]
I've been adding to the HomeKit accessories been developing for around the house. My latest one is a irrigation system.

Using the valve service with them sprinkler type configured, I've added optional characteristics for default duration, remaining duration and zone enabled. 

If I set the zone to enabled in HomeKit and confirm via "Done", it reverts back to not enabled

If I stop Core.js and restarted, the configured default duration is reset to 0.

Any ideas why this is occurring?

Running node v10.6

Code below:

var JSONPackage = require('../package.json')
var Accessory = require('../').Accessory; 
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var GPIO = require('rpio');

// Defines for the accessory
const AccessoryName =  "Irrgation System";              // name of accessory
const AccessoryPincode = "031-45-154";                  // pin code for paring 
const AccessoryUsername = "69:34:CC:5A:13:3A";          // MAC like address used by HomeKit to differentiate accessories. 
const AccessoryManufacturer = "";             	        // manufacturer (optional)
const AccessoryModel = "";                              // model (optional)
const AccessorySerialNumber = "MH20180713";             // serial number (optional) 
const AccessoryFirmwareRevision = JSONPackage.version;  // firmware revision (optional)

// Create the "valve" object. 
function ValveClass() {
    this.ValveService = null;               // Homekit service for this door
    this.zoneID = null;                     // Number of the zone
    this.timerFunc = null;                  // object to created timer for sprinkler runtime
    this.defaultRunTimeS = null;            // Pre-configured runtime in seconds
    this.GPIO_ValveRelay = 0;               // GPIO Pin for sprinkler valve control
}

ValveClass.prototype = {
	addValve: function(homekitAccessory, thisServiceName, zoneID) {
        console.log("Setting up additional service '%s' on '%s'", thisServiceName, homekitAccessory.username);

		// Add this irrigation valve to the "master" accessory and set properties
        this.ValveService = homekitAccessory.addService(Service.Valve, thisServiceName, zoneID); 
        this.ValveService.getCharacteristic(Characteristic.ValveType).setValue(Characteristic.ValveType.IRRIGATION);
        this.ValveService.addCharacteristic(Characteristic.SetDuration);
        this.ValveService.addCharacteristic(Characteristic.RemainingDuration);
        this.ValveService.addCharacteristic(Characteristic.IsConfigured);
        
        if (this.defaultRunTimeS != null) {
            this.ValveService.getCharacteristic(Characteristic.SetDuration).setValue(this.defaultRunTimeS);
            console.log("Seeting default duration on '%s' of '%s' seconds", thisServiceName, this.defaultRunTimeS);
        }
        
        this.zoneID = zoneID;

        // Initialise the GPIO input/output PINs for this valve
        GPIO.init({gpiomem: true});
        GPIO.init({mapping: 'gpio'});
        if (this.GPIO_ValveRelay != 0) GPIO.open(this.GPIO_ValveRelay, GPIO.OUTPUT, GPIO.LOW);

        // Setup Homekit callback to set the state of the sprinkler as the target
		this.ValveService.getCharacteristic(Characteristic.Active).on('set', this.setActiveState.bind(this));
    },

    setActiveState: function (state, callback) {
        if (this.ValveService.getCharacteristic(Characteristic.IsConfigured).value == Characteristic.IsConfigured.CONFIGURED) {
            if ((state == Characteristic.Active.ACTIVE) && (this.ValveService.getCharacteristic(Characteristic.Active).value == Characteristic.Active.INACTIVE)) {
                this.openValve();
                this.ValveService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.ACTIVE);
                this.ValveService.getCharacteristic(Characteristic.InUse).setValue(Characteristic.InUse.IN_USE);
                this.ValveService.getCharacteristic(Characteristic.RemainingDuration).setValue(this.ValveService.getCharacteristic(Characteristic.SetDuration).value);
                this.timerFunc = setInterval(this.runningTimer.bind(this), 100, Math.floor(new Date() / 1000), Math.floor(new Date() / 1000) + this.ValveService.getCharacteristic(Characteristic.SetDuration).value);
            } else if ((state == Characteristic.Active.INACTIVE) && (this.ValveService.getCharacteristic(Characteristic.Active).value == Characteristic.Active.ACTIVE)) {
                clearInterval(this.timerFunc);
                this.closeValve();
                this.ValveService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.INACTIVE);
                this.ValveService.getCharacteristic(Characteristic.InUse).setValue(Characteristic.InUse.NOT_IN_USE);
                this.ValveService.getCharacteristic(Characteristic.RemainingDuration).setValue(0);
            }
        }
        callback();
    },

    runningTimer: function(startTimerMS, endTimerMS) {
        this.ValveService.getCharacteristic(Characteristic.RemainingDuration).updateValue(endTimerMS - Math.floor(new Date() / 1000));
        if (this.ValveService.getCharacteristic(Characteristic.RemainingDuration).value <= 0) {
            clearInterval(this.timerFunc);
            this.closeValve();
            this.ValveService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.INACTIVE);
            this.ValveService.getCharacteristic(Characteristic.InUse).setValue(Characteristic.InUse.NOT_IN_USE);
            this.ValveService.getCharacteristic(Characteristic.RemainingDuration).setValue(0);
        }
    },

    openValve: function() {
        // Outout a high signal on the GPIO, this will trigger the connected relay to open
        GPIO.write(this.GPIO_ValveRelay, GPIO.HIGH);
        console.log("'%s' - Opened valve", this.ValveService.getCharacteristic(Characteristic.Name).value);
    },

    closeValve: function() {
        // Outout a low signal on the GPIO, this will trigger the connected relay to close
        GPIO.write(this.GPIO_ValveRelay, GPIO.LOW);
        console.log("'%s' - Closed valve", this.ValveService.getCharacteristic(Characteristic.Name).value);
    }
}

// Create the garage door opener accessory
var irrigationUUID = uuid.generate('hap-nodejs:accessories:irrigation_' + AccessoryName);
var irrigationAccessory = exports.accessory = new Accessory(AccessoryName, irrigationUUID);
irrigationAccessory.username = AccessoryUsername; 
irrigationAccessory.pincode = AccessoryPincode;
irrigationAccessory.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.Manufacturer, AccessoryManufacturer);
irrigationAccessory.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.Model, AccessoryModel);
irrigationAccessory.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.SerialNumber, AccessorySerialNumber);
irrigationAccessory.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.FirmwareRevision, AccessoryFirmwareRevision);

// Create the garage for the homekit garage door opener accessory
var Valve1 = new ValveClass();
Valve1.GPIO_ValveRelay = 14;
Valve1.addValve(irrigationAccessory, "Back Lawn", 1);

var Valve2 = new ValveClass();
Valve2.GPIO_ValveRelay  = 15;
Valve2.addValve(irrigationAccessory, "Side Lawn", 2);

var Valve3 = new ValveClass();
Valve3.GPIO_ValveRelay  = 18;
Valve3.addValve(irrigationAccessory, "Front Lawn 1", 3);

var Valve4 = new ValveClass();
Valve4.GPIO_ValveRelay  = 23;
Valve4.addValve(irrigationAccessory, "Front Lawn 2", 4);

**Comment by n0rt0nthec4t** [comment]
Done some more digging, the reverting of the "Enable Zone" setting appears to be a bug in iOS 12. (Submitted feedback on that)

**Comment by lboue** [comment]
You should probably test this: https://github.com/goedh452/homebridge-http-sprinkler
