### ISSUE TITLE
Question: Homebridge over BLE?

### ISSUE THREAD

**Issue by mlsmrc** [homebridge/HAP-NodeJS#598]
as I wrote is not a really issue but just a question.

I'm using HAP-NodeJS for my own domotic project.
Is it possible to discover the homebridge over the BLE instead of the WiFi.

Like this:
iPhone -- (BLE) -> HomeBridge -- (WiFi) -> HomeKitDevices

Thanks
Regards

**Comment by lucsoft** [comment]
nope
