### ISSUE TITLE
HomeKit Neopixel Control HAP-NodeJS

### ISSUE THREAD

**Issue by BertanStar** [homebridge/HAP-NodeJS#601]
Hi! Do you know if it is possible to control a WS2812(Neopixel) Adressable LED which is attached to Raspberry Pi’s GPIO pins using HAP-NodeJS. I just want to change the color of the LEDs using the Apple’s Home App(Screen Shot at the attachment) I’m pretty new to this so if it’s possible, can you please tell me how to do it? Thanks! Have a great day... 😇

Attachment: 
![f651b9e1-b206-4f52-82ec-e103e573e37f](https://user-images.githubusercontent.com/41781897/43313567-1ddfd00e-9199-11e8-9ff7-a97633f7fb08.jpeg)

**Comment by rigg77** [comment]
Short answer is yes, it is possible. [HomeBridge-NEOPixel](https://github.com/AchimPieters/HomeBridge-NeoPixel) from AchimPieters does a pretty good job of showing how to integrate NEOPixels with HomeBridge and his code could be a good basis to create an accessory in HAP-NodeJS. His project uses an ESP8266 to control the tape. I am working on this now, I'll let you know how it goes.
