### ISSUE TITLE
Persisting "Nearby Accessories"

### ISSUE THREAD

**Issue by bibixx** [homebridge/HAP-NodeJS#603]
So today I have finally started fiddling with HomeKit (at first with Node-RED and than purely with HAP-NodeJS) and I have run into a quite infuriating thing.
After turning off all processes connected with HomeKit (I have event turned off my computer) some of accessories still appear in a "Nearby Accessories" and I have no idea how to get rid of them.

**Comment by KhaosT** [comment]
You need call “unpublish” on accessory object on exit.

**Comment by bibixx** [comment]
Actually I thought about that but how do I do it now when the server is no longer running and I don't really remember settings I started them prviously?

**Comment by bibixx** [comment]
And still, when I run default `Core.js` or `Bridge.js` and I even added logging to unpublish method to ensure the unpublishing and still... the don't disappear.

**Comment by KhaosT** [comment]
Interesting, in those situation, when you use Bonjour browser to look around, does the accessory still show up there? Unpublish should trigger a Bonjour remove event, resulting the accessory no longer appear in accessory list.

**Comment by bibixx** [comment]
![image](https://user-images.githubusercontent.com/14880213/44802336-bcd35280-abbb-11e8-81e2-f7e8ff76a09c.png)
That's all

**Comment by KhaosT** [comment]
In this situation HAP server is not even advertising… try reboot your iOS device?

**Comment by bibixx** [comment]
Done that multiple times

**Comment by bibixx** [comment]
And the interesting thing is also that they appear on other devices and they didn't even have the Home app installed long after I turned off the server

**Comment by bibixx** [comment]
In the evening I'll try to make a clean install on my iPhone

**Comment by bibixx** [comment]
Nope still they are there 😢

**Comment by bibixx** [comment]
@KhaosT maybe I don't know how to set up Bonjour Browser or smth but even if I have the server running nothing shows up in the Browser
![image](https://user-images.githubusercontent.com/14880213/44847710-9c0b0b80-ac54-11e8-8381-b97f41561b80.png)

**Comment by ebaauw** [comment]
I see the same: _Bonjour Browser_ (on macOS) doesn't show `_hap._tcp.` advertisements, even though `dns-sd -B _hap._tcp` on the same mac does show these advertisements.  It doesn't seem to be related to homebridge - the advertisements of my v2 Hue bridge are missing just as well.  Same for _iStumbler_ on mac and _Discovery_ on iOS: they don't show _hap._tcp.  
On Raspbian Stretch, `avahi-browse -a` doesn't show any `_hap._tcp.` advertisements either, but `avahi-browse _hap._tcp.` does show them.

I'm not sure why this is happening.  I distinctly remember having seen `_hap._tcp` announcements in _Bonjour Browser_ in the past; I don't know what has changed.

**Comment by NorthernMan54** [comment]
Erik,

Keep in mind that during the Spring we switched from using the mdns package to Bonjour package to resolve challenges with the mdns installation.  But with that said, I have not seen any issues with advertisements in my ecosystem except my AirPort Extreme occasional not passing around advertisements and needing a reboot.

I have also seen some of the same flakiness in some of the various “bonjour” browsers as well, but I have noticed any operational impact as a result.

**Comment by ebaauw** [comment]
Thanks, Sean.  I don’t think it’s related to the different Bonjour im0lementation.  As I mentioned, I’m seeing the same for my Hue bridge’s native HomeKit function.

**Comment by ebaauw** [comment]
Just figured out, if you add the `_hap._tcp.` service in _Preferences_, then _Bonjour Browser_ does show the announcements:
![untitled](https://user-images.githubusercontent.com/22179355/44868217-78fb4e80-ac8a-11e8-9a05-9708a4373c04.jpeg)

**Comment by bibixx** [comment]
Well, now suddenly everything disappeared and guess what. Now I can't find any accessory even though it is in a _Bonjour Browser_ (thanks @ebaauw for a solution to _BB_)

**Comment by bibixx** [comment]
![image](https://user-images.githubusercontent.com/14880213/44873968-fda19900-ac99-11e8-9f0d-4b7ee3da6cee.png)
And now... It appears that if I stop the server it doesn't unpublish, even though it logs that it does (I have added logging here
```javascript
Accessory.prototype.unpublish = function() {
  debug("[%s] Unpublishing", this.displayName);
  if (this._server) {
    this._server.stop();
    this._server = undefined;
  }
```
)
