### ISSUE TITLE
Hidden service

### ISSUE THREAD

**Issue by Gatux** [homebridge/HAP-NodeJS#611]
Has anyone been able to make this work recently? (HAP-NodeJS 0.4.47 and iOS 12)

I thought the service would be hidden in Home but I can still see it.

https://github.com/KhaosT/HAP-NodeJS/blob/9eaea6df40811ccc71664a1ab0c13736e759dac7/accessories/AirConditioner_accessory.js#L148

**Comment by Supereg** [comment]
https://github.com/KhaosT/HAP-NodeJS/blob/9eaea6df40811ccc71664a1ab0c13736e759dac7/accessories/AirConditioner_accessory.js#L8

This is from the HAP specs:
```
2.3.2.1 Service Naming
Not all services provide user-visible or user-interactive functionality. Services which provide either user-visible or user-interactive functionality must include the Name characteristic, see Name (page 157); all other services must not include this characteristic. This convention is used by iOS controllers to determine which services to display to users.
```

If you don't include a name service the service should also be marked as hidden. Don't know though if this works in the Home App. You could try it.

**Comment by Gatux** [comment]
Thanks for your reply.

Indeed it might be not possible to hide a service with the Home App :

```
2.3.2.4 Hidden Service
Accessories may specify the services that are to be hidden from users by a generic HomeKit application.
Accessories may expose several services that could be used to configure the accessory or to update firmware
on the accessory, these services should be marked as hidden. When all characteristics in a service are marked
hidden then the service must also be marked as hidden
```
-> "generic HomeKit application"

I tried different things like removing the Name characteristic and adding to all charateristics the "hidden" perm but nothing changed, still visible :(

**Comment by Supereg** [comment]
So hiding services does not work at all? Do other apps like the Eve app respect hidden services?
Hiding characteristics should work though?
