### ISSUE TITLE
HomeKit Support For Remote Controls

### ISSUE THREAD

**Issue by erokoder** [homebridge/HAP-NodeJS#612]
iOS 12 To Offer HomeKit Support For Remote Controls, 
do you have plan to add this accessories to HomeKitTypes.js ?
Thanks

**Comment by erokoder** [comment]
@KhaosT 
If I understand well, Remotes Accessories in iOS12 use for **3rd Party Device**, not only apple TV.
HomeKit support for third-party remote controls coming in iOS 12 also include apple TV.
Link: https://appleinsider.com/articles/18/06/12/homekit-support-for-third-party-remote-controls-coming-in-ios-12-and-tvos-12
Because I have some plugin for homebridge when I must use many switch for power OFF/ON, Volumes UP and Down, change channel, turn HDMI. 
It would be wonderful to have it all in one Accessories. I suppose that new Remotes Accessories used to it.

**Comment by KhaosT** [comment]
That’s not what the remote controller profile is primarily for… the whole profile is designed to only work for tvOS…

**Comment by leoneleone** [comment]
@KhaosT 
Is that still the case in the latest iOS 12.1.1?

**Comment by KhaosT** [comment]
Yup

**Comment by MiguelRipoll23** [comment]
I can't find any information about the profile, is the information you got coming from reverse engineering or a developer webpage?

**Comment by KhaosT** [comment]
Anything specific you want to know? Yeah, you can figure out the capability of remote from tvOS homed binary.

**Comment by MiguelRipoll23** [comment]
Not sure but I guess the “Remote” profile is being used to interact with TV’s and the Apple TV?

https://9to5mac.com/2019/01/06/apple-says-leading-tv-manufacturers-will-integrate-airplay-2-send-video-to-tv-with-siri-voice-commands/

**Comment by KhaosT** [comment]
That's done over AirPlay 2 protocol, which is different from HAP protocol, and the remote control profile.

**Comment by DoctorNSA** [comment]
Does this remote controller profile support Siri integration?
If yes I would be interested in trying to implement it

**Comment by KhaosT** [comment]
It allows accessory to act as a Siri Remote to Apple TV. If you are interested in supporting data stream for HomeKit, feel free to do so :)

**Comment by Supereg** [comment]
Any idea where to start? Anything documented which one could work with?

**Comment by DoctorNSA** [comment]
Unfortunately I can’t find any information about the tvOS homed binary. Where did you get the human readable version?

**Comment by Supereg** [comment]
Feature was added some time ago
