### ISSUE TITLE
Door Accessory always in opening state

### ISSUE THREAD

**Issue by DevSpur** [homebridge/HAP-NodeJS#622]
Hi I'm having an issue getting the door accessory working correctly I have half it working by receiving the value from 0 to 100 to open the door to a certain position  but the problem Im having is that once I stop on a value the door status is alway in opening with the loading wheel spinning and never stops. So I don't know what Im missing Ive attached a image to show the opening state and spinning wheel 
![img_0939](https://user-images.githubusercontent.com/18281465/48074763-58032c80-e1ea-11e8-9451-0173d9808f52.PNG)

This is the code Im using
`var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var lightState = 0;

////////////////CHANGE THESE SETTINGS TO MATCH YOUR SETUP BEFORE RUNNING!!!!!!!!!!!!!//////////////////////////
////////////////CHANGE THESE SETTINGS TO MATCH YOUR SETUP BEFORE RUNNING!!!!!!!!!!!!!//////////////////////////
var name = "Door1";                                       //Name to Show to IOS
var UUID = "hap-nodejs:accessories:windowDoor1xx";     //Change the RGBLight to something unique for each light - this should be unique for each node on your system
var USERNAME = "00:AA:AA:AA:AA:AA";              //This must also be unique for each node - make sure you change it!

var MQTT_IP = '192.168.8.113'
var TopicOpen = 'Home/Door1O'
var TopicClose = 'Home/Door1C'
////////////////CHANGE THESE SETTINGS TO MATCH YOUR SETUP BEFORE RUNNING!!!!!!!!!!!!!//////////////////////////
////////////////CHANGE THESE SETTINGS TO MATCH YOUR SETUP BEFORE RUNNING!!!!!!!!!!!!!//////////////////////////

// MQTT Setup
var mqtt = require('mqtt');
var options = {
  port: 1883,
  host: MQTT_IP,
  clientId: '00GAK35243'
};
var client = mqtt.connect(options);
client.on('message', function(topic, message) {

});

//setup HK light object
var lightUUID = uuid.generate(UUID);
var light = exports.accessory = new Accessory(name, lightUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
light.username = USERNAME;
light.pincode = "031-45-154";

//add a light service and setup the On Characteristic
light
  .addService(Service.Door)
  .getCharacteristic(Characteristic.TargetPosition)
  .on('get', function(callback) {
    callback(null, lightAction.getState());
  });

  light
  .getService(Service.Door)
  .getCharacteristic(Characteristic.TargetPosition)
  .on('set', function(value, callback) {
    lightAction.setState(value);
    console.log("Door " + value);
    callback();
  });

// here's a fake temperature sensor device that we'll expose to HomeKit
var lightAction = {

  //initialize the various state variables
  currentState: 0,

  //On Characteristic set/get
  getState: function() { return this.currentState;},
  setState: function(newState){

 if(newState != this.currentState ){
      console.log("Setting new Door state: " + newState.toString());
      if(newState > 0){
        client.publish('Home/Door1O', newState.toString());
        this.currentState = newState;
      }
      else if(newState == 0){
        client.publish('Home/Door1C', newState.toString());
        this.currentState = 0;
      }
    }

  },
  //other light setting functions
  updateState: function() {
    this.currentState = lightState;
  },
  
}

// update the characteristic values so interested iOS devices can get notified
setInterval(function() {
  light
    .getService(Service.Door)
    .setCharacteristic(Characteristic.TargetPosition, lightAction.currentState);
}, 2000);`

**Comment by Supereg** [comment]
You are missing the `CurrentPosition` characteristic of the door service. This is used to determine the state of the door.

You are also so missing the required characteristic `PositionState`

**Comment by DevSpur** [comment]
@Supereg  Hi thanks for the reply do you have an example code as I have no clue where to put it and how to use it 
Thanks
