### ISSUE TITLE
Adding accessory in home.app keeps searching

### ISSUE THREAD

**Issue by iAmRenzo** [homebridge/HAP-NodeJS#623]
I've made my Raspberry Pi 3 B+ into a camera, like described in [this tutorial](https://raspberrytips.nl/raspberry-pi-homekit-camera). The camera works but when adding it to the home.app it keeps searching and won't add it.
Somewhere I read that one had issues with the same thing if there is another Pi with HomerBridge allready added to the home.app. I have this too.
I changed the HAP-NodeJS pincode (otherwise it would be the same) but that doesn't work.
I don't know how to fix this or make it that my HAP-NodeJS can be added.

**Comment by iRayanKhan** [comment]
Make sure you are on the same Wi-Fi and band as the Rpi
