### ISSUE TITLE
Add Characteristic.CurrentRelativeHumidity as an optional to Service.HeaterCooler

### ISSUE THREAD

**Issue by nitaybz** [homebridge/HAP-NodeJS#627]
Hey!

I've notice lately the the CurrentRelativeHumidity Characteristic can be added to the HeaterCooler service and it actually looks natural in Home App (see pic).

![zhnelyfksiirpdn ela69q_thumb_f1b](https://user-images.githubusercontent.com/16838394/49430026-9d4b5780-f7b2-11e8-8477-411b8d8f4c3a.jpg)

I think it should be added as an optional if homekit support that and the error `HAP Warning: Characteristic... not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.` will not show regarding this case.

**Comment by songzh96** [comment]
very nice.

Airpurifier also can add Filter element

**Comment by songzh96** [comment]
Hi，Brother。
when you use thermostat，if you use siri to say "turn off thermostat",it will turn off?
well, when i say it. thermostat will switch to auto mode.
Do you have met this bug?
