### ISSUE TITLE
AC power info from tasmota to homekit ??

### ISSUE THREAD

**Issue by lisergio** [homebridge/HAP-NodeJS#632]
Hi, 
I have connected a power meter to an esp8266 with the tasmota firmware, to see the consumption information of my house.

https://github.com/arendst/Sonoff-Tasmota/issues/3694

there is some accessory that we can connect to HAP-NodeJS to see it in homekit

![img_1852](https://user-images.githubusercontent.com/289037/50523839-7db5ff00-0ad2-11e9-8882-75b295c4cf2b.PNG)

i try tu use temperature_accessory,  but not work... 
thanks!!

**Comment by justme-1968** [comment]
you can use the private characteristics vom legato eve for most of these. see here: https://gist.github.com/gomfunkel/b1a046d729757120907c
