### ISSUE TITLE
Changing display name of characteristic

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#636]
Been searching past issues here and cannot find really an answer to my question. Say I have created a battery service attached to an accessory. In the settings for the accessory teh text describing, for example, the battery level, is shown as "Battery Level". 

Is there a way to change this displayed text in the accessory settings for the characteristic? So rather than seeing the name "Battery Level" I could have it "Solar Level"

**Comment by NorthernMan54** [comment]
Unfortunately that is not a feature of the home app.
