### ISSUE TITLE
Service.InputSource use case?

### ISSUE THREAD

**Issue by leoneleone** [homebridge/HAP-NodeJS#641]
@KhaosT 

Looking at the new Television services added:

Can you please explain Service.InputSource, how and what it can be used for?
What use-case is there for:

Characteristic.InputSourceType and Characteristic.InputDeviceType 

```
/**
 * Service "Input Source"
 */

Service.InputSource = function(displayName, subtype) {
  Service.call(this, displayName, '000000D9-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.ConfiguredName);
  this.addCharacteristic(Characteristic.InputSourceType);
  this.addCharacteristic(Characteristic.IsConfigured);
  this.addCharacteristic(Characteristic.CurrentVisibilityState);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Identifier);
  this.addOptionalCharacteristic(Characteristic.InputDeviceType);
  this.addOptionalCharacteristic(Characteristic.TargetVisibilityState);
  this.addOptionalCharacteristic(Characteristic.Name);
};

inherits(Service.InputSource, Service);

Service.InputSource.UUID = '000000D9-0000-1000-8000-0026BB765291';
```

Thanks for the info :)

**Comment by KhaosT** [comment]
I’m not entirely sure. Those just exist in accessory metadata, and currently nothing in iOS uses it.

**Comment by ebaauw** [comment]
These form the drop down list entries that the Home app shows when selecting _Input_.  Each service instance is an entry.  The _Identifier_ gives the value for _ActiveIdentifier_ in the TV service.  Also, the _ConfiguredName_ is shown in the tile (when the TV is on).  These names are user editable under _Settings_.

**Comment by leoneleone** [comment]
@ebaauw 
Thanks for the clarification.
Any idea what the (Optional) **Characteristic.InputDeviceType** is or how it can be used? 
None of the homebridge plugins with iOS 12.2 "TV Service" support seem to be utilising this Characteristic and I'm curious to see what this Characteristic actually does if assigned to a Service.InputSource

```
/**
 * Characteristic "Input Device Type"
 */

Characteristic.InputDeviceType = function() {
  Characteristic.call(this, 'Input Device Type', '000000DC-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.UINT8,
    maxValue: 5,
    minValue: 0,
    validValues: [0,1,2,3,4,5],
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.InputDeviceType, Characteristic);

Characteristic.InputDeviceType.UUID = '000000DC-0000-1000-8000-0026BB765291';

// The value property of InputDeviceType must be one of the following:
Characteristic.InputDeviceType.OTHER = 0;
Characteristic.InputDeviceType.TV = 1;
Characteristic.InputDeviceType.RECORDING = 2;
Characteristic.InputDeviceType.TUNER = 3;
Characteristic.InputDeviceType.PLAYBACK = 4;
Characteristic.InputDeviceType.AUDIO_SYSTEM = 5;

```

**Comment by ebaauw** [comment]
I can only theorise that HomeKit apps might use this to display an icon for the corresponding input source.  I would hope that changing the accessory category displays a different icon in the tile, but I haven't been able to test this out.  Historically, the accessory category seemed to be used only for the icon displayed during device discovery/pairing.

**Comment by leoneleone** [comment]
> I can only theorise that HomeKit apps might use this to display an icon for the corresponding input source.

Your theory seems logical, but the current TV service implementation does not display any icons next to the individual InputSource in the Inputs list. Perhaps since its a Television this characteristic defaults to the TV=1 value?
Plus, if this Characteristic simply changes the display icon for the Inputs listed in only the "Television Service" then the choice of values: Other, TV, Recording, Tuner, Playback, Audio System seems slightly off, especially "recording" and "playback". 
I wonder whether Apple is laying the groundwork for more "InputSource" accessories other than just TVs.
AV Receivers within HomeKit could use an InputSource selection architecture similar to the new TV Service, instead of appearing as a near useless "Speaker" tile for example.

If you do manage to find out what Characteristic.InputDeviceType actually does or changes please do let me know :)

**Comment by n0rt0nthec4t** [comment]
I've developed two accessories since teh initial support for TVs was added.. One for my Sony Bravia TV and the other for my Denon AVR (Even though not a TV, its create to be able to select Input sources and use those in HomeKit scenes.  Happy to share the code if anyones interested in playing with what developed

**Comment by justme-1968** [comment]
i have trouble getting the input selection to work with the old style platform plugin. is this supposed to work with non dynamic plugins? as homebridge-fhem always fetches the current state from fhem there was no need to convert it to the dynamic style.

**Comment by leoneleone** [comment]
@n0rt0nthec4t 
I wouldn’t mind taking a look at your plugin for the DenonAVR.
Can you please share that with me? 😊

**Comment by leoneleone** [comment]
@n0rt0nthec4t 
Also, Does your plugin use the different values for Characteristic.InputDeviceType? In the DenonAVR plugin: have you set Characteristic.InputDeviceType.Audio_System = 5 ?

**Comment by lboue** [comment]
@n0rt0nthec4t 
I am also interested to look at your plugin for the Denon AVR.

**Comment by n0rt0nthec4t** [comment]
Here's my Denon accessory. Just update IP income to your AMP. I have an AVR-X3300W which it works on so far using iOS 12.2beta2

https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/blob/master/Denon_accessory.js

**Comment by leoneleone** [comment]
@n0rt0nthec4t 
Thanks for your code. 
I’ve yet to use it as I want to create a HomeBridge plugin based on your code first. 

Can you tell me what changes in HomeKit when using the various values for Characteristic.InputDeviceType? 
You code uses that characteristic.

**Comment by n0rt0nthec4t** [comment]
> @n0rt0nthec4t
> Thanks for your code.
> I’ve yet to use it as I want to create a HomeBridge plugin based on your code first.
> 
> Can you tell me what changes in HomeKit when using the various values for Characteristic.InputDeviceType?
> You code uses that characteristic.
> Screencaps? 😊

Not using that characteristic. Using Characteristic.InputSourceType. Under iOS 12.2 beta 2 it doesn't change anything in HomeKit

![img_0148](https://user-images.githubusercontent.com/19759130/52749283-c9017e00-303c-11e9-82fe-b6c326c85099.png)
![img_0147](https://user-images.githubusercontent.com/19759130/52749286-ca32ab00-303c-11e9-9321-3034ae06865d.png)

**Comment by nicoduj** [comment]
Hi, I have written a version for harmony hub that use this mode. However, I have an issue I can't solve : when I had 2 accessories (two hubs), Only one is showing in the remote controls app (the 2 are shown in the home app, and working). Any idea ?

**Comment by ebaauw** [comment]
> when I had 2 accessories (two hubs), Only one is showing in the remote controls app (the 2 are shown in the home app, and working). Any idea ?

I see the same exposing multiple (five) Sonos speakers as _TV_ accessories.  For now, I assume it's because we're on iOS beta.

**Comment by nicoduj** [comment]
Thank you @ebaauw !

**Comment by nicoduj** [comment]
I might have an idea there on what’s happening  : if i have 2 homebridge instance on my nas and my mac it works fine. I think remote app might discover the tv device through ip on the same network (like it does for atv). Since homebridge hub is showing only as one ip / device on the network that might be a problem. What do you think ?

**Comment by ebaauw** [comment]
I doubt whether it's because of the same IP address (you could check by running both homebridge instances on you mac), but it might have to do with the Remote app not liking multiple TVs behind the same Bonjour service.

Somewhere in the fine print, the HAP spec states that a HomeKit bridge is only to be used for accessories that don't natively talk IP.  I've never encountered a smart TV that used another protocol, so it might very well be that Apple simply doesn't cater for the use case of (multiple) TV accessories behind a HomeKit bridge (Bonjour service).  Meaning it might not be fixed in the beta cycle...

**Comment by nicoduj** [comment]
Makes sense thank you for sharing your opinion . I tried to post a question through apple bug report and on dev forums, let’s see if we have any answer on this !

**Comment by ebaauw** [comment]
I tested with two homebridge instances running on my macBook, each exposing five _Television_ accessories.  The AppleTV widget showed two televisions alright, one from each homebridge instance.

Just a crazy idea: how would the widget handle two _Television_ services in one accessory.  I've been wondering why the _Input Source_ services need to be linked to the _Television_ service.  The again, the _Television Speaker_ service doesn't...

**Comment by nicoduj** [comment]
Hum, I can try exposing 2 TV Service just to see ! concerning the Speaker Service, I do link it also 
    this.mainService.controlService.addLinkedService(
      this.tvSpeakerService.controlService
    );

**Comment by justme-1968** [comment]
but the speaker service works without being linked. (it works perfectly fine from a mapping in my FHEM plugin. without any special handling.)

till now i have not gotten the input service to work with my plugin.
