### ISSUE TITLE
TLV8 format for TV DisplayOrder characteristic

### ISSUE THREAD

**Issue by zwaldowski** [homebridge/HAP-NodeJS#644]
Not sure where else to put this information or where it would be helpful to keep it documented, but for bschlenk/homebridge-roku#63 I figured out the format for the `Characteristic.DisplayOrder`: it's an array of `UInt32`, containing the identifiers (`Characteristic.Identifier`) of the input sources. Each element is a TLV of type `1`, with consecutive elements joined by `0000` (empty TLV of type `0`). Even implementing it read-only, ordering them relative to what the TV shows is way better than HomeKit alphabetizing them.

Some code for that looks something like:

```javascript
var DisplayOrderTypes = {
  ARRAY_ELEMENT_START: 0x01,
  ARRAY_ELEMENT_END: 0x00
}

function encodeIdentifiers(listOfIdentifiers) {
  var identifiersTLV = Buffer.alloc(0)
  listOfIdentifiers.forEach(function(identifier, index) {
    if (index != 0) {
      identifiersTLV = Buffer.concat([
        identifiersTLV,
        tlv.encode(DisplayOrderTypes.ARRAY_ELEMENT_END, Buffer.alloc(0))
      ])
    }

    var element = Buffer.alloc(4)
    element.writeUInt32LE(identifier, 0)
    identifiersTLV = Buffer.concat([
      identifiersTLV,
      tlv.encode(DisplayOrderTypes.ARRAY_ELEMENT_START, element)
    ])
  })
  return identifiersTLV.toString('base64')
}
```

`HomeKitDaemon` has support for writing this payload out, but making the characteristic writable doesn't seem to work to make them reorderable as a beta 2.

**Comment by tobekas** [comment]
It does also work without these empty TLV entries and with a length of 1 byte, like this:
`displayOrderTlvValue = new Buffer.from([1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 4, ...]).toString('base64');`
