### ISSUE TITLE
Add new project based on HAP-NodeJS to README

### ISSUE THREAD

**Issue by Shaquu** [homebridge/HAP-NodeJS#648]
Hey there,
From some time we are working on the node-red-contrib-homekit fork which last update is like year ago and a contact to project owner is lost.

We got our fork here:
https://github.com/oliverrahner/node-red-contrib-homekit-bridged

Please add it to README so more people know us :)

Thanks!

**Comment by sjorge** [comment]
+1 I recently (last week) found this and I'm using it with the node-red openhab2 plugin and it's amazing!

**Comment by Shaquu** [comment]
@sjorge thanks :) 
We are still working to improve it.

**Comment by Shaquu** [comment]
@sjorge If you like my work then please rate module on node-red site:
https://flows.nodered.org/node/node-red-contrib-homekit-bridged
