### ISSUE TITLE
Modified Fan Won't Turn Off

### ISSUE THREAD

**Issue by ahnyerkeester** [homebridge/HAP-NodeJS#650]
I've taken the Fan_accessory and modified it a bit to run my Swamp Cooler (a.k.a. Evaporative Cooler) controller. It works well for various fan speeds but when I tell Siri "Turn off the Swamp Cooler" she says she did but nothing happens. It only turns off the fan if i say "Set the Swamp Cooler to zero" or do it manually on the slider.

The code is listed below but I'm also wondering if there is a place I can learn how to code these things. I know js but there are things going on that I'm not really clear on. Help?
```

var cmd = require('node-cmd');
var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;

var SWAMP_COOLER = {
  name: "Swamp Cooler",
  username: "1A:2B:CC:17:01:FF",
  pincode: "031-45-154",

  speed: 0,

  setSpeed: function(value) {
//    if(this.outputLogs) console.log("Setting Speed to %s", this.name, value ? "high" : "low");
    this.speed = value;

      if (value >= 1 && value <= 33) {
      // First third is low
      cmd.run('sudo python /home/pi/python/fanlow.py');}

      else if (value > 33 && value <= 66) {
      // Second third is medium
      cmd.run('sudo python /home/pi/python/fanmed.py');}

      else if (value > 66 && value <= 100) {
      // Top third is high
      cmd.run('sudo python /home/pi/python/fanhi.py');}

      else {
      // < 1 or > 100 is off
      cmd.run('sudo python /home/pi/python/fanoff.py'); }

  },

 setPowerOn: function(on) {
    if(on){
      //put your code here to turn on the fan
//      SWAMP_COOLER.powerOn = true;
      cmd.run('sudo python /home/pi/python/fanon.py');
    } else {
      //put your code here to turn off the fan
//      SWAMP_COOLER.powerOn = false;
      cmd.run('sudo python /home/pi/python/fanoff.py');
    }
    SWAMP_COOLER.powerOn = on;
  },

  identify: function() {
    if(this.outputLogs) console.log("'%s' Identified!", this.name);
  }
}

var fanUUID = uuid.generate('hap-nodejs:accessories:Fan'+ SWAMP_COOLER.name);
var fanAccessory = exports.accessory = new Accessory(SWAMP_COOLER.name, fanUUID);

fanAccessory.username = SWAMP_COOLER.username;
fanAccessory.pincode = SWAMP_COOLER.pincode;

//SWAMP_COOLER
//  .getService(Service.AccessoryInformation);

fanAccessory.on('identify', function(paired, callback) {
  SWAMP_COOLER.identify();
  callback();
});

fanAccessory
  .addService(Service.Fan, SWAMP_COOLER.name)
  .getCharacteristic(Characteristic.RotationSpeed)
  .on('set', function(speed, callback) {
     SWAMP_COOLER.setSpeed(speed);
     callback();
  })
  .on('get', function(callback) {
    callback(null, SWAMP_COOLER.setSpeed());
  });

```

**Comment by Supereg** [comment]
Note the following. You have configured the Fan **Service**. As of the HomeKit Spec the Fan has the following **Characteristics**:
- **On** (required)
- **RotationDirection** (optional)
- **RotationSpeed** (optional)

All required characteristics are added to the Service automatically in HAP-NodeJS.
In your Code you have configured for the RotationSpeed characteristic 'set' and 'get' events. So far so good (Note that in the get event you actually don't return any value for HomeKit, so probably the percentage isn't correctly displayed once HomeKit updates the values).
When you power on/off the fan that action is handled by the **On** characteristic and you haven't setup any 'get' or 'set' listeners. So what basically happens is that HomeKit talks to HAP-NodeJS and just updates the internal value of the **On** characteristic, but nothing is hooked up to your code yet.

I hope that is a bit understandable 😅

If you need more information about the HAP (HomeKit Accessory Protocol) Spec you could look into the source of HAP-NodeJS where all Service and characteristics are defined, the most relevant is [HomeKitGen.js](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js).
You could also have a look into the Non-Commercial Spec sheet directly from Apple [HAP Spec](https://developer.apple.com/support/homekit-accessory-protocol/) (This PDF is not that well maintained and is missing some of the newer Services an characteristics from iOS 11 and iOS 12 but the official spec is sadly only for licensed MFI Partners). The third method would be to learn from existing code, maybe also looking into the Homebridge project which basically implements a HomeKit bridge with an API for third party plugins.

**Comment by ahnyerkeester** [comment]
> I hope that is a bit understandable 😅
I am a noob when it comes to this which is why I asked where I might learn more. But I _think_ I get it. Thank you! I really appreciate your patience. I wish there was an introductory course on this, I have the PDF but didn't find it super helpful or clear.

What I think I need to do, then, is add this to `fanAccessory`?

```
  .on('set', function(on, callback) {
     SWAMP_COOLER.setPowerOn(on);
     callback();
  })
```
Is that it?

**Comment by ahnyerkeester** [comment]
Ha! I did some digging around in other accessories and figured it out. For those of you playing along at home, I added this:

```
fanAccessory
  .getService(Service.Fan, SWAMP_COOLER.name)
  .getCharacteristic(Characteristic.On)
  .on('set', function(value, callback) {
    SWAMP_COOLER.setPowerOn(value);
    callback()
  })
  .on('get', function(callback) {
    callback(null, SWAMP_COOLER.setPowerOn());
  });
```
I think I might be getting the hang of this. Thanks again @Supereg !!
