### ISSUE TITLE
Update accessories examples

### ISSUE THREAD

**Issue by lucsoft** [homebridge/HAP-NodeJS#651]
How do you use the StatelessProgrammableSwitch?

**Comment by ebaauw** [comment]
To use it, you need an AppleTV, HomePod, or powered iPad as HomeKit hub.

To expose it from HAP-NodeJS, you need to create an accessory with a single ServiceLabel service and a StatelessProgrammableSwitch service per button.

**Comment by lucsoft** [comment]
Can you show me how you did it?

**Comment by ebaauw** [comment]
It's in https://github.com/ebaauw/homebridge-hue/blob/master/lib/HueSensor.js, but that's probably the most difficult example you can think of.

For e.g. the Hue dimmer switch, I create four buttons, with _Single Press_ and _Long Press_ actions for each button: https://github.com/ebaauw/homebridge-hue/blob/b6be9e7c7f291fafbef341c921abd2a54a9941fe/lib/HueSensor.js#L242.  I use helper routines to setup the services: https://github.com/ebaauw/homebridge-hue/blob/b6be9e7c7f291fafbef341c921abd2a54a9941fe/lib/HueSensor.js#L1327 and https://github.com/ebaauw/homebridge-hue/blob/b6be9e7c7f291fafbef341c921abd2a54a9941fe/lib/HueSensor.js#L1332.

**Comment by lucsoft** [comment]
now i'm wondering where you get those functions (getInfoService,getLabelService)

Here is my code (Its not the best)
https://github.com/lucsoft-DevTeam/HomeSYS/blob/master/Mainframe/modules/lucsoft.HAPWrapper.js#L243

**Comment by ebaauw** [comment]
They're from here: https://github.com/ebaauw/homebridge-hue/blob/b6be9e7c7f291fafbef341c921abd2a54a9941fe/lib/HueAccessory.js#L351.  I'm combining multiple Hue bridge resources into a single accessory, and I want to make sure there's only one _Accesory Information_ and one _Label Service_ per accessory.

You want to be doing something like:
```javascript
const labelService = new Service.LabelService(displayName)
labelService.getCharacteristic(Characteristic.ServiceLabelNamespace)
  .setValue(Characteristic.ServiceLabelNamespace.ARABIC_NUMERALS)
cmodule.addService(labelService)
const button1Service = new Service.StatelessProgrammableSwitch('Button 1', 1)
button1Service.getCharacteristic(Characteristic.ProgrammableSwitchEvent)
  .setProps({
    minValue: Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS,
    maxValue: Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS
  })
button1Service.getCharacteristic(Characteristic.LabelIndex)
  .setValue(1)
cmodule.addService(button1Service)
const button2Service = new Service.StatelessProgrammableSwitch('Button 2', 2)
button2Service.getCharacteristic(Characteristic.ProgrammableSwitchEvent)
  .setProps({
    minValue: Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS,
    maxValue: Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS
  })
button2Service.getCharacteristic(Characteristic.LabelIndex)
  .setValue(2)
cmodule.addService(button2Service)
```
_ProgrammableSwitchEvent_ is event only, it doens't allow read nor write.  So there's no `'get'` nor `'set'` events.  To fire the switch, do something like:
```javascript
button1Service.getCharacteristic(Characteristic.ProgrammableSwitchEvent)
  .updateValue(Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS)
```

**Comment by lucsoft** [comment]
Where do you get LabelService from?
(Note: Im using HAP-NodeJS only)

Error:
``` /root/Mainframe/Mainframe/modules/lucsoft.HAPWrapper.js:242
Mär 03 23:05:20 homesys node[1604]:     const labelService = new Service.LabelService(settings.displayName)
Mär 03 23:05:20 homesys node[1604]:                          ^
Mär 03 23:05:20 homesys node[1604]: TypeError: Service.LabelService is not a constructor
Mär 03 23:05:20 homesys node[1604]:     at Object.ed.createCustom (/root/Mainframe/Mainframe/modules/lucsoft.HAPWrapper.js:242:26)
Mär 03 23:05:20 homesys node[1604]:     at Object.mmanager.onModulesAllCompleted (/root/Mainframe/Mainframe/modules/lucsoft.Mainframe.js:107:17)
Mär 03 23:05:20 homesys node[1604]:     at mmang.onModulesInitialized (/root/Mainframe/Mainframe/lib/modulemanager.js:46:19)```

**Comment by ebaauw** [comment]
https://github.com/KhaosT/HAP-NodeJS/blob/414cd96ca9708596b1f71304bd4e6dff5ab045fc/lib/gen/HomeKitTypes.js#L3303

Sorry, it’s ServiceLabel.
