### ISSUE TITLE
Television Service - RemoteKey - how to send some keys ?

### ISSUE THREAD

**Issue by nicoduj** [homebridge/HAP-NodeJS#653]
Hi,

Does anyone knows how to send the following keys from IOS to Television Service ? :
Characteristic.RemoteKey.REWIND = 0;
Characteristic.RemoteKey.FAST_FORWARD = 1;
Characteristic.RemoteKey.NEXT_TRACK = 2;
Characteristic.RemoteKey.PREVIOUS_TRACK = 3;
Characteristic.RemoteKey.EXIT = 10;

**Comment by ebaauw** [comment]
No.  There was an _Exit_ button in the _Remote_ widget in an earlier beta, but seems they removed it.

**Comment by nicoduj** [comment]
Ok, thank you, same feeling here :) 
I am also wondering how to use the following characterisitc and if they have any consequence on the remote.  I tried different ones but saw no change :

For Television Service : 
- Characteristic.CurrentMediaState (and TargetMediaState)
- Characteristic.PowerModeSelection

For Input Service : 
- Characteristic.InputDeviceType
- Characteristic.InputSourceType

**Comment by ebaauw** [comment]
Haven't tried the _Television_ service characteristics, but indeed, the _Input Service_ characteristics don't seem to do anything currently.

I'm exposing five TV accessories (for my Sonos zones), but under public beta 5, they're only visible in Apple's Home app - no longer in other HomeKit apps?!  Tried Eve, Matthias' Home app, and Hesperus.  I share my test home (from my test Apple ID) to my real apple ID, and I can see the TV accessories in other HomeKit apps on iOS 12.1.4.  Seems to be a "feature" of the iOS 12.2 beta 5 HomeKit runtime?

**Comment by nicoduj** [comment]
I have the same issue. In beta 4 television service and inputs were visible in eve app. Not anymore in beta 5 ! I think it is still under development and maybe won’t be fully ready for final release since lg announced a mid year availability I think, maybe they will delay some features in a 12.2.x ... will see ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by n0rt0nthec4t** [comment]
> For Television Service :
> 
> * Characteristic.CurrentMediaState (and TargetMediaState)
> * Characteristic.PowerModeSelection
 
PowerModeSelction appears to create the "View Tv Settings" option under the settings menu. If you create an "on.set" call-back, can use to open the settings menu on your TV with the appropriate commands

**Comment by nicoduj** [comment]
@n0rt0nthec4t thank you will try that ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leoneleone** [comment]
@nicoduj 

I believe Characteristic.PowerModeSelection exposes a “Menu” button in the iOS Remote widget, very useful

**Comment by justme-1968** [comment]
i have a PowerModeSelection but no menu button. which is quite annoying. there must be something else to get the menu button.

**Comment by nicoduj** [comment]
It odes not expose it in the widget, but in the properties of the accessory in home app . As far as I know, the button on the widget remote itself was removed in beta 2.
![IMG_EAA084711996-1](https://user-images.githubusercontent.com/19813688/54475599-3991eb00-47f3-11e9-9243-7cc09f1c6cab.jpeg)

**Comment by justme-1968** [comment]
yes. i know. but this ist quite unusable...  changing the app, tap, long press, tap, scroll, tap. this is something that can be used for first time setup. not for actual remote control.

a menu button in the widget and a menu key in the RemoteKey characteristic are the only sensible solution. like it is in the apple tv widget version.

but as this is not a homebridge fault there is nothing we can do but wait. i think when the first native devices support this then it will be quite apparent that this is needed.

**Comment by nicoduj** [comment]
Agree, but I think it is not finished yet some characteristic exposed doesn’t have any visible way to be activated yet (like fast forward or mute)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by n0rt0nthec4t** [comment]
> It does not expose it in the widget, but in the properties of the accessory in home app . As far as I know, the button on the widget remote itself was removed in beta 2.
> ![IMG_EAA084711996-1](https://user-images.githubusercontent.com/19813688/54475599-3991eb00-47f3-11e9-9243-7cc09f1c6cab.jpeg)

How did you get the orange ticks to appear next to the inputs? Cant get them to be selected on/off via the HomeKit app, so wondering if a haven't set a characteristic for the inputs..

**Comment by nicoduj** [comment]
Hi @n0rt0nthec4t : you have to handle TargetVisibilityState and CurrentVisibilityState for inputs :)

**Comment by n0rt0nthec4t** [comment]
> Hi @n0rt0nthec4t : you have to handle TargetVisibilityState and CurrentVisibilityState for inputs :)

Thanks! sorted..

**Comment by NorthernMan54** [comment]
@nicoduj Did you ever figure these buttons out?
```
Characteristic.RemoteKey.REWIND = 0;
Characteristic.RemoteKey.FAST_FORWARD = 1;
Characteristic.RemoteKey.NEXT_TRACK = 2;
Characteristic.RemoteKey.PREVIOUS_TRACK = 3;
Characteristic.RemoteKey.EXIT = 10;
```

**Comment by nicoduj** [comment]
Hi,

Unfortunately no. Exit was available in first beta but the button was removed in beta 2 of iOS 12.2.  Maybe some new functions will be available in iOS 13 now !

Nicolas

**Comment by NorthernMan54** [comment]
@nicoduj In my Yamaha-zone-tv plugin, I was able to figure out how to use

Characteristic.PowerModeSelection - The comments above
Characteristic.RemoteKey - The comments above
Service.InputSource and Characteristic.CurrentVisibilityState/Characteristic.TargetVisibilityState
Characteristic.VolumeSelector

Do you have any ideas how to take advantage of these characteristics?

Characteristic.VolumeControlType
Characteristic.InputSourceType
Characteristic.TargetMediaState

**Comment by leoneleone** [comment]
@nicoduj 
@n0rt0nthec4t 
@ebaauw 

From looking at how the Apple TV functions within iOS Control Centre, I believe these non-visible HomeKit characteristics are tied to the Notification Centre functionality, and can actually be controlled via Siri Voice Commands. 
So, FastForward, Rewind, Play, etc: are all tied to how the TV content appears within Notification Centre, and how it can be controlled (particularly via Siri Voice Commands). 
When using my Apple TV, I can say things to my HomePod like “Hey Siri, Apple TV HomeScreen” and that will take me to the Apple TV HomeScreen. Same with the Media Playback Characteristics. 
I believe if we can integrate these “non-visible” characteristics into HomeKit TV plugins, they will still function within the HomeKit system despite not being visible. 

This is an educated guess of course, until Apple confirms it, or we can reverse engineer the code of an Official HomeKit TV (LG, Samsung, Vizio) once they are actually launched.

**Comment by nicoduj** [comment]
Hi,

Nice suggestion ! They are already bind in my plugin so if anyone wants to give a try ! I tried in French with no luck however

Nicolas
