### ISSUE TITLE
How is this possible?

### ISSUE THREAD

**Issue by SeydX** [homebridge/HAP-NodeJS#665]
I recently see a video of a valve(?) service with following ui

![7BEB5A7B-CBD0-45B6-B544-A98D9B1C0523](https://user-images.githubusercontent.com/34152761/56690768-9039f100-66de-11e9-81cc-63f61d323c53.jpeg)
![446E4498-7AE0-4B17-A0EF-6AC27C59FDCB](https://user-images.githubusercontent.com/34152761/56690769-9039f100-66de-11e9-9604-975cd38b6ec8.jpeg)

Is this currently possible? Or is this a special version of HomeKit?

Here in action:
https://m.youtube.com/watch?feature=youtu.be&v=D6FzNLDbw5Q

I tried to create a valve service or faucet service with additional current/target temperature characteristics etc.. no chance

Any idea @KhaosT  ?

Best regards

**Comment by KhaosT** [comment]
Linked services I assume

https://github.com/nfarina/homebridge/issues/1707#issuecomment-486418630

**Comment by tobekas** [comment]
Ah... wow!
I was wondering what the usecase of `Characteristic.ValveType.SHOWER_HEAD` would be.
But not sure, how you can get this to work. Maybe it’s similar to the irrigation system. You may need a `Service.Faucet` and a `Service.Valve` for each shower head (with ValveType set to SHOWER_HEAD) linked to the Faucet service. But it‘s still a guess. I‘m not able to test this out for the next week.

For the temperature it might be a `Service.Thermostat` or just a `Characteristic.TargetTemperature`. Since TargetTemlerature is not defined as an optional characteristic for Faucet or similar, I suspect it‘s a service.

Unfortunately there is no HAP documentation out there, that states which combinations of linked services are supported.

**Comment by SeydX** [comment]
So, i tried many combinations with different services als linked service and characteristics... I cant get the temp slider... other things like to shower heads etc is no problem, but how can i get the slider....????

**Comment by SeydX** [comment]
As "Main Service" we need the ```Service.Faucet``` and we need to add ```Service.Valve``` as linked services with different subtypes to the ```Service.Faucet```

It is possible to add multiple ```Service.Valve``` to ```Service.Faucet```

Because of slider i tried adding ```Service.Thermostat``` as linked Service and ```Service.TemperatureSensor```

I tried also different characteristics on ```Service.Valve``` and ```Service.Faucet```but the temperature slider will not appear...

**Comment by SeydX** [comment]
I finally made it!

![IMG_4064](https://user-images.githubusercontent.com/34152761/56709724-02ccc000-6723-11e9-8134-5f7236136f2c.PNG)

Have to test something, will immediately post an instruction

**Comment by SeydX** [comment]
Ok guys, i think im ready..

- First of all, you need to add a "main" Service. In this case it is ```Service.Faucet```
- If you want to adjust the temperature, you need to add at some characteristics to ```Service.Faucet``` 
- These are: ```Characteristic.HeatingThresholdTemperature```, ```Characteristic.CoolingThresholdTemperature``` (you dont need to add both, one is enough) **AND** ```Characteristic.TargetHeaterCoolerState```(this one is important, otherwise the slider will not appear)
- The "icons" are ```Service.Valve```. It is possible to add multiple valves with different types (shower head, generic valve, faucet) but you need to give them unique subtypes! All of these can be disabled under settings and are summarized as "Shower Heads" in the settings.
- It is also important to set ```Characteristic.ServiceLabelIndex``` for the valves ! (1 for Valve 1, 2 for Valve 2 etc.)
- To add names, you need also add ```Characteristic.ConfiguredName```to these services, otherwise all ```Service.Valve```will appear as Faucet 1, Faucet 2, Faucet 3 etc...
- After adding these extra services, you need to link them to the main service ```Service.Faucet```

It is possible to trigger all added valves at the same time, but at least one of them must be "InUse" (InUse = 1 / Active = 1) to activate the main Faucet, otherwise it will loop at "Starting..." - Also for disabling the main Faucet, all extra valves need to disabled (InUse = 0 / Active = 0)

A short summary for Active / InUse - Logic:

Active=0, InUse=0 -> Off
Active=1, InUse=0 -> Waiting [Starting, Activated but no water flowing (yet)]
Active=1, InUse=1 -> Running
Active=0, InUse=1 -> Stopping

(thx to [@tobekas](https://github.com/tobekas) for the short summary)

**Comment by tobekas** [comment]
Nice!
I wonder if there are even more combined control elements available in Home. Would be also useful for multiple lightbulbs or switches...

**Comment by jvmahon** [comment]
@SeydX. Can you post a file with the code?
@tobekas - I was wondering the same thing about multiple dimmers. For example, in my kitchen, I have 4 dimmers to control lighting. Could they be linked so they show up as one device but with 4 sliders on its main page? If you find out anything more, let us know.

**Comment by SeydX** [comment]
@jvmahon 

yes, im implementing it to my tado-platform plugin but with only one valve

https://github.com/SeydX/homebridge-tado-platform/blob/dev/src/accessories/boiler.js

**Comment by n0rt0nthec4t** [comment]
> * To add names, you need also add `Characteristic.ConfiguredName`to these services, otherwise all `Service.Valve`will appear as Faucet 1, Faucet 2, Faucet 3 etc...

Interestingly, using this idea, I added that characteristic to my "sprinklers" in my irrigation system. Seems you can have an on.('set' event bound to that to get notified of the name changing in the Home App. awesome

**Comment by tobekas** [comment]
I found this header file with some very interesting comments in it for the usage and combination (linked services...) of the HAP Services:
https://github.com/MrAB-AbhijeetMahashabde/Quectel_BG96/blob/c97440947309d13c41c5cc55919413fa2c1847e9/Apple_Homekit/HomeKit%20ADK%202.0/HomeKit%20ADK%202.0/ADK/HAP/include/HAPServiceTypes.h

Especially the use of IrrigationSytem and Faucet (with linked HeaterCooler) is well documented there.

**Comment by tobekas** [comment]
@SeydX: So it seems to be better to put the temperature characteristics into a linked HeaterCooler Service for this Shower system.

**Comment by SeydX** [comment]
@tobekas 
Thx for the link!

Im reading the hap r13 pdf and there are all informations we need to build these accessories... there are also informations about tv accessories and some (new?) characteristics like siri etc

https://github.com/MrAB-AbhijeetMahashabde/Quectel_BG96/blob/c97440947309d13c41c5cc55919413fa2c1847e9/Apple_Homekit/HomeKit%20Accessory%20Protocol%20Specification%20R13.pdf

@KhaosT maybe something for homebridge here?

**Comment by KhaosT** [comment]
As of right now there is no plan to implement support for remote control profile, since that's a really useless profile... Just use Siri Remote for that 😅

**Comment by n0rt0nthec4t** [comment]
> I finally made it!
> 
> ![IMG_4064](https://user-images.githubusercontent.com/34152761/56709724-02ccc000-6723-11e9-8134-5f7236136f2c.PNG)
> 
> Have to test something, will immediately post an instruction

Doesn't work atm like this in IOS 13 (beta2 and public beta 1). Just shows the on/off switch without the temp control.. See how it goes in future betas

**Comment by jvmahon** [comment]
> @tobekas
> Thx for the link!
> 
> Im reading the hap r13 pdf and there are all informations we need to build these accessories... there are also informations about tv accessories and some (new?) characteristics like siri etc
> 
> https://github.com/MrAB-AbhijeetMahashabde/Quectel_BG96/blob/c97440947309d13c41c5cc55919413fa2c1847e9/Apple_Homekit/HomeKit%20Accessory%20Protocol%20Specification%20R13.pdf
> 
> @KhaosT maybe something for homebridge here?

I tried to download that R13 HAP specification, but no luck. Is there a new link to it?

**Comment by Supereg** [comment]
> I tried to download that R13 HAP specification, but no luck. Is there a new link to it?

Apple was pretty quick in removing it. As it should only be accessible to people with an Mfi license agreement. 
Only the non-commercial version from few years ago is publicly available.

**Comment by SeydX** [comment]
@jvmahon 

You can find the file here

https://github.com/SeydX/hap-r13/blob/master/HomeKit%20Accessory%20Protocol%20Specification%20R13.pdf

**Comment by noelhibbard** [comment]
I wrote a plugin for a custom outdoor shower which I made using two sprinkler solenoids and a Raspberry Pi. This thread was really helpful in writing the plugin. I'm curious though, has anyone been able to use Siri to set the temperature? I can use Siri to turn the shower on and off but when I set the temp, Siri responds saying she did it but the slider doesn't actually move.
