### ISSUE TITLE
How do you add multiple child switches to an Outlet Accessory

### ISSUE THREAD

**Issue by qsxzaqq** [homebridge/HAP-NodeJS#674]
[https://i.loli.net/2019/06/14/5d027634e627d77726.png](https://i.loli.net/2019/06/14/5d027634e627d77726.png)

The picture.

**Comment by tobekas** [comment]
Just provide multiple „Switch“ services for one accessory. In iOS12 there will still be one tile per Service. But in this iOS13 preview, the services should probably be grouped in this way.
