### ISSUE TITLE
Suggestion: Bump to 1.0

### ISSUE THREAD

**Issue by hobbyquaker** [homebridge/HAP-NodeJS#676]
Hi! 
I'm maintaining two projects that depend on HAP-Nodejs, both have quite a bunch of users that are using them since years "in production". As HAP-Nodejs can be considered stable for a long time now I suggest to bump the Version to 1.0.
Would have some advantages: You could fully utilize the semantic versioning scheme, patch only for bugfixes, minor for compatible changes/features, major for breaking changes. With the current 0.x scheme this is not possible, patch is bumped for features, changes _and_ bugfixes and the role of the minor is unclear.
For me as a maintainer of packages depending on HAP-Nodejs it would be much easier to specify a proper version range in the package.json - and last but not least: I see no reason for not doing it :-)
@KhaosT what do you think?
Regards,
Sebastian

**Comment by Shaquu** [comment]
+1 for semantic versioning 
I have the same situation here

**Comment by hassankhan** [comment]
Here's a list of things I'd like to see before v1:

- [ ] [Transitioning `node-persist` to v3.0](https://github.com/KhaosT/HAP-NodeJS/issues/629)
- [ ] Use Promises as well as callbacks
- [ ] Lose legacy compatibility (Node 10+ only)
- [ ] Remove `buffer-shim`
- [ ] Improve unit test coverage
- [ ] Create integration test suite using `hap-client`
- [ ] Add code quality tooling (ESLint + Prettier)
- [ ] Set up CI/CD process
- [ ] Add contributing documentation

**Comment by Apollon77** [comment]
Why break nodejs 8 before it is eol? Or wait till next April. ;-)
What benefit would it have to only support node 10+?

**Comment by hobbyquaker** [comment]
@hassankhan Sounds legit :)

> Create integration test suite using hap-client
> Set up CI/CD process

I can offer my help regarding integration tests and travis setup, I think we could reuse a lot of the testing setup of https://github.com/hobbyquaker/homekit2mqtt

> Why break nodejs 8 before it is eol?

I would also suggest to support all versions as long as they are in maintanence, so for Node 8 until Januar 2020: ![](https://github.com/nodejs/Release/raw/master/schedule.svg?sanitize=true)

**Comment by Supereg** [comment]
#778

**Comment by crxporter** [comment]
Can I add a bump and a vote for this? Semantic versioning would be helpful so we know about all breaking changes and can act accordingly!

As always, thanks for all your hard work!

**Comment by Supereg** [comment]
[v1.0.0](https://github.com/homebridge/HAP-NodeJS/projects/5) is planned to be the next release (apart from potential 0.9.x Bug fix releases).

**Comment by crxporter** [comment]
> [v1.0.0](https://github.com/homebridge/HAP-NodeJS/projects/5) is planned to be the next release (apart from potential 0.9.x Bug fix releases).

So, it's been another year and we've gone through 0.9 and now 0.10... any new plans for 1.0 and true semver support?

**Comment by crxporter** [comment]
Hello again. I'm back with a yearly reminder that the projects who depend on this library would really appreciate semantic versioning. 

Is 2023 the year?!

**Comment by crxporter** [comment]
Please?

How many more years do I need to come beg for this until we get semver and bump to 1.0?

**Comment by hjdhjd** [comment]
Some day, but not today. It will come…a little housecleaning first.

**Comment by Shaquu** [comment]
Bump :)

Guys, SemVer is a very good thing.

Also, in node based projects, it allows using version regex in `package.json`, at the end, someone will be able to automatically update to some bugfix version without the need to pull the change manually by each project.

**Comment by hjdhjd** [comment]
We intend to do this in the near future. No need to keep bumping this...it's already on our radar.

**Comment by Shaquu** [comment]
@hjdhjd After my bump there is a PR ;) https://github.com/homebridge/HAP-NodeJS/pull/1045

**Comment by Shaquu** [comment]
https://github.com/homebridge/HAP-NodeJS/pull/1045

**Comment by crxporter** [comment]
> We intend to do this in the near future. No need to keep bumping this...it's already on our radar.

It's been nearly 5 years of "coming soon" and "next release" promises. You've got to understand why we feel forgotten. 

I appreciate finally seeing some progress on it this year. Thanks! I hope it actually does come in the next release!

**Comment by hjdhjd** [comment]
> > We intend to do this in the near future. No need to keep bumping this...it's already on our radar.
> 
> It's been nearly 5 years of "coming soon" and "next release" promises. You've got to understand why we feel forgotten.
> 
> I appreciate finally seeing some progress on it this year. Thanks! I hope it actually does come in the next release!

Correlation isn’t causation. Closing this.

**Comment by Shaquu** [comment]
lol

**Comment by hjdhjd** [comment]
Reopening until we **actually** release 1.0.0…got ahead of myself. 😄

**Comment by hjdhjd** [comment]
> > We intend to do this in the near future. No need to keep bumping this...it's already on our radar.
> 
> It's been nearly 5 years of "coming soon" and "next release" promises. You've got to understand why we feel forgotten.
> 
> I appreciate finally seeing some progress on it this year. Thanks! I hope it actually does come in the next release!

It will come…we had a couple of things to close out which have been in the past few days/weeks…there’s one more potentially, but we may push it to a post-1.0 release.

**Comment by Shaquu** [comment]
GG
