### ISSUE TITLE
How to implement wall switches?

### ISSUE THREAD

**Issue by lbohlmann** [homebridge/HAP-NodeJS#689]
Hey everyone:)

I use commercial smart bulbs at my home, so currently all my wall switches are turned on forever.
But because Siri is great for activating special scenes or disable specific lights but not so much for quick all lights on/off actions, I am trying to equip my former 230 volts switches with small battery-driven transmitters. Their signals should be received from a raspberry pi which is running HAP-NodeJS. 

But thats the problem, I think the StatelessProgrammableSwitch service is what I need here? As I was not able to get any code running with this service, I looked for reference implementations, but found nothing. So I tried the MotionSensor accessory as a possible substitute, which comes with HAP-NodeJS, but even this code seems not to work? 

I tried the GarageDoorOpener to make sure it's not a general problem, which worked well.

My questions are:
- Are there any known issues with the MotionSensor?
- Has anybody a working example of the StatelessProgrammableSwitch?

I would be thankful for any help/code/ideas :)

**Comment by NorthernMan54** [comment]
Lukas

Take a look at the homebridge plugins available, there should be several available that could be used as base for what you are trying to do.

**Comment by ebaauw** [comment]
I use them extensively in homebridge-hue.  Not the simplest plugin, though.

You need to expose an accessory with a single _ServiceLabel_ service and a _Stateless Programmable Switch_ service per button.  Note that you can only use them to trigger HomeKit automations.  You need a Home hub (AppleTV, HomePod, or mains-powered iPad) for the automations.

**Comment by lbohlmann** [comment]
@NorthernMan54 Thanks I'll have a look:) homebride-hue seems to be a good starting point

@ebaauw I've read trough your code and tried to extract the parts for the switch, I came up with the following:

```javascript
var Accessory = require("../").Accessory;
var Service = require("../").Service;
var Characteristic = require("../").Characteristic;
var uuid = require("../").uuid;

var lightswitchUUID = uuid.generate("hap-nodejs:accessories:" + "LightSwitch");

var lightswitch = (exports.accessory = new Accessory(
  "Light Switch",
  lightswitchUUID
));

lightswitch.username = "C1:2E:3F:D2:5E:FA";
lightswitch.pincode = "031-45-154";

lightswitch
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "Default Manufacturer")
  .setCharacteristic(Characteristic.Model, "0.1")
  .setCharacteristic(Characteristic.SerialNumber, "001");

lightswitch.on("identify", function(paired, callback) {
  console.log("Identify: fake light switch");
  callback();
});

const labelService = new Service.ServiceLabel("Light Switch");

labelService
  .getCharacteristic(Characteristic.ServiceLabelNamespace)
  .setValue(Characteristic.ServiceLabelNamespace.ARABIC_NUMERALS);

lightswitch.addService(labelService);

const SPSService = new Service.StatelessProgrammableSwitch(
  "Light Switch Button",
  "Button"
);

SPSService.getCharacteristic(Characteristic.ProgrammableSwitchEvent).setProps({
  minValue: Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS,
  maxValue: Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS
});
SPSService.getCharacteristic(Characteristic.ServiceLabelIndex).setValue(1);
SPSService
  .getCharacteristic(Characteristic.ProgrammableSwitchEvent)
  .updateValue(false);
lightswitch.addService(SPSService);
```
But unfortunately after a few moments the switch dissapears from homekit with the following log output:

```
EventedHTTPServer [::ffff:192.168.2.103] HTTP request: /pairings +181ms
HAPServer [C1:2E:3F:D2:5E:FA] HAP Request: POST /pairings +0ms
HAPServer [C1:2E:3F:D2:5E:FA] Removing pairing info for client +0ms
Accessory [Light Switch] Unpairing with client DBB219C6-BA46-4F56-92F5-B87999722136 +1ms
EventedHTTPServer [::ffff:192.168.2.103] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:192.168.2.103] Client connection closed +140ms
EventedHTTPServer [::ffff:192.168.2.103] HTTP connection was closed +0ms
EventedHTTPServer [::ffff:192.168.2.103] HTTP server was closed +0ms
```
Any ideas whats going on here?

**Comment by ebaauw** [comment]
Looks like HomeKit has banished the accessory for having an illegal characteristic value.  You should only set the value of the _Programmable Switch Event_ to `Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS`.  And only when the button is pressed.

You might need to wait a couple of weeks before HomeKit will again accept the accessory.  Or change the username.
