### ISSUE TITLE
StatusActive characteristic missing for Thermostat accessory

### ISSUE THREAD

**Issue by adriancable** [homebridge/HAP-NodeJS#692]
StatusActive is a valid optional characteristic for the Thermostat accessory (and reports on the device Settings page in iOS Home app) but it is not registered as an optional characteric in HomeKitTypes.js. As a result trying to use this characteristic for a Thermostat results in a 'HAP Warning'.

Fix would be to add:

  this.addOptionalCharacteristic(Characteristic.StatusActive);

in the Service.Thermostat constructor in HomeKitTypes.js.

**Comment by Supereg** [comment]
Not sure where your informations are coming from. StatusActive is not an optional characteristic for a Thermostat as defined by Apple (when referring to the spec and also to internal metadata information).

![Bildschirmfoto 2020-01-14 um 21 45 56](https://user-images.githubusercontent.com/9783857/72381197-446d2300-3717-11ea-9288-431f80865613.png)

**Comment by ebaauw** [comment]
I think Apple's Home app will show _Status Active_ for any type of service.

Anyway, after creating a new instance of the `Thermostat` service, you can add the optional characteristic to that instance from you plugin, to get rid of the warning.
