### ISSUE TITLE
Sonoff L1

### ISSUE THREAD

**Issue by ShonP40** [homebridge/HAP-NodeJS#693]
Will I be able to control the color of the Sonoff L1 LED strip through the Home app using HAP-Node JS?

**Comment by sszczep** [comment]
If there is an ESPxxxx inside, you probably can flash your own firmware onto it (check Tasmota or ESPEasy, maybe it is on supported devices list). If so, you won’t have bigger problems connecting it with HAP

**Comment by Timetogetstarted** [comment]
Sent from Yahoo Mail for iPhone


On Wednesday, July 31, 2019, 11:12 AM, Shon Pogorelis <notifications@github.com> wrote:


Will I be able to control the color of the Sonoff L1 LED strip through the Home app using HAP-Node JS?

**Comment by ShonP40** [comment]
It is supported on Tasmota but will I be able to control the color of the LED’s through the Home app?

**Comment by sszczep** [comment]
Yes sure. There is a light accessory and hue, saturation, brightness characteristics.

**Comment by ShonP40** [comment]
So all I need to do is put the SonoffMQTT_accessory.js file and it will automatically detect that the Sonoff L1 can change colors and show it in the Home app? Or I need a different file made for the Sonoff L1?

**Comment by sszczep** [comment]
I would need to take a look at that file first.

**Comment by ShonP40** [comment]
nvm, I forgot that it’s a Sonoff basic specific file.
So there is no file for the Sonoff L1.

Can someone make me one?
