### ISSUE TITLE
Server not listening on IPv4

### ISSUE THREAD

**Issue by illiteratewriter** [homebridge/HAP-NodeJS#695]
In `util/eventedhttp.js`, `EventedHttpServer.prototype.listen`  you can only pass targetPort and not the host. This works in most of the scenarios, since 

> In most operating systems, listening to the unspecified IPv6 address (::) may cause the net.Server to also listen on the unspecified IPv4 address (0.0.0.0).

But, in Ubuntu the server is listening only on the IPv6. It would be great if there can be some way to add the host (which is the second parameter in `server.listen([port[, host[, backlog]]][, callback])` ) so that we can configure if needed for the server to listen to IPv4. One example use case would be for this https://github.com/nfarina/homebridge/issues/1277 issue.

**Comment by buckmelanoma** [comment]
Still an issue for me.  I had to manually edit eventedhttp.js to restore IPv4

**Comment by Supereg** [comment]
The latest beta adds an option to specify a `PublishInfo` option to specify on which interfaces to listen for, as well as limiting to ipv4 only.
