### ISSUE TITLE
Suppress notifications

### ISSUE THREAD

**Issue by knuckleheadsmiff** [homebridge/HAP-NodeJS#711]
I’d like to know if it is possible to temporarily suppress a notifications when setting characteristic values. This is an issue on startup for me where a notification sent when initializing an accessory via polling after my startup code is run. 

More detail: 

I have a garage door opener plugin for homebridge. I also restart homebridge nightly on my server to rollover my log files and get everything into a clean state and just for good hygiene.

So what happened is the middle of the night when things startup and my polling code gets triggered I get a “door closed” notification sent FYI my iOS device from the first “poll” event when the state gets initialized to the correct state. 

Yes I know I can ignore notifications as a workaround on my device during certain times but the time would change if I’m traveling... I also don’t want to i it the state when the accessory is created to fake state as i’d Like it to not every report a false state. 

(_Note if the door is “open” during the this period i’d Actually like a notification, should don’t want to see a “closed” notification. So ideally I wasn’t a setcharacteristic/no notification on specific calls._)

FYI you can look at my code here: [https://github.com/knuckleheadsmiff/homebridge-garagedoor-ryobi](https://github.com/knuckleheadsmiff/homebridge-garagedoor-ryobi)

So either: I’m doing something wrong, it is not possible, or it is possible but need more HAP support. So this may or may not be a feature request. 

Any help would be appreciated.

**Comment by knuckleheadsmiff** [comment]
I've tried dong a 

accessory.garageDoorService.getCharacteristic(Characteristic.CurrentDoorState).setProps({"ev":false});

to see if I can suppress all notifications (and then turn it on later, but when I set the value I still get a notification.

**Comment by NorthernMan54** [comment]
This sounds like a problem with the plugin, and it setting an incorrect state during initialization, then overwriting it with the correct status. Try running in DEBUG mode and seeing what is being sent to HomeKit and determine what state is being incorrectly sent.

I’m saying this as I have never seen this type of issue with my garage door plugin.

**Comment by knuckleheadsmiff** [comment]
I did run in debug mode but don’t see anything obvious. However (and I forked my code from a different garage door project) I realized that the code does not use an accessory that is cached. Just always creates a new one. So when I get the chance I’ll try to use the cached accessory which should have the old state in it...which would be the right thing to use in this case.

**Comment by knuckleheadsmiff** [comment]
Well I don’t think I have any “cached” accessories in my plugin, it just create one static accessory which as I understand is not cached. So, I guess I’m back where I started, want to just temporarily set values with “ev” to false and can’t figure out how to do that.
