### ISSUE TITLE
Webcam Audio and Video Stream (FFmpeg RTP Settings)

### ISSUE THREAD

**Issue by tevfik6** [homebridge/HAP-NodeJS#713]
Hi there, 

I built the HAP into my Raspberry PI and it works fine with no audio streams. (Actually, it is still questionable) 

I moved to the next stage and try to implement audio next to the video. 
What I don't know is:
How does communication between iPhone/iPads and HAP? Not knowing this I don't understand the communications (For example how does apple devices know the ports to connect)

Another thing It looks like RTP is streaming every single component(audio/video/subtitle) as a separate stream. I noticed that there is an implementation in https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/ffmpeg.js#L339 that it looks like it needs to completely separate set of FFmpeg commands. 

Using this line;
`ffmpeg -re -i /dev/video0 -f alsa -i hw:1,0 -map 0:v:0 -map 1:a:0 -vcodec h264_omx -pix_fmt yuv420p -r:v 25 -f rawvideo -b:v 300k -bufsize 300k -payload_type 99-acodec libfdk_aac -profile:a aac_eld -flags +global_header -ar 24k -b:a 16k -bufsize 16k -ac 1 -payload_type 110 -f mp4 test.mp4`

I can get perfect video and audio stream. (even though raspberry pi3).
However, when it comes to converting the lines like in the https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/ffmpeg.js#L339 video is working fine but the audio is not coming.

I know that the settings have been working fine. However, when it comes to RTP protocol something is messing with audio.

I was playing around suspecting the packet size could be the problem. 
Noticed that packet size has other options: https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/ffmpeg.js#L265
Changing Audio to 188 started to give some sound but with an echo and at some point audio was going off. 
I guess it could be helpful if @KhaosT could tell me based on what these settings are written and commented? How can I calculate find out what packet size I need? 

Since I don't know the communication in between HAP and Apple devices, I'm not sure what is wrong with the packet. Could this be a defect in the HAP?

Any clue? Or where to look/start from? 

Thanks in advance!
Tev.
cc/ @KhaosT

**Comment by n0rt0nthec4t** [comment]
I’d be interest to know the outcome. I’ve got a project in mind for this, but also want to know you could do a two/way audio stream from iOS device to a HomeKit accessory with a speaker

**Comment by kajaba** [comment]
Can you please give us some hint how didi you manage to run only video?
I am totaly confuses. Can you please share ffmpeg command for rtp streaming and your Camera.ts file (I dont know if any other configs is needed)?
Thank you

**Comment by n0rt0nthec4t** [comment]
This is a camera accessory I write to stream off a raspberry pi camera 

// HAP-Nodejs camera accessory
// Version 31/7/2018

var JSONPackage = require('../package.json')
var Accessory = require('../').Accessory; 
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var Camera = require('../').Camera;
var spawn = require("child_process").spawn;

// Defines for the accessory
const AccessoryName =  "Camera";	      		      	// name of accessory
const AccessoryPincode = "031-45-154";                  // pin code for paring 
const AccessoryUsername = "69:34:CC:5A:13:5A";          // MAC like address used by HomeKit to differentiate accessories. 
const AccessoryManufacturer = "RaspberryPi";            // manufacturer (optional)
const AccessoryModel = "2.1";                    		// model (optional)
const AccessorySerialNumber = "MH20180731";             // serial number (optional) 
const AccessoryFirmwareRevision = JSONPackage.version;  // firmware revision (optional)

const SnapShotRotation = 0;
const VideoRotation = 0;

// Create the camera accessory
var cameraAccessory = exports.accessory = new Accessory(AccessoryName, uuid.generate('hap-nodejs:accessories:camera_' + AccessoryName));
cameraAccessory.username = AccessoryUsername; 
cameraAccessory.pincode = AccessoryPincode;
cameraAccessory.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.Manufacturer, AccessoryManufacturer);
cameraAccessory.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.Model, AccessoryModel);
cameraAccessory.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.SerialNumber, AccessorySerialNumber);
cameraAccessory.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.FirmwareRevision, AccessoryFirmwareRevision);
cameraAccessory.configureCameraSource(new Camera(cameraAccessory));

console.log("Setup IP Camera '%s' on '%s'", AccessoryName, AccessoryUsername);

Camera.prototype.handleSnapshotRequest = function (request, callback) {
    let rotation = '';
    if (SnapShotRotation) {
        switch(SnapShotRotation) {
            case 90:
                rotation = ',rotate=90*(PI/180):bilinear=0';
                break;
            case 180:
                rotation = ',rotate=180*(PI/180):bilinear=0';
                break;
            case 270:
                rotation = ',rotate=-90*(PI/180):bilinear=0';
                break;
        }
    }

   let ffmpegCommand = [
        '-f', 'video4linux2',
        '-vcodec', 'mjpeg',
        '-video_size', `${request.width}x${request.height}`,
        '-i', '/dev/video0',
        '-vframes', '1',
        '-vf', `scale=w=${request.width}:h=${request.height}${rotation}`,
        '-f', 'mjpeg',
        '-'
   ];

    let ffmpeg = spawn('ffmpeg', ffmpegCommand, {env: process.env});
    var imageBuffer = Buffer.alloc(0)
    ffmpeg.stdout.on('data', function (data) { imageBuffer = Buffer.concat([imageBuffer, data]) });
    ffmpeg.on('close', function (code) { callback(null, imageBuffer) })
}

Camera.prototype.handleStreamRequest = function(request) {
     // Invoked when iOS device asks stream to start/stop/reconfigure
    var sessionID = request["sessionID"];
    var requestType = request["type"];
    if (sessionID) {
        let sessionIdentifier = uuid.unparse(sessionID);
  
        if (requestType == "start") {
            var sessionInfo = this.pendingSessions[sessionIdentifier];
            if (sessionInfo) {
                var width = 1280;
                var height = 720;
                var fps = 30;
                var bitrate = 300;
  
                let videoInfo = request["video"];
                if (videoInfo) {
                    width = videoInfo["width"];
                    height = videoInfo["height"];
        
                    let expectedFPS = videoInfo["fps"];
                    if (expectedFPS < fps) {
                        fps = expectedFPS;
                    }
        
                    bitrate = videoInfo["max_bit_rate"];
                }

                let targetAddress = sessionInfo["address"];
                let targetVideoPort = sessionInfo["video_port"];
                let videoKey = sessionInfo["video_srtp"];
                let videoSsrc = sessionInfo["video_ssrc"];

                let rotation = 'rotate=0:bilinear=0';

                if (VideoRotation) {
                    switch(VideoRotation) {
                        case 90:
                            rotation = 'rotate=90*(PI/180):bilinear=0';
                            break;
                        case 180:
                            rotation = 'rotate=180*(PI/180):bilinear=0';
                            break;
                        case 270:
                            rotation = 'rotate=-90*(PI/180):bilinear=0';
                        break;
                    }
                }
        
                let ffmpegCommand = [
                    '-f', 'video4linux2',
                    '-i', '/dev/video0',
                    '-vcodec', 'h264',
                    '-an',
                    '-video_size', `${width}x${height}`,
                    '-framerate', `${fps}`,
                    '-vf', `${rotation}`,
                    '-b:v', `${bitrate}k`,
                    '-payload_type', '99',
                    '-ssrc', `${videoSsrc}`,
                    '-f', 'rtp',
                    '-srtp_out_suite', 'AES_CM_128_HMAC_SHA1_80',
                    '-srtp_out_params', `${videoKey.toString('base64')}`,
                    `srtp://${targetAddress}:${targetVideoPort}?rtcpport=${targetVideoPort}&localrtcpport=${targetVideoPort}&pkt_size=1378`
                ]; 
                let ffmpeg = spawn('ffmpeg', ffmpegCommand, {env: process.env});
                this.ongoingSessions[sessionIdentifier] = ffmpeg;
            }
            delete this.pendingSessions[sessionIdentifier];
        } else if (requestType == "stop") {
            let ffmpegProcess = this.ongoingSessions[sessionIdentifier];
            if (ffmpegProcess) {
                ffmpegProcess.kill('SIGKILL');
            }
            delete this.ongoingSessions[sessionIdentifier];
        }
    }
}

**Comment by kajaba** [comment]
This you have as accessory.ts stored in src/accessory folder?

**Comment by n0rt0nthec4t** [comment]
> This you have as accessory.ts stored in src/accessory folder?

It is stored in accessory folder as camera_accessory.js

I haven’t moved cross to the typescript version yet

**Comment by kajaba** [comment]
n0rt0nthec4t and for video, do I need to use -vcodec h264?
because now, I am using this command: 
`ffmpeg -re -f v4l2 -i /dev/video0 -threads 0 -an -pix_fmt yuyv422 -tune zerolatency -f rawvideo -vf scale=1280:720 -b:v 299k -payload_type 99 -ssrc 3157421 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params NC/mTok4rVgibJpTboEcPIIEK21Z1rSTwvmM5ZDt "srtp://192.168.2.131:55523?rtcpport=55523&localrtcpport=55523&pkt_size=1378"`

but I cant seem to get video playback. 
Whan I launch ffmpeg streaming without srtp (just rtp) and port like 1234. In VLC it works
