### ISSUE TITLE
HomeKit Secure Video

### ISSUE THREAD

**Issue by Dvorf** [homebridge/HAP-NodeJS#714]
Hi,
Is there a chance HAP will support HomeKit Secure Video?

**Comment by Supereg** [comment]
I doubt it that we are able to easily implement that feature. There is currently no information about the way this is gonna be implemented though. So let’s just wait and see. But i have my doubts.

**Comment by d0n4v4nb3ck3r** [comment]
@Supereg was this implemented today?

**Comment by Supereg** [comment]
No. Only the necessary characteristics and services were added. The logic is still missing.

**Comment by netRunner0** [comment]
https://blog.logitech.com/2019/11/14/circle-2-now-works-with-apple-homekit-secure-video/

**Comment by Dvorf** [comment]
Hello there!
Any updates regarding Homekit Secure Video?

**Comment by Supereg** [comment]
Still at it. Seems doable.
#741 is currently the issue with the most and latest information about secure video
