### ISSUE TITLE
setState and context

### ISSUE THREAD

**Issue by benzman81** [homebridge/HAP-NodeJS#717]
Hi,
I need some help, as I am a bit confused. I developed a lock plugin some time ago and it always
worked. For some days now, I need to add a new feature and stumble about the "context" that
is passed to the setState function.

I have two lock services and they need to be in sync with its open state.
So in the setState function I do something like the following:

```
function(homeKitState, callback, context) {
	...
	var myLockActionCallback = function() {
		//update lock service A
		this.lockServiceA.getCharacteristic(Characteristic.LockTargetState).updateValue(newHomeKitStateTarget, undefined, null);
		this.lockServiceA.getCharacteristic(Characteristic.LockCurrentState).updateValue(newHomeKitStateCurrent, undefined, null);
		
		//update lock service B
		this.lockServiceB.getCharacteristic(Characteristic.LockTargetState).updateValue(newHomeKitStateTarget, undefined, "myContextString");
		this.lockServiceB.getCharacteristic(Characteristic.LockCurrentState).updateValue(newHomeKitStateCurrent, undefined, "myContextString");
		
		callback(...);
	}
	...
	if(context === "myContextString") {
		//only call callback as characteristic already has corret state
		callback(...);
	}
	else {
		execLockAction(..., myLockActionCallback);
	}
	...
}
```

I once used the "context" like this, as the "setState" function gets called for "lockServiceB",too.
Otherwise it would also call execLockAction for "lockServiceB".
Now the problem is, that today I dont receive a string as "context" in setState method but some object
like this:

```
{ 
  request: [Function: bound ],                                                      
  encrypt: [Function: bound ],                                                                    
  decrypt: [Function: bound ],                                                                    
  close: [Function: bound ],                                                                      
  keepalive: true,                                                                                
  '86.10': true
  ...
}
```

What am I doing wrong? Did something change and I missed the migration?

Thanks

**Comment by benzman81** [comment]
One addition, on my iphone I run iOS 13.1.2 on my Mac I run Mojave 10.14.6. 
If I execute lockService A on my iPhone, then the setState gets called twice, on call for lockServiceA and one Call for lockServiceB. If I do the same on my Mac with the Home App the setState gets called only once for lockServiceA. Both devices update the lock services correctly in the UI.

**Comment by Supereg** [comment]
Okay first of all. You are using the `updateValue` function. This function is specifically intended to only update the value and thus does never call the `set` event (you didn't supply the full code so I assume a standard setup). So your function will never be called with your given `context`. The `updateValue` function does only emit a `change` event (which you can also subscribe too if you really need to).

The context you sometime see, is the context object which is supplied when HAP-NodeJS gets a set request from HomeKit. That's an internal object (reasoning explained [here](https://github.com/KhaosT/HAP-NodeJS/blob/1081ab05939d57f4152de1d6df18bbc89b9001cb/src/lib/Accessory.ts#L984)) and is unique for every session (basically any apple device connected) and [stored](https://github.com/KhaosT/HAP-NodeJS/blob/1081ab05939d57f4152de1d6df18bbc89b9001cb/src/lib/util/eventedhttp.ts#L195) in the session object.

Regarding your second issue I can't really help with that since you didn't really supply code I can work with.

**Comment by benzman81** [comment]
@Supereg ok, than it must be the second issue that is causing the first. The setState function with example code from above will be called twice if I de-/activate lockServiceA. The first call is the one for lockServiceA and the second time it get there is for lockServiceB. I assume this is because I update the state for lockServiceB from the setState function from lockServiceA. If I comment out the two lines below "//update lock service B" then the setState function will only be called once for setting the state of lockServiceA. 

This behavior only occurs from my iPhone using iOS 13.1.2 and I guess only after I updated to iOS 13. If I do the same on my Mac which uses the old Home App style where each service is a tile in the Home App, then the setState function will only be called once just the way you described it.

**Comment by benzman81** [comment]
@Supereg just build an example plugin at https://github.com/benzman81/homebridge-lock-test.
The issue did not occur until I added the third lock service "C" and it does also not occur on my Mac. Same as with my plugin, which has also three lock services per accessory. So there must be a bug, maybe in my example plugin, or in HAPNodeJS/Homebridge or on Apples side.

**Comment by Supereg** [comment]
Sorry for the late response. I'm currently don't really have the time to test this out myself.
Does this only occur when using lock services or also with different service types?

Your setup is latest iOS 13.1.2 and latest macOS Mojave right? Any home hubs? HomePod still with iOS 12? Or Apple TV tvOS 13? Though I assume when you tested this, you were at home with direct connection.
You are using the latest homebridge version? Or do you call the current hap-nodejs api directly?

**Comment by benzman81** [comment]
@Supereg No problem. I just tested with three switches and the problem did not occur. My setup is  latest iOS 13.1.2 and latest macOS Mojave, also AppleTV tvOS 14 And HomePods latest 12.4. Always tested in local network running homebridge 0.4.50.

**Comment by benzman81** [comment]
@Supereg some fun fact: If yo use iOS 13 and open the accessory with the three locks and open/close Lock A, then setState is called two times, one for Lock A and then one for Lock B. Now if you open the accessory and don't open/close Lock A in this screen but instead go to its settings -> devices and then trigger open/close Lock A, then only one setState is called for Lock A as expected and Lock B ist still updated correctly.

**Comment by Supereg** [comment]
Okay, I'm now running your lock-test plugin. I get the following output when I unlock the lockServiceA

```
[2019-10-5 19:21:03] [LockTest] S E T S T A T E: unlockType = A, doLock = false,homeKitState = 0
[2019-10-5 19:21:03] [LockTest] execLockAction is execute for unlockType 'A' and doLock 'false'
[2019-10-5 19:21:03] [LockTest] S E T S T A T E: unlockType = B, doLock = false,homeKitState = 0
[2019-10-5 19:21:03] [LockTest] execLockAction is execute for unlockType 'B' and doLock 'false'
```

Just to clarify, this seems to be the expected unexpected output. Am I right? Tested this with my iPhone running iOS 13.1.2. Same output on macOS Catalina. And you can confirm, that this does not happen on macOS Mojave?

**Comment by benzman81** [comment]
Yes, it does not happen on Mojave and also on iOS 13.1.2 if you open the device -> settings -> devices and switch LockA from here.

**Comment by Supereg** [comment]
Also another odd behavior I noticed.
If you switch LockA like you explained via device -> settings -> devices
```
[2019-10-5 21:26:52] [LockTest] S E T S T A T E: unlockType = A, doLock = false,homeKitState = 0
[2019-10-5 21:26:52] [LockTest] execLockAction is execute for unlockType 'A' and doLock 'false'
```
and then you leave the devices section and you get thrown back to the detailed view of the three lock accessories it executes setState for both A and B again lol
```
[2019-10-5 21:27:01] [LockTest] S E T S T A T E: unlockType = A, doLock = false,homeKitState = 0
[2019-10-5 21:27:01] [LockTest] execLockAction is execute for unlockType 'A' and doLock 'false'
[2019-10-5 21:27:01] [LockTest] S E T S T A T E: unlockType = B, doLock = false,homeKitState = 0
[2019-10-5 21:27:01] [LockTest] execLockAction is execute for unlockType 'B' and doLock 'false'
```

I'm going to dig deeper, this is some weird behavior 😂

**Comment by Supereg** [comment]
Okay so I tested some stuff and can only validate this issue.
I did some modifications to your plugin (only the lock accessory). It is now more readable and straightforward in my opinion and is restricted to the relevant parts (https://github.com/Supereg/homebridge-lock-test).

Here the a log output with HAP-NodeJS debug messages:
```
  EventedHTTPServer [::ffff:192.168.178.70] HTTP request: /characteristics +7s
  HAPServer [AC:72:E6:6D:1D:83] HAP Request: PUT /characteristics +0ms
  Accessory [Testbridge] Processing characteristic set: [{"aid":2,"iid":11,"value":0}] +0ms
  Accessory [Testbridge] Setting Characteristic "Lock Target State" to value 0 +1ms
[5.10.2019, 22:43:48] [TestLock] S E T S T A T E: service=someLockName A; SECURING=false
  EventedHTTPServer [::ffff:192.168.178.70] Muting event '2.11' notification for this connection since it originated here. +1ms        // lockA LockTargetState
  EventedHTTPServer [::ffff:192.168.178.70] Sending HTTP event '2.10' with data: {"characteristics":[{"aid":2,"iid":10,"value":0}]} +0ms        // lockA LockCurrentState
  EventedHTTPServer [::ffff:192.168.178.70] Sending HTTP event '2.15' with data: {"characteristics":[{"aid":2,"iid":15,"value":0}]} +0ms        // lockB LockTargetState
  EventedHTTPServer [::ffff:192.168.178.70] Sending HTTP event '2.14' with data: {"characteristics":[{"aid":2,"iid":14,"value":0}]} +0ms        // lockB LockCurrentState
  EventedHTTPServer [::ffff:192.168.178.70] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.178.70] Writing pending HTTP event data +0ms
  EventedHTTPServer [::ffff:192.168.178.70] HTTP request: /characteristics +375ms
  HAPServer [AC:72:E6:6D:1D:83] HAP Request: PUT /characteristics +0ms
  Accessory [Testbridge] Processing characteristic set: [{"aid":2,"iid":15,"value":0}] +0ms
  Accessory [Testbridge] Setting Characteristic "Lock Target State" to value 0 +0ms
[5.10.2019, 22:43:48] [TestLock] S E T S T A T E: service=someLockName B; SECURING=false
  EventedHTTPServer [::ffff:192.168.178.70] HTTP Response is finished +2ms
```

This seems to be an issue with the new grouping panel (although I can't really confirm since I cannot validate it in the HomeKit source lol). Lock A gets switched by hand. Then a notification for lock B gets sent to the requesting iOS device (I did also tried delaying the state change for lock B, makes no difference). Every time (but only if a third lock service is attached to the same accessory) the requesting iOS sends a PUT /characteristics request for Lock B and sets the state again.
This issue does also exist on the new Home App in the macOS Catalina GM.
I have sadly no old devices to test this with.
Also I can confirm if you initiate all steps via the `device -> settings -> devices` panel the second request is not sent

**Comment by Supereg** [comment]
I will try to test this setup without a homebridge instance only using hap-nodejs instance from my fork. There are some changes which adds support to the latest protocol version v1.1.0. In this version HomeKit seems to send a /prepare request first before it sends the actual update request for a lock service. I'm curious how this might affect anything.
