### ISSUE TITLE
How-To: fetch current state of CarbonDioxidwDetected?

### ISSUE THREAD

**Issue by deanlyoung** [homebridge/HAP-NodeJS#720]
If I want to fetch the current state of CarbonDioxideDetected from HomeKit, how would I structure that call with NodeJS?

This is one method I have seen:
```
this.service = new Service.CarbonDioxideSensor(this.name);
this.service.getCharacteristic(Characteristic.CarbonDioxideDetected).on('get',this.getState.bind(this));
```

**Comment by MiguelRipoll23** [comment]
That code is creating a carbon dioxide sensor service and it’s up to you to decide if you have detected it or not. You should create a boolean variable like carbonDioxideDectected and return it on the getState function you got referenced there.

You decide when you’re detecting it o not by changing that boolean’s value. Remember that you creating an accessory, not communicating to an existing one (that’s not possible unless they’re from Homebridge too).

**Comment by deanlyoung** [comment]
Ahh, that explains it then. I was trying to use the HomeKit value as a server-of-sorts. In other words, not trying to spam HomeKit with updates if the value hasn't changed by first fetching the current state and then updating it if the new value is different.

**Comment by deanlyoung** [comment]
Turns out it is possible, using this syntax:

`that.carbonDioxideService.getCharacteristic(Characteristic.CarbonDioxideDetected).value;`

The `.value` on the end was the piece I was missing.
