### ISSUE TITLE
EventedHTTPServer HTTP server was closed

### ISSUE THREAD

**Issue by daddvok** [homebridge/HAP-NodeJS#727]
when I see "EventedHTTPServer HTTP server was closed" or "Sending HTTP event 'keepalive' with data: {"characteristics":[]} +6s hapNodeJSClient Ending Homebridge instance discovery +19s"
in debug, it is no longer possible to connect to devices in the home program (via remote access via Apple tv)
everything reconnects properly on the local network, but there is no access outside the network until http server reconnects

I also noticed that a device with another email id that is invited to the house, when trying to connect to the local network, gives
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: POST /pair-verify +1ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Pair verify step 2/2 +1ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Client DF368DF5-7C7A-4F65-A7B9-7B5DA26D7002 attempting to verify, but we are not paired; rejecting client 
  EventedHTTPServer [192.168.0.154] HTTP Response is finished +1ms
  EventedHTTPServer [192.168.0.154] Client connection closed +6ms
  EventedHTTPServer [192.168.0.154] HTTP connection was closed +1ms
  EventedHTTPServer [192.168.0.154] HTTP server was closed +1ms

and further connection is already through apple tv even in local network

i use node-red-contrib-homekit-bridged 6.2.0
and homebridge 0.4.50
ios 13.2

**Comment by daddvok** [comment]
Full log 

 hapNodeJSClient HAP Device discovered HB Bridge [ '192.168.0.105', '169.254.124.185' ] +1s
  hapNodeJSClient HAP instance address: HB Bridge -> 0E_C9_99_2C_A2_C6.local -> 192.168.0.105:51826 +4ms
  hapNodeJSClient HAP Device discovered TV Гостиная [ '192.168.0.105', '169.254.124.185' ] +18ms
  hapNodeJSClient HAP instance address: TV Гостиная -> 45_80_EC_29_9E_90.local -> 192.168.0.105:35227 +1ms
  hapNodeJSClient Homebridge instance discovered HB Bridge-ABF3 with 7 accessories +104ms
  hapNodeJSClient Homebridge instance discovered TV Гостиная-6842 with 1 accessories +20ms
  EventedHTTPServer Server listening on port 41773 +0ms
  hapNodeJSClient HAP Device discovered NR Bridge [ '192.168.0.105', '169.254.124.185' ] +6s
  hapNodeJSClient HAP instance address: NR Bridge -> 00_2c_44_f9_30_8f_d1_2e.local -> 192.168.0.105:41773 +1ms
  EventedHTTPServer [192.168.0.105] New connection from client +849ms
  EventedHTTPServer [192.168.0.105] HTTP server listening on port 42505 +2ms
  EventedHTTPServer [192.168.0.105] HTTP request: /accessories +21ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: GET /accessories +1ms
  EventedHTTPServer [192.168.0.105] HTTP Response is finished +51ms
  hapNodeJSClient Homebridge instance discovered NR Bridge-F266 with 30 accessories +156ms
  EventedHTTPServer [192.168.0.105] Client connection closed +49ms
  EventedHTTPServer [192.168.0.105] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.0.105] HTTP server was closed +3ms
  EventedHTTPServer [192.168.0.177] New connection from client +100ms
  EventedHTTPServer [192.168.0.177] HTTP server listening on port 34993 +1ms
  EventedHTTPServer [192.168.0.177] HTTP request: /pair-verify +4ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: POST /pair-verify +1ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Pair verify step 1/2 +3ms
  EventedHTTPServer [192.168.0.177] HTTP Response is finished +284ms
  EventedHTTPServer [192.168.0.139] New connection from client +16ms
  EventedHTTPServer [192.168.0.139] HTTP server listening on port 34659 +2ms
  EventedHTTPServer [192.168.0.177] HTTP request: /pair-verify +35ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: POST /pair-verify +1ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Pair verify step 2/2 +3ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Client FE512FBA-A970-46D4-9A0C-6B350DCAFDA3 verification complete +126ms
  EventedHTTPServer [192.168.0.177] HTTP Response is finished +3ms
  EventedHTTPServer [192.168.0.139] HTTP request: /pair-verify +1ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: POST /pair-verify +1ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.0.139] HTTP Response is finished +131ms
  EventedHTTPServer [192.168.0.177] HTTP request: /accessories +15ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: GET /accessories +1ms
  EventedHTTPServer [192.168.0.177] HTTP Response is finished +45ms
  EventedHTTPServer [192.168.0.139] HTTP request: /pair-verify +258ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: POST /pair-verify +1ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Pair verify step 2/2 +2ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Client 75F95F7A-3109-4B30-A9C6-78D4A0E864E1 attempting to verify, but we are not paired; rejecting client +2ms
  EventedHTTPServer [192.168.0.139] HTTP Response is finished +1ms
  EventedHTTPServer [192.168.0.139] Client connection closed +93ms
  EventedHTTPServer [192.168.0.139] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.0.139] HTTP server was closed +2ms
  EventedHTTPServer [192.168.0.177] HTTP request: /characteristics +95ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: PUT /characteristics +1ms
  EventedHTTPServer [192.168.0.177] HTTP Response is finished +15ms
  EventedHTTPServer [192.168.0.141] New connection from client +2s
  EventedHTTPServer [192.168.0.141] HTTP server listening on port 39667 +1ms
  EventedHTTPServer [192.168.0.141] HTTP request: /pair-verify +12ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: POST /pair-verify +0ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.0.141] HTTP Response is finished +167ms
  EventedHTTPServer [192.168.0.141] HTTP request: /pair-verify +34ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: POST /pair-verify +1ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Pair verify step 2/2 +2ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] Client FE512FBA-A970-46D4-9A0C-6B350DCAFDA3 verification complete +84ms
  EventedHTTPServer [192.168.0.141] HTTP Response is finished +3ms
  EventedHTTPServer [192.168.0.141] HTTP request: /accessories +7ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: GET /accessories +1ms
  EventedHTTPServer [192.168.0.141] HTTP Response is finished +30ms
  EventedHTTPServer [192.168.0.141] HTTP request: /characteristics +481ms
  HAPServer [00:2c:44:f9:30:8f:d1:2e] HAP Request: PUT /characteristics +0ms
  EventedHTTPServer [192.168.0.141] HTTP Response is finished +12ms
  hapNodeJSClient Ending Homebridge instance discovery +12s

**Comment by Supereg** [comment]
One thing I noticed is, that the username (device id) for your accessory (`00:2c:44:f9:30:8f:d1:2e`) is not valid. This must be a valid Mac address, six 8 bit hex codes like `XX:XX:XX:XX:XX:XX`.
Could be that this is the root cause. Note that you will need to completely repair your device if you change the username.

> HAPServer [00:2c:44:f9:30:8f:d1:2e] Client DF368DF5-7C7A-4F65-A7B9-7B5DA26D7002 attempting to verify, but we are not paired; rejecting client

Regarding the client which is rejected. Could you navigate into the `persist` folder inside you `homebridge` folder an open file called something like `AccessoryInfo.002C44F9308FD12E.json` and check if the client id is present in the `pairedClients` clients property.
If it is not present' try removing and adding the person to your home again in the Home App.
But it could well be resolving the issue with the id length above could also resolve this issue.

**Comment by daddvok** [comment]
Completely reinstalled everything from scratch, the problem with HAPServer [00:2c:44:f9:30:8f:d1:2e] Client DF368DF5-7C7A-4F65-A7B9-7B5DA26D7002 attempting to verify, but we are not paired; rejecting client disappeared. But remote access still works through time. Please explain for stupid, how to solve a problem with

> One thing I noticed is, that the username (device id) for your accessory (00:2c:44:f9:30:8f:d1:2e) is not valid. This must be a valid Mac address, six 8-bit hex codes like XX:XX:XX:XX:XX:XX.

My full log now:
 hapNodeJSClient HAP Device discovered TV Гостиная [ '192.168.0.105' ] +1s
  hapNodeJSClient HAP instance address: TV Гостиная -> 45_80_EC_29_9E_90.local -> 192.168.0.105:37925 +4ms
  hapNodeJSClient HAP Device discovered HB [ '192.168.0.105' ] +18ms
  hapNodeJSClient HAP instance address: HB -> CC_62_5E_E9_B2_11.local -> 192.168.0.105:28888 +1ms
28 Oct 17:27:07 - [info] [tcp out:yeelight 650] connected to 192.168.0.138:55443
28 Oct 17:27:07 - [info] [deconz-server:Deconz-rask] WebSocket opened
  hapNodeJSClient Homebridge instance discovered TV Гостиная-6842 with 1 accessories +192ms
  hapNodeJSClient Homebridge instance discovered HB-CF4A with 7 accessories +15ms
  EventedHTTPServer Server listening on port 46261 +0ms
  hapNodeJSClient HAP Device discovered NR [ '192.168.0.105' ] +6s
  hapNodeJSClient HAP instance address: NR -> 00_0e_d5_7d_6c_84_e0_05.local -> 192.168.0.105:46261 +1ms
  EventedHTTPServer [192.168.0.105] New connection from client +883ms
  EventedHTTPServer [192.168.0.105] HTTP server listening on port 41689 +2ms
  EventedHTTPServer [192.168.0.105] HTTP request: /accessories +9ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: GET /accessories +1ms
  EventedHTTPServer [192.168.0.105] HTTP Response is finished +44ms
  hapNodeJSClient Homebridge instance discovered NR-C350 with 33 accessories +130ms
  EventedHTTPServer [192.168.0.105] Client connection closed +58ms
  EventedHTTPServer [192.168.0.105] HTTP connection was closed +1ms
  EventedHTTPServer [192.168.0.105] HTTP server was closed +3ms
  EventedHTTPServer [192.168.0.177] New connection from client +40ms
  EventedHTTPServer [192.168.0.177] HTTP server listening on port 35681 +0ms
  EventedHTTPServer [192.168.0.177] HTTP request: /pair-verify +5ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: POST /pair-verify +0ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] Pair verify step 1/2 +4ms
  EventedHTTPServer [192.168.0.177] HTTP Response is finished +297ms
  EventedHTTPServer [192.168.0.177] HTTP request: /pair-verify +32ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: POST /pair-verify +1ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] Pair verify step 2/2 +3ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] Client FE512FBA-A970-46D4-9A0C-6B350DCAFDA3 verification complete +163ms
  EventedHTTPServer [192.168.0.177] HTTP Response is finished +4ms
  EventedHTTPServer [192.168.0.177] HTTP request: /accessories +21ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: GET /accessories +0ms
  EventedHTTPServer [192.168.0.177] HTTP Response is finished +66ms
  EventedHTTPServer [192.168.0.177] HTTP request: /characteristics +531ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: PUT /characteristics +0ms
  EventedHTTPServer [192.168.0.177] HTTP Response is finished +16ms
  hapNodeJSClient Ending Homebridge instance discovery +12s
  hapNodeRed Discovered 122 new evDevices +19s
  hapNodeRed Discovered 91 new ctDevices +9ms
  EventedHTTPServer [192.168.0.154] New connection from client +2m
  EventedHTTPServer [192.168.0.154] HTTP server listening on port 34521 +2ms
  EventedHTTPServer [192.168.0.154] HTTP request: /pair-verify +7ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: POST /pair-verify +0ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] Pair verify step 1/2 +5ms
  EventedHTTPServer [192.168.0.154] HTTP Response is finished +163ms
  EventedHTTPServer [192.168.0.154] HTTP request: /pair-verify +32ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: POST /pair-verify +1ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] Pair verify step 2/2 +1ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] Client DF368DF5-7C7A-4F65-A7B9-7B5DA26D7002 verification complete +117ms
  EventedHTTPServer [192.168.0.154] HTTP Response is finished +3ms
  EventedHTTPServer [192.168.0.154] HTTP request: /accessories +12ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: GET /accessories +1ms
  EventedHTTPServer [192.168.0.154] HTTP Response is finished +43ms
  EventedHTTPServer [192.168.0.154] HTTP request: /characteristics +634ms
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: PUT /characteristics +1ms
  EventedHTTPServer [192.168.0.154] HTTP Response is finished +19ms

**Comment by daddvok** [comment]
_now such things began to appear:_
  EventedHTTPServer [192.168.0.177] Muting event '6.10' notification for this connection since it originated here. +2ms
  EventedHTTPServer [192.168.0.177] HTTP Response is finished +1ms
  EventedHTTPServer [192.168.0.177] HTTP request: /characteristics +1s
  HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: PUT /characteristics +0ms
  EventedHTTPServer [192.168.0.177] Muting event '6.10' notification for this connection since it originated here.

**Comment by Supereg** [comment]
So you installed homebridge, right? In your config.json you have something like the following:
```
{
    "bridge": {
        "name": "some name",
        "username": "00:2c:44:f9:30:8f:d1:2e",
        "port": <some port number>,
        "pin": "xxx-xx-xxx"
    },
    ...
}
```
As of your logs it seems the username property should be set to `00:2c:44:f9:30:8f:d1:2e` in your configuration. This is the part which you need to change as it is formatted incorrectly. It has 8 hexadecimal digits separated by `:` while it should have 6. Just delete two of them (for example `44:f9:30:8f:d1:2e`, but anything you like works) and restart homebridge and then repair it to your home (the old installation will become invalid in the home app).

**Comment by daddvok** [comment]
Not only, yet node-red
Config homebridge ->
![изображение](https://user-images.githubusercontent.com/47695947/67697924-64176980-f9ba-11e9-80d6-cb42832893cc.png)

**Comment by Supereg** [comment]
Okay but that is not the homebridge instance which from which the logs are, isn't it? 🤔 
And I hope the pin is not the real one 😅 

The username in the config differs from the username found in the logs

> HAPServer [00:0e:d5:7d:6c:84:e0:05] HAP Request: GET /accessories +1ms 

... is one log message where `00:0e:d5:7d:6c:84:e0:05` is the username.

**Comment by daddvok** [comment]
maybe it's a nodred, but neither bridge works normal outside local network. In node-red i can't indicate username.
this is my real config, but what is wrong with the pin?) all works wonderful inside my wi-fi, there were no errors when adding bridges into homekit

**Comment by Supereg** [comment]
Okay then. Remote access doesn't work at all? What are you using as your Home Hub? Apple TV 4th Gen? What tvOS version is running?

**Comment by daddvok** [comment]
From the outside sometimes everything works well, but basically I always see the update status on all devices in homekit, waiting a few minutes and then no response. After some time, access appears again and so cyclically.
There are no problems on the apple's side, I did a complete reset apple tv, home app, in and out in icloud on all devices, check few different internet providers.
node v10.17.0
npm 6.12.0
apple tv 4k with tvOs 13
iphone 8 with iOs 13.2

**Comment by NorthernMan54** [comment]
@daddvok @Supereg The malformed username is definitely node-red and the node-red-contrib-homekit-bridged node.  I saw the same thing when I was looking at mdns requests on my network with WireShark, and saw the same malformed names.  At the time I had just ignored it, but when you saw the same same it was a quick aha moment. After reviewing the code, I can confirm it.

@Shaquu I wondering if this may be causing some of the stability issues with the node?

The problematic spot in the code

https://github.com/NRCHKB/node-red-contrib-homekit-bridged/blob/72d07f3b0456b722020bf71b46c61f4a28712c03/lib/HAPBridgeNode.js#L64

**Comment by Shaquu** [comment]
@NorthernMan54 it was always like that. But it indeed looks like it is wrong so I will have to fix it.
I am concerned about backward compatibility though.

**Comment by NorthernMan54** [comment]
I submitted a pull request that resolves the name issue, but it is a breaking change for existing users.  They will need to unpair and repair their devices in the Home app as part of implementing

https://github.com/NRCHKB/node-red-contrib-homekit-bridged/pull/172

**Comment by daddvok** [comment]
any news?

**Comment by daddvok** [comment]
After updating to 0.5.4 the problem with apple tv “no response” was resolved, but there are still some problems, sometimes devices are updated outside the home network for a very long time, and sometimes everything is fine. If once it was updated normally, then within 10 minutes everything is updated as expected, and then I assume the connection is broken and again a long update

**Comment by Shaquu** [comment]
@daddvok regarding 0.5.4 and MAC address generation fix it was merged on the latest dev branch of nrchkb.
