### ISSUE TITLE
0.5 deg C thermostat changes impossible in iOS 13

### ISSUE THREAD

**Issue by adriancable** [homebridge/HAP-NodeJS#738]
I don't know if this is an iOS 13 issue, or a HAP-NodeJS issue, but it seems under iOS 13 (but not iOS 12, which works as expected) .setProps({ minStep: 0.5 }) on Characteristic.TargetTemperature no longer works. There's no indication of an error being returned, but HomeKit still only allows the target temperature of thermostats to be adjusted in 1 degree C increments.

Has anyone else seen this and/or know of a fix? Thank you!

**Comment by n0rt0nthec4t** [comment]
Yep, definitely seen this with thermostat accessories I've created. I think it stems from an issue with iOS 13 where its very hard (or impossible??) to select 0.5 increments in HomeKit with the new design. could be wrong..?

**Comment by adriancable** [comment]
@n0rt0nthec4t - maybe I just have smaller fingers than you :-) but it was fine for me in iOS 13 betas, where the 0.5 degree C increments still worked.

0.5 degrees C is approx. 1 degree F - so it makes no sense that we have finer temperature control in the US, than in the rest of the world. (American exceptionalism?!)

**Comment by codyc1515** [comment]
I have just checked this in the HomeKit Accessory Simulator. It seems like you can set 0.5 degrees with Siri, but not using the new "wheel" temperature design (minimum increments of 1 degree). I'm not sure why this is but it seems like an intentional design choice of Apple given that there is no 0.5 increment marks on the visual design.

**Comment by adriancable** [comment]
@codyc1515 - before iOS 13.2 (I think), if you set minStep to 0.5 for Characteristic.TargetTemperature, you would get 0.5 increment marks on the visual design.

**Comment by adriancable** [comment]
@codyc1515 - does your commit #751 have anything to do with this issue?

**Comment by n0rt0nthec4t** [comment]
Looks like the 0.5 steps are back in iOS 13.4 PB 2.... see what the final release holds

**Comment by Supereg** [comment]
0.5 steps are back in iOS 13.4
