### ISSUE TITLE
New install issues

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#754]
Trying to install the typescript version of this, but come up with teh following errors. certainly not straight forward. Just installed the latest master branch files.

pi@raspberrypi:~/HAP-NodeJS $ node_modules/.bin/ts-node src/Core.ts 

/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:293
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/Core.ts:3:21 - error TS7016: Could not find a declaration file for module 'node-persist'. '/home/pi/HAP-NodeJS/node_modules/node-persist/src/node-persist.js' implicitly has an 'any' type.
  Try `npm install @types/node-persist` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-persist';`

3 import storage from 'node-persist';
                      ~~~~~~~~~~~~~~

    at createTSError (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:293:12)
    at reportTSError (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:297:19)
    at getOutput (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:399:34)
    at Object.compile (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:457:32)
    at Module.m._compile (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:530:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:533:12)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
pi@raspberrypi:~/HAP-NodeJS $ npm install @types/node-persist
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ @types/node-persist@3.0.0
added 1 package from 2 contributors and audited 876448 packages in 137.335s
found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~/HAP-NodeJS $ node_modules/.bin/ts-node src/Core.ts 

/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:293
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/Core.ts:10:9 - error TS2339: Property 'initSync' does not exist on type 'typeof NodePersist'.

10 storage.initSync();
           ~~~~~~~~

    at createTSError (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:293:12)
    at reportTSError (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:297:19)
    at getOutput (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:399:34)
    at Object.compile (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:457:32)
    at Module.m._compile (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:530:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/pi/HAP-NodeJS/node_modules/ts-node/src/index.ts:533:12)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
pi@raspberrypi:~/HAP-NodeJS $

**Comment by oddwires** [comment]
Yes - I got exactly the same

**Comment by oddwires** [comment]
Finally got v0.5.0 (typescript version) to install, run and connect to HomeKit.

First attempt yesterday was based on my existing (pre-typescript) installer. When that failed to work,  I just threw in a load of commands at the end in an attempt to install ts-node.

So I went for a fresh image, tidied things up, took on board the (much earlier ) [comment from KhaosT](https://github.com/KhaosT/HAP-NodeJS/issues/410#issuecomment-280941104) about installing locally rather than globally, and it all progressed beyond the issue described above.

But I still couldn't see the BridgedCore.ts as an accessory in HomeKit.

Running using 'DEBUG=*' showed the sample accessories were being parsed ok.

Then I remembered I'd seen this before. My earlier, pre-typescript install was still active on my network. Both installs were using the default MAC address. So one quick change of MAC address in the BridgedCore.ts file and everything kicked into life.

,,, but start up is really really slow using typescript.

**Comment by n0rt0nthec4t** [comment]
Do you remember the commands used to install which got it working? I hadn't done a glob install, only a local.

Yes, startup is VERY VERY VErY painful with typescript.. I stil have the personal view that the project has gone backwards with the typescript conversion. 

All my projects are still on the none typescript branch, as for one, haven't had luck getting this install and running

**Comment by oddwires** [comment]
Well I thought I had written it all down, but I've just tried re-creating it and the permissions have all gone wrong.
I'll have another go at it over the weekend.

**Comment by oddwires** [comment]
Got it working again and scripted. Here's the details...

Hardware: Raspberry Pi 3 model B+
Image: Raspbian Buster Lite - Release date:2019-09-26

I install HAP-NodeJS as part of [my project](https://github.com/oddwires/alarm-system), the full install is scripted, and other software components dictate that the install script has to be sudo'd. 
It seems sudo'ing the install script affects the git clone stage, changing the default ownership and permissions on the cloned files and folders. So I've had to add  additional commands just after the git clone to put the directory back into a usable state.

If you are performing a manual install, or running this from a non-sudo'd script, you should be safe to omit the permissions section, although I have only tested this install in the format provided below.

So here is the relevant section, extracted from my [install script](https://github.com/oddwires/alarm-system/blob/master/install.sh)...
 
```# install various pre requisites...\n
# install into the Downloads directory

  sudo apt-get install libavahi-compat-libdnssd-dev -y
  sudo apt-get install -y npm
  
 # Ideally these should be installed locally. But this causes issues with the ts-node executable
 # not being found. Its probably just a path issue, but I installed Globally as a workaround.
  sudo npm install -g ts-node
  sudo npm install -g typescript

  # install the HAP-NodeJS server...
  git clone git://github.com/KhaosT/HAP-NodeJS.git
   
  # because we've sudo'd the git clone, the directory structure will belong to root. This causes issues.
  # the first time the service runs, it creates a 'persists' folder, but assigns the wrong permissions.
  # the following 5 lines return the sudo cloned repo to a usable state...
  mkdir HAP-NodeJS/persist          # Create the folder now rather than letting the service
                                    # do it at first run.
  sudo chown -R pi ./HAP-NodeJS     # Belt and braces solution - force permissions from root to pi
  sudo chgrp -R pi ./HAP-NodeJS
  sudo chmod g+s ./HAP-NodeJS       # new folders + files will inherit directory group details
  sudo chmod u+s ./HAP-NodeJS       # new folders + files will inherit directory user details

  cd HAP-NodeJS/
  npm install bonjour-hap
  npm install decimal.js
  npm install node-persist
  npm install debug
  npm install buffer-shims
  npm install bonjour-hap
  npm install fast-srp-hap
  npm install ip
  npm install tweetnacl

  npm install
  npm install --only=dev
  ```

I'm sure this can be optimised, I'm not really all that clued up on NPM, I'm just using it as a component.

**Comment by KhaosT** [comment]
Err...  you shouldn't need to manually do

```
  npm install bonjour-hap
  npm install decimal.js
  npm install node-persist
  npm install debug
  npm install buffer-shims
  npm install bonjour-hap
  npm install fast-srp-hap
  npm install ip
  npm install tweetnacl
```

 in there... and a single `npm install` should just work. Are you seeing error with that?

**Comment by n0rt0nthec4t** [comment]
Yep, I get the error with a straight npm install after doing a git clone and then trying to run with ts-node installed locally, not globally

**Comment by oddwires** [comment]
I've just removed the redundant lines of code, and re-run [my installer](https://github.com/oddwires/alarm-system/blob/master/install.sh) on a clean image.
All still working OK for me.

Thanks for the tip - I really must find some time to learn more about Node rather than just trying to mangle existing code to work in my scripts.

**Comment by Sportsgraphics** [comment]
I'm stuck with the same issue as the beginning with node-persist.    
Ran npm install @types/node-persist

Now at this point..
TSError: ⨯ Unable to compile TypeScript:
src/BridgedCore.ts:10:9 - error TS2339: Property 'initSync' does not exist on type 'typeof NodePersist'.

**Comment by meyer** [comment]
All sync functions have been removed from `node-persist@^3`, so v3 types won’t be too useful. Here’s the commit where they were removed: https://github.com/simonlast/node-persist/commit/b03311106421cba6774f4c7c65805d51ac1ffd33#diff-04c6e90faac2675aa89e2176d2eec7d8R9
