### ISSUE TITLE
Door Accessory example

### ISSUE THREAD

**Issue by MaikoHermans** [homebridge/HAP-NodeJS#757]
Does anyone have a example for a Door accessory. 
I've been trying to get it to work most of it works fine but it stays on opening. I figured it would be somewhat the same as the garagedoor which I do have working but this doesn't seem to be the case.
I'm hoping someone has an example for it so I can see what needs to be done.

**Comment by Final-Hawk** [comment]
I got you
`var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var wpi = require('wiringpi-node');

var DeurSensorPin=22; //sensor 2 GPIO25 
var lastState=0;
// here's a door device that we'll expose to HomeKit
var DOOR = {
  open: false,
  sensor: 0,
  read: function(){
    wpi.setup('phys');
    wpi.pinMode(DeurSensorPin,wpi.INPUT)
    var DeurSensorValue = wpi.digitalRead(DeurSensorPin);
    //console.log('read sensor',DeurSensorValue);
    DOOR.sensor=DeurSensorValue;
    if(DOOR.sensor==0){
       DOOR.open=false;
       if(lastState!=false){
         console.log('door is closed');
         lastState=false;
       }
    }else{
       DOOR.open=true;
       if(lastState!=true){
       console.log('door is open');
       lastState=true;
       }
    }
  },wait: function() {
     var seconds=1;
     var waitTill = new Date(new Date().getTime() + seconds * 1000);
     while(waitTill > new Date()){}
  },
  identify: function() {
    console.log("Identify the door!");
  }
}

// Generate a consistent UUID for our Lock Accessory that will remain the same even when
// restarting our server. We use the `uuid.generate` helper function to create a deterministic
// UUID based on an arbitrary "namespace" and the word "door".
var doorUUID = uuid.generate('hap-nodejs:accessories:contactsensor');

// This is the Accessory that we'll return to HAP-NodeJS that represents our door
var door = exports.accessory = new Accessory('ContactSensor', doorUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
door.username = "AA:BB:CC:DD:EE:01";
door.pincode = "031-45-154";

// set some basic properties (these values are arbitrary and setting them is optional)
door
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "Electronics")
  .setCharacteristic(Characteristic.Model, "Garage")
  .setCharacteristic(Characteristic.SerialNumber, "HI");

// listen for the "identify" event for this Accessory
door.on('identify', function(paired, callback) {
  DOOR.identify();
  callback(); // success
});

door
   .addService(Service.ContactSensor,"Binnen Deur Sensor")
   .getCharacteristic(Characteristic.ContactSensorState)
   .on('get', function(callback) {
    DOOR.read();
    // return our current value
    callback(null, DOOR.open);
});
setInterval(function() {  
  DOOR.read()
  
  // update the characteristic value so interested iOS devices can


  // update the characteristic value so interested iOS devices can get notified
   door
    .getService(Service.ContactSensor)
    .getCharacteristic(Characteristic.ContactSensorState)
    .setValue(DOOR.open);  
}, 1000);
`

**Comment by n0rt0nthec4t** [comment]
Here's one I wrote

https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/blob/master/GarageOpener_accessory.js

**Comment by codyc1515** [comment]
The door service is different to the contact sensor service, although a subtype of contact sensors can be door.
