### ISSUE TITLE
Damper Accessory

### ISSUE THREAD

**Issue by mihailescu2m** [homebridge/HAP-NodeJS#758]
I am trying to add a damper accessory for a multi-zone AC.
The settings available for the damper are:
* zone on/off (damper on/off)
* damper open position (0-100)
* optional if exists a temperature sensor

How to implement the open position and make if controllable from Home and Eve app?
In order to use it from Home, I need to add an existing Service - closest that has the Current/Target Position Characteristics for the damper position is Window (or Door or WindowCovering) but it really looks awful to have a Window as an AC Zone.

Having it as a Fanv2 is actually better, but it's annoying to have the labels "Speed" in Home app for the open position. It's also very annoying the fan animation: sometimes the fan spins, sometime it doesn't (even if active state is set); sometimes for 2 zones with the same settings i had the fan spinning for one and not spinning for another (is there a way to disable the fan spinning in the home app??). Is it possible to change the RotationSpeed labels shown in the Home app??

I ended up using a Switch primary service (for on/off) and adding a Window service, combined in one tile that uses the Switch icon:

![home](https://user-images.githubusercontent.com/4421731/69846714-d71b4500-12c4-11ea-95de-bc2980affa81.jpeg)

It's actually not bad, but then I was surprised in Eve app there is no position control - the interface has only the ON/OFF buttons!

![eve](https://user-images.githubusercontent.com/4421731/69846768-00d46c00-12c5-11ea-895d-f94e5e7831f7.jpeg)

I tried having a Switch and add characteristics to it (CurrentPosition/TargetPosition or RotationSpeed) but Home App would not show the slider - only by having the actual service (Window/Fanv2) the slider would be there...

Any recommendations??
Thanks!

**Comment by jvmahon** [comment]
What about using either the  Heater/Cooler Service and using the "Slat" characteristic for the damper? In my mind, that fits this scenario pretty well.

**Comment by mihailescu2m** [comment]
@jvmahon my device's damper control is in percentage, so I would have to convert arcdegrees from slat to %.
The AC console also uses % so it would be confusing to see different values on the phone than on the console.
How does the slat target tilt looks like in Home App? Could not get any info on that on Google....
