### ISSUE TITLE
TargetRelativeHumidity missing for Service HumidifierDehumidifier

### ISSUE THREAD

**Issue by tomSmartHome** [homebridge/HAP-NodeJS#765]
I believe a TargetRelativeTemperature Characteristic is missing for Service HumidifierDehumidifier:
https://developer.apple.com/documentation/homekit/hmcharacteristictypetargetrelativehumidity

Regards,
Tom

**Comment by Supereg** [comment]
Looking at the HAP spec and also into internal metadata files of homed, the `HumidifierDehumidifier` service does not have a `TargetRelativeTemperature` characteristic.

Instead the two characteristics `RelativeHumidityDehumidifierThreshold` or `RelativeHumidityHumidifierThreshold` for dehumidifier/humidifier are used to define a value when the it should turn on.

//close

**Comment by vadim-s-melnikov** [comment]
@tomSmartHome I believe you are right. Looks like TargetRelativeHumidity is missing.
Please look at the difference in HomeKit behaviour when thresholds are declared and when not.

![IMG_0018](https://user-images.githubusercontent.com/32674985/76544685-81e0f900-6499-11ea-8854-b87608f0bfb7.png)
![IMG_0017](https://user-images.githubusercontent.com/32674985/76544692-84dbe980-6499-11ea-8d71-d99283ab9d07.png)

**Comment by shawnli87** [comment]
@Supereg I’m pretty sure that @tomSmartHome is right, and this is an issue. I believe he meant to say the `TargetRelativeHumidity` characteristic is missing.

While the `RelativeHumidityDehumidifierThreshold` or `RelativeHumidityHumidifierThreshold` characteristics are used to define when the device should turn on, the slider in HomeKit does not function properly without the `TargetRelativeHumidity` characteristic. The thresholds present as a percentage of the range between the defined minValue and maxValue, instead of displaying the correct value.

**Comment by Supereg** [comment]
@shawnli87 I can assure you that `TargetRelativeHumidity` is not listed as an optional nor a required characteristic for the `Humidifier Dehumidifier` service.

Note that either `RelativeHumidityDehumidifierThreshold` or `RelativeHumidityHumidifierThreshold` is required depending on wether you are modeling a dehumidifier or a humidifier (even though both are listed as optional).

Please refer to the homekit accessory protocol specification for further information https://developer.apple.com/support/homekit-accessory-protocol/

In any case you are always able to alter the characteristics configuration as you want. If you think you need that service on your accessory you can easily add it for your use case.

**Comment by Supereg** [comment]
You may also download the HomeKit Accessory Simulator https://developer.apple.com/documentation/homekit/testing_your_app_with_the_homekit_accessory_simulator and create a HumdifierDehumidifier service to see how Apple expects you to use that service and play around with it.

**Comment by shawnli87** [comment]
@Supereg Then why is `TargetRelativeHumidity` listed under Humidity in the documentation for the HomeKit accessory protocol? [https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types](url)
![IMG_0895](https://user-images.githubusercontent.com/56144082/87247937-54429700-c41c-11ea-85a0-749ae1bae1e3.jpeg)

**Comment by Supereg** [comment]
The documentation site you lined does not state at all that this characteristic should be included for the `HumidifierDehumidifier` service. It only groups all `Humidity` related services.
So don't really know how you would come to that conclusion.
