### ISSUE TITLE
SecuritySystem accessory - can't make it work properly

### ISSUE THREAD

**Issue by modena01** [homebridge/HAP-NodeJS#788]
Hi I have been using HAP-NodeJS for a few years, have great success with using it for garage door, controlling my spinklers (outlets), and even showing some temperartures by reading text file. This is all done on a pi. Thank you to all for your continued good work to make this such a great platform.

I am integrating my home alarm system. I have two GPIO pins, one to toggle and arm/disarm the system, and a second pin which reads if the alarm is armed or disarmed. In this way it is almost exactly like the garage door opener. So I started with the garage door example, and modified it. I had to add a couple more CurrentState conditions to check for NIGHT_ARM, STAY/AWAY mode etc., but it is still 95% the same as the garage door opener, but I cant get any joy.

The accessory shows up just fine in the Home app. If I arm the alarm with the physical keypad, the Home app does not change to show me that the alarm is armed in AWAY mode (which is what my code should be doing).

If I arm the alarm via the Home app by choosing "AWAY" then I get a spinner with "ARMING" (and the alarm does in fact arm) but the spinner just sits there forever with "ARMING", or may eventually timeout.

Please help, I'm no javascript expert!

Here is my accessory;

```javascript
//START SETUP
var alarmName = 'House Alarm';
var uuidTag = 'housealarm';
//END SETUP

var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var cmd=require('node-cmd');
var wpi = require('wiringpi-node');
var sensorReading;
var newStatus;
var falseAlert = false;

var HOUSE_ALARM = {
  armed: false,
  arm: function() {
    if(!HOUSE_ALARM.armed)
    console.log("Arming the House Alarm!");
    cmd.run('sudo python /home/pi/HAP-NodeJS/python/arm_and_disarm_alarm.py');
    HOUSE_ALARM.armed = true;
  },
  disarm: function() {
    if(HOUSE_ALARM.armed)
    console.log("Disarming the House Alarm!");
    cmd.run('sudo python /home/pi/HAP-NodeJS/python/arm_and_disarm_alarm.py');
    HOUSE_ALARM.armed = false;
  },
  identify: function() {
    console.log("Identify the House Alarm");
  }
};

var housealarmUUID = uuid.generate('hap-nodejs:accessories:'+uuidTag);
var housealarm = exports.accessory = new Accessory(alarmName, housealarmUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
housealarm.username = "C1:5D:3F:EE:5E:FA"; //edit this if you use Core.js
housealarm.pincode = "031-45-154";

housealarm.on('identify', function(paired, callback) {
  HOUSE_ALARM.identify();
  callback();
});

housealarm
  .addService(Service.SecuritySystem, "House Alarm")
  .setCharacteristic(Characteristic.SecuritySystemTargetState, Characteristic.SecuritySystemTargetState.DISARM) // force initial state to DISARMED
  .getCharacteristic(Characteristic.SecuritySystemTargetState)
  .on('set', function(value, callback) {

    if (value == Characteristic.SecuritySystemTargetState.DISARM) {
      if(falseAlert)
      {
        falseAlert=false;
        callback();
      }
      else{
        HOUSE_ALARM.disarm();
        callback();
      }
    }
    else if (value == Characteristic.SecuritySystemTargetState.AWAY_ARM) {
      if(falseAlert)
      {
        falseAlert=false;
        callback();
      }
      else{
        HOUSE_ALARM.arm();
        callback();
      }
    }
    else if (value == Characteristic.SecuritySystemTargetState.STAY_ARM) {
      if(falseAlert)
      {
        falseAlert=false;
        callback();
      }
      else{
        HOUSE_ALARM.arm();
        callback();
      }
    }
    else if (value == Characteristic.SecuritySystemTargetState.NIGHT_ARM) {
      if(falseAlert)
      {
        falseAlert=false;
        callback();
      }
      else{
        HOUSE_ALARM.arm();
        callback();
      }
    }

  });

housealarm
  .getService(Service.SecuritySystem)
  .setCharacteristic(Characteristic.SecuritySystemCurrentState, Characteristic.SecuritySystemCurrentState.DISARMED)
  .getCharacteristic(Characteristic.SecuritySystemCurrentState)
  .on('get', function(callback) {

    var err = null;

    wpi.setup('phys');
    sensorReading = wpi.digitalRead(21);
    sensorReading = Number(sensorReading);
    if (sensorReading == '0'){
      HOUSE_ALARM.armed = false;
    }
    if (sensorReading == '1'){
      HOUSE_ALARM.armed = true;
    }

    if (HOUSE_ALARM.armed) {
      console.log("Query: Is House Alarm armed? Yes.");
      callback(err, Characteristic.SecuritySystemCurrentState.AWAY_ARM);
    }
    else {
      console.log("Query: Is House Alarm armed? No.");
      callback(err, Characteristic.SecuritySystemCurrentState.DISARMED);
    }
  });

setInterval(function() {
  wpi.setup('phys');
  sensorReading = wpi.digitalRead(21);
  sensorReading = Number(sensorReading);
  if (sensorReading == '0'){
    newStatus = false;
  }
  if (sensorReading == '1'){
    newStatus = true;
  }

  if(newStatus != HOUSE_ALARM.armed){
    falseAlert = true;
    HOUSE_ALARM.armed = newStatus;
    housealarm
      .getService(Service.SecuritySystem)
      .setCharacteristic(Characteristic.SecuritySystemCurrentState, !HOUSE_ALARM.armed);

      housealarm
        .getService(Service.SecuritySystem)
        .setCharacteristic(Characteristic.SecuritySystemTargetState, !HOUSE_ALARM.armed);
  }
}, 1000);

```

**Comment by modena01** [comment]
is no-one using a security system with HAP-NodeJS?

**Comment by marcus-j-davies** [comment]
Hi - I use the SECURITY_SYSTEM service quite extensively without issue.
I do note you're setting boolean values, the alarm service is numerical based - I'm not sure if that will make any difference.

STAY_ARM = 0;
AWAY_ARM = 1;
NIGHT_ARM = 2;
DISARMED = 3;
ALARM_TRIGGERED = 4;


Do you get any output when printing sensorReading to console?

**Comment by modena01** [comment]
Thank you for the input, you were right about the boolean of course. I have updated things to use the proper values, and am pretty much there now, EXCEPT! sometimes I get "arming....." and a spinner after arming the alarm, or "disarming...." and a spinner when disarming it, and it sits there forever spinning (the change to the actual alarm does work). If close and re-open homekit sometimes this spinner goes away and it shows the correct status, other times the accessory will actually go into "not responding" state. Run out of ideas now, is this perhaps something to do with callback hell, as it works fine sometimes, but not others?

`//START SETUP
var alarmName = 'House Alarm';
var uuidTag = 'housealarm';
//END SETUP

var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var cmd=require('node-cmd');
var wpi = require('wiringpi-node');
var sensorReading;
var newStatus;
var falseAlert = false;
var switchstatus1;
var switchstatus2;

var HOUSE_ALARM = {
  armed: false,
  arm: function() {
    if(!HOUSE_ALARM.armed)
    console.log("Arming the House Alarm!");
    cmd.run('sudo python /home/pi/HAP-NodeJS/python/arm_and_disarm_alarm.py');
    HOUSE_ALARM.armed = true;
  },
  disarm: function() {
    if(HOUSE_ALARM.armed)
    console.log("Disarming the House Alarm!");
    cmd.run('sudo python /home/pi/HAP-NodeJS/python/arm_and_disarm_alarm.py');
    HOUSE_ALARM.armed = false;
  },
  identify: function() {
    console.log("Identify the House Alarm");
  }
};

var housealarmUUID = uuid.generate('hap-nodejs:accessories:'+uuidTag);
var housealarm = exports.accessory = new Accessory(alarmName, housealarmUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
housealarm.username = "C1:5D:3F:EE:5E:FA"; //edit this if you use Core.js
housealarm.pincode = "031-45-154";

housealarm.on('identify', function(paired, callback) {
  HOUSE_ALARM.identify();
  callback();
});

housealarm
  .addService(Service.SecuritySystem, "House Alarm")
  //.setCharacteristic(Characteristic.SecuritySystemTargetState, 3) // force initial state to DISARMED
  .setCharacteristic(Characteristic.SecuritySystemTargetState, Characteristic.SecuritySystemTargetState.DISARM) // force initial state to DISARMED
  .getCharacteristic(Characteristic.SecuritySystemTargetState)
  .on('set', function(value, callback) {

    if (value == Characteristic.SecuritySystemTargetState.DISARM) {
      if(falseAlert)
      {
        falseAlert=false;
        callback();
      }
      else{
        HOUSE_ALARM.disarm();
        callback();
      }
    }
    else if (value == Characteristic.SecuritySystemTargetState.AWAY_ARM) {
      if(falseAlert)
      {
        falseAlert=false;
        callback();
      }
      else{
        HOUSE_ALARM.arm();
        callback();
      }
    }
    else if (value == Characteristic.SecuritySystemTargetState.STAY_ARM) {
      if(falseAlert)
      {
        falseAlert=false;
        callback();
      }
      else{
        HOUSE_ALARM.arm();
        callback();
      }
    }
    else if (value == Characteristic.SecuritySystemTargetState.NIGHT_ARM) {
      if(falseAlert)
      {
        falseAlert=false;
        callback();
      }
      else{
        HOUSE_ALARM.arm();
        callback();
      }
    }

  });

housealarm
  .getService(Service.SecuritySystem)
  .setCharacteristic(Characteristic.SecuritySystemCurrentState, Characteristic.SecuritySystemCurrentState.DISARMED)
  .getCharacteristic(Characteristic.SecuritySystemCurrentState)
  .on('get', function(callback) {

    var err = null;

    wpi.setup('phys');
    sensorReading = wpi.digitalRead(21);
    sensorReading = Number(sensorReading);
    if (sensorReading == '0'){
      HOUSE_ALARM.armed = false;
    }
    if (sensorReading == '1'){
      HOUSE_ALARM.armed = true;
    }

    if (HOUSE_ALARM.armed) {
      console.log("Query: Is House Alarm armed? Yes.");
      callback(err, Characteristic.SecuritySystemCurrentState.AWAY_ARM);
    }
    else {
      console.log("Query: Is House Alarm armed? No.");
      callback(err, Characteristic.SecuritySystemCurrentState.DISARMED);
    }
  });

setInterval(function() {
  wpi.setup('phys');
  sensorReading = wpi.digitalRead(21);
  sensorReading = Number(sensorReading);
  if (sensorReading == '0'){
    newStatus = false;
  }
  if (sensorReading == '1'){
    newStatus = true;
  }

  if(newStatus != HOUSE_ALARM.armed){
    falseAlert = true;
    HOUSE_ALARM.armed = newStatus;

        if (HOUSE_ALARM.armed){
                var switchstatus1 = Characteristic.SecuritySystemCurrentState.AWAY_ARM;
                var switchstatus2 = Characteristic.SecuritySystemTargetState.AWAY_ARM;
        } else {
                var switchstatus1 = Characteristic.SecuritySystemCurrentState.DISARMED;
                var switchstatus2 = Characteristic.SecuritySystemTargetState.DISARM;
        }

    housealarm
      .getService(Service.SecuritySystem)
      .setCharacteristic(Characteristic.SecuritySystemCurrentState, switchstatus1);

      housealarm
        .getService(Service.SecuritySystem)
        .setCharacteristic(Characteristic.SecuritySystemTargetState, switchstatus2);
  }
}, 1000);

`

**Comment by marcus-j-davies** [comment]
Much like the Garage Door opener, the Alarm service will spin if there is a difference between
`SecuritySystemTargetState` & `SecuritySystemCurrentState`

Essentially, the spinner will appear whilst `SecuritySystemCurrentState` is waiting to be set to match `SecuritySystemTargetState`

1 potential issue.
HomeKit will poll or at least GET on `SecuritySystemCurrentState`
here you are `wpi.digitalRead(21)`.

now, this also happens via `setInterval` - I wonder if at times, you happen to cause these 2 to occur at the same time - which may explain the intermittency.

try adding some exclusivity around `wpi.digitalRead(21)`
i.e in your setInterval don't execute unless you are sure` wpi.digitalRead(21)` is not already happening via the GET happening by HomeKit.

**Comment by modena01** [comment]
Thanks for the response. On the garage door, when it closes, obviously there is a delay between when setting TargetState and when the relay closes after the door completes shutting which is when CurrentState matches TargetState, so the spinner would be expected during the closing time.

However, it also shows the spinner when opening the door. Now, Homekit does not know when the door physically finishes opening, as far as homekit is concerned TargetState is set, the reed-switch opens, and the door is now instantly "open" as far as homekit is concerned (even though it may take 10 seconds for the door to complete opening). So why does it show the spinner when opening, and seemingly for a set amount of time? It always does this for the GarageDoor accessory.

Just trying to understand the spinner behaviour to work out how it may relate (sometimes) to my SecuritySystem spinner issue.

**Comment by marcus-j-davies** [comment]
I like to think of the spinner as the transition from Current to Target.
They must match for the spinner to settle, it's down to us to ensure they do.

Having just setup a quick garage door opener - it does not go to 'Open' unless I ensure Target And Current match as such. I'm using my own [implementation](https://github.com/marcus-j-davies/Homekit-Device-Stack) 

**Closed**   :: Target-> 1, Current -> 1
**Opening** :: Target -> 0, Current -> 1
**Open**      ::  Target -> 0, Current -> 0
**Closing**   ::  Target -> 1, Current -> 0,

If you're  getting the Open status - there must be logic that is somehow setting it, or at least some logic that is resulting in Target and Current matching.

Reviewing your code a little further, I have added a check on the origin of the request for `set` to determine if it was initiated via your device or code. 

if `hap` is not null - then it was the device that requested the change.
calling `.setCharacteristic(Characteristic.SecuritySystemTargetState, switchstatus2);`
will actually trigger `.on('set',...`

[alarm.js.zip](https://github.com/KhaosT/HAP-NodeJS/files/4442719/alarm.js.zip)

 ```
.on('set', function (value, callback,hap)
    {

        if(hap == null)
        {
            callback(null);
            return;
        }

        .....
```
