### ISSUE TITLE
Question: What modifications was done in SRP library?

### ISSUE THREAD

**Issue by ex3ndr** [homebridge/HAP-NodeJS#796]
Hey! I was reimplementing SRP in more modern, compatible and correct way and one of the most interested use cases for SRP is a Homekit and HAP-NodeJS forked one implementation and made some changes to it. Most of the libraries for SRP are not portable - they are not working well with different implementations and often does not follow spec like the one used by HAP-NodeJS.

Is it something very apple specific or just replace keys and fix paddings?

**Comment by KhaosT** [comment]
I think [this article](http://blog.dzhuvinov.com/?p=1066) described the issue with SRP compatibility pretty well in terms of why there are changes made to `fast-srp`.

HAP follows RFC2945 when computing `M1` (where `M1 = H(H(N) XOR H(g) | H(U) | s | A | B | K)`), when some other libraries may computed M1 differently.

**Comment by ex3ndr** [comment]
Yeah, exactly my experience with existing libraries.

Yeah, i can see a different (quite strange!) implementation in fast-srp: 
https://github.com/zarmack/fast-srp/blob/master/lib/srp.js#L304-L320

Is HAP-NodeJS open for PR for a different library?
