### ISSUE TITLE
Add support Xiaomi Mi Air Purifier A1 (MJXFJ-150-A1) dmaker.airfresh.a1

### ISSUE THREAD

**Issue by ad0brynin** [homebridge/HAP-NodeJS#800]
Please add support.

**Comment by iRayanKhan** [comment]
That is not how Hap-NodeJS works. Find a Xiaomi repo and raise the question there.

**Comment by Supereg** [comment]
HAP-NodeJS is just a library which implements the HomeKit protocol. There are no specific implementations provided with this library.
