### ISSUE TITLE
My Accesorry wont show up in the homekit app. 

### ISSUE THREAD

**Issue by Zack1324** [homebridge/HAP-NodeJS#810]
So I use HAP-NodeJS to control my LED strip in my room. it all works and nodejs starts up and my script runs. only now it won't show up on my homekit app. it won't show any app and I don't have a clue what wrong. could somebody help me with this? If you need more information react to my post with what you need!

**Comment by Supereg** [comment]
You you check if there are maybe already some files in the `persist` folder and as result HAP-NodeJS thinks it's already paired and will advertise itself as `paired`, which result in HomeKit not listing this accessory.
