### ISSUE TITLE
How to solve this problem when run ts-node Core.ts cmd

### ISSUE THREAD

**Issue by xuhehua** [homebridge/HAP-NodeJS#813]
After I installed nodejs(13.13.0), npm(6.14.0), HAP-Nodejs(latest), its seem to no problem.
But when I try to run:ts-node Core.ts
It shows lots of err as the pic shows:
Could u help me, many thanks.

![微信图片_20200422171913](https://user-images.githubusercontent.com/6175592/79964560-767fe500-84bd-11ea-8352-7fc7ca8bc2de.png)

**Comment by Supereg** [comment]
Try to run it the following way `ts-node --files src/Core.ts`.
For one adding the `--files` argument will resolve the errors display. 
Additional one would suggest that you run it not in the src directory so persistent files won‘t be created there.

**Comment by xuhehua** [comment]
> 
> 
> Try to run it the following way `ts-node --files src/Core.ts`.
> For one adding the `--files` argument will resolve the errors display.
> Additional one would suggest that you run it not in the src directory so persistent files won‘t be created there.

thanks very much
