### ISSUE TITLE
Limitation InputSources in TV Accessory 

### ISSUE THREAD

**Issue by grzegorz914** [homebridge/HAP-NodeJS#814]
Hi,

I have created some plugins (homebridge-denon-tv, homebridge-openweif-tv) which’s are publish as dynamicPlatform TV accessory and I have observed if I create more as 97 InputSources (in config.json) then the device no response in HomeKit app, if the InputSources are =< 97 all working OK. It is HomeKit Limitation or bug in HAP-NodeJS or bug in Homebridge.?

Thanks for Your support.

**Comment by Supereg** [comment]
Hm, the only limit which is communicated by Apple is the maximum limit of `150` accessories per instance. 
Anybody else having more information about this? If you running a Mac you could possibly use the `Console` app to view the log files and then check if `homed` process spits out any useful warning messages.
What is the total amount of services your accessory has? There is probably a television service, anything else?

**Comment by grzegorz914** [comment]
The accessory use only Television and Speaker Service. Right now I’m not on Mac, write from iPad 😀.

**Comment by Supereg** [comment]
Hm okay, so 97 InputSource services, 1 television service, 1 speaker services and 1 hidden mandatory AccessoryInformation services. I don't think a maximum of 100 services is a coincidence and sounds to me that is could well be a limit imposed by HomeKit itself.

**Comment by grzegorz914** [comment]
It seems logical, although it is a pity that such a limit is set.

**Comment by Supereg** [comment]
Seems to be the case. As when a HAP server exposes more than the allowed 150 accessory you can observer the exact same behavior 🤔

**Comment by grzegorz914** [comment]
OK. I close this as HomeKit Limitation.

**Comment by Supereg** [comment]
Just seen in it ne spec: 

<img width="615" alt="Bildschirmfoto 2020-04-28 um 22 20 39" src="https://user-images.githubusercontent.com/9783857/80533811-7e98c280-899e-11ea-847c-9ace4afbd153.png">

<img width="616" alt="Bildschirmfoto 2020-04-28 um 22 20 46" src="https://user-images.githubusercontent.com/9783857/80533820-82c4e000-899e-11ea-8cd7-ba62bd75bf92.png">
