### ISSUE TITLE
Missing value for "Current Heating Cooling State"

### ISSUE THREAD

**Issue by MervinDelfin** [homebridge/HAP-NodeJS#815]
In apple's documentation for [HMCharacteristicValueHeatingCooling](https://developer.apple.com/documentation/homekit/hmcharacteristicvalueheatingcooling) an "auto" value is present which isn't in CurrentHeatingCoolingState class.

https://github.com/homebridge/HAP-NodeJS/blob/ffb8fc75c7b932fbb567f96478a589974cacacab/src/lib/gen/HomeKit.ts#L654-L674

3 (for AUTO) should also be a valid value according to apple.

**Comment by Supereg** [comment]
As specified by the HAP specification, AUTO (=3) ist just used for the `TARGETHeatingCoolingState` characteristic. `CURRENTHeatingCoolingState` on the other hand defines then what the **current** state is. And AUTO(=3) is not a valid state for that (wouldn't even make sense).
So you as a user would set the target state to AUTO and the device itself decides into what state it will go, maybe heat, maybe cool, depending on the temperature.

**Comment by ztalbot2000** [comment]
Hi.  I'm John Talbot, author of Homebridge-cmd4.  I wrote it based on the HAP-Spec and always agreed with the logic you just stated. However, Mervin has a point in that the HomeKit specification that we previously never had access to does allow the CurrentHeatingCoolingState to be Auto.  
See:  https://developer.apple.com/documentation/homekit/hmcharacteristictypecurrentheatingcooling

If that is true then, would not HomeKit asking for the CurrentHeatingCoolingState expect it to be Auto, set by the TargetHeatingCoolingState?

My two cents worth, which may be nothing.

**Comment by Supereg** [comment]
Will double check this. There seems to be a difference between heater-cooler and heating-cooling taget/current values.

**Comment by Supereg** [comment]
Okay got time to look at it again. I'm still and my standpoint. Checked all sources. HAP spec states the MIN/MAX values to NOT include AUTO. The functionality is as described above

<img width="470" alt="Bildschirmfoto 2020-04-28 um 00 30 58" src="https://user-images.githubusercontent.com/9783857/80427219-89445080-88e7-11ea-996d-7dd588fea53b.png">
<img width="436" alt="Bildschirmfoto 2020-04-28 um 00 32 43" src="https://user-images.githubusercontent.com/9783857/80427350-d1fc0980-88e7-11ea-8c06-03a0dd67a0a5.png">

The reason you discovered this is that HAP defines the SAME unit for both of the characteristics. But excluding one of the values using min/max properties. You can see that below how the unit is defined for "Read" and "Write" but specifying different characteristics.
<img width="418" alt="Bildschirmfoto 2020-04-28 um 00 30 23" src="https://user-images.githubusercontent.com/9783857/80427411-f7891300-88e7-11ea-8155-256c962b9286.png">

And again, it wouldn't be logical for a service to expose that the heating mode is currently AUTO. AUTO can't be a heating mode, it's COOLING or HEATING.

**Comment by NorthernMan54** [comment]
@Supereg Agreed, CurrentHeatingCoolingState should be mapped to what the furnace is currently doing.  If it is in a heating cycle, it should be a 1, if it is in a cooling cycle it should be a 2 and if the unit is not currently heating or cooling, then off.  This is used to control the state of the Home app icon.

**Comment by ztalbot2000** [comment]
I agree that the HAP spec does not have auto. HomeKiit spec says otherwise
and that was my conundrum.  I'm going to play with Homebridge and trace the
messages to see what HomeKit expects. I'll let you know what I find.
TTFN,
John

**Comment by Supereg** [comment]
There is nothing like a HomeKit Spec. HAP (HomeKit Accessory Protocol) is the HomeKit spec.
The enum values where just grouped into one enum for simplicity.

**Comment by ztalbot2000** [comment]
I don't want to argue with you. The Hap spec is the Hap Spec but is downstream from Apples HomeKit Specification of which we are quoting.  Now it may make totally no difference to Apple if the current state is not the target state. The Apple Developer Spec does not say so, but it does say that it can be Auto, to which the answer may all be moot if nobody cares anyway. All I'm saying is that I want to find out for sure and I can do this by tracing what is sent to Hap and determine what it expects to receive, which from what I can see so far, it does not care because the Hap never responds with Auto anyway and everything seems to work well.

All I can say, is let me see and I'll get back to you.

**Comment by Supereg** [comment]
I made my standpoint clear. We will adhere to the specification.

You can however adjust the characteristics properties for your custom services as you like. HAP-NodeJS does not force those values onto to you.
