### ISSUE TITLE
Camera snapshots for legacy cameras broken in 0.6.0 and above?

### ISSUE THREAD

**Issue by adriancable** [homebridge/HAP-NodeJS#816]
In 0.6.0 and later, handleSnapshotRequest function in CameraSource is called with the wrong signature for legacy cameras. Works in 0.5.11. I believe the regression was introduced when adding the new CameraController logic.

Issue seems to be in lib/controller/CameraController.ts. Near the end of the file:

    handleSnapshotRequest(height: number, width: number, callback: NodeCallback<Buffer>) {

has the wrong signature. Legacy signature is:

    handleSnapshotRequest(request: SnapshotRequest, callback: NodeCallback<Buffer>) {

**Comment by Supereg** [comment]
I'm not sure what you mean. The function handleSnapshotRequest correctly class the delegate: https://github.com/homebridge/HAP-NodeJS/blob/ffb8fc75c7b932fbb567f96478a589974cacacab/src/lib/controller/CameraController.ts#L314-L319

**Comment by Supereg** [comment]
In what way are you observing that the parameters are called in the wrong way?

**Comment by adriancable** [comment]
@Supereg - I'm so sorry. Please ignore. Too little sleep last night.

**Comment by Supereg** [comment]
And even the adapter is transforming the type correctly 🤔 

https://github.com/homebridge/HAP-NodeJS/blob/ffb8fc75c7b932fbb567f96478a589974cacacab/src/lib/camera/Camera.ts#L53-L57

**Comment by Supereg** [comment]
ah okay 😅
