### ISSUE TITLE
Characteristic.CarbonDioxideLevel not expected on Service.AirQualitySensor

### ISSUE THREAD

**Issue by nicoduj** [homebridge/HAP-NodeJS#817]
**Describe The Bug:**

Not sure it is a bug, but in latest version there is a warnign about Characteristic.CarbonDioxideLevel not expected on Service.AirQualitySensor

**To Reproduce:**

use this plugin : https://github.com/skrollme/homebridge-eveatmo/blob/7a99d19199dc9e29c5d6e23d74aab86171d7679e/service/eveatmo-room-airquality.js

**Expected behavior:**

Was not a warning before, and home app reports the value in detail pane.

**Logs:**

HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.

**Screenshots:**

![IMG_AEC8DE3FD791-1](https://user-images.githubusercontent.com/19813688/80518147-61f09080-8986-11ea-9149-51285c892f4b.jpeg)
**Environment:**

* **Node.js Version**:  12.16.2
* **NPM Version**:  6.14.4
* **Operating System**:  Docker
* **Process Supervisor**:  hb-service

**Comment by Supereg** [comment]
The reason is it is indeed not a defined characteristic for the AirQuality sensor (at least it is not specified by the HAP specification). Nonetheless HomeKit may accept it anyways.

<img width="640" alt="Bildschirmfoto 2020-04-28 um 19 32 59" src="https://user-images.githubusercontent.com/9783857/80518666-138fc180-8987-11ea-8c5d-7765ceebf478.png">

**Comment by nicoduj** [comment]
@Supereg : That is what I thought, but was not sure. I asked the plugin developer to move it to a new service CarbonDioxideSensor.

https://github.com/skrollme/homebridge-eveatmo/issues/40

Thanks for the fast answer, and great work by the way ! Glad to do some plugins for this awesome platform :)

**Comment by Videonisse** [comment]
> The reason is it is indeed not a defined characteristic for the AirQuality sensor (at least it is not specified by the HAP specification). Nonetheless HomeKit may accept it anyways.
> 
> <img alt="Bildschirmfoto 2020-04-28 um 19 32 59" width="640" src="https://user-images.githubusercontent.com/9783857/80518666-138fc180-8987-11ea-8c5d-7765ceebf478.png">

@Supereg Regarding the documentation, I can see that your screen dump is from the pdf r2 of the non-commercial version of  HAP Spec. However, should the same info also be available in the online documentation? 

I have been searching the site but can't find details about the Services and required and optional characteristics. Maybe you know if I missed it or if Apple actually is hiding those details. Source: 
https://developer.apple.com/documentation/homekit

**Comment by oznu** [comment]
> However, should the same info also be available in the online documentation?

https://developers.homebridge.io/#/service/AirQualitySensor

**Comment by Videonisse** [comment]
> > However, should the same info also be available in the online documentation?
> 
> https://developers.homebridge.io/#/service/AirQualitySensor

This is a good example of why I ask the question. The above info on the Homebridge site does not match the information in Apple's pdf from 2019 (r2). But the Homebridge site (and code) does seem to match the settings in the most recent HomeKit Accessory Simulator in Xcode. But from where is this info taken?

Therefore, I would like to understand if this info about the Homekit API is officially available online. Or is it necessary to have access to the latest Commercial HAP Specs to find the updated info, or does actually someone manually review the latest HAP Simulator every time to find out if Apple updated the API?

**Comment by Videonisse** [comment]
Thanks, but can someone confirm if Apple actually doesn't provide this information also on their official developer portal for Homekit? 

Is it necessary to have access to the closed version of the Commercial Spec to get the latest updates of the Homekit API? Or are someone always reviewing the latest HAP Simulator to find out new settings and update Homebridge etc?
