### ISSUE TITLE
Version Characteristic has different perms in HomeKit than HomeKit-Bridge

### ISSUE THREAD

**Issue by ztalbot2000** [homebridge/HAP-NodeJS#822]
I do not know if this is a bug but they used to be the same.
HomeKit and HomeKit-Bridge both have the Characteristic "Version" and they used to be identical.  They still have identical UUID's for instance. However the perms are now different.
If you call Characteristic = homebridge.hap.Characteristic and then look at Characteristic.Version you no longer get what it used to be.
I do not know if this is an issue, but possibly a difference when changed over to typescript?

**Comment by Supereg** [comment]
wtf 😅 
I see, they are declared twice and only the one defined in HomeKit-Bridge is made accessible via Characteristic.Version 🤔 

Gonna check where this originated from and what the expected definition is according to the spec. Thanks for noticing.

**Comment by ztalbot2000** [comment]
Your Welcome. I've noticed the duplicate years ago and not an issue. Only
now they are different.

**Comment by Supereg** [comment]
One seemed to have been forgotten while the other one was updated, though it seems the updates never got reflected as the old one was still referenced 😅 at least my observation is that it seems like the HomeKit-Bridge one is the one getting written into the variable 🤔

**Comment by ztalbot2000** [comment]
Hi Andi,

The Bridge one is the one written/read to.  I had created a unit test
between my structure and yours and that is how I flagged it.

TTFN,
John

**Comment by ztalbot2000** [comment]
The HAP R2 Spec has it as paired-read only.

**Comment by Supereg** [comment]
Patch was applied to master. Will be released with the next release, as this is currently not a very urgent fix. Thanks for reporting.

**Comment by Supereg** [comment]
Change was now published as v0.7.4, finally 😅 honestly, forgot about it
