### ISSUE TITLE
HAP-NodeJS - Cannot find module 'node-persist' (error 638)

### ISSUE THREAD

**Issue by grucha532** [homebridge/HAP-NodeJS#825]
Hello guys,

I've trying everything for the past few days to run the HAP-NodeJS... I have even reinstalled the rasbian system so now I've just the system itself with HAP-NodeJS.

Does anyone has a clue how to solve this problem?
I'll appreciate any hint you could give me.

**Logs:**

```
pi@raspberrypi:~/HAP-NodeJS $ ls
accessories     CameraCore.js  index.js  LICENSE       README.md
BridgedCore.js  Core.js        lib       package.json
```
```
pi@raspberrypi:~/HAP-NodeJS $ sudo node Core.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node-persist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/HAP-NodeJS/Core.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
Besides, I've read that it can be anywhere but I have no _node_modules_ under the directory /usr/local/lib/node_modules/npm, so i cannot remove it and install again as written in many threads:
```
pi@raspberrypi:/usr/local/lib $ ls
pypy2.7  python2.7  python3.7
```
The node and npm are install in:
```
pi@raspberrypi:~ $ which npm
/usr/bin/npm
pi@raspberrypi:~ $ which node
/usr/bin/node
```

**Screenshots:**

I've also tried to install npm in the HAP-NodeJS directory as a solution in quite a few threads but didn't work as well.
![image](https://user-images.githubusercontent.com/64309335/82752689-1502ad00-9dc0-11ea-81f9-ff96cd6e3ab6.png)

**Environment:**
* **Node.js Version**:  v10.19.0
* **NPM Version**:  6.14.5
* **Operating System**: Raspbian

**Comment by Supereg** [comment]
npm install must run successfully, so all dependencies required for hap-nodejs to run get installed.
The output of the `npm install` command clearly states what the problem is. The user `pi` seems to not have permissions to access the folder `/home/pi/HAP-NodeJS`.
So update the permissions for the folder (using `chown` and/or `chmod`) or change to the user used previously cloning the repo.

**Comment by Supereg** [comment]
Closing the issue as it seems stale and now response from the originator was received.
