### ISSUE TITLE
How to get remote keys and volume to work with TV accessory

### ISSUE THREAD

**Issue by kkirby** [homebridge/HAP-NodeJS#826]
Hello,

I feel like I have to be doing something wrong. I've setup HAP-NodeJS on my machine and added the bridge to my HomeKit. When I go to control the example TV accessory I can only control the input and the power. I don't have any option to use an of the remote keys or control the volume. Am I missing anything? I'm running macOS Catalina and node 14.2.0. iOS 13.5

Thanks!

**Comment by Supereg** [comment]
The Remote does only appear in the Remote Tile in the Control Center of an iOS device (just like when you control an Apple TV).

**Comment by kkirby** [comment]
@Supereg Woah. That's it. Thank you!

**Comment by Supereg** [comment]
And volume is just controlled by pressing the volume buttons on your phone while having the remote for the TV open.

**Comment by mczac** [comment]
Remote support in HomeKit is very clunky, other option is to press and hold Apple TV and then select remote
