### ISSUE TITLE
Accessing video feeds with FFMPEG

### ISSUE THREAD

**Issue by dxdc** [homebridge/HAP-NodeJS#830]
**Describe Your Problem:**
If I run a command like this, accounting for the correct port# and pin#, I can see retrieve a list of all hb accessories:

```sh
curl -X PUT http://127.0.0.1:51826/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-154"
```

My question is, is it possible to use FFMPEG to retrieve a snapshot and/or 5 second video clip from cameras, and if so, what command line switches are needed?

This must be possible as HomeKit is doing it somehow when I click on live video feeds, but it's not clear what the correct RTSP link would be.

For each camera accessory, I can see these values listed (note: masked), but I have no idea how to use them. What I'd like to do is be able to retrieve a snapshot or 5s video clip and then upload to Google Drive, for example, so this is the first step.

```js
SupportedVideoStreamConfiguration: "xx"
SupportedAudioStreamConfiguration: "xx"
SupportedRTPConfiguration: "xx"
SelectedRTPStreamConfiguration: "xx"
StreamingStatus: "xx"
SetupEndpoints: "xx"
Active: 1
```

A related question: Is there a simple way to send an MP3 file to a Microphone as input? :)

**Logs:**

**Screenshots:**

**Environment:**

* **Node.js Version**: 10.12
* **NPM Version**: 6.14.5
* **Operating System**: Raspbian
* **Process Supervisor**: pm2

**Comment by Supereg** [comment]
HAP defines a `POST /resource HTTP/1.1` request to gather camera snapshots with the following json body

```json5
{
  "aid": number, // optional
  "resource-type": "image",
   "image-width": number,
  "image-height": number
}
```

I hope this is what you are searching for?

**Comment by dxdc** [comment]
Wow @Supereg this is great!! Do you know if there a similar way to send audio (e.g., to microphone, speaker), receive audio (to audio file), or receive video (to video file)?

This is how I did it so far:
```sh
curl --request POST http://127.0.0.1:51826/resource --header "Content-Type:Application/json" --header "authorization: 031-45-154" --data '{ "aid": 115, "resource-type": "image" }'  --output "snapshot.jpg"
```

**Comment by Supereg** [comment]
`image-width` and `image-height` are **required**. Though some plugins don't bother to check those and some plugins don't event respect those and will just return the snapshot in a predefined size.
This is not expected behavior and not including those could eventually break in the future.

> Do you know if there a similar way to send audio (e.g., to microphone, speaker), receive audio (to audio file), or receive video (to video file)?

Well you would need to go through the (S)RTP handshake process and act like a (S)RTP/(S)RTCP receiver (or sender if you want to use the audio backchannel). I would redirect you to go checkout the HAP specification (non-commercial) and reading through the IP Camera section.
