### ISSUE TITLE
Connect MotionEye cameras

### ISSUE THREAD

**Issue by xavi-burgos14** [homebridge/HAP-NodeJS#839]
**Describe Your Problem:**
I'm trying to connect my surveillance system to HomeKit, and I have the next address for the cameras: ```rtsp://192.168.1.15/user=xavi_password=<private>_channel=1_stream=0.sdp?real_stream```

I connected this addres to MotionEye and I have obtained the following address for this camera:
```http://192.168.1.55:8081/```

I was able to insall HAB-NodejS on my Raspberry Pi and is working fine, but I can't connect the camera to ```Camera_accessory.ts```. Do you know some easy way to connect cameras from MotionEye? Thanks a lot!

**Screenshots:**

![image](https://user-images.githubusercontent.com/59119435/89031960-da733e80-d333-11ea-890d-d9bafa59fe84.png)
![image](https://user-images.githubusercontent.com/59119435/89031817-86685a00-d333-11ea-9f02-293b7bf2d213.png)

**Environment:**

* **Node.js Version**: v14.7.0
* **NPM Version**: 6.14.7
* **Operating System**: Raspbian

**Comment by bdruth** [comment]
Are you using `homebridge` + `homebridge-camera-ffmpeg`?

**Comment by Supereg** [comment]
I think a better location to search for help is the homebridge discord or the homebridge subreddit (see [here](https://github.com/homebridge/homebridge#community)).

The issue section of HAP-NodeJS is not really suited for individual setup questions.
