### ISSUE TITLE
Smart Speaker Set TargetMediaState Loading Indicator

### ISSUE THREAD

**Issue by mcclurec** [homebridge/HAP-NodeJS#842]
**Describe Your Problem:**

I'm currently developing a plugin that exposes a Smart Speaker accessory. I'm running into the same issue mentioned by @supereg in his initial post in [PR 798](https://github.com/homebridge/HAP-NodeJS/pull/798) about the loading indicator sticking around after toggling from play to pause. Interestingly, The loading indicator doesn't show when toggling from pause to play. Did anyone ever figure out a way around this, or are we stuck until we can figure out the Airplay2 interaction?

Plugin code for reference
https://github.com/mcclurec/homebridge-volumio-speakers/blob/socket-api/src/platformAccessory.ts#L148-L162

Let me know if this issue should be kicked to another project instead of `HAP-NodeJS`.

**Environment:**

* **Node.js Version**: v12.18.3
* **NPM Version**: v6.14.6
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by Supereg** [comment]
There is now updated information on this to my knowledge. And as nobody replied I would assume there is indeed nothing new. Thus will close the issue for now.

**Comment by mcclurec** [comment]
@Supereg I poked around for any new info but didn't see anything that jumped out at me. Could you link any updated info here please?
