### ISSUE TITLE
Support Power Meter and other...

### ISSUE THREAD

**Issue by grzegorz914** [homebridge/HAP-NodeJS#843]
Hi,

any way to add this Characteristic and Services to HAP-NodeJS:
https://github.com/sprut666666/new-types-for-homekit/blob/master/hap.js 

thanks

**Comment by justme-1968** [comment]
just add them by uuid.

but: it is much better to use the eve versions: https://gist.github.com/gomfunkel/b1a046d729757120907c as they are better supported in eve.

**Comment by Supereg** [comment]
duplicates https://github.com/homebridge/HAP-NodeJS/issues/564

there is currently no intention to add any custom/third party service and characteristic definitions.
Just as the predefined characteristics (or services), you can create any custom characteristics (or services) you want and HAP-NodeJS will happily work with it.
