### ISSUE TITLE
Accessory shows "Not supported" instead of characteristic value

### ISSUE THREAD

**Issue by arpadsooky** [homebridge/HAP-NodeJS#844]
Hi, 
I have created a custom accessory (CurrentSensor) I have one Service: CurrentCheckSerive, and one characteristic: RunningState.

Based on the example code the accessory can be added to Home app, but the value of the RunningState is not displayed, but a "Not supported" labed is shown. Apparently I am missing something, but just don't know what.

Code is here below. Any help apprectiated.

Thank you

Node.js Version: v12.18.3
NPM Version: v6.14.6
Operating System: MacOS

****************************************
```js
const hap = require("hap-nodejs");

const Accessory = hap.Accessory;
const Characteristic = hap.Characteristic;
const CharacteristicEventTypes = hap.CharacteristicEventTypes;
const Service = hap.Service;
const Formats = hap.Formats
const Perms = hap.Perms

class RunningState extends Characteristic {

  constructor() {
    super('Current Sensor State', hap.uuid.generate("hap.homecontrol.current3"));
    this.setProps({
      format: Formats.BOOL,
      perms: [Perms.READ, Perms.NOTIFY]
    });
    this.value = false
    this.on(CharacteristicEventTypes.GET, (callback) => {
        console.log('get request')
        callback(null, true);
    })
  }
}
Characteristic.RunningState = RunningState;

class CurrentCheckService extends Service {

  constructor(displayName, subtype) {
    super(displayName, hap.uuid.generate("hap.homecontrol.current2"), subtype);
    this.addCharacteristic(Characteristic.RunningState);
  }
}
Service.CurrentCheckService = CurrentCheckService;

const accessoryUuid = hap.uuid.generate("hap.homecontrol.current1");
var accessory = new Accessory("CurrentSensor", accessoryUuid);

// Create service
var currentService = new Service.CurrentCheckService("CurrentServiceX");

accessory.addService(currentService);
// once everything is set up, we publish the accessory. Publish should always be the last step!
accessory.publish({
    username: "25:51:07:F4:BC:8A",
    pincode: "678-90-882",
    port: 47134,
    category: hap.Categories.OTHER, // value here defines the symbol shown in the pairing screen
});

console.log("Accessory setup finished : Other");
```

*********************
![IMG_1C560DE7B20F-1](https://user-images.githubusercontent.com/5219573/92328662-9c6be780-f062-11ea-8fd2-c855ba8610ca.jpeg)

**Comment by Supereg** [comment]
The Home App does only support Apple predefined services and characteristics. Something like the Eve Apps improves on that and gives limited control for custom characteristics.

In short: If you want to have something displayed in the Home App or want to control it with Siri, you have to use Apples predefined characteristics and services (which are already defined in HAP-NodeJS).
