### ISSUE TITLE
Homekit TELEVISION Accessory icon iPadOS 14

### ISSUE THREAD

**Issue by marcus-j-davies** [homebridge/HAP-NodeJS#846]
Hi Devs!

Just installed iPadOS 14 GM Seed.
Since doing so, the TV accessory icon has defaulted to the House Icon (as if the accessory is not supported).

The accessory its self however, still has all relevant services operating normally (Remote Key, Inputs, Volume etc etc).
I'm using the **TELEVISION** category. and the icon was correctly displayed prior to iPadOS 14.

Any Clues?

![IMG_8560](https://user-images.githubusercontent.com/55892693/93326658-0fb6eb80-f811-11ea-8e26-98fab702abe4.jpg)

![IMG_6451](https://user-images.githubusercontent.com/55892693/93326676-16456300-f811-11ea-878f-38ae25c84ced.jpg)

![IMG_2233](https://user-images.githubusercontent.com/55892693/93326707-28270600-f811-11ea-8af2-4c4187894a31.jpg)

**Comment by Supereg** [comment]
If I'm not wrong, we had that already in the iOS14 beta discussion.

Are you having your TVs behind a bridge?

**Comment by marcus-j-davies** [comment]
Yup.

They are bridged. I did look at that topic but couldn't see anything relating to the Television representation.

**Comment by marcus-j-davies** [comment]
So,

Have published the TV without it being bridged, and it renders correctly.
it all still worked when bridged apart from the icon.

Do you think it's worth having a list of Accessory Categories that can or can't be bridged? may be an entry on the wiki?

I suppose it depends if  this is intentional via HAP or is their code changes needed to correct this behaviour?

**Comment by Supereg** [comment]
Might have something to do with the fact, that TV now supports multiple icons https://twitter.com/herrsupereg/status/1306278447317123072?s=21

**Comment by Supereg** [comment]
https://twitter.com/herrsupereg/status/1306279252745166848?s=21

**Comment by Supereg** [comment]
> Do you think it's worth having a list of Accessory Categories that can or can't be bridged? may be an entry on the wiki?

TV is currently the only one afaik. Previously first TV worked bridged, only second or third one wouldn’t work with the Remote Control in the Control Center.

**Comment by marcus-j-davies** [comment]
Yup - that makes sense.

I guess the TV Services on i*OS will use the advertised Cat specifically (in this instance a bridge), instead of interrogating  the accessory(s) cat(s) behind it (which will be the said TV Service)

As you say, to-date it seems the TV Service  is the only one.
is it of any benefit to have some sort of blacklist that is checked on `addAccessory` and maybe spit out a warning if the cat is found?

We could see this more later.

**Comment by Supereg** [comment]
> instead of interrogating the accessory(s) cat(s) behind it 

Bridged accessories don‘t/can’t have an category assigned, only the „primary“/„main“ accessory. HAP-NodeJS doesn’t model that correctly.

**Comment by marcus-j-davies** [comment]
Ah I see,

I thought the icon was always based on the category.
I have a few devices that are bridged that show the correct icon, and thought its the cat that does this.

I guess not (with the exception of TV Accessory)

**Comment by marcus-j-davies** [comment]
I'm not sure if its worth keeping this live?

As it stands - Please correct me if I'm wrong :grimacing:

The icons are based on the Service (previously I thought it was the category) recently learnt this only ensures the paring icons are correct.

The TELEVISION service can, as of 13-14? be seen as a USB Stick, Set Top Box and of course a standard TV.
As these are all managed by the same service - iOS uses the category (instead of the service) to correctly display the icon.

now then, if a TV is behind a bridge (which of course is a category of BRIDGE) , it's using the standard icon.
it would have been nice for Apple to allow the icon to be selected.

Given that the service is identical, its a bit odd - although, they may have further plans.

**Comment by nicoduj** [comment]
@marcus-j-davies I have the same understanding . The only question I am still thinking of is to make the tv accessory defaults as external (even the first) so that it is not confusing . Would break existing conf however ... and during the beta like I said it handled it at one moment (using category also for the icon in this particular case). Tv accessory is kind of special ( or seen through api by other apps for example), so they might decide to handle it differently ... again .

Interested into opinions of users there in order to make a choice for default behavior

**Comment by marcus-j-davies** [comment]
This is my approach (which caters for future changes like this)

I have allowed (well after an upcoming update) accessories to be published bridged or non-bridged.
this allows already configured TV's to continue (albeit with the incorrect icon)

If users choose to publish non-bridged, they are shown the pair QR Code.
else it will appear automatically ( given they would have already paired up with the bridge)   

![Screenshot 2020-09-20 at 11 01 15](https://user-images.githubusercontent.com/55892693/93708769-d643f000-fb30-11ea-9249-6df8dde604cd.png)

**Comment by Supereg** [comment]
> The TELEVISION service can, as of 13-14? be seen as a USB Stick, Set Top Box and of course a standard TV.

Someone on twitter discovered that it can also show the Audio Receiver Icon. Wonder if there are any other icons that can be shown.

**Comment by marcus-j-davies** [comment]
I think the Audio Receiver does make sense.

TV, Set Top Box, USB Stick, Audio Receiver all share (to some degree) the same abilities.

- Multiple Input Sources (USB Stick i.e fire TV stick having different apps)
- Arrow Navigation, 
- Volume

Just a shame the icon can't be controlled by the user, in the same a SWITCH can.
