### ISSUE TITLE
Characteristic event listeners should infer callback type

### ISSUE THREAD

**Issue by bschlenk** [homebridge/HAP-NodeJS#848]
**Describe The Bug:**

When adding an event listener to a characteristic, the callback types are not automatically inferred.

```ts
const television = this.accessory.getService(Service.Television);

television
  .getCharacteristic(Characteristic.Active)
  // Parameter 'cb' implicitly has an 'any' type.(7006)
  .on('get', (cb) => { /* ... */ })
  // Parameter 'value' implicitly has an 'any' type.(7006)
  // Parameter 'cb' implicitly has an 'any' type.(7006)
  .on('set', (value, cb) => { /* ... */ });
```

**To Reproduce:**

I extracted the types into [this typescript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcgrgGwQQwEYIgHgCoD4oC8U2UAPlAHaIIDcAUHaJFAMLJKrIDGA1oVAAoAdCOQAnAOYBnAFxRkFEAG0AugEpC+AG4B7AJYATek2gwdBiGw7ceOfEQEQxYufCRoMmAKLOdY-ORwFBYAZnoUEAYANFAGyMDIAPxy2BoE2vpGjODQAGqZVgicvPyOzsmw1B5YPmJ+uGkZhsY5UAAKyHpi4dKFxbZ4pU4ulHAAtqhOMXEJFamaULrN2cxt3WN6wHpaENg5UvxSwN0UEmSjE07nqDo6GAotzADKEFJSejoUAJIWFFthVyIRxOEnodAgAA8wH5gFATKwABbibjAJx6I56Li5dhwaBENZ6DZbHZ7SAHcgEonbXb7VTnADeUCUPAgIDkwJ6KjklM21NJrygAF8wfCWEixCi0RiuABxCDAPo2HD8NwodBYMXIrio7rS7EIXG4eyCYZ+Cq1PznKhIKAxLQ4iBzRqLTIraCaiXaqVbLgvBXsIo2Ia+MTmkNW6h2h0VD2S3U+-W451LAwMSHQsSw0XiuPon2a054qD0uhQSgQADuiYgcljXvjmOr9DLdwM1drOfrecbDubUC4n1REOAFQUID7XE7Ou7XA7Wun0vowoY8K8Oz+ByIJbLk4UEhrgl3hbnnoX+aRheTmT7++AcgEXFQJ9z0rl-usvBiA7+kJHcjHX6fBE2ofN8AAiFQvG8oE-BAfx6ACYhXssZZSPK972gaB51mePZYV+T6IvO3qYn6iqfv2g6-qOiiARQwFbJ8XwQXIUHvExvz-HoTjIVkqFwKgUhcN0kxyPkhjkTwfZBFIAlCSJB7iQYklLmmUIwnCrRrnBwAANKsocxw9OcUggBMdz0OmGmruuwB2PwJAAGRQNpfz6eO4LqZmmnMK5wAALLIGA-CMkoFDIGMB4cqcXKsAG-RCmC4Q6iE3DQH5XhEjqyq-nBBgHH5gVgDEulQLlwQFbZmAsiAOghMQxp+dVrJ1Q1+DblAnyOLZci6TECB5nBTgpEounqHIwAIuiql0MlTipVw7pTiRXBlcOeWVTpmWbNlflSO1goMBgsJcAAhM+XaLgwXBCF1ADkaHAHdMQCJhuIEc69KCmoQA). 

**Expected behavior:**

Typescript should be able to infer the types automatically from the [Events](https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/Characteristic.ts#L103-L109) type.

**Logs:**

**Screenshots:**

**Environment:**

* **Node.js Version**: v14.8.0
* **NPM Version**: 6.14.7
* **Operating System**: macOS
* **Process Supervisor**: none

**Comment by bschlenk** [comment]
It looks like moving the `K extends Event<keyof T>` into the methods themselves fixes this. See [this typescript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcgrgGwQQwEYIgHgCoD4oC8U2UAPlAHaIIDcAUHaJFAMLJKrIDGA1oVAAoAdCOQAnAOYBnAFxRkFEAG0AugEpC+AG4B7AJYATek2gwdBiGw7ceOfEQEQxYufCRoMmAKLOdY-ORwFBYAZnoUEAYANFAGyMDIAPxy2BoE2vpGjODQAGqZVgicvPyOzsmw1B5YPmJ+uGkZhsY5UAAKyHpi4dKFxbZ4pU4ulHAAtqhOMXEJFamaULrN2cxt3WN6wHpaENg5UvxSwN0UEmSjE07nqDo6GAotzADKEFJSejoUAJIWFFthVyIRxOEnodAgAA8wH5gFATKwABbibjAJx6I56Li5dhwaBENZ6DZbHZ7SAHcgEonbXb7VTnADeUCUPAgIDkwJ6KjklM21NJrygAF8wfCWEixCi0RiuABxCDAPo2HD8NwodBYMXIrio7rS7EIXG4eyCYZ+Cq1PznKhIKAxLQ4iBzRqLTIraCaiXaqVbLgvBXsIo2Ia+MTmkNW6h2h0VD2S3U+-W451LAwMSHQsSw0XiuPon2a054qD0uhQSgQADuiYgcljXvjmOr9DLdwM1drOfrecbDubUC4n1REOAFQUID7XE7Ou7XA7Wun0vowoY8K8Oz+ByIJbLk4UEhrgl3hbnnoX+aRheTmT7++AcgEXFQJ9z0rl-usvBiA7+kJHcjHX6fBE2ofN8AAiFQvG8oE-BAfx6ACYhXssZZSPK972gaB51mePZYV+T6IvO3qYn6iqfv2g6-qOiiARQwFbJ8XwQXIUHvExvz-HoTjIVkqFwKgUhcN0kxyPkhjkTwfZBFIAlCSJB7iQYklLmmUIwnCrRrnBwB2PwJAAGRQBypz0OmGmruuwAALLIGA-CMkoFDIGMB4mRIXKsAG-RCmC4Q6iE3DQNpfxeESOrKr+cEGAcIU2XZ+DblAnyYAA0lAUXBLFVmYCyIA6CExBGo4VlyKlMQIHmcFOCkSipeocjAAi6KqXQ-lOIFXDulOJFcBlw7RdlOlhZsEVxVIiWCgwGCwlwACEz5douDBcEInwCAA5LeG0xA+qDOvSgpqKWa0UJtaHADtgiYbiBEHUd9BAA). 

The [EventEmitter](https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/EventEmitter.ts) class would be changed to something like this:

```ts
export type Event<T> = T & string;
export type EventMap = { [name: string]: Callback };

export class EventEmitter<T extends EventMap> extends BaseEventEmitter {
  // ...
  on<K extends Event<keyof T>>(event: K, listener: T[K]): this {
    return super.on(event, listener);
  }
```

I can send a PR if you want.

**Comment by Supereg** [comment]
no need for a PR. Next beta version will already fix that as we are moving away from the custom typed EventEmitter class.

**Comment by bschlenk** [comment]
Awesome, thank you! For now I'll continue to explicitly type the callback params. Looking forward for this making it into homebridge :)
