### ISSUE TITLE
Fix for correct tsc command working

### ISSUE THREAD

**Issue by reejinbouk** [homebridge/HAP-NodeJS#850]
Hello

**Describe The Bug:**
When I'm running "tsc homekits.ts" command, I've got error - error TS1192: Module '"http"' has no default export.

**To Reproduce:**
make any example, then run "tsc file.ts

**Expected behavior:**
get new file homekit.js

**Environment:**

* **Node.js Version**: v12.19.0
* **NPM Version**: 6.14.8
* **Operating System**: macOS
* **Process Supervisor**: launchctl 

To fix this error please change this at file ./dist/lib/util/eventedhttp.d.ts:

-- 3. import { Server **as HTTPServer**, IncomingMessage, OutgoingMessage, ServerResponse } from 'http';
-- 4. import { Server **as NetServer**, Socket } from 'net';
--65.    _tcpServer: **NetServer**;
-- 129.     _httpServer: **HTTPServer**;
 
After fixing it tsc command works correctly.

**Comment by Supereg** [comment]
Could quickly elaborate on your project setup up please? is hap-nodejs installed as a dependency?
Do you have the appropriate @types/node installed in your project?
What version of the typescript compiler are you running?

**Comment by Supereg** [comment]
Will close the issue for now, as OP didn't respond and I can't reproduce the issue on my side.
