### ISSUE TITLE
Stateless Programmable Switch Service order random

### ISSUE THREAD

**Issue by StefanNienhuis** [homebridge/HAP-NodeJS#851]
**Describe The Bug:**
When creating an accessory with multiple Stateless Programmable Switch services (displayed as multiple buttons in the Home app), the order of those buttons is random. The Home app also doesn't show the name of the buttons, which is a Home app issue, but it does cause it to be impossible to see which button you should use without trial and error.

**To Reproduce:**
Create an accessory with multiple Stateless Programmable Switch services

**Expected behavior:**
For the services to appear in the correct order.

**Logs:**
No errors or other logs

**Screenshots:**
Not necessary 

**Environment:**

* **Node.js Version**: v14.7.0
* **NPM Version**: 6.14.7
* **Operating System**: macOS
* **Process Supervisor**: none

**Comment by ebaauw** [comment]
Use the _LabelIndex_ characteristic to set the order.

**Comment by StefanNienhuis** [comment]
@ebaauw thanks for the suggestion. I tried it in Homebridge, but it didn't work. I tried `service.setCharacteristic(this.hap.Characteristic.ServiceLabelIndex, index)`, `service.getCharacteristic(...).setValue(index)` and `service.getCharacteristic(...).setProps({ minValue: index, maxValue: index })`. Index is 1, 2 or 3.

Is there additional setup that needs to be done for this to work?

**Comment by ebaauw** [comment]
Did you expose a _ServiceLabel_ service (with _ServiceLabelNameSpace_) next to the _StatelessProgrammableSwitch_ services?  You need to expose _ServiceLabelIndex_ on each _StatelessProgrammableSwitch_ service.  I think their values need to be consecutive, starting at 1.

**Comment by StefanNienhuis** [comment]
Oh never mind, I forgot to recompile the Typescript code. Whoops😅

Thanks a lot for your help.
