### ISSUE TITLE
Valve service missing pre-defined timer values

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#857]
Since the release of iOS 14, a valve service not longer displays a full list of runtime values to select other than 5 or 10mins Is there a way to pre-populate the list now??

iOS 14:

![](https://user-images.githubusercontent.com/19759130/87887189-461cf800-ca66-11ea-938c-3f898647c1b3.jpeg)

iOS 13:

![](https://user-images.githubusercontent.com/19759130/87887210-6d73c500-ca66-11ea-863e-cde093b6493c.png)

**Comment by Supereg** [comment]
Played with it a bit. Couldn't find a way to show more than 5 and 10 entries.
My certified Eve Water has the same "problem". Thus I think this is not an issue with HAP-NodeJS. Even the HomeKit simulator has the same issue.

**Comment by Supereg** [comment]
The Eve app still allows you to set more detailed durations. And then Home app will also show it to you.

**Comment by n0rt0nthec4t** [comment]
FYI.. In iOS 15 beta 2 and macOS 12 beta 2, the runtime values are back!!

<img width="516" alt="Screen Shot 2021-07-07 at 11 13 17 am" src="https://user-images.githubusercontent.com/19759130/124685367-7d551500-df14-11eb-8a84-29e3ec7177a0.png">
