### ISSUE TITLE
CurrentTemperature characteristic don't accept negatives values

### ISSUE THREAD

**Issue by alexplak** [homebridge/HAP-NodeJS#858]
**Describe The Bug:**
If "result" has negative value (for example -5) accessory in Home app return error "Don't responce"

_function (result: any) {
          hkAccessory.getService(Service.TemperatureSensor)!.updateCharacteristic(Characteristic.CurrentTemperature, result);
        }_

**To Reproduce:**
_hkAccessory.getService(Service.TemperatureSensor)!.updateCharacteristic(Characteristic.CurrentTemperature, -5);_

**Expected behavior:**
Expected negative current temperature value in Home app.

**Screenshots:**
<img width="375" alt="Снимок экрана 2020—11—17 в 23 54 37" src="https://user-images.githubusercontent.com/70775221/99447839-5ff51b80-2930-11eb-88bf-64d70b1f565e.png">

**Environment:**
* **Node.js Version**: v12.18.4
* **NPM Version**: 6.14.6
* **Operating System**: Debian
* **Process Supervisor**: Systemd

**Comment by NorthernMan54** [comment]
If you search thru closed issues this has been answered numerous times

ie #147

**Comment by alexplak** [comment]
> If you search thru closed issues this has been answered numerous times
> 
> ie #147

Thank you for your reply.
