### ISSUE TITLE
LockMechanismLastKnownAction additional state

### ISSUE THREAD

**Issue by ztalbot2000** [homebridge/HAP-NodeJS#859]
**Describe The Bug:**

HomeKit defines the characteristic of LockLastKnownAction as:
```objective-c
typedef NS_ENUM(NSInteger, HMCharacteristicValueLockMechanismLastKnownAction) {
    HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementInterior = 0,
    HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovementInterior,
    HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovementExterior,
    HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovementExterior,
    HMCharacteristicValueLockMechanismLastKnownActionSecuredWithKeypad,
    HMCharacteristicValueLockMechanismLastKnownActionUnsecuredWithKeypad,
    HMCharacteristicValueLockMechanismLastKnownActionSecuredRemotely,
    HMCharacteristicValueLockMechanismLastKnownActionUnsecuredRemotely,
    HMCharacteristicValueLockMechanismLastKnownActionSecuredWithAutomaticSecureTimeout,
    HMCharacteristicValueLockMechanismLastKnownActionSecuredUsingPhysicalMovement,
    HMCharacteristicValueLockMechanismLastKnownActionUnsecuredUsingPhysicalMovement,
} API_AVAILABLE(ios(8.0), watchos(2.0), tvos(10.0), macCatalyst(14.0)) API_UNAVAILABLE(macOS);
```
It seems they added the last two where the lock can be secured/unsecured via a motion sensor.

**To Reproduce:**

**Expected behavior:**

**Logs:**

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by Supereg** [comment]
I don't think this has to something to do with motion sensors. Judging by the naming of the first four entries, this is basically the same just without specifying interior or exterior. This isn't yet mentioned in any spec of the HomeKit protocol itself. Even some of the metadata files found in homed doesn't specify a maxValue bigger than `8`.
I'm not entirely sure if we should add that to HAP-NodeJS.
In any case you can always manually overwrite the maxValue of a Characteristic if you want to use it.

**Comment by Supereg** [comment]
Changed by mind. Just added two new predefined valid values for `LockLastKnownAction`:
`SECURED_PHYSICALLY` and `UNSECURED_PHYSICALLY`.

**Comment by mgoeller** [comment]
Is this characteristic displayed somewhat in the Home App for a Lock accessory?

**Comment by ztalbot2000** [comment]
Hi,

Just to let you know I got your message.

There are just so many characteristics and accessories I'm not always sure
right away.  I'll have to create one to test it and let you know.

Bbl,
John

**Comment by ztalbot2000** [comment]
Hi,

So LockLastKnownAction is an Optional type of the accessory type
LockManagement. It is not part of any other accessory.
LockLastKnownAction does have the possible values of
validValues:
                   "UNSECURED_PHYSICALLY_INTERIOR",
                   "SECURED_PHYSICALLY_EXTERIOR",
                   "UNSECURED_PHYSICALLY_EXTERIOR",
                    "SECURED_BY_KEYPAD",
                    "UNSECURED_BY_KEYPAD",
                    "SECURED_REMOTELY",
                    "UNSECURED_REMOTELY",
                    "SECURED_BY_AUTO_SECURE_TIMEOUT",
                    "SECURED_PHYSICALLY",
                    "UNSECURED_PHYSICALLY"

This device type also has a required characteristic of LockControlPoint of
type TLV8 (Array of bytes). I will not be able to help you with this part
at all. That is not what your asking though.

I did create an accessory of the type LockManagement in Cmd4.

"accessories": [
                {
                    "type": "LockManagement",
                    "Cmd4_Mode": "Demo",
                    "category": "ALARM_SYSTEM",
                    "name": "LockManagement",
                    "Version": "1.0",
                    "CurrentDoorState": 0,
                    "LockLastKnownAction": "SECURED_PHYSICALLY"
                }
            ]

Unfortunately this is what the Home App thought of it


 don't know what Eve would think about the accessory. You would have to
try.  The fact though that a required characteristic is TLV8 is a big tip
off to me that this is something more for a standalone App.

I hope this helps you.  Sorry it is not the answer you were probably hoping
for.


John
