### ISSUE TITLE
HAP-NodeJS as a library with multiple accessory

### ISSUE THREAD

**Issue by ivale** [homebridge/HAP-NodeJS#860]
I am trying to use the new HAP-NodeJS as a library but I don't understand how to run multiple accessory at the same time.
How do I need to set package.json file ?

Thanks 👍

**Comment by Supereg** [comment]
Not sure where you are at with your code right now. But you will need to create a `Bridge` Accessory where you then can add multiple bridged `Accessory` instances.

**Comment by ivale** [comment]
I was trying to understand the HapNodeJs LightBulb example. To have more accessories now I am running multiple js script with random ports and it works but its laborious. 

Can you share an example of a Bridge Accessory running multiple accessory instances pls?

**Comment by marcus-j-davies** [comment]
Instantiating multiple accessories, to be served by a bridge is as follows.

Create your bridge accessory (with a category of BRIDGE), and set the `_isBridge` property to true.
making sure to provide the other bits as necessary (PIN, Username etc etc)

`const MyBridge = new Accessory('My Bridge', uuid.generate('My Bridge'));`
`MyBridge._isBridge = true;`

Then create your various (other) accessories, again taking care of required properties.
for each accessory you create here - add it to the bridge.

`MyBridge.addBridgedAccessory(light_1_accessory);`

When it comes to publish time, you don't publish the individual accessories, but the bridge itself, all accessories attached to it, will be added to Homekit when you enroll your bridge on your device.

```
/* Random port assigned by hap-nodejs */
const CFG = {
  username: MyBridge.username,
  pincode: MyBridge.pincode,
  category: MyBridge.category,
  setupID: MyBridge.setupID
}

MyBridge.publish(CFG)
```

**Comment by Supereg** [comment]
Instead manually setting `_isBridge` which is private API, please use the `Bridge` class directly 

instead of 
> `const MyBridge = new Accessory('My Bridge', uuid.generate('My Bridge'));`
> `MyBridge._isBridge = true;`

use 
```ts
const MyBridge = new Bridge('My Bridge', uuid.generate('My Bridge'));
```

**Comment by marcus-j-davies** [comment]
> Instead manually setting `_isBridge` which is private API, please use the `Bridge` class directly
> 
> instead of
> 
> > `const MyBridge = new Accessory('My Bridge', uuid.generate('My Bridge'));`
> > `MyBridge._isBridge = true;`
> 
> use
> 
> ```ts
> const MyBridge = new Bridge('My Bridge', uuid.generate('My Bridge'));
> ```

Good shout!
I have tendancy to do things as transparent as possible.

**Comment by ivale** [comment]
> Instantiating multiple accessories, to be served by a bridge is as follows.
> 
> Create your bridge accessory (with a category of BRIDGE), and set the `_isBridge` property to true.
> making sure to provide the other bits as necessary (PIN, Username etc etc)
> 
> `const MyBridge = new Accessory('My Bridge', uuid.generate('My Bridge'));`
> `MyBridge._isBridge = true;`
> 
> Then create your various (other) accessories, again taking care of required properties.
> for each accessory you create here - add it to the bridge.
> 
> `MyBridge.addBridgedAccessory(light_1_accessory);`
> 
> When it comes to publish time, you don't publish the individual accessories, but the bridge itself, all accessories attached to it, will be added to Homekit when you enroll your bridge on your device.
> 
> ```
> /* Random port assigned by hap-nodejs */
> const CFG = {
>   username: MyBridge.username,
>   pincode: MyBridge.pincode,
>   category: MyBridge.category,
>   setupID: MyBridge.setupID
> }
> 
> MyBridge.publish(CFG)
> ```

my bridge looks like this 

```
const hap = require("hap-nodejs");

const Accessory = hap.Accessory;
const Characteristic = hap.Characteristic;
const CharacteristicEventTypes = hap.CharacteristicEventTypes;
const Service = hap.Service;

const path = require('path');

const myBridge = new Accessory('My Bridge', hap.uuid.generate('My Bridge'));
myBridge._isBridge = true;

var dir = path.join(__dirname, "accessories");
var accessories = hap.AccessoryLoader.loadDirectory(dir);
accessories.forEach(function (accessory) {
  myBridge.addBridgedAccessory(accessory);
});

myBridge.publish({
  username: "CC:22:3D:E3:CE:F6",
  port: 51826,
  pincode: "031-45-154",
  category: 2 /* BRIDGE */
});
```
and seems working but when I run it gives me back _Invalid accessory!_ error.
If I run the single accessories they works, if I run the bridge without accessories it works.
What do I need to set in the accessory to be validated from the bridge??

**Comment by marcus-j-davies** [comment]
2 optimisations.

Don't pick up on my bad habits.

Use the `Bridge` class, as Supereg has mentioned

Use 
`const MyBridge = new Bridge('My Bridge', hap.uuid.generate('My Bridge')); `

instead of 
```
const MyBridge = new Accessory('My Bridge', uuid.generate('My Bridge'));
MyBridge._isBridge = true;
```

get rid of `port` in your publish, hap-nodejs will auto assign a free port.

can you provide one of your accessories?

**Comment by ivale** [comment]
Corrected bridge script :)

I tried with a thermostat accessory

```
const hap = require("hap-nodejs");

const Accessory = hap.Accessory;
const Characteristic = hap.Characteristic;
const CharacteristicEventTypes = hap.CharacteristicEventTypes;
const Service = hap.Service;


const accessoryUuid = hap.uuid.generate("ThermostatExample");
const accessory = new Accessory("ThermostatExample", accessoryUuid);

const thermostatService = new Service.Thermostat("Thermostat Example");

let currentHeatingCoolingState = 3;
let targetHeatingCoolingState = 3;
let currentTemperature = 10;
let targetTemperature = 10;
let temperatureDisplayUnit = 0;
let heatingThresholdTemperature = 3;

const heatingCoolingState_Characteristic          = thermostatService.getCharacteristic(Characteristic.CurrentHeatingCoolingState);
const targetHeatingCoolingState_Characteristic    = thermostatService.getCharacteristic(Characteristic.TargetHeatingCoolingState);
const currentTemperature_Characteristic           = thermostatService.getCharacteristic(Characteristic.CurrentTemperature);
const targetTemperature_Characteristic            = thermostatService.getCharacteristic(Characteristic.TargetTemperature);
const temperatureDisplayUnits_Characteristic      = thermostatService.getCharacteristic(Characteristic.TemperatureDisplayUnits);



var mqtt = require('mqtt');
var client  = mqtt.connect('mqtt://192.168.0.154');

client.on('connect', function () {
  client.subscribe('valerio/bmpTemperature', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt');
    }
  })
})


//
//        Characteristic
//


// 1 heatingCoolingState_Characteristic
heatingCoolingState_Characteristic.on(CharacteristicEventTypes.GET, callback => {
  callback(undefined, currentHeatingCoolingState);
});
heatingCoolingState_Characteristic.on(CharacteristicEventTypes.SET, (value, callback) => {
  // console.log("heatingCoolingState set to " + currentHeatingCoolingState);
  currentHeatingCoolingState = value;
  callback();
});

// 2  targetHeatingCoolingState_Characteristic
targetHeatingCoolingState_Characteristic.on(CharacteristicEventTypes.GET, callback => {
  callback(undefined, targetHeatingCoolingState);
});
targetHeatingCoolingState_Characteristic.on(CharacteristicEventTypes.SET, (value, callback) => {
  // console.log("targetHeatingCoolingState set to " + targetHeatingCoolingState);
  targetHeatingCoolingState = value;
  callback();
});

// 3 currentTemperature_Characteristic
currentTemperature_Characteristic.on(CharacteristicEventTypes.GET, callback => {
  callback(undefined, currentTemperature);
});
currentTemperature_Characteristic.on(CharacteristicEventTypes.SET, (value, callback) => {
  currentTemperature = value;
  callback();
});

// 4  targetTemperature_Characteristic
targetTemperature_Characteristic.on(CharacteristicEventTypes.GET, callback => {
  callback(undefined, targetTemperature);
});
targetTemperature_Characteristic.on(CharacteristicEventTypes.SET, (value, callback) => {
  targetTemperature = value;
  console.log("Target Temperature set to " + targetTemperature);
  callback();
});

// 5  temperatureDisplayUnits_Characteristic
temperatureDisplayUnits_Characteristic.on(CharacteristicEventTypes.GET, callback => {
  callback(undefined, temperatureDisplayUnit);
});
temperatureDisplayUnits_Characteristic.on(CharacteristicEventTypes.SET, (value, callback) => {
  temperatureDisplayUnit = 1;
  callback();
});

//
//---------------------------
//

client.on('message', function (topic, message) { currentTemperature = Number(message);})

accessory.addService(thermostatService);

// once everything is set up, we publish the accessory. Publish should always be the last step!
accessory.publish({
  username: "17:51:57:F4:9C:8A",
  pincode: "678-90-876",
  // port: 47129,
  category: hap.Categories.THERMOSTAT, // value here defines the symbol shown in the pairing screen
});

console.log("Accessory setup finished!");
```

and with the standard light example. Both gives me back _Invalid accessory!_

**Comment by marcus-j-davies** [comment]
I can't lend much help with the loader its self as I don't use it.
but the error is not specific to the Bridge - its from  the  AccessoryLoader module.

```
 return accessories.map((accessory) => {
    if(accessory === null || accessory === undefined) { //check if accessory is not empty
      console.log("Invalid accessory!");
      return false;
    } else {
      return (accessory instanceof Accessory) ? accessory : parseAccessoryJSON(accessory);
    }
  }).filter((accessory: Accessory | false) => { return accessory ? true : false; }) as Accessory[];
}
```

Try and create you accessory and bridge (only publishing the publish) in one source file.
the bridge should have no problem  - again the error is specific to the loader.

**Comment by marcus-j-davies** [comment]
I have taken the liberty of prototyping an example thermostat accessory for bridging.
I rushed this example - so don't hold me accountable :stuck_out_tongue_closed_eyes:

**MyThermostat.js**
```
'use strict'
const HapNodeJS = require("hap-nodejs");
const Service = HapNodeJS.Service;
const Accessory = HapNodeJS.Accessory;
const Characteristic = HapNodeJS.Characteristic;
const uuid = HapNodeJS.uuid;
const CharacteristicEventTypes = HapNodeJS.CharacteristicEventTypes;
const AccessoryEventTypes = HapNodeJS.AccessoryEventTypes;
const Catagories = HapNodeJS.Categories;

class MyThermostat 
{
    constructor(DisplayName, Username)
    {
        /* Create the Accessory */
        const UUID = uuid.generate('hap-nodejs:accessories:'+ DisplayName+':'+Username);
        this._accessory = new Accessory(DisplayName, UUID);
        this._accessory.category = Catagories.THERMOSTAT;
        this._accessory.username = Username;

        /* Custom metadata */
        this._accessory.getService(Service.AccessoryInformation)
        .setCharacteristic(Characteristic.SerialNumber, "SN1234567")
        .setCharacteristic(Characteristic.Manufacturer, "Me Enterprises")
        .setCharacteristic(Characteristic.FirmwareRevision,"1.0")
        .setCharacteristic(Characteristic.Name, DisplayName )

        /* Create the thermostat service */
        this._service = new Service.Thermostat(DisplayName,DisplayName);

        /* attach the set event for TargetTemperature - allowing you to react */
        this._service.getCharacteristic(Characteristic.TargetTemperature)
        .on(CharacteristicEventTypes.SET,(value, callback) => {...});

        /* add the service to the accessory */
        this._accessory.addService(this._service);

    }
      
}

/* Create the getAccessory() method so we can pass it to the addBridgedAccessory() method of the bridge */
MyThermostat.prototype.getAccessory = function()
{
  return this._accessory;
};

/* export MyThermostat class with a name of ThermostatAccessory */
module.exports = {
    ThermostatAccessory:MyThermostat
}
```

**Bridge.js**
```
'use strict'
const HapNodeJS = require("hap-nodejs");
const Service = HapNodeJS.Service;
const Accessory = HapNodeJS.Accessory;
const Characteristic = HapNodeJS.Characteristic;
const uuid = HapNodeJS.uuid;
const CharacteristicEventTypes = HapNodeJS.CharacteristicEventTypes;
const AccessoryEventTypes = HapNodeJS.AccessoryEventTypes;
const Catagories = HapNodeJS.Categories;
const MyThermostat = require("./MyThermostat");


const MyBridge = new Bridge('My Bridge', uuid.generate('My Bridge'));
const MyThermostat = new MyThermostat.ThermostatAccessory('My Thermostat','XX:XX:XX:XX:XX:XX');

MyBridge.addBridgedAccessory(MyThermostat.getAccessory())

MyBridge.publish()
```

**Comment by shadowtsw** [comment]
Hey there....
I´m interested in developing with HAP-NodeJS and after some research in this repo I have read this topic.

Of course, I´ve tried the example @ "Beginners guide" and it´s quite easy. But is there any further documentation about, e.g. setting up a bridge, different accessories and services, parameters ?

In HomeKit.ts I found the required characteristics for the services, but where I can find the corresponding required parameters for a bridge ?

Thx and best regards :)

**Comment by marcus-j-davies** [comment]
Hey!

> e.g. setting up a bridge

There isn't a lot that a bridge its-self requires. looking at my example above, **Bridge.js**, it should provide most of the functionality - if not, all. - Note : I haven't actually tested my example, it was a quick write up.

You can customise its meta-data by getting a handle on the Accessory Information Service (that all accessories will have)

```
MyBridge.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.SerialNumber, "HJDYHHDUD")
MyBridge.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.Manufacturer, "Marcus Davies")
MyBridge.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.FirmwareRevision,"10.0")
MyBridge.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.Name, 'My Super Bridge' )
```
A bridge is just a special type  of Accessory, but its like a 'bear-metal' accessory, the functionality comes from the accessories hosted on it,

For each accessory that you create, add it to the bridge.
`MyBridge.addBridgedAccessory(MyAccessory)`

Then once all added - ask the bridge to advertise itself on the network.
`MyBridge.publish({ username: "XX:XX:XX:XX:XX", pincode:"123-45-678", category: Catagories.BRIDGE, setupID:"HD893" })`

The bridge should show up when adding a device in Home app - once you enrol the bridge, the accessories will show also, on your device.

**Comment by shadowtsw** [comment]
Many thanks for your fast reply.

I´ve already tested a simple setup and works fine with a switch and a bulb. And thx for the given information about the service details. Now I can develop my application with more details :D

One more question, off-topic, but just for my better understanding: where are the issued devices initialised after reboot ? I´ve seen there is a persist storage with the details, but how will be approved if the device already exists or needs to be issued ?

**Comment by marcus-j-davies** [comment]
>  I´ve seen there is a persist storage

you can actually change the location to better suite your needs - I actually do this myself [Here](https://github.com/marcus-j-davies/Homekit-Device-Stack/blob/68adfa130d4bf601c6dd5bdcc1aea048248de9fe/core/accessory.js#L39)
`HapNodeJS.HAPStorage.setCustomStoragePath("/path/to desired cache folder");`

I believe this is to store the client associations - I could be wrong (i.e your bridge won't advertise its self, once its enrolled)
as the enrolled clients will already know of its where abouts, the cache helps with telling iOS devices
'Hey - you already know about me' after a reboot.

if you delete the cache, the bridge will advertise its self again, the same happens if you Remove the bridge on device.
The cache folder is what helps glue your devices with  your accessory's 

providing your accessory identifier information don't change between reboots (and the cache is in tact) it will "just work"

**Comment by shadowtsw** [comment]
Ok, I ask because I wanna know more about the code structure and actually I have no time to read all the files in detail :D
But I will explore, for sure.

Is there any intention to issue a more detailed Wiki page ?

**Comment by marcus-j-davies** [comment]
the devs are already working in it.

[Here](https://developers.homebridge.io/HAP-NodeJS/modules.html)

**Comment by shadowtsw** [comment]
really nice :) exactly what I´m looking for

**Comment by shadowtsw** [comment]
Ok, last question for today, I promise :D

I´ve tested around, everything works great and really fast (I expected more lags or higher latency).

I want to reuse code and especially the "onCharacteristic.on(xx.GET....){}" & "onCharacteristic.on(xx.SET....){}" Services which are added to the responsive accessory at the end. Is there an implemented possibility to identify, which device triggers the SET or GET event ? Then I´m able to write templates which can be used by all other accessories from the same type ?

**Comment by marcus-j-davies** [comment]
You can identify that A device triggered the SET, I'm not sure if you can identify what Actual device though, I could be wrong @Supereg ?

The signature for the SET event is

`(value: CharacteristicValue, callback: CharacteristicSetCallback, context: any, connection?: HAPConnection)`

If **connection** is not null, then it was an iOS device that triggered SET as apposed to your own code.

**Comment by shadowtsw** [comment]
No, I didn´t mean the IOS device :)

Thx for your effort and advice.

I just want to write a template, which can be used not depending on number of switches....
My goal was to auto-generate accessories via interface/userinput for example, or just by define the number of accessories. Actually I have a object/map holding each accessory with related state. Also its customizable... works well....

**Comment by marcus-j-davies** [comment]
You should be able to create a common Set/Get function.
and call it from the associated event

```
.on(CharacteristicEventTypes.SET,(value, callback) => MySetFunction(Value,callback, AccessoryInstance));
.on(CharacteristicEventTypes.GET,(callback) => MyGetFunction(callback, AccessoryInstance));
```

Your common functions can then respond accordingly and alter their behaviour based on `AccessoryInstance` that you pass to it.

**Comment by shadowtsw** [comment]
My solution looks a bit differently:

Instead of issuing new SET/GET functions,
I use a loop which inside 
- issues the Service
- calls getCharacterisitic
- sets the event types with associated accessory name
- adds the service to its accessory

The loop iterates to its accessories, so I just need to add a name(key) to the object. Everything else is a reusable snippet of code ^^
I guess in long term I will optimise this process, but for developing it is fine.

**Comment by shadowtsw** [comment]
Many ways to reach the goal, thx ;)
