### ISSUE TITLE
Why AccessoryLoader doesn't load accessories?

### ISSUE THREAD

**Issue by alexplak** [homebridge/HAP-NodeJS#861]
I'm trying to make own bridge while using HAP-nodejs as a library, but array with accessories after AccessoryLoader.loadDirectory(dir) always empty:

```ts
import { AccessoryLoader } from 'hap-nodejs';

console.log("HomeKit Accessory Service starting...");
var targetPort = 51826;
var dir = "/HAP-NodeJS-custom/src/accessories"
var accessories = AccessoryLoader.loadDirectory(dir); 

accessories.forEach((accessory) => {

    // To push Accessories separately, we'll need a few extra properties
    // @ts-ignore
    if (!accessory.username)
      throw new Error("Username not found on accessory '" + accessory.displayName +
                      "'. Core.js requires all accessories to define a unique 'username' property.");
  
    // @ts-ignore
    if (!accessory.pincode)
      throw new Error("Pincode not found on accessory '" + accessory.displayName +
                      "'. Core.js requires all accessories to define a 'pincode' property.");
  
    // publish this Accessory on the local network
    accessory.publish({
      port: targetPort++,
      // @ts-ignore
      username: accessory.username,
      // @ts-ignore
      pincode: accessory.pincode,
      // @ts-ignore
      category: accessory.category
    });
});
```

When I start accessory directly with "ts-node --files src/accessories/Temperature_accessory.ts" it runs successfully.

**Environment:**

* **Node.js Version**: v14.3.0
* **NPM Version**: 6.14.8
* **Operating System**: MacOS

**Comment by Supereg** [comment]
Looking at the code is `/HAP-NodeJS-custom/src/accessories` really the place where you place your accessory files? 
I would suspect they are located inside `HAP-NodeJS-custom/src/accessories` (not the missing slash at the beginning, makes a huge difference).

**Comment by alexplak** [comment]
> Looking at the code is `/HAP-NodeJS-custom/src/accessories` really the place where you place your accessory files?
> I would suspect they are located inside `HAP-NodeJS-custom/src/accessories` (not the missing slash at the beginning, makes a huge difference).

That is my mistake. Change to full path
`var dir = "/Users/*********/Диск Google/Visual Studio Code/HAP-NodeJS-custom/src/accessories";
`

Terminal log:
`
> Executing task in folder HAP-NodeJS-custom: npm run start2 <


> hap-nodejs-custom@0.0.1 start2 /Users/a.plakidin/Диск Google/Visual Studio Code/HAP-NodeJS-custom
> ts-node --files src/main.ts

HomeKit Accessory Service starting...
Invalid accessory!
lug001-ctr01-lib | Климатический датчик | Температура: -0.12
lug001-ctr01-lib | Климатический датчик | Влажность: 80.51
lug001-ctr01-lib | Климатический датчик | Температура: -0.12
lug001-ctr01-lib | Климатический датчик | Влажность: 80.51
lug001-ctr01-lib | Климатический датчик | Температура: -0.12
lug001-ctr01-lib | Климатический датчик | Влажность: 80.52
lug001-ctr01-lib | Климатический датчик | Температура: -0.10
lug001-ctr01-lib | Климатический датчик | Влажность: 80.51
lug001-ctr01-lib | Климатический датчик | Температура: -0.12`

**Comment by alexplak** [comment]
> Looking at the code is `/HAP-NodeJS-custom/src/accessories` really the place where you place your accessory files?
> I would suspect they are located inside `HAP-NodeJS-custom/src/accessories` (not the missing slash at the beginning, makes a huge difference).

That is my mistake. Change to full path
`var dir = "/Users/*********/Диск Google/Visual Studio Code/HAP-NodeJS-custom/src/accessories";`

Terminal log:

`

Executing task in folder HAP-NodeJS-custom: npm run start2 <
hap-nodejs-custom@0.0.1 start2 /Users/*********/Диск Google/Visual Studio Code/HAP-NodeJS-custom
ts-node --files src/main.ts
HomeKit Accessory Service starting...
Invalid accessory!
lug001-ctr01-lib | Климатический датчик | Температура: -0.12
lug001-ctr01-lib | Климатический датчик | Влажность: 80.51
lug001-ctr01-lib | Климатический датчик | Температура: -0.12
lug001-ctr01-lib | Климатический датчик | Влажность: 80.51
lug001-ctr01-lib | Климатический датчик | Температура: -0.12
lug001-ctr01-lib | Климатический датчик | Влажность: 80.52
lug001-ctr01-lib | Климатический датчик | Температура: -0.10
lug001-ctr01-lib | Климатический датчик | Влажность: 80.51
lug001-ctr01-lib | Климатический датчик | Температура: -0.12`

**Comment by Supereg** [comment]
`Invalid accessory!` is being printed by the AccessoryLoader.

See https://github.com/homebridge/HAP-NodeJS/blob/eab77bfecde1813c136b3732a1989f03c54f65e4/src/lib/AccessoryLoader.ts#L49-L56

I know the message isn't really helpful, as the code for the AccessoryLoader is already pretty ancient. 
If I may ask, why do you use the AccessoryLoader. As you are under full control, you can just expose the created `Accessory` objects yourself. There isn't really any necessity to use AccessoryLoader, this was only really used for the old style APIs.

In any case, this means that the AccessoryLoader could successfully find your directory, but there is something wrong with the accessory code itself.

**Comment by alexplak** [comment]
Yes, I traced this issue to AccessoryLoader.ts and I couldn't understand what is wrong. Otherwise if I use my Temperature_accessory.ts with HAP-NodeJS not as the library my accessory is loaded with no problem with Core.ts.
I started use AccessoryLoader cos I tried to make own loader (main.ts) for several accessories in my project. I saw this method in Core.ts. If this way is wrong could you advise how to load several accessories in my case?

**Comment by alexplak** [comment]
> `Invalid accessory!` is being printed by the AccessoryLoader.
> 
> See
> 
> https://github.com/homebridge/HAP-NodeJS/blob/eab77bfecde1813c136b3732a1989f03c54f65e4/src/lib/AccessoryLoader.ts#L49-L56
> 
> I know the message isn't really helpful, as the code for the AccessoryLoader is already pretty ancient.
> If I may ask, why do you use the AccessoryLoader. As you are under full control, you can just expose the created `Accessory` objects yourself. There isn't really any necessity to use AccessoryLoader, this was only really used for the old style APIs.
> 
> In any case, this means that the AccessoryLoader could successfully find your directory, but there is something wrong with the accessory code itself.

Yes, I traced this issue to AccessoryLoader.ts and I couldn't understand what is wrong. Otherwise if I use my Temperature_accessory.ts with HAP-NodeJS not as the library my accessory is loaded with no problem with Core.ts.
I started use AccessoryLoader cos I tried to make own loader (main.ts) for several accessories in my project. I saw this method in Core.ts. If this way is wrong could you advise how to load several accessories in my case?
