### ISSUE TITLE
iOS 14 - 28 days after

### ISSUE THREAD

**Issue by marcus-j-davies** [homebridge/HAP-NodeJS#862]
So.

I am interested to find out if anyone else seems to be facing a problem with HomePod?

First of here is my environment.

hap-nodejs                                             : 0.8.2
Node                                                       : 10.21.0
RPI (v4, GB Wired, Static IP)                :   Raspbian GNU/Linux 10 (buster)
HomePod (Static IP, 5Ghz only wifi)    : 14.2 

I seem to be facing an issue in that the HomePod, will often respond with 'your device is not responding'.

when I ask Siri to turn something off - she will complain it can't be reached, but all other iOS devices seem fine, it's only the HomePod that seems to struggle. Not always but I am having to restart hap, in order for the HomePod to see the device(s) again.

When this issue occurs - I am of course not able to control anything out of network (as the HomePod acts as a proxy)
when back on the network - my iPhone will suddenly see things again, but the HomePod still acts up.

Sometimes - HomePod can see some device but not others.

Anyone else seeing this?

**Comment by marcus-j-davies** [comment]
Interestingly - I am facing the issue now.

and running `dns-sd -B _hap._tcp.` on the Mac.

I get,
```
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
17:12:55.091  Add        3   4 local.               _hap._tcp.           Philips hue - XXXXX
17:12:55.091  Add        2   5 local.               _hap._tcp.           Philips hue - XXXXX
```

Whereas 10 minuets prior - when the issue was not occurring, HomePod was able to communicate, plus all devices were listed in terminal.

is this anything to do with [#856](https://github.com/homebridge/HAP-NodeJS/issues/856)

**Comment by marcus-j-davies** [comment]
ok - more info.

I ran dns-sd again (10-15 mins after), and my device are listed.
```
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
17:19:09.103  Add        3   4 local.               _hap._tcp.           Philips hue - XXXXX
17:19:09.103  Add        2   5 local.               _hap._tcp.           Philips hue - XXXXX
17:29:50.751  Add        3   4 local.               _hap._tcp.           Living Room XXXX
17:29:50.751  Add        3   4 local.               _hap._tcp.           Kitchen XXXX
17:29:50.751  Add        3   4 local.               _hap._tcp.           TV XXXX
17:29:50.751  Add        3   4 local.               _hap._tcp.           HomeKit Device Stack XXXX
17:29:50.751  Add        3   5 local.               _hap._tcp.           Living Room XXXX
17:29:50.751  Add        3   5 local.               _hap._tcp.           Kitchen XXXX
17:29:50.751  Add        3   5 local.               _hap._tcp.           TV XXXX
17:29:50.751  Add        2   5 local.               _hap._tcp.           HomeKit Device Stack XXXX
```

and HomePod is now suddenly ok again.

**Comment by Supereg** [comment]
It could be related to #856. Could you try the 0.9.0 beta and check if that improves anything?

Otherwise, are you running HomePod Mini or regular HomePod. Cause I also heard about the Mini having some connectivity problems (and also encountered some problems myself where Mini wasn't reachable as a HomeHub from outside of my House).

**Comment by marcus-j-davies** [comment]
I have the regular HomePod.

My gut feeling is telling me its something mDNS related.
during the inability for HomePod to see my devices,  `dns-sd` does not deporting my devices.

but my devices are listed, when HomePod is working fine.

Oddly, my iPhone doesn't have a problem as long as I'm on wifi,
the iPhone acts up  only when off the network and when the HomePod is acting up.

I will experiment with 0.9.0 and see how it pans out.

**Comment by Supereg** [comment]
> My gut feeling is telling me its something mDNS related.

Same. 0.8.x had some issues over for homebridge people. Thats why I suggested to try the beta.

**Comment by marcus-j-davies** [comment]
Hi @Supereg,

Initial observation on 0.9.0.

Prior to 0.9.0 we had
`.on(CharacteristicEventTypes.SET, (value, callback, hap) => {...})`

I was able to determine if the change originated from an iOS device, by checking for a null reference on hap

0.9.0
`.on(CharacteristicEventTypes.SET, (value, callback, hap)` always returns `NULL` for `hap`

has the event signature changed?

Many Thanks.

**Comment by Supereg** [comment]
Yes.

Previously the event signature for the listener was the following 
```js
(value: CharacteristicValue, cb: CharacteristicSetCallback, context?: any, connectionID?: SessionIdentifier) => void
```

`context` and `connectionId` could be considered pretty much to be private API. When handling a request coming from HomeKit context was always an object holding all the registered events for a given connection and connectionID represented some internal maintained identifier for the tcp connection.
This changed to 

```js
(value: CharacteristicValue, callback: CharacteristicSetCallback, context: any, connection?: HAPConnection) => void
```

where context is now not set anymore for any request coming from HomeKit itself and connection is the actual connection object. Context is still based when you are passing your own via setValue (so context is pretty much kept for backwards compatibility).

**Comment by Supereg** [comment]
> I was able to determine if the change originated from an iOS device, by checking for a null reference on hap

any reason why you needed to do that?

**Comment by marcus-j-davies** [comment]
I use this library in another project I have going [HomeKit Device Stack](https://github.com/marcus-j-davies/Homekit-Device-Stack)

think of it as a universal middleware sever - a wiring harness for hap if you will.

I was checking the hap property, to allow end users to filter out calls that may have been triggered by them self calling into my API (to stop infinite looping) 

so `HAPConnection` will still be populated if originating from a device?

**Comment by Supereg** [comment]
> so HAPConnection will still be populated if originating from a device?

exactly. I assume you call setValue manually then from somewhere? If that's the case you can just pass a custom context value to `setValue` ([docs](https://developers.homebridge.io/HAP-NodeJS/classes/characteristic.html#setvalue)). Best to sue sort sort of object or whatever. You can then check if the call was caused by your own code if that is any help?
I think that would be the more stable approach 🤔 

But yeah, just checking for the existence of parameter four would also work.

**Comment by marcus-j-davies** [comment]
I do yes.

Characteristics can be set via a REST API or MQTT.
I really should spend more time in reading the docs. :innocent:

Thanks

**Comment by Supereg** [comment]
> I really should spend more time in reading the docs. 😇

Well the docs are new and still WIP 😅 so not your fault

**Comment by marcus-j-davies** [comment]
back to the subject matter.

I'm now using 0.9.0 for my install, will report if mDNS issues improve.

**Comment by marcus-j-davies** [comment]
OK,

so to report - using 0.9.0 does indeed have a positive impact on DNS performance.
