### ISSUE TITLE
Is it possible to limit allowed characteristic values (e.g. only 0% and 100%, but not 79%)?

### ISSUE THREAD

**Issue by rutzfutz** [homebridge/HAP-NodeJS#865]
I'm currently trying to allow control of various devices in my smart home through the Apple Home app.

This works really well so far, however, I didn't find a way to tell the Home app that my motorized door doesn't support arbitrary TargetPosition percentages. It only supports 0% (fully closed) and 100% (fully open).

I tried creating my own versions of the TargetPosition and CurrentPosition characteristics where I added `minStep: 100` and `validValues: [0, 100]`, but this didn't help. It's still possible in the Apple Home app UI to select arbitrary percentages.

I also tried to use the SET callback to return 0 or 100 instead of the value that was sent in, but that also didn't work. The Home app still pretends that the percentage selected by the user was written.

Is it possible to limit the slider to 0 & 100, or make it snap to these values somehow, or is this simply not possible?

**Comment by marcus-j-davies** [comment]
one way is to overwrite **TargetPosition** in code

so, if on device you set to 70%
**TargetPosition** is set as such.

but then you can do.

```
.setCharacteristic(Characteristic.TargetPosition, 100)
.setCharacteristic(Characteristic.CurrentPosition , 100)
```

this should make the UI on Homeapp stop showing out of sycn values.

**Comment by rutzfutz** [comment]
Thank you, this workaround works for me. However, I need to set the values after a timeout of 100ms. If I set them immediately in the onSet handler, the Home app ignores them for some reason.

**Comment by marcus-j-davies** [comment]
The "Fisher Price" approach, is to set it on the trigger of `setTimeout`?

I don't use `onSet` - does it have a callback?
if so, call it as normal, but after setting `CurrentPosition` to the value of `TargetPosition`

Then...
```
.setCharacteristic(Characteristic.TargetPosition, 100)
.setCharacteristic(Characteristic.CurrentPosition , 100)
```

on the lapse of a setTimeout?
I'm guessing, this is already tour approach ?

**Comment by rutzfutz** [comment]
No, the `onSet` way of dealing with events does not have a callback as far as I know.

Hmm. I converted my handler back to the old `.on(CharacteristicEventTypes.SET, (value, callback) => { ... })` style and tested your approach. It's interesting that it actually seems to matter if the callback is called before or after updating `CurrentPosition` to the value of `TargetPosition`. It seems to work more reliably if I do it your way, but I was still able to get the Home app to display a `TargetPosition` of 73% one time.

My 100ms debounce delay approach avoids flooding HomeKit with rapid value set notifications from my code when the user is playing with the door target position slider, and the slider always snaps to the desired values correctly. I'm not particularly proud of this workaround, but it seems to be the most reliable way to deal with the snapping requirement currently.

**Comment by rutzfutz** [comment]
I'd still like to know if it possible to tell HomeKit that my characteristic only supports a subset of the possible value range. However, it seems that my attempt of defining my alternative `TargetPosition` characteristic with `validValues: [0, 100]` does not work because the `validValues` property does not even get sent to HomeKit. Is this correct?

Could someone with more insight into the HomeKit protocol (@Supereg?) please confirm if this is the case and that there is no better solution than the ones we discussed above?

**Comment by marcus-j-davies** [comment]
Out of curiosity, does your custom characteristic actually get obeyed in say, the EVE home app?
this could be an oversight into the HomeApp, and others like EVE might actually obey these properties.

Just a thought.

**Comment by rutzfutz** [comment]
> Out of curiosity, does your custom characteristic actually get obeyed in say, the EVE home app?
> this could be an oversight into the HomeApp, and others like EVE might actually obey these properties.

I don't use any third-party HomeKit apps, only the Apple Home app.
