### ISSUE TITLE
New .onGet / .onSet handlers in beta do not receive connection info

### ISSUE THREAD

**Issue by rutzfutz** [homebridge/HAP-NodeJS#869]
I'm trying to differentiate between users connected to my HomeKit installation, e.g. to prevent guests from controlling devices I don't want them to control.

When using the old-style handlers `.on(CharacteristicEventTypes.SET, (value, callback, context, connection) => { ... }`, I can use `connection && connection.username` to access the ID of the user trying to set a characteristic value. This worked well in my tests so far - no matter which device I'm using (iPhone, Apple Watch, iPad), the username seems to be tied to the Apple ID using the device and therefore allows me to differentiate between users.

However, when I'm using your modern .onGet / .onSet handlers available in the beta, the `context` and `connection` arguments are missing and I therefore cannot detect where requests are coming from. I don't care about the `context` argument (as I don't really know what it's good for), but being able to access `connection` from the characteristics handlers is crucial for me.

Was it a mistake that you didn't pass the connection info to the new handlers, or was that intentional? Would you mind adding at least the `connection` argument to the .onGet / .onSet handlers?

I'm currently on `0.9.0-beta.108`.

**Comment by Supereg** [comment]
Ah I see. Yeah, the new API tried to minimize any exposure of internal structures or types. But I see why you could need access to the connection instance for example.

I'll try to ship a solution with the 0.9.0 release. 👍
