### ISSUE TITLE
Typescript error with characteristic.updateValue, Error Objects and latest beta

### ISSUE THREAD

**Issue by NorthernMan54** [homebridge/HAP-NodeJS#873]
Am getting this error when compiling my plugin homebridge-tasmota with the latest beta

```
src/TasmotaService.ts:174:37 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'Error | 0' is not assignable to parameter of type 'Nullable<CharacteristicValue>'.
      Type 'Error' is not assignable to type 'Nullable<CharacteristicValue>'.
        Type 'Error' is not assignable to type '{ [key: string]: string | number | boolean; }'.
          Index signature is missing in type 'Error'.

174     this.characteristic.updateValue(availability);
                                        ~~

  node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.d.ts:764:5
    764     updateValue(value: Nullable<CharacteristicValue>, context?: any): Characteristic;
            ~~~~~
    The last overload is declared here.
```

Trigging this, is this line in my plugin

https://github.com/NorthernMan54/homebridge-tasmota/blob/650a785411d2926798b8465c0dfbe95414e4a710/src/TasmotaService.ts#L172

Looking at the HAP-NodeJS code, it appears that the definition of updateValue does not allow the passed value to be either a valid value or an error object.  Individually they are okay, but not a combination.

https://github.com/homebridge/HAP-NodeJS/blob/bf6859e99dc0a7b3a306e00c79c5d713507982c3/src/lib/Characteristic.ts#L1232

Am thinking that the updateValue definition needs to be adjusted to be

```
  updateValue(value: Nullable<CharacteristicValue> | Error): Characteristic;
```

**Comment by Supereg** [comment]
The "problem" is that the `updateValue` signature was changed from 
```ts
updateValue(newValue: Nullable<CharacteristicValue | Error>, callback?: () => void, context?: any): Characteristic
```

to four distinct signatures depending on the circumstances:

```ts
updateValue(value: Nullable<CharacteristicValue>): Characteristic;
updateValue(error: Error | HapStatusError): Characteristic;
updateValue(value: Nullable<CharacteristicValue>, callback?: () => void, context?: any): Characteristic;
updateValue(value: Nullable<CharacteristicValue>, context?: any): Characteristic;
```

I adjusted my decision to make distinct cases for Error and Value cases.

**Comment by NorthernMan54** [comment]
@Supereg tks for this much appreciated
