### ISSUE TITLE
How do I make an smtp camera work using bridgedcore?

### ISSUE THREAD

**Issue by MrUbun2** [homebridge/HAP-NodeJS#874]
**Describe Your Problem:**

I have a simple bridge setup with HAP-NodeJS and I need to add a WYZE camera to it.
I have already setup the camera to work with smtp but I need help with the code to get that into HomeKit

* **Node.js Version**:  v14.15.4
* **NPM Version**:  6.14.11
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd (using a custom-coded service)

**Comment by NorthernMan54** [comment]
Have you looked at homebridge and the homebridge-camera-ffmpeg plugin?  Wyze cameras are one of the working configurations

**Comment by MrUbun2** [comment]
I know what homebridge is but I wanted to try and make something *like* it, but not actually homebridge. So I need code for BridgedCore.js

**Comment by Supereg** [comment]
Maybe its worth checking out the homebridge discord https://discord.gg/kqNCe2D to get in touch with other fellows which might be able to help you.
It might help to provide a more detailed description of what you are trying to do and what you already **have** e.g. in existing running code you are trying to make work. Additionally existing homebridge plugins might be a help to understand some of the processes. Homebridge actually shares pretty much everything with HAP-NodeJS when abstracting the plugin api away.
