### ISSUE TITLE
"No response" beta 9.0

### ISSUE THREAD

**Issue by kontur11** [homebridge/HAP-NodeJS#875]
I have 3 versions of HAP 0.7.3, 0.8.5, 0.9.0beta116 running simultaneously in Docker Synology. In the home Wi-Fi network, there were and there are absolutely no problems. But if I am in the WAN, I periodically observe in versions 8.5 and 9.0 beta - "no response", after 20-30 minutes everything is restored. I also use Homebridge 1.3.0 beta48 - it works perfectly everywhere.

**Comment by Supereg** [comment]
While homebridge 1.3.0 used the `bonjour-hap` library by default, the HAP-NodeJS library used the `ciao` mdns responder library as default. This was changed with the latest beta iteration to match the behavior of homebridge.
So assuming the issue can be closed, otherwise feel free to reopen.
