### ISSUE TITLE
Video doorbell

### ISSUE THREAD

**Issue by lorenzoCuevas** [homebridge/HAP-NodeJS#877]
**Describe Your Problem:**
Hi again sorry, I just accidentally closed the last issue about implementing a video doorbell in HAP-Node js. So about that could you provide a sample code of Implementing a Ring video doorbell api into HAP-node js using JavaScript. Thanks!

**Comment by Supereg** [comment]
You might want to checkout the [homebridge-ring](https://www.npmjs.com/package/homebridge-ring) plugin for homebridge (building on top of HAP-NodeJS) which already ships somewhat support for Ring video doorbells.

**Comment by lorenzoCuevas** [comment]
Yes, but is there a sample JavaScript code that I could see because I'm planning to build my own HAP accessory service as a hobby.

**Comment by Supereg** [comment]
Maybe its worth checking out the homebridge discord https://discord.gg/kqNCe2D to get in touch with other fellows which might be able to help you.
It might help to provide a more detailed description of what you are trying to do and what you already have e.g. in existing running code you are trying to make work. Additionally existing homebridge plugins might be a help to understand some of the processes. Homebridge actually shares pretty much everything with HAP-NodeJS when abstracting the plugin api away.

There is also a good writeup about the Ring API https://github.com/dgreif/ring/wiki/SIP-Communication
Some of the original write-ups are linked at the bottom of that page.
