### ISSUE TITLE
URL Characteristic

### ISSUE THREAD

**Issue by HappyStriker** [homebridge/HAP-NodeJS#878]
Hey there,

is there a characteristic, which can be applied to every kind of device (or at least to some), which adds an URL hyperlink field in the Home app, which can directly open a custom website (eg. device configuration web interface)?

Thanks in advance!

Best regards,
Happy Striker

**Comment by Supereg** [comment]
No. There is no such characteristic defined by Apple.
The closest thing to "redirection" is the `App Matching Identifier` of the `AccessoryInformation` service, which lets you redirect to the "manufacturer" app.
