### ISSUE TITLE
Support passing PublishOptions (like advertiser) to BridgeCore.ts and Core.ts

### ISSUE THREAD

**Issue by kontur11** [homebridge/HAP-NodeJS#882]
When running HAP-nodejs 9.0, bonjour-hap backend is used by default. How do I switch to ciao?

Synology docker.

**Comment by mrMiimo** [comment]
Hi, did you read this https://github.com/homebridge/homebridge/issues/2765#issuecomment-778703046 ?

**Comment by kontur11** [comment]
> Hi, did you read this [homebridge/homebridge#2765 (comment)](https://github.com/homebridge/homebridge/issues/2765#issuecomment-778703046) ?
This works for Homebridge, how do I switch to HAP-nodejs?

**Comment by Supereg** [comment]
As noted in the [release notes](https://github.com/homebridge/HAP-NodeJS/releases/tag/v0.9.0), you can pass the [advertiser](https://developers.homebridge.io/HAP-NodeJS/interfaces/publishinfo.html#advertiser) option (of the `PublishInfo`) to the [Accessory.publish](https://developers.homebridge.io/HAP-NodeJS/classes/accessory.html#publish) method.

**Comment by marcus-j-davies** [comment]
@Supereg ,
really nice to see 0.9.0 in daylight! 👍 

Are there pros/cons to using bonjour-hap over ciao?

**Comment by Supereg** [comment]
If `ciao` is working for you, use it. All in all, its the better one, creating less stress on the network and fully adhering to the mDNS (and DNS-SD over mDNS) standards [if you need some bedtime reading: RFC 6762, RFC 6763].

Use `bonjour-hap` if `ciao` doesn't work for you. We seemingly still have some issues in certain network environments, trying to resolve those issues over time.

**Comment by marcus-j-davies** [comment]
I'll stick with CIAO.

Great work  on getting 0.9.0 out in the open! 👍

**Comment by kontur11** [comment]
> As noted in the [release notes](https://github.com/homebridge/HAP-NodeJS/releases/tag/v0.9.0), you can pass the [advertiser](https://developers.homebridge.io/HAP-NodeJS/interfaces/publishinfo.html#advertiser) option (of the `PublishInfo`) to the [Accessory.publish](https://developers.homebridge.io/HAP-NodeJS/classes/accessory.html#publish) method.

Please provide a sample code for running ciao, my knowledge is very limited for this.

**Comment by Supereg** [comment]
Maybe just provide a snippet of your code what you have running, maybe even describing your setup real quick. So we can point you to the right direction.

**Comment by kontur11** [comment]
> Maybe just provide a snippet of your code what you have running, maybe even describing your setup real quick. So we can point you to the right direction.

I just run BridgetCore.ts along with my files in the Accesories folder

**Comment by Supereg** [comment]
I'm afraid the `BridgeCore.ts` currently doesn't support an easy way of changing Publish options.
You will have to modify the file itself, looking for the `publish` call and adding `advertiser: "ciao"` to the options.

There are some plans to add a command line option of this in the future though.

**Comment by marcus-j-davies** [comment]
As above....

Edit `BridgeCore`

Find this.
```
bridge.publish({
....
});
```

To Add this.
```
bridge.publish({
advertiser: "ciao"
....
});
```

**Comment by marcus-j-davies** [comment]
@Supereg - a little off-topic
is bonjour-hap considered legacy? I' am adding an option for users to select, and not sure if legacy is a correct determination? 

![image](https://user-images.githubusercontent.com/55892693/108223521-d07b2680-7131-11eb-8cd9-a4a8d0293813.png)

**Comment by Supereg** [comment]
I think it would be fair to call it `legacy`. I think for uneducated users it really marks the difference or role of the different advertisers.
We might to certain compatibility patches to bonjour-hap, but won't continue development, so calling it legacy would seem fair.

**Comment by kontur11** [comment]
Returns an error:
src/BridgedCore.ts:35:3 - error TS2322: Type '"ciao"' is not assignable to type 'MDNSAdvertiser | undefined'.

**Comment by Supereg** [comment]
@kontur11 either but a
```ts
bridge.publish({
  // @ts-ignore
  advertiser: "ciao",
  ...
});
```
above the line

or changed it to 

```ts 


bridge.publish({
  advertiser: MDNSAdvertiser.CIAO,
  ....
});
```

This however requires that you also put the following at the top of the file
```ts
import { MDNSAdvertiser } from "./";
```

**Comment by marcus-j-davies** [comment]
@Supereg,

How about adding some `ENV`s, to be consumed by `bridgecore` if they exist 
`export HAP_MDNS_ADVERTISER=CIAO`
`export HAP_MDNS_PORT=1234`
`export HAP_MDNS_USERNAME=xx:xx:xx:xx`

would remove some ugly command line mess?

**Comment by Supereg** [comment]
> would remove some ugly command line mess?

environment values would remove the ability to have different settings when running multiple instances though.
I think for those instance specific options command line options are way more intuitive.

**Comment by marcus-j-davies** [comment]
I hadn't put multiple instances launched from the same console to thought.
again - my biased mind getting in the way
