### ISSUE TITLE
General Type issues in 0.9.1 + mdns advertiser logging can't be suppressed

### ISSUE THREAD

**Issue by Shaquu** [homebridge/HAP-NodeJS#883]
While migrating from 0.8.5 to 0.9.1 (which I guess should be backward compatible?) I found some issues with some Types.

1. All fields in  bonjour-hap.MulticastOptions should be optional. I believe previously you could pass to Accessory.publish mdns config which was of free form
```typescript
export type MulticastOptions = {
    multicast: boolean;
    interface: string;
    port: number;
    ip: string;
    ttl: number;
    loopback: boolean;
    reuseAddr: boolean;
  };
```

2. props in Characteristic constructor should be optional as code checks for empty value anyway
```typescript
public constructor(displayName: string, UUID: string, props: CharacteristicProps) {
    super();
    this.setProps(props || {}); // ensure sanity checks are called
  }
```

**Comment by Shaquu** [comment]
Also I see you used `console.log` in Advertiser.ts which does not seems best? Could you replace it with debug mechanism?

**Comment by Supereg** [comment]
Thanks for reporting. Will address those type errors in the next 0.9.2 beta, as soon as #884 is merged.
For now, as a workaround just use `@ts-expect-error` (you can also you `@ts-ingore`, but ts-expect-error will notify you once there is not error anymore).

I'll see what we do with the logging of the mdns advertiser. We might just move that into the homebridge project.
For us this log message is essential, so we can better assist with incoming issues.

**Comment by Shaquu** [comment]
Regarding that logs I would suggest to move that to use debug() if possible as the rest of the code does

**Comment by Supereg** [comment]
Just checked the sources. The `props` argument becoming required is actually an intentional change.
A characteristic MUST always be created with predefined CharacteristicProperties (having format and unit defined).
The legacy version weirdly assumed so undocumented defaults if you wouldn't supply it or override it afterwards.

If you could present your use case, I might get a glimpse on why you consider this an error.

The `MulticastOptions` type was updated within the latest 0.9.2 beta.

**Comment by Shaquu** [comment]
My case is that I am modifying props on the fly or I create new Characteristics too. So having props mandatory would not be an issue, I just assumed something is wrong since in constructor it is mandatory but later on it is `props || {}` which looks like props are not mandatory at all.

**Comment by Supereg** [comment]
The `props || {}` is just there to have it still backwards compatible with old code.
As even HAP-NodeJS previously called `.setProps` after the constructor call in its Characteristic definitions.

**Comment by Shaquu** [comment]
@Supereg Just to catch on a logging part. Can we make it dependant on debug package too?

**Comment by Supereg** [comment]
I'm closing this issue, moving all discussions related to logging to #909
