### ISSUE TITLE
Current Heating Cooling State

### ISSUE THREAD

**Issue by salimyzadeh** [homebridge/HAP-NodeJS#885]
Current Heating Cooling State should have 4 states
0 - off
1 - heat
2 - cool
3 - auto
https://developer.apple.com/documentation/homekit/hmcharacteristicvalueheatingcooling

this used to be correct, but in V0.9.1 auto has been removed and now I am getting a bunch of warnings on the state

**Comment by ebaauw** [comment]
I think the _target_ heating cooling state has four values, but the _current_ only three?  Makes sense as the device is actually either heating or cooling.

**Comment by Supereg** [comment]
@ebaauw is correct. Auto for **current** state doesn't make sense. You set the **target** state to `auto`, so the accessory can decide what state it wants to choose.

This issue duplicates #815.

Nonetheless HAP-NodeJS allows you to change the predefined properties using [characteristics.setProps](https://developers.homebridge.io/HAP-NodeJS/classes/characteristic.html#setprops), if you really think that you need that changed.
