### ISSUE TITLE
Accessories.Categories deprecation, can't access original enum keys

### ISSUE THREAD

**Issue by plasticrake** [homebridge/HAP-NodeJS#886]
I maintain the homebridge plugin `homebridge-tplink-smarthome` and I currently use the following code to get the name/key of the Categories enum value:

```js
this.api.hap.Accessory.Categories[category];
```

For example that would evaluate to `'LIGHTBULB'` for category of `5`

`Accessory.Categories` is now marked as deprecated, however doing the following does not work as you cannot use a variable to access a const enum:

```js
import { Categories } from 'homebridge';

Categories[category]; // This will throw error
```

I use the name of the category to display to the user how an accessory is setup, and my plugin allows the user to configure the accessory type in some cases. 

Currently my only alternative would be to copy the enum from `HAP-NodeJS` and place it in my plugin, but I'd rather not have to duplicate this.

Would it be possible to offer a function that will return the category name/key from the id or to still expose this enum?

**Comment by plasticrake** [comment]
I get a runtime error if I use `Categories[category]` though, so that wasn't working for me. I do have to use a `@ts-ignore` for `this.api.hap.Accessory.Categories[category]` but at least it works!

**Comment by Supereg** [comment]
> I get a runtime error if I use Categories[category] though

yeah, sorry I didn't clarify this properly. `Categories` is still only a type import.
You need to access it via the "hap" object, as you did.

**Comment by Supereg** [comment]
Assuming issues as solved.

**Comment by plasticrake** [comment]
@Supereg It is still deprecated and you had noted above a workaround would need to be found. My homebridge plugin will start breaking if this is removed in two months as it states in the comment. If this is something that will not be changed I will need to know so I can work around it.
https://github.com/homebridge/HAP-NodeJS/blob/c6f162279d3a5ad13b6f13f13da1ed83bd9074d2/src/lib/Accessory.ts#L361
