### ISSUE TITLE
Mismatch TargetTemp CurrentTemp range

### ISSUE THREAD

**Issue by ztalbot2000** [homebridge/HAP-NodeJS#887]
**Describe The Bug:**

In CharacteristicDefinitions.ts you define CurrentTemperature with a min/max value of -273.15 and a maxValue of 100, however the TargetTemperature has a minValue of 10 and a maxValue of 38.  I believe the -273.15 and 100 is correct. Setting a TargetTemperature lower than 10 will result in: `a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number -5 exceeded minimum of 10`
A Freezer for example may wish to set the TargetTemperature to below zero.

**To Reproduce:**

**Expected behavior:**

Both Target and Current Temperature ranges should be the same.
**Logs:**

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.19.0
* **NPM Version**: 7.5.4
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other Linux TestHost 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none.   launchctl
"name": "hap-nodejs", "version": "0.9.2",

**Comment by Supereg** [comment]
Apple defines those two Characteristics in the [HomeKit Accessory Protocol Specification](https://developer.apple.com/homekit/) as follows (in celcius):
* `CurrentTemperature`: `minValue`: `0`, `maxValue`: `100`
 * `TargetTemperature`: `minValue`: `10`, `maxValue`: `38`

Though even Apple **suggests** those predefined values, you can change them as you like, as it fits your specific accessory.
HAP-NodeJS mirrors those predefined Services and Characteristics, so developers don't need to always redefine them and easily can adapt and experiment with those.

The `CurrentTemperature` characteristic is used with multiple different Services (like `TemperatureSensor`, `Thermostat` and more) to show the current temperature. As we saw, that in many cases negative temperatures are sensible (and developers seem to fail to always do that override themselves) we decided with `0.9.x` to not stick to the Apple predefined values and set the lowest temperature value possible.

Doing the same thing for `CurrentTemperature` doesn't make sense and would actually break a lot of peoples code.
See `CurrentTemperature` is used only on the `Thermostat` service to define the temperature for the thermostat.
The Home App actually uses the `minValue` and `maxValue` properties to Redner the temperature Dial!
Changing minValue to -273, would create a huge temperature dial and wouldn't make sense as no device really support cooling to exakt zero.

So thermostat plugins really have to define their valid range of values themselves using [characteristic.setProps](https://developers.homebridge.io/HAP-NodeJS/classes/characteristic.html#setprops).
We can't possibly guess the correct the possible temperature ranges for alle different devices out there, so we just stick to the Apple predefined values!

The warning is therefore expected, and serves as a hint that indeed there is a error in your code, as you don't define the `minValue` property properly.

**Comment by ztalbot2000** [comment]
I don't set either value, I just use what is supplied.  I have the ability
to change it and understand your position and accept it.

TTFN,
John
