### ISSUE TITLE
HAP Context is not set anymore -> dependent module NRCHKB doesn't work as expected  

### ISSUE THREAD

**Issue by djiwondee** [homebridge/HAP-NodeJS#891]
**Describe The Bug:**
I'm a heavy user of [NRCHKB](https://github.com/NRCHKB/node-red-contrib-homekit-bridged) which is build based on and depending the HAP-NodeJS-package.

As a member of the NRCHKB beta tester team, since some release cycles the HAP context is not present anymore. Unfortunately I can't they with what particular HAP-NodeJS release, embedded in NRCHKB, this went away. I assume since NRCHKB is using the updated hap-nodejs 0.9.1 (and nowhap-nodejs 0.9.4) the problem came up

**Test Node.red flow**
<img width="693" alt="image" src="https://user-images.githubusercontent.com/37173958/112446817-e5f6f800-8d50-11eb-8733-90045baeb37b.png">

**Current behavior**
![image](https://user-images.githubusercontent.com/37173958/112447255-6584c700-8d51-11eb-98bb-b19dfb1c4959.png)

**Expected behavior:**
Something like this
<img width="226" alt="image" src="https://user-images.githubusercontent.com/37173958/112447664-dd52f180-8d51-11eb-948e-df59bfa0af5f.png">
The full msg payload contains HAP context data. This is an example of a msg of a flow, running on a production env. which is using HAP-NodeJS 0.7.8 (embedded in production release 1.2.0 of NRHCKB)

I've talked already with @Shaquu about it. He has double checked this on its own env as well experiencing the same symptom.

**My Test-Environment:**

- Raspberry 4B+
- NPM Version 6.14.11 
- Node-RED version: v1.2.9
- Node.js  version: v12.21.0
- Raspbian Linux 5.10.17-v7l+ arm LE
- HAP-NodeJS v0.9.4...

Running all native on it. Do you have any idea of the root cause?

**Comment by Shaquu** [comment]
Possibly broken in 0.9.0

https://github.com/homebridge/HAP-NodeJS/compare/v0.8.5...v0.9.1#diff-9151f9e2dae83d23fd0c4aab1bcbc3f2bf3a3a7406e9ffe2a413e0ce14f2f872L1461-L1489

**Comment by Shaquu** [comment]
Bump

**Comment by Supereg** [comment]
@Shaquu Sorry for the long response time.
Would you mind explaining what information inside the "old" context object is not available anymore via mechanisms present in the latest 0.9.x release?
The previous `context` object wasn't really well defined. When set via HAP requests it was passed the `events` dictionary, containing all subscribed events for the connection which made the request.
However a plugin might also pass arbitrary values to the `context` parameter.

For SET and GET events:
With 0.9.x release the context is now set to `undefined` for calls coming from HAP-NodeJS itself (so originating from a request coming from HomeKit) and the last parameter was changed form being the connectionId to being the fully fledged connection object (which contains a updated form of the events dictionary).

For CHANGE events:
Similarly the `context` object isn't passed anymore, only if something is explicitly passed from e.g. a call coming from a plugin or somewhere else. Newly added, the `originator` property if the change event object points now, if present in the given context, to the HAPConnection from which the update originated from.

**Comment by Shaquu** [comment]
Difficult to say what was the date in it (some gibberish) but the thing is that it was defined at least when Home.app was triggering value change. Many of my users were using that for logic to decide origin.

We already made some overrides for that in our code, so this ticket is more to clarify that you intend to leave it that way.

**Comment by Supereg** [comment]
> Many of my users were using that for logic to decide origin.

I would suggest to add a compatibility layer on the nodered side (e.g. building the "old" context thing from the connection object) and maybe manually adding a dedicated `isHAPRequest` flag (based on if connection is present or not) for future users to rely on.

> We already made some overrides for that in our code, so this ticket is more to clarify that you intend to leave it that way.

But sounds like you did that already.

**Comment by djiwondee** [comment]
Issue can be closed since context is 'replaced' by session processing.
