### ISSUE TITLE
testCharacteristic not working correctly

### ISSUE THREAD

**Issue by ztalbot2000** [homebridge/HAP-NodeJS#892]
**Describe The Bug:**

if you create a new characteristic and pass that characteristic into testCharacteristic it will fail because the code checks for typeof === "function" and not "object".

**To Reproduce:**

Here is a test script:

```js
'use strict';

const which = require('which');
const path = require( "path" );

// Get the real path of homebridge instead of a dev dependancy,
const homebridgePath = which.sync( 'homebridge', { nothrow: true } )
let dirname = path.dirname( homebridgePath );
console.log("dirname:%s", dirname);
let apiPath = `${ dirname }/../lib/node_modules/homebridge/lib/api.js`;
console.log( "Found api in %s", apiPath );


let HomebridgeAPI = require( apiPath ).HomebridgeAPI;


var api = new HomebridgeAPI(); // object we feed to Plugins
var Service = api.hap.Service;
var Characteristic = api.hap.Characteristic;

let switchService = new Service.Switch();

let type = "PointX";
let props = { };
    props.format = "uint32";
    props.minValue = 0;
    props.minStep = 1;
    props.perms = [ "pr", "pw", "ev" ];

let UUID = api.hap.uuid.generate( type );
// Create a new characteristic
let newCharacteristic = new api.hap.Characteristic( type, UUID, props );

// Make sure our new characteristic is okay
if ( newCharacteristic instanceof Characteristic )
   console.log( "newCharacteristic created - OK" );
else
   console.log( "newCharacteristic created - NOT OK" );

// Test an existing Characteristic
if ( switchService.testCharacteristic( Characteristic.On ))
   console.log( "switchService contains Characteristic.On - OK" );
else
   console.log( "switchService contains Characteristic.On - NOT OK" );

// Test that our new characeristic is not yet part of the service
if ( switchService.testCharacteristic( newCharacteristic ))
   console.log( "switchService contains our yet to be added new Characteristic - NOT OK" );
else
   console.log( "switchService does not contain the new Characteristic yet - OK" );

// Add our new characteristic to the service.
switchService.addCharacteristic( newCharacteristic );

// testCharacteristic works if you pass in the displayName
if ( switchService.testCharacteristic( newCharacteristic.displayName ))
   console.log( "switchService contains our new Characteristic.displayName - OK" );
else
   console.log( "switchService DOES NOT contain our new Characteristic.displayName - NOT OK" );

// Test that our new characteristic is part of the service
// This fails because testCharacteristic is typeof name === 'function' and not 'object'
if ( switchService.testCharacteristic( newCharacteristic ))
   console.log( "switchService contains our new Characteristic object - OK" );
else
   console.log( "switchService DOES NOT contain our new Characteristic object - NOT OK" );



```

**Expected behavior:**

testCharacteristic should pass of the newly created characteristic

**Logs:**

**Screenshots:**

**Environment:**

* **Node.js Version**: 15.5.1
* **NPM Version**: 7.5.2
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other OSX
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by Supereg** [comment]
See https://developers.homebridge.io/HAP-NodeJS/classes/service.html#testcharacteristic

The `testCharacteristic` is working as intended.
You can either pass the name (for backwards compatibility) or a Characteristic constructor (thus the function check) such as `Characteristic.On`.
Passing an **instance** of a characteristic is not intended to be supported right now.
We might include support for such checks in the future.

**Comment by ztalbot2000** [comment]
Accepted answer.  It's just odd that when you create one you can't check it
the way it is. It is like, "Here is your new phone number, but sorry we
can't check it unless you give us your name first" ;-)

thanks,
John

**Comment by ztalbot2000** [comment]
Andi,

  So the real answer is that this was not the way to create a custom
characteristic and therefore fails testCharacteristic. At least it won't
create a characteristic equivalent to Characteristic.On. I guess that is
also what your answer eluded to, being that the result of "new
Characteristic" is not a Function.

I'm just answering my own question, if by chance others read through it all.

ttyl,
John

**Comment by Supereg** [comment]
Not sure if I understood you correctly.

But custom characteristics work as well with `testCharacteristic` just pass the constructor of your custom characteristic.

if you have 

```js
class CustomCharacteristic extends Characteristic {
  // ...
}
```

Just do 

```js
service.testCharacteristic(CustomCharacteristic);
```

**Comment by ztalbot2000** [comment]
Hi Andi,

I did just that and it fails as the code snippet I sent you explains.
However I did resolve the issue by

service.testCharacteristic( customCharacteristic.< type > )

Where type is the type aka displayName you created it with.

It just took me a while to figure that out.

I have my solution so all is well.

There is so many cool things you have done with Homebridge. It's hard to
keep up. I have a lot of plans for my own plugin. Funny that it just
started out by wanting to see what the IOS Home App could do.

Take care,
John

**Comment by Supereg** [comment]
> I did just that and it fails as the code snippet I sent you explains.

How does it fail?

I updated the example above, after double checking. You will need to match the characteristic declarations as it is done by HAP-NodeJS and include a static `UUID` property holding the unique identifier for the characteristic (as it is used in the constructor).

the `testCharacteristic` method really only relies on that property to compare with the existing characteristics on the service.

**Comment by ztalbot2000** [comment]
it fails by not returning true


if ( switchService.testCharacteristic( newCharacteristic))
   console.log( "switchService contains our new Characteristic.NODISPLAYNAME" );
else
   console.log( "switchService DOES NOT contain our new Characteristic.NODISPLAYNAME" );

if ( switchService.testCharacteristic( newCharacteristic.PointX ))
   console.log( "switchService contains our new Characteristic.PointX" );
else
   console.log( "switchService DOES NOT contain our new Characteristic.PointX" );

**Comment by ztalbot2000** [comment]
Your answer here is correct.  Your previous answer,

Just do

service.testCharacteristic(CustomCharacteristic);

Was incorrect and the whole point of my original post.

I think we both understand what is correct.

Ttyl,
John

**Comment by ztalbot2000** [comment]
I'm happy with knowing how it works now that I figured it out.  Maybe add a note in the documentation, but otherwise I'm okay with this.
