### ISSUE TITLE
Characteristic CHANGE event - unexpected behaviour since 0.9.x

### ISSUE THREAD

**Issue by Shaquu** [homebridge/HAP-NodeJS#893]
Hi, my folks (from nrchkb NRCHKB/node-red-contrib-homekit-bridged#390) spotted a strange behavior since our last release (when we started using hap-nodejs 0.9.4)

I checked the code and looks like some logic has been changed 0.8.5 => 0.9.x
https://github.com/homebridge/HAP-NodeJS/blob/186ce56fab55b5868142e27b59af6c5ab53038d6/src/lib/Characteristic.ts#L668

In 0.8.5 event was only triggered when value changed (0 => 1, 1 => 0)
Since 0.9.x event is triggered always (0 =>1, 1 => 1, 1 => 0)

**Comment by Supereg** [comment]
This was an intended change to e.g. support things like the `AdaptiveLightingController` which needs to act on a change unconditionally if the value changed or not (e.g. as soon as the color temperature is controlled by the user, adaptive lighting schedule must be disabled).
In the linked issues, I saw that you already implemented a change on your side.

**Comment by Shaquu** [comment]
I see but it means I cannot trust any HapNodeJS release. 0.9 broke compatibility in too many ways

**Comment by Supereg** [comment]
https://semver.org/#spec-item-4

The next planned release is [v1.0.0](https://github.com/homebridge/HAP-NodeJS/projects/5), finally adopting proper SemVer versioning.

**Comment by Shaquu** [comment]
Great news @Supereg 
Huge thanks for your hard work!
