### ISSUE TITLE
Numerical (0/1) response is being given for boolean properties

### ISSUE THREAD

**Issue by dxdc** [homebridge/HAP-NodeJS#894]
**Describe The Bug:**

In the latest HB (1.3.4), which uses the latest HAP-NodeJS, bool properties are being reported as either 0 or 1. Previously, they were being reported as true or false. I'm not sure when this behavior changed, but it was working fine in HB 1.2.5.

E.g., 

```
 curl -X PUT http://127.0.0.1:XXXXX/accessories --header "Content-Type:application/json" --header "authorization: XXX-XX-XXXX"
```

Currently, boolean properties like `MotionDetected` and `On` are showing as 0 or 1 (vs. true/false). 

```js
        {
          "type": "85",
          "iid": 11,
          "characteristics": [
            {
              "type": "23",
              "iid": 12,
              "value": "Early Rise Trigger",
              "perms": [
                "pr"
              ],
              "description": "Name",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "22",
              "iid": 13,
              "value": 0,
              "perms": [
                "ev",
                "pr"
              ],
              "description": "Motion Detected",
              "format": "bool"
            }
          ]
        }        {
          "type": "49",
          "iid": 8,
          "characteristics": [
            {
              "type": "23",
              "iid": 9,
              "value": "Dryer Finish",
              "perms": [
                "pr"
              ],
              "description": "Name",
              "format": "string",
              "maxLen": 64
            },
            {
              "type": "25",
              "iid": 10,
              "value": 0,
              "perms": [
                "ev",
                "pr",
                "pw"
              ],
              "description": "On",
              "format": "bool"
            }
          ]
        },
```

* **Node.js Version**: 12.22.1
* **NPM Version**: 7.10.0
* **Operating System**: Raspbian 
* **Process Supervisor**: pm2

**Comment by dxdc** [comment]
May be related: https://github.com/homebridge/homebridge/issues/2876

**Comment by NorthernMan54** [comment]
With homebridge 1.3.x all characteristic values are now validated to ensure alignment with HAP Spec.  So a couple of subtle things like this are now enforced.  Personally in my setup I didn't notice it when I upgraded my setup to homebridge 1.3.x as part of the pre-release regression testing.

If your using javascript 0/1 and false/true are basically treated the same.

**Comment by dxdc** [comment]
@NorthernMan54 In the official HAP spec, you're right that it does say it can be any one of `true`, `false`, `1`, `0`. However, in the example JSON, they also show `bool` as only `true` or `false`.

This changed to HAP-NodeJS ruined some of my flows that relied on the `Switch` node since I had them listed as `true` or `false` not `== 1` or `== 0`.

Personally, I like bool being represented as true/false, it seems more native to me, and also, it seems like this is already preferred in the HAP documentation as well as parts of the existing HAP-NodeJS code:

https://github.com/homebridge/HAP-NodeJS/blob/c6f162279d3a5ad13b6f13f13da1ed83bd9074d2/src/lib/Characteristic.ts#L1903-L1913

<img width="818" alt="Screen Shot 2021-04-23 at 7 16 36 PM" src="https://user-images.githubusercontent.com/7200365/115940833-89c6e700-a468-11eb-9dbd-dcb4e8a7a3db.png">

<img width="709" alt="Screen Shot 2021-04-23 at 7 16 57 PM" src="https://user-images.githubusercontent.com/7200365/115940825-86336000-a468-11eb-850e-46fbd019af23.png">

**Comment by NorthernMan54** [comment]
Not sure what the potential next steps could be here besides adding the additional values to your switch nodes.  In the code I don’t think I’m massaging the values received over the wire from homebridge at all.

I did go back at look at my flows using motion sensors, and I was triggering based on receiving a message and not the value itself.  It is triggering my cameras to take a picture so I guess I never noticed the additional snapshots for motion cleared.

**Comment by NorthernMan54** [comment]
My camera flow, which is triggered by my pir sensors or motioneye detecting motion, passing the image thru amazon rekognition, uploading to google photos and if the image contains a person, trigger a rich iOS notification with People fake camera and include the snapshot.


![C19F61BE-DC6B-4CF3-89DB-0A39D25AD613](https://user-images.githubusercontent.com/19808920/115943768-ee417080-a47f-11eb-85cf-9d9ccebec257.png)

**Comment by dxdc** [comment]
> Not sure what the potential next steps could be here besides adding the additional values to your switch nodes. In the code I don’t think I’m massaging the values received over the wire from homebridge at all.

Yes, I updated my switch nodes which resolved it.

But, shouldn't the correct boolean values be returned in JSON? It used to be the case in earlier HAP-NodeJS versions that it returned true/false, but not sure where the problem lies. 

> In the code I don’t think I’m massaging the values received over the wire from homebridge at all.

Exactly,  I can see this even here:
```sh
 curl -X PUT http://127.0.0.1:XXXXX/accessories --header "Content-Type:application/json" --header "authorization: XXX-XX-XXXX"
 ```
 
 That's why I believe it would be caused by HAP-NodeJS, unless HB is adjusting values but I doubt it?

**Comment by NorthernMan54** [comment]
When Andi put all the changes into the most recent version of hap-nodejs he was trying to increase the over stability of homebridge etc, and forced all the plugins to send compliant values.  If your plugin sends a non-compliant value homebridge now exits with an error where before you would get weird errors in the home app or other issues like not responding.  Since that and several other changes were made stability for users has increased immensely and the number of ‘issues’ has dropped to minimal.

so the massaging of that value is inside hap-nodejs.

**Comment by dxdc** [comment]
Thx. My vote would be to have bool values then return as true/false instead of 0/1. It seems more in line with my reading of the HK Spec.

**Comment by Supereg** [comment]
As you noted correctly, the HAP spec defines `false`, `true`, `0`, `1` as valid values for the `bool` characteristic format.
While the specification seemingly favors using `true`/`false` notation, all the implementation done by Apple (on the ADK part, as well on the client side part on e.g. iDevices) favor using `0` and `1` as it saves some bytes in transmission.
Pretty much every `boolFromString` implementation is capable of dealing with `false`/`true` as well as `0`/`1`. Thus this changed was done in 0.9.0 to reduce transmission size.

**Comment by Supereg** [comment]
I hope this kinda explains the rationale behind that change.

Feel free to reopen the issue or add further comments if you have any further points.
