### ISSUE TITLE
Current/Target/HeatingCoolingState values

### ISSUE THREAD

**Issue by ztalbot2000** [homebridge/HAP-NodeJS#896]
**Describe Your Problem:**

In the IOS app, if you had defined a Homebridge Thermostat that has Characteristics of "CurrentHeatingCoolingState" and "TargetHeatingCoolingState", The IOS app displays a wheel with the Target values of "Off", "Heat", "Cool", "Auto" as defined in CharacteristicDefinitions.ts.  
There is no "Auto" value for "CurrentHeatingCoolingState" defined in the Hap.  Trying to set the "Current" value too "Auto" will generate the appropriate warning of "'Current Heating Cooling State': characteristic was supplied illegal value: number 3 exceeded maximum of 2", based on the defined Characteristic traits.
Are these two characteristics not supposed to have the same values as all other "Current"/"Target" characteristics do?
If they do not match, What value should "CurrentHeatingCoolingState" be for a "TargetHeatingCoolingState" of "Auto"? Because if you set the "CurrentHeatingCoolingState" to either "Cool" or "Heat" based on the current temperature, the IOS app wheel flips from "Auto" to either "Cool" or "Heat" based on what you just set it as it gets this value upon its next query of the devices Heating/Cooling state.
I'm just need a bit of clarification as to what should be the CurrentHeatingCoolingState value with a TargetHeatingCoolingState set to "Auto".

thanks,
John Talbot

**Logs:**

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.19.0
* **NPM Version**: 7.6.3
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other Linux SixtyFiveStableWay 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none hb-service
*

**Comment by Supereg** [comment]
Duplicates #855, #815, #888

The situation is probably best explained in https://github.com/homebridge/HAP-NodeJS/issues/885#issuecomment-782880351.

But here in short:

> If they do not match, What value should "CurrentHeatingCoolingState" be for a "TargetHeatingCoolingState" of "Auto"? 

If **TARGET** is set to AUTO, the accessory decides by itself (based on current temperature and target temperature) if **CURRENT** will be HEAT or COOL (or maybe OFF).

> he IOS app wheel flips from "Auto" to either "Cool" or "Heat" based on what you just set it as it gets this value upon its next query of the devices Heating/Cooling state.

This shouldn't happen. Note that even if **CURRENT** is e.g. HEAT, the **TARGET** characteristic must stay at AUTO.
The wheel always just reflects the **TARGET** characteristic. The orange or blue (or gray) circle of the tile reflects the **CURRENT** characteristic.
You can test it with the HomeKit Accessory Simulator https://developer.apple.com/documentation/homekit/testing_your_app_with_the_homekit_accessory_simulator. 

Note, you can also adjust the `validValues` characteristic property to e.g. disable certain values like AUTO or COOL of the **TAGRET** characteristic.

**Comment by ztalbot2000** [comment]
Hi Andi,

Thanks for the response.  I understand and accept your answer. I had
figured out your solution as well and that was to change the props as I see
fit.

Thanks for answering my question.

Ttyl,
John
