### ISSUE TITLE
Accessory not persisting "reseting" in HomeKit.

### ISSUE THREAD

**Issue by ddmunhoz** [homebridge/HAP-NodeJS#898]
**Describe Your Problem:**

I wrote a custom app to control Synology NAS features by using HomeKit. But the problem is that I cannot get my accessories to persist through restarts. You can check the code here [SynoNasHKB](https://github.com/ddmunhoz/SynoNasHKB) and as you can [see at this line ](https://github.com/ddmunhoz/SynoNasHKB/blob/6d8192c2d930c70fedad0028be25fb8df715c775/src/synoNasShare.js#L102) I'm generating a unique ID that is stored in the app folder under persist/IdentifierCache.json

If I change the cache file I can see that the UUIDS are there, but they do not persist when the app restarts. So that makes HomeKit forget all configs like rooms/favorite/scenes

Can anybody shed some light on this issue ? Maybe I'm missing something, Back then I gave up on the project since I could not solve this. It would be nice to get some help to keep moving.

Thanks!

**Logs:**

IdentifierCache.json
```
{"cache":{"d8e8a655-4b6c-42a2-86f0-b31482e1b2aa|nextIID":10,"d8e8a655-4b6c-42a2-86f0-b31482e1b2aa|0000003E-0000-1000-8000-0026BB765291|00000014-0000-1000-8000-0026BB765291":2,"d8e8a655-4b6c-42a2-86f0-b31482e1b2aa|0000003E-0000-1000-8000-0026BB765291|00000020-0000-1000-8000-0026BB765291":3,"d8e8a655-4b6c-42a2-86f0-b31482e1b2aa|0000003E-0000-1000-8000-0026BB765291|00000021-0000-1000-8000-0026BB765291":4,"d8e8a655-4b6c-42a2-86f0-b31482e1b2aa|0000003E-0000-1000-8000-0026BB765291|00000023-0000-1000-8000-0026BB765291":5,"d8e8a655-4b6c-42a2-86f0-b31482e1b2aa|0000003E-0000-1000-8000-0026BB765291|00000030-0000-1000-8000-0026BB765291":6,"d8e8a655-4b6c-42a2-86f0-b31482e1b2aa|0000003E-0000-1000-8000-0026BB765291|00000052-0000-1000-8000-0026BB765291":7,"d8e8a655-4b6c-42a2-86f0-b31482e1b2aa|000000A2-0000-1000-8000-0026BB765291":8,"d8e8a655-4b6c-42a2-86f0-b31482e1b2aa|000000A2-0000-1000-8000-0026BB765291|00000037-0000-1000-8000-0026BB765291":9,"|nextAID":3,"08865fd8-25cf-465d-bbd6-4375eeb01449":2,"08865fd8-25cf-465d-bbd6-4375eeb01449|nextIID":13,"08865fd8-25cf-465d-bbd6-4375eeb01449|0000003E-0000-1000-8000-0026BB765291|00000014-0000-1000-8000-0026BB765291":2,"08865fd8-25cf-465d-bbd6-4375eeb01449|0000003E-0000-1000-8000-0026BB765291|00000020-0000-1000-8000-0026BB765291":3,"08865fd8-25cf-465d-bbd6-4375eeb01449|0000003E-0000-1000-8000-0026BB765291|00000021-0000-1000-8000-0026BB765291":4,"08865fd8-25cf-465d-bbd6-4375eeb01449|0000003E-0000-1000-8000-0026BB765291|00000023-0000-1000-8000-0026BB765291":5,"08865fd8-25cf-465d-bbd6-4375eeb01449|0000003E-0000-1000-8000-0026BB765291|00000030-0000-1000-8000-0026BB765291":6,"08865fd8-25cf-465d-bbd6-4375eeb01449|0000003E-0000-1000-8000-0026BB765291|00000052-0000-1000-8000-0026BB765291":7,"08865fd8-25cf-465d-bbd6-4375eeb01449|00000049-0000-1000-8000-0026BB765291":8,"08865fd8-25cf-465d-bbd6-4375eeb01449|00000049-0000-1000-8000-0026BB765291|00000023-0000-1000-8000-0026BB765291":9,"08865fd8-25cf-465d-bbd6-4375eeb01449|00000049-0000-1000-8000-0026BB765291|00000025-0000-1000-8000-0026BB765291":10,"08865fd8-25cf-465d-bbd6-4375eeb01449|00000049-0000-1000-8000-0026BB765291|00000021-0000-1000-8000-0026BB765291":11,"08865fd8-25cf-465d-bbd6-4375eeb01449|00000049-0000-1000-8000-0026BB765291|00000052-0000-1000-8000-0026BB765291":12}}
```

**Environment:**

* **Node.js Version**:v16.3.0
* **NPM Version**: 7.15.1
* **Operating System**: macOS / Docker / linux

**Comment by Supereg** [comment]
I just quickly glanced over the code while on my phone, but try to move the „publish“ call at the end of main https://github.com/ddmunhoz/SynoNasHKB/blob/6d8192c2d930c70fedad0028be25fb8df715c775/src/synoNasBridge.js#L13

what you are doing is creating an empty bridge and then adding all the accessories **after** it is published.
I don’t remember the exact internals right now, but it some situations this can lead to removing the previous accessories in HomeKit and creating new ones (the exact identical ones) afterwards, therefore rearranging them in the Home App and resetting scenes and automations.

the UUID you pointed out is a HAP-NodeJS specific id and is only used to lookup storage files for the **main** accessory, so for the accessory which gets published.

Check if above change resolves anything. Otherwise I can look over the code again in more detail then.

**Comment by ddmunhoz** [comment]
Thank you man! that indeed fixed the issue! I never knew that adding accessories to the bridge after its published would create such issue.

Thats fine, I made some changes on my code to work around that. One last thing, maybe you have an answer for this as well:

There's anyway to add accessories to the bridge and Unset the favorite option ? Because every new accessory my bridge brings up on the first time is set as favorite.

**Comment by Supereg** [comment]
> There's anyway to add accessories to the bridge and Unset the favorite option ? Because every new accessory my bridge brings up on the first time is set as favorite.

This is entirely controlled by the Home App and cannot be influenced by the accessory. So no.
