### ISSUE TITLE
Adding services to the lib

### ISSUE THREAD

**Issue by GuySawyer** [homebridge/HAP-NodeJS#899]
I would like to contribute to this lib and add Services, namely a Moisture Sensor for now.

I see that the ```ServiceDefinitions.ts``` and ```CharacteristicDefinitions.ts``` both have comments at the top stating that these files are generated.

But I cannot figure out where they are generated from.

What is the correct way to go about adding a custom Service?

**Comment by Supereg** [comment]
Could you clarify what type of service you are talking about? 
Is this an Apple defined one, can't find it in the docs?

If its a custom Service you can happily define it yourself in your code.
There is no need to define a custom service in `HAP-NodeJS`. `HAP-NodeJS` predefines only Apple defined Services and Characteristics.

**Comment by GuySawyer** [comment]
Thanks for your quick response.

Yes, I am talking about a custom service.
I am building a moisture sensor to monitor my indoor plants.

Ok I see, I had a feeling ```HAP-NodeJS``` was only supporting app defined services.
Would you mind providing me with a link to the docs you reviewed?

Follow up question:

How would I go about defining it in code?

The problem I am facing is within the apple Home App, I cannot get it to display an appropriate icon, nor the correct device name.
The name is determined by the Service definition.
Currently I am using the HumiditySensor service definition to mimic the capability I am trying to achieve.

I appreciate your assistance.

**Comment by Videonisse** [comment]
> The problem I am facing is within the apple Home App, I cannot get it to display an appropriate icon, nor the correct device name.
> The name is determined by the Service definition.
> Currently I am using the HumiditySensor service definition to mimic the capability I am trying to achieve.
> 
> I appreciate your assistance.

The Apple Home App doesn't support custom services, you need to use a third-party app for this. For example the Eve app.

**Comment by Supereg** [comment]
Exactly, as @Videonisse explained, the Home App (and Siri) only support Apple defined services and characteristics.
You can add custom services which you then could use in your custom app to do fancy icons.
Most third party HomeKit apps (like the Eve one) also do a good job at displaying and interacting with custom services (as long as you adhere to the standard characteristic properties like `unit`, `format´ etc).

Apple provides a non-commercial specification for HAP: https://developer.apple.com/homekit. In that document you will find most of the apple defined services and characteristics (as they are in HAP-NodeJS). Some services are only for MFi usage though. Most of those are still incorporated in HAP-NodeJS by digging through some internal framework files.

> How would I go about defining it in code?

Have a look at the definition files, pretty much exactly like that (though without the last line of setting properties in the Service or Characteristic class).
