### ISSUE TITLE
How to develop HAP-NodeJS in an existing HomeBridge plugin?

### ISSUE THREAD

**Issue by Hanh94** [homebridge/HAP-NodeJS#900]

**Comment by NorthernMan54** [comment]
Pls explain your question further?

Personally when I’m developing or working on the core components i change the normal version of homebridge or hap-nodejs in the npm package directory structure to a version in my coding folders where I have cloned the package from GitHub. I do using symlinks in the os to replace the package.  The other step is to run “npm install” in the cloned package folder to install all the dependencies of your cloned package.

**Comment by Hanh94** [comment]
Hi @NorthernMan54 , Currently I have a HomeBridge plug-in based on the HomeBridge template, which implements LIGHTBULB Accessory, Now I want to through the HAP-NodeJS **AdaptiveLightingController** realize the Adaptive Lighting, How do I develop on my original plugin？

**Comment by NorthernMan54** [comment]
I was hopping one of the plugin developers who had added adaptive lighting control to their plugins would chime in here with some tips.

If you look at the Homebridge-hue and homebridge-meross plugins, they both support adaptive lighting, so you use them as a starting point.

**Comment by NorthernMan54** [comment]
Another option is to join the homebridge discord server, and ask your question in the #plugin-development channel.  Several devs who implemented the feature are there.

**Comment by donavanbecker** [comment]
> I was hopping one of the plugin developers who had added adaptive lighting control to their plugins would chime in here with some tips.
> 
> 
> 
> If you look at the Homebridge-hue and homebridge-meross plugins, they both support adaptive lighting, so you use them as a starting point.

@bwp91

**Comment by Hanh94** [comment]
@donavanbecker @NorthernMan54 , Thank you guys.
