### ISSUE TITLE
Finite error warning if sign a function "casting"

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#907]
Think my error is related to this commit "Fix Validate Client Supplied Values + float min/max #890"

error:

[SolarEdge SE5000H-AU000NNU2@SolarEdge SE5000H-AU000NNU2@Eve Current Consumption] characteristic value expected valid finite number and received "() => {
                    // Use last history entry for currrent power consumption
                    var historyEntry = this.lastHistory(this.EveHome.type, this.EveHome.sub);
                    var lastWatts = 0;
                    if (historyEntry && Object.keys(historyEntry).length != 0) {
                        lastWatts = historyEntry.watts;
                    }
                    return lastWatts;
                }" (function)

Code:

               service.getCharacteristic(Characteristic.EveCurrentConsumption).updateValue(() => {
                    // Use last history entry for currrent power consumption
                    var historyEntry = this.lastHistory(this.EveHome.type, this.EveHome.sub);
                    var lastWatts = 0;
                    if (historyEntry && Object.keys(historyEntry).length != 0) {
                        lastWatts = historyEntry.watts;
                    }
                    return lastWatts;
                });

With the validation, seems cannot cast in a function to return the value???

**Comment by ebaauw** [comment]
You’re passing the function definition as argument, which obviously isn’t a numeric value.  You need to call the function, to pass its result to `updateValue()`.  Change the last line to `})())`.

I don’t understand why you want to define a function for this in the first place.  I’d just use the function block (without the `return`) and then use `updateValue(lastWatts)`.

**Comment by Supereg** [comment]
Closing the issue as it was resolved by @ebaauw.
