### ISSUE TITLE
HoldPosition doesn’t work

### ISSUE THREAD

**Issue by TheNON75** [homebridge/HAP-NodeJS#908]
**Describe The Bug:**

The HoldPosition (bool) doesn't work.
If value 1 is sent, According to the specification:
"A write to ”9.117 Target Position” (page 229) characteristic will release the hold."
Instead nothing happens

**To Reproduce:**

By using door, window or WindowCovering service with a valid TargetPostion and a different CurrentPosition, send ```HoldPosition:1```

**Expected behavior:**

TargetPostion that is equal to the actual CurrentPosition shall be the output

**Logs:**

**Screenshots:**

**Environment:**

* **Node.js Version**: 
10.24.1
* **NPM Version**: 
6.14.12
* **Operating System**: Docker
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by Supereg** [comment]
HAP-NodeJS doesn’t implement characteristic logic. You need to implement that yourself as any other characteristic.
