### ISSUE TITLE
Trying to trace this *very* intermittent error with video streams

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#914]
### Current Situation

Occasionally with been seeing the following error pop up in my logs

"Selected RTP Stream Configuration] Unhandled error thrown inside write handler for characteristic: Cannot read properties of undefined (reading 'stopPlayback')"

Not sure where to start looking for it. Not sure if its being generated within the HAP library itself or something my accessory throws when doing video?

Any help appreciated

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

### Additional Context

 .

**Comment by Supereg** [comment]
Looking at the error message `"[Selected RTP Stream Configuration] Unhandled error thrown inside write handler for characteristic: Cannot read properties of undefined (reading 'stopPlayback')"` I deduct the following information:
* You are running some sort of camera accessory (or homebridge plugin). Can you list those?
* The implementation of the camera is thrown the error `Cannot read properties of undefined (reading 'stopPlayback')` in its `CameraStreamingDelegate`, specifically in the `handleStreamRequest` implementation.

If you enable `DEBUG=HAP-NodeJS:Accessory` you will also see a detailed stack trace of the error. This will probably make it easier where exactly this error was thrown.
