### ISSUE TITLE
Siri via third party accessories 

### ISSUE THREAD

**Issue by M-Whitaker** [homebridge/HAP-NodeJS#915]
### Current Situation

At the 2021 keynote Apple announced support for HomeKit accessories to forward Siri requests to a HomePod. I can't find any developer documentation for it, nevertheless, I think it would be a great feature to have, assuming it doesn't require a mfi certification 

### Proposed Change

Introduce a system for capturing audio data for a Siri command and forwarding it onto HomePod for processing 

### Additional Context

As I said before the fact that I can't find any dev documentation or references apart from this user documentation: https://support.apple.com/en-gb/guide/homepod/apd049cbc929/homepod doesn't give me much hope but this is a request nonetheless even to just get some documentation

**Comment by Supereg** [comment]
You pretty much answered your own question. This feature isn't openly documented and isn't trivially reversed just by looking at the services and characteristics definitions (we got those at least). I would assume (from what I have seen), that the feature is relatively similar to how Siri support for HomeKit based Apple TV Remotes works.
However, to implement this, we need people who take a shot at reverse engineering the feature fully. To my knowledge, no one is currently working at this. But any contribution would be well appreciated.

**Comment by M-Whitaker** [comment]
Thanks for the reply, I think its worth the documenation if nothing else. I was maybe hoping for someone to have started the reverse enginnering however in relection the newness of the feature that was maybe too optomistic.

**Comment by Supereg** [comment]
In any case, it could be helpful to compile a list of available accessories that support that feature. Could be helpful to anyone who might be interested in reversing the feature.
