### ISSUE TITLE
Future Matter Support - Anything Being Contemplated?

### ISSUE THREAD

**Issue by jvmahon** [homebridge/HAP-NodeJS#921]
### Current Situation

I regularly use HomeBridge to bridge my z-wave devices on Hubitat to iOS. Works great.

I also have some plugins on Hubitat to bridge to Google Home / Alexa. Those aren't nearly as good as homebridge.

Was wondering - given the "unifying" Matter standard, does anybody know of any homebridge-like projects that may be considering Matter support?

### Proposed Change

Apple has indicated that there will be a SDK that essentially allows HomeKit HAP to be translated to matter. See at about 3:00 in this video: https://developer.apple.com/videos/play/wwdc2021/10298/

So, it seems that hap-nodeJS / Homebridge might be able to be adapted to do a similar translation.  I.e., it seems that, at the very least, Apple is likely influencing the Matter standard so that there is a mapping between Homekit HAP and Matter that can be used to translate / map between the protocols, so in simple terms, it seems like the back-end of Hap-NodeJS that actually talks to the iOS devices could be mapped to send/receive Matter formatted date while still allowing the current homebridge plugins to work (with little / no modification).  I was just wondering if that was something being considered.

### Additional Context

This is a bit early as the standard still isn't finalized, I was just wondering what the authors / main contributors to homebridge and hap-nodejs might be thinking about this topic and the future of homebridge / hap-nodejs.

**Comment by Supereg** [comment]
> Apple has indicated that there will be a SDK that essentially allows HomeKit HAP to be translated to matter. See at about 3:00 in this video: https://developer.apple.com/videos/play/wwdc2021/10298/

What you are here referring to is the client side. iOS apps which use the HomeKit framework (e.g. Home App or apps like Eve) can directly integrate with Matter devices through the existing APIs. This has nothing to do with the accessory server interface. 

But yeah. I already though about this as well. Depending how much internal refactoring is required we might consider adding support for Matter. Maybe not directly into `hap-nodejs` (after all this package is about the HAP protocol and shouldn't turn into a monolith), but maybe as a separate package used within homebridge to translate HAP-NodeJS' API into a Matter interface. This could allow use to expose the huge amount of homebridge plugins to the Matter world. I think this could be very well worth it.
But I haven't really looked at the spec at much detail. So not sure how feasible this is from a technical perspective.


So ...

> I was just wondering if that was something being considered.

... yes. But no idea if we actually get to this point.
As you said: 

> This is a bit early as the standard still isn't finalized.
