### ISSUE TITLE
Unexpected error when restarting HB if HSV recording is still running

### ISSUE THREAD

**Issue by seydx** [homebridge/HAP-NodeJS#926]
### Analysis

<img width="1271" alt="Bildschirmfoto 2022-01-16 um 18 29 05" src="https://user-images.githubusercontent.com/34152761/149672170-46ad8beb-6b7d-4c9a-9ae5-f32673d6cb7b.png">

### Expected Behavior

Suppress the error message when the system is restarted

### Steps To Reproduce

1. Trigger HSV recording
2. Restart HB while HSV recording is still running

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- Software: HB v1.4-beta.4
- Node: v16.13.0
- npm: 8.1.0

### Process Supervisor

hb-service

**Comment by Supereg** [comment]
Thanks for reporting 🚀 

The issue was fixed in `hap-nodejs@0.10.0-beta.15`/`homebridge@1.4.0-beta.8`.
