### ISSUE TITLE
Memory Leak in HKSV.

### ISSUE THREAD

**Issue by hjdhjd** [homebridge/HAP-NodeJS#931]
### Analysis

There seems to be a persistent memory leak occurring when HKSV is used in HAP-NodeJS. After turning on warnings in Node...I've tracked it down to:

```
(node:31143) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 closed listeners added to [HAPConnection]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at HAPConnection.addListener (node:events:487:10)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/datastream/DataStreamServer.ts:736:27
    at DataStreamServer.handleSessionIdentification (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/datastream/DataStreamServer.ts:370:5)
    at DataStreamConnection.emit (node:events:390:28)
    at DataStreamConnection.onSocketData (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/datastream/DataStreamServer.ts:727:12)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
```

They largely seem to occur when HomeKit decides to cancel an HKSV event recording. I suspect things aren't getting fully cleaned up. It may occur in other circumstances as well, but this is as best I can pin it down at this time:

The sequence in question involves HAP-NodeJS calling `handleRecordingStreamRequest` and then later sending a `closeRecordingStream` request with `HDSProtocolSpecificErrorReason.CANCELLED` specified as the reason.

As more people deploy HKSV-based solutions, I expect you'll see more data points like this one.

### Expected Behavior

No memory leaks. :smile:

### Steps To Reproduce

See above...

### Logs

```markdown
See above...
```

### Configuration

```json
Unneeded.
```

### Environment

Unneeded.

### Process Supervisor

pm2

**Comment by louis49** [comment]
Same with --trace-warnings option : 

(node:67537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added to [HAPConnection]. Use emitter.setMaxListeners() to increase limit at _addListener (node:events:601:17) at HAPConnection.addListener (node:events:623:10) at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/datastream/DataStreamServer.ts:736:27 at DataStreamServer.handleSessionIdentification (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/datastream/DataStreamServer.ts:370:5) at DataStreamConnection.emit (node:events:526:28) at DataStreamConnection.onSocketData (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/datastream/DataStreamServer.ts:727:12) at Socket.emit (node:events:526:28) at addChunk (node:internal/streams/readable:324:12) at readableAddChunk (node:internal/streams/readable:297:9) at Socket.Readable.push (node:internal/streams/readable:234:10)
writeOut                                    	warning:50
onWarning                                   	warning:112
emit                                        	events:526
process.emit                                	source-map-support.js:516
doEmitWarning                               	warning:77
processTicksAndRejections                   	task_queues:82
Async call from TickObject
init                                        	inspector_async_hook:25
emitInitNative                              	async_hooks:201
emitInitScript                              	async_hooks:506
nextTick                                    	task_queues:133
emitWarning                                 	warning:155
_addListener                                	events:609
addListener                                 	events:623
(anonymous function)                        	DataStreamServer.js:568
DataStreamServer.handleSessionIdentification	DataStreamServer.js:261
emit                                        	events:526
DataStreamConnection.onSocketData           	DataStreamServer.js:560
emit                                        	events:526
addChunk                                    	readable:324
readableAddChunk                            	readable:297
Readable.push                               	readable:234
onStreamRead                                	stream_base_commons:190
callbackTrampoline                          	async_hooks:130
Async call from TCPWRAP
init                                        	inspector_async_hook:25
emitInitNative                              	async_hooks:201

**Comment by Supereg** [comment]
hap-nodejs@0.10.2-beta.1 was just pushed with a fix to the originally reported issue. Would be great if you could verify that this issue is solved.

**Comment by n0rt0nthec4t** [comment]
Installed.. Will test for the next few days and see. Also, there a couple of places in the HKSV lib code (RTPStreamManagement) which output via console.log rather than debug ie: turning off video recording outputs etc.. Intentional or need a PR to update?

**Comment by n0rt0nthec4t** [comment]
@Supereg haven't seen the memory leak over the past 24hrs with the beta release

**Comment by Supereg** [comment]
Thanks for the notice. 0.10.3 was released with a fix for the above reported issue (which I, myself could reproduce and fix).

@hjdhjd has reported that there is seemingly still some other issue. We are currently investigating this within the 0.10.3 beta line. Still keeping the issue open for now.

**Comment by n0rt0nthec4t** [comment]
@Supereg no worries. The other weird thing I've seen, there are occasions where if for example a recording is in progress and for whatever reason get a code crash, then restart the accessory, the recording gets trigger immediately even if the associated motion sensor says no motion. I've put a check in my code when entering "handleRecordingStreamRequest" that if no motion, don't trigger associated recording that is required.

Seems like there is some stateful config being maintained?

**Comment by hjdhjd** [comment]
> @Supereg no worries. The other weird thing I've seen, there are occasions where if for example a recording is in progress and for whatever reason get a code crash, then restart the accessory, the recording gets trigger immediately even if the associated motion sensor says no motion. I've put a check in my code when entering "handleRecordingStreamRequest" that if no motion, don't trigger associated recording that is required.
> 
> Seems like there is some stateful config being maintained?

@n0rt0nthec4t Please open a different issue if you have something to report that's a bug...this thread is strictly for the memory leak issue that we've been working through. Anecdotally, I've got the largest major plugin deployment with a large user population using HKSV for months and I haven't seen anything like that...my suggestion and suspicion is to look more closely at your own code first, or take a look at some of the other implementations or the sample in HAP-NodeJS for inspiration...it works as intended, in my experience.

Now, back to our regularly scheduled bug hunting.

**Comment by n0rt0nthec4t** [comment]
@hjdhjd snarky or WHAT.. Really, who cares if you have "largest major plugin deployment with a large user population". Seriously, *blah*
