### ISSUE TITLE
HKSV: characteristic changes??

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#934]
### Current Situation

Starting to develop support for my project to use HKSV. The camera has option to turn on/off Night vision and I'd like to reflect this in HomeKit

Changes to my code allows the camera to been seen as a HKSV in the Home app (not for video recording going yet), but no matter what changes I make updating the "Characteristic.NightVision" attached to the Service.CameraOperatingMode doesn't reflect in the Home app camera settings 

Same also goes for the RecordingaudioActive characteristic. Debug shows no matter what data I put into the characteristics, always remains "true" or 1

 
Code using to set

```javascript
this.cameraController.recordingManagement.operatingModeService.getCharacteristic(Characteristic.NightVision).updateValue((deviceData.irled_enabled == true));

this.cameraController.recordingManagement.recordingManagementService.getCharacteristic(Characteristic.RecordingAudioActive).updateValue(deviceData.audio_enabled == true
    ? Characteristic.RecordingAudioActive.ENABLE
    : Characteristic.RecordingAudioActive.DISABLE);
```
<img width="514" alt="Screen Shot 2022-03-28 at 11 55 34 am" src="https://user-images.githubusercontent.com/19759130/160309426-e974966c-cc92-4fcd-8ad0-2c024d3c0ccb.png">
<img width="518" alt="Screen Shot 2022-03-28 at 11 55 23 am" src="https://user-images.githubusercontent.com/19759130/160309427-e0e0e08a-8553-4881-a9b6-39d3cec65d3a.png">

### Logs

```markdown
 HAP-NodeJS:Accessory [Cam Outdoor 62D7] Setting Characteristic "Active" to value 1 +8ms
  HAP-NodeJS:Accessory [Cam Outdoor 62D7] Setting Characteristic "Active" to value 1 +1ms
  HAP-NodeJS:Accessory [Cam Outdoor 62D7] Setting Characteristic "Active" to value 1 +0ms
  HAP-NodeJS:Accessory [Cam Outdoor 62D7] Setting Characteristic "HomeKit Camera Active" to value 1 +0ms
  HAP-NodeJS:Accessory [Cam Outdoor 62D7] Setting Characteristic "Night Vision" to value true +0ms
  HAP-NodeJS:Accessory [Cam Outdoor 62D7] Setting Characteristic "Event Snapshots Active" to value true +1ms
  HAP-NodeJS:Accessory [Cam Outdoor 62D7] Setting Characteristic "Periodic Snapshots Active" to value true +0ms
  HAP-NodeJS:Accessory [Cam Outdoor 62D7] Setting Characteristic "Recording Audio Active" to value 1 +0ms
```

### Configuration

```json
....
```

### Environment

- OS Raspbian (buster):
- Software: HAP 0.0.10/iOS 15.4/iPadOS 15.4/macOS 12.3
- Node 17
- npm 

### Process Supervisor

not applicable

**Comment by adriancable** [comment]
At least the RecordingAudio characteristic is set by the HomeKit side, not the accessory side. The value for its characteristic will be 1 if the 'record audio' slider under 'More Options' is turned on, and 0 otherwise. You can't override this setting on the accessory side.

Yes, HAP-NodeJS in its code to serialize/deserialize the recording management service, writes to the RecordingAudio characteristic, and also other characteristics on the recording management service that are also set only by the HomeKit side like Characteristic.Active. I am pretty certain this is a mistake in HAP-NodeJS, although writes to these characteristics from accessories seem to be a no-op.

Hope this helps.

**Comment by n0rt0nthec4t** [comment]
Yep, I get the feeling hap-nodejs is forcing these states and shouldn’t be.. @Supereg

**Comment by Supereg** [comment]
> I am pretty certain this is a mistake in HAP-NodeJS, although writes to these characteristics from accessories seem to be a no-op.

It's not. State of those characteristics need to be persisted across reboots. This is exactly what's happening in the `deserialize` method which is called on startup. In this sense we are not writing a _new_ value, but just maintain the current value.

> Changes to my code allows the camera to been seen as a HKSV in the Home app (not for video recording going yet), but no matter what changes I make updating the "Characteristic.NightVision" attached to the Service.CameraOperatingMode doesn't reflect in the Home app camera settings

This is not the first time I heard, that changing those values aren't reflected on the HomeKit side. Not sure what characteristics the previous reports were about. I would assume that stuff like RecordingAudioActive just isn't meant to be configurable from an accessory side. Equally NightVision. I could envision that a Camera accessory is not allowed to e.g. just switch on night vision if it was previously turned off by the user. Maybe that's the reason, accessory updates to those characteristics aren't handled by the Home App?

**Comment by n0rt0nthec4t** [comment]
I guess the issue I see is, an accessory SHOULD be able to set it status for NightVision,  CameraOperatingModeIndicator etc WITHOUT HAP (or HomeKit) always forcing the value to these

**Comment by Supereg** [comment]
It's definitely not HAP/Homebridge which is interfering here. `NightVision` has NOTIFY permissions set.
