### ISSUE TITLE
Snapshot interval change 10s -> 60s for some cameras in iOS 15.4?

### ISSUE THREAD

**Issue by adriancable** [homebridge/HAP-NodeJS#935]
@Supereg / @sunoo

We have noticed that there's a change in snapshot interval behaviour in iOS 15.4. Some cameras (but not all) now have a snapshot update interval of 60s whether you are inside your home network, or outside (Previously 10s when inside, 60s when outside.) Looking at 'commercial' cameras (not Homebridge) the pattern seems to be that the interval is 60s for battery-powered cameras, but 10s when plugged in. It feels like possibly some characteristic has been added or changed recently to allow cameras to tell HomeKit whether to request snapshots at a 60s interval (presumably to save power) or a 10s interval (for more frequent updates).

For now, Homebridge cameras (which of course do not implement this mystery mechanism) apparently now always run on 60s instead of 10s updates, even when inside the home network, so this is effectively a regression.

Any ideas? Any new or changed characteristics in iOS 15.4 that could account for this?

**Comment by Supereg** [comment]
Interesting. I would assume that without changing something on the camera side, Home should still request 10s snapshots. Otherwise this would be a breaking change on Apples side. I mean there are other HomeKit certified cameras which should equally work without requiring an update.
Not sure how this new „mode“ works and how one advertises feature set, but any data points from HomeKit camera owners would be helpful.
I would assume that there is something either in the mDNS advertisement or in the accessory database (e.g. some sort of characteristic).

Are your cameras which you are testing it with bridged or standalone accessories? Maybe that has something to do with?

**Comment by adriancable** [comment]
@Supereg - regarding your first sentence, you might assume so, but Apple are no stranger to the breaking change.

Your question about bridged vs. standalone cameras is interesting. My experiments have been with bridged cameras only. I will try both and see if there is any difference in behaviour.

I believe the HomeKit Accessory Simulator can create bridged and unbridged cameras, so I will also try that and report back.

**Comment by adriancable** [comment]
Additional update: maybe bridged vs unbridged does have something to do with it. Having left HAS and the Home app running for a few minutes with the bridged and unbridged camera displayed, the unbridged camera is continuing to update every 10s but the bridged camera is now updating every 60s.

**Comment by california444** [comment]
I have observed the same behavior. 
After changing to unbridged the camera now updates every 10s again

**Comment by Supereg** [comment]
> Additional update: maybe bridged vs unbridged does have something to do with it. Having left HAS and the Home app running for a few minutes with the bridged and unbridged camera displayed, the unbridged camera is continuing to update every 10s but the bridged camera is now updating every 60s.

This would be the most likely explanation for now. Are there commercial, HomeKit certified, bridged cameras out there? As my standalone HomeKit certified cameras continue to update in an 10s interval it definitely seems to be bridge related.

> Update: created a bridged and unbridged camera in the HAS and added them both. Updates at 10s over the LAN in both cases. So it isn't that.

Oh wait. So the HomeKit simulator created camera also updates at 10s over LAN? 

So the question really is, is this something Apple/HomeKit forces on us or which we have control over?

**Comment by adriancable** [comment]
@Supereg - I'm not sure what changed, or if I was mistaken, but with the HomeKit Accessory Simulator, the bridged camera updates every 60s over LAN, but the unbridged camera updates every 10s over LAN.

So there are two possibilities: either a recent version of iOS (?) introduced a bug with bridged cameras, or there is some additional setting/characteristic that's required for bridged cameras to update every 10s, that we are not setting.

> So the question really is, is this something Apple/HomeKit forces on us or which we have control over?

Yes, that is the question! How would we know if we have control over it? To my knowledge, there are not many (any?) commercial bridged cameras, which means presumably it's hard to know if we're setting them up correctly i.e. if this issue is our bug, or HomeKit's bug.
