### ISSUE TITLE
Change CharacteristicDefinitions.ts and ServiceDefinitions.ts into json file so they can be shared with other HomeKit implementation

### ISSUE THREAD

**Issue by klem-everywhere** [homebridge/HAP-NodeJS#936]
### Current Situation

Now HAP-NodeJS and other implementation (esp-homekit, HAP-python, homekit_python,  aiohomekit, etc) all generate Characteristic and Service in their own way, I'm also writing my own.

### Proposed Change

Make it into json so all projects can use it.

**Comment by klem-everywhere** [comment]
Just found /System/Library/PrivateFrameworks/HomeKitDaemon.framework/Resources/plain-metadata.config

**Comment by NorthernMan54** [comment]
Personally I just write my own parser module against the source files, and include it as part of the build process.

https://github.com/NorthernMan54/Hap-Node-Client/blob/master/scripts/gen-hap-types.js
