### ISSUE TITLE
Is it known how Characteristic.AppMatchingIdentifier works?

### ISSUE THREAD

**Issue by adriancable** [homebridge/HAP-NodeJS#940]
As is well known, the Home app can shows links to vendor apps in the settings page for a HomeKit device:

![IMG_FFA7FE033653-1](https://user-images.githubusercontent.com/6544927/163467012-4b91be55-130b-4af3-aa31-071b4e9cd63e.jpeg)

My understanding is that this is enabled by setting Characteristic.AppMatchingIdentifier on the AccessoryInformation service.

Does anyone know how this is actually achieved in practice? Looking online, there are plugins that do something like:

 ... .setCharacteristic(Characteristic.AppMatchingIdentifier, 'com.aqara.aqara');

But this doesn't actually work, and I don't think it can be right even in theory, because this characteristic is TLV format not string.

Does anyone have a dump or something of what the value for this characteristic is, from a 'real' HomeKit device?

**Comment by Supereg** [comment]
Not sure if I ever saw a certified accessory which actually had this characteristic included.
I know my Eve Light Strip doesn't have it.

I tested some random WiFi light switch which has a pretty minimal AccessoryInformation service: Name, Manufacturer, Model, SerialNumber, Identify and FirmwareRevision. That's all. And still the App is displayed. I also mirrored this accessory and the App is also displayed on the non certified accessory (with the same info). So maybe the App info is pulled out via manufacturer and model data?

The AppMatchingIdentifier was also never documented in the HAP spec sheet. So I would assume it is deprecated?

But in any case one would supply the [App ID](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/AppID.html), I would assume. But as you said, absolutely no idea what the TLV format is.

**Comment by adriancable** [comment]
@Supereg - a little more insight in this. It seems that for the 'matching app' widget to be displayed, there are two conditions:

- the Characteristic.Manufacturer value must exactly match (case sensitive) the manufacturer string of the App Store app, for example in the screenshot above `Signify Netherlands B.V.`
- there must be at least one 'matching' App Store app which has the HomeKit entitlement

If these are both true, the widget will be displayed, otherwise it will not be. It doesn't appear that Characteristic.AppMatchingIdentifier is used.

**Comment by 0x5e** [comment]
> @Supereg - a little more insight into this, after some experimentation. It seems that for the 'matching app' widget to be displayed, there are two conditions:
> 
> * the Characteristic.Manufacturer value must exactly match (case sensitive) the manufacturer string of the App Store app, for example in the screenshot above `Signify Netherlands B.V.`
> * there must be at least one 'matching' App Store app with that manufacturer string, **which has the HomeKit entitlement**
> 
> If these are both true, the widget will be displayed, otherwise it will not be. It doesn't appear that Characteristic.AppMatchingIdentifier is used.

Hi, I tried with manufactor exactly same as my app, and the app with homekit entitlements already on the appstore for years, but still not work.

with or without AppMatchingIdentifier, I got the same result.

**Comment by adriancable** [comment]
@0x5e - as I explained above, AppMatchingIdentifier is not used by HomeKit in any way. This is why your experiments with AppMatchingIdentifier did not work.

**Comment by 0x5e** [comment]
> @0x5e - as I explained above, AppMatchingIdentifier is not used by HomeKit in any way. This is why your experiments with AppMatchingIdentifier did not work.

Yes, I mean, the manyfactor did not work too.
