### ISSUE TITLE
Info: Affacted by network family change in Node.js 18 : "IPv4" is now 4 ??

### ISSUE THREAD

**Issue by Apollon77** [homebridge/HAP-NodeJS#945]
### Analysis

mainly an info because I found IPv4 as String in the code... 

See: https://github.com/nodejs/node/pull/41431#pullrequestreview-929717323

### Expected Behavior

Considers when working on Node.js 18 compatibility

### Steps To Reproduce

n/a

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

Node.js 18

### Process Supervisor

not applicable

**Comment by oznu** [comment]
Fixed as of v0.10.2-beta.3

A release will come shortly.
