### ISSUE TITLE
How does Ecobee do this?

### ISSUE THREAD

**Issue by adriancable** [homebridge/HAP-NodeJS#951]
### Current Situation

Take a look at this: https://youtu.be/zrNCGYbx5dQ

Look at around 2:34. You’ll see a bunch of slider controls as part of the accessory which look very non-standard (Intercom, Analytics & Improvements etc.) How is that done - and, how would we go about finding out how that is done?

I wasn’t aware of any HomeKit services or characteristics to add custom settings. Are there missing services/characteristics in HAP-NodeJS?

**Comment by NorthernMan54** [comment]
Looking at the video, I'm wondering if it has Embedded Siri, and those are the Siri controls.

**Comment by adriancable** [comment]
@NorthernMan54 - if you look at 1:54, you can see the Embedded Siri controls. But if you look at around 2:30, you will see other settings which I don't think are related to Siri, e.g. 'Analytics & Improvements'. So I'm not really sure this explains it.

**Comment by Supereg** [comment]
This might be the Diagnostics service (see https://github.com/homebridge/HAP-NodeJS/blob/f20ee4ba4f0f5192761e1f36b73bca9a09b1c47b/src/lib/definitions/ServiceDefinitions.ts#L510). Could be a required service if you want to implement on-device Siri.

**Comment by adriancable** [comment]
@Supereg - that's an interesting thought. Do you have any ideas how to use this? It would be very nice for many (most?) plug-ins to be able to implement custom settings controls in a HomeKit device's settings.

**Comment by adriancable** [comment]
I'd like to add - if you have the tools to figure out how the new Ecobee thermostat does all this (including embedded Siri) and you think it would be useful to the Homebridge community to dig into it, I would be more than happy to donate a new Ecobee thermostat if that would be helpful. Please feel free to send me an email if that might be of interest.
