### ISSUE TITLE
HomeKit supports Filter characteristics on AirPurifier, but the HAP-NodeJS doesn't

### ISSUE THREAD

**Issue by OrigamiDream** [homebridge/HAP-NodeJS#954]
### Analysis

Homebridge API document indicates that following characteristics can only work with `FilterMaintenance` service.
- `FilterLifeLevel`
- `FilterChangeIndication`
- `FilterResetChangeIndication`

However, the characteristics officially support the `AirPurifier` service, too
Reference: [Apple Developers](https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types), Section **`Purifiers and Filters`**

And I could find the Filters section in Home app that the characteristics have properly added.

At first, I thought the problem occurs on the `homebridge` side, but I figured out this is handled by `HAP-NodeJS`
Reference: [homebridge/bridgeService.ts#L16](https://github.com/homebridge/homebridge/blob/749be2a5ec72fbae5f5387c89046d01b9cf62a4f/src/bridgeService.ts#L167)

### Expected Behavior

If I add the characteristics on `AirPurifier` service, the Homebridge warns:
```
This plugin generated a warning from the characteristic 'Filter Life Level': Characteristic not in required or optional characteristics section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
```

However, the warnings must be removed in this case.

### Steps To Reproduce

1. Create a sample plugin that supports `AirPurifier` service.
2. Add the characteristics on the service.
3. Run the plugin on Homebridge.
4. Ta-da

### Logs

I only have `homebridge` outputs
```markdown
[5/25/2022, 6:04:50 PM] [homebridge-test-platform] This plugin generated a warning from the characteristic 'Filter Life Level': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[5/25/2022, 6:04:50 PM] [homebridge-test-platform] This plugin generated a warning from the characteristic 'Filter Change Indication': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
```

### Configuration

No configuration needed
```json
```

### Environment

- **OS**: macOS Monterey 12.4
- **Homebridge**: v1.4.1
- **Node**: v18.0.0
- **npm**: v8.10.0

### Process Supervisor

hb-service

**Comment by Supereg** [comment]
As a reference. You may use [Service.addCharacteristic](https://developers.homebridge.io/HAP-NodeJS/classes/Service.html#addCharacteristic) to arbitrarily add any characteristics to your service yourself.
HAP-NodeJS provides a default definition for all services and characteristics as defined by Apple or uncovered through reverse engineering.

**Comment by OrigamiDream** [comment]
@Supereg Of course I know, but the "default definition" have been changed by Apple.
This must be reflected to the HAP-NodeJS definition.
