### ISSUE TITLE
New iOS beta 3 related issues

### ISSUE THREAD

**Issue by mikegapinski** [homebridge/HAP-NodeJS#97]
Hey, 

I have just updated my iOS to current beta and I have multiple problems with HAP. Sometimes the accessories just don't pair, sometimes the password prompt just does not show. Did they change some homekit related stuff or it's just related to HAP itself? I figured a way for adding accessories, just reboot the iOS device after adding one accessory. I can add one more after reboot and it goes over and over.

**Comment by KhaosT** [comment]
Strange, I didn't see these issues. Can you post logs from iOS side?

**Comment by mikegapinski** [comment]
Sure, I'll just make sure all is correct on my side. Restore and fresh HAP install first

**Comment by legotheboss** [comment]
I'm having the same issues. Sometimes HAP just doesn't connect. The logs on both sides don't seem to have any errors

**Comment by nzhome** [comment]
Same here, I have the same problem.

**Comment by WoodySlum** [comment]
Had also some troubles with iOS 9.1 final - clearing the content of persist folder and restarting HAP fixed the problem.
