### ISSUE TITLE
Disable or provide configuration on HKSV camera logs

### ISSUE THREAD

**Issue by x-magic** [homebridge/HAP-NodeJS#975]
### Current Situation

Homebridge's log get polluted with messages like "STREAMING DISABLED ACTIVE". 
I have noticed such behaviour when I setup `homebridge-unifi-protect` and set some cameras as "detective activity" mode. 

### Proposed Change

After raising issue with hjdhjd/homebridge-unifi-protect#804, I have realised that the message could come from somewhere else in the chain, and a bunch of search leads me here. 

The line of code in mind is here: (the version currently installed on my setup is v0.10.2)
https://github.com/homebridge/HAP-NodeJS/blob/f20ee4ba4f0f5192761e1f36b73bca9a09b1c47b/src/lib/camera/RTPStreamManagement.ts#L694

Currently it seems those logs are arbitrarily printed directly into the log without identifiers/tags. I wonder if those logs can be disabled by providing a configuration setting. 

### Additional Context

See the screenshot below: 
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/3180639/193403169-bd13456f-9c79-4145-8a21-0f3e969d2e35.png">

**Comment by Supereg** [comment]
Oh, seems like a left over debug print 🙊 thanks for reporting 🚀

**Comment by Supereg** [comment]
This was fixed already in HAP-NodeJS [v0.10.3](https://github.com/homebridge/HAP-NodeJS/releases/tag/v0.10.3) within this commit https://github.com/homebridge/HAP-NodeJS/commit/5ffff952b26f32cd78ee7b80622c764d304dca09.

There is currently no corresponding homebridge release (1.5.1 is about to be release). However, reinstalling the 1.5.1. should pull in the latest 0.10.x version of HAP-NodeJS
