### ISSUE TITLE
Doesn't fallback from systemd-resolved advertiser if MulticastDNS is disabled.

### ISSUE THREAD

**Issue by Supereg** [homebridge/HAP-NodeJS#980]
### Analysis

For some (many?) configurations systemd-resolved `MulticastDNS` option is disabled by default. See the `MulticastDNS` option: https://linuxreviews.org/Systemd-resolved.

This results in the following error when starting up with `RESOLVED` advertiser enabled in HAP-NodeJS:
```
Could not create mDNS advertisement. The HAP-Server won't be discoverable: Error: dbusInvoke error: ["Support for MulticastDNS is disabled"]
```

Also the original PR #965 added instructions to enable permissions for mdns advertising. This should be explained in the documentation!

### Expected Behavior

This should be checked at startup within the `ResolvedAdvertiser.isAvailable()` function, if `RESOLVED` is actually available on the platform, in order to fall back to a supported advertiser in the erroneous case.

### Steps To Reproduce

1. Setup `/etc/systemd/resolved.conf` to disable the `MulticastDNS` option.
2. Startup HAP-NodeJS instance with advertiser set to `MDNSAdvertiser.RESOLVED`.
3. See the supplied output.

### Logs

```markdown
Could not create mDNS advertisement. The HAP-Server won't be discoverable: Error: dbusInvoke error: ["Support for MulticastDNS is disabled"]
```

### Configuration

```json
-
```

### Environment

- OS: Ubuntu 20.04
- Software: 0.11.0 beta
- Node: v10.19.0
- npm: 6.14.4

### Process Supervisor

not applicable

### Additional Context

CC: @elyscape

**Comment by elyscape** [comment]
Good catch. It should be fairly simple to add a check for this to `isAvailable()`. I'll give it a go tomorrow.

**Comment by Supereg** [comment]
Is there a way to query the systmed dbus interface to check if the MulticastDNS option is enabled? Or is the only way to probe if we are successful in advertising our service?

Also, could you write a short abstract for this Wiki page (https://github.com/homebridge/homebridge/wiki/mDNS-Options) about what steps you need to do to configure the resolved advertiser (e.g. including the link above on how to enable the MulticastDNS option and also to set the permissions so homebridge/hap-nodejs is actually allowed to access it).

Lastly, what error message is thrown if the respective user doesn't have permissions to access the interface? We should definitely also catch that in the `isAvailable` method.

**Comment by elyscape** [comment]
> Is there a way to query the systmed dbus interface to check if the MulticastDNS option is enabled?

That's exactly what I intend to do, actually.

> Also, could you write a short abstract for this Wiki page (https://github.com/homebridge/homebridge/wiki/mDNS-Options) about what steps you need to do to configure the resolved advertiser (e.g. including the link above on how to enable the MulticastDNS option and also to set the permissions so homebridge/hap-nodejs is actually allowed to access it).

I don't have permissions to edit it directly, but I'll write a blurb and post it in a comment here so that you or someone else can add it in.

> Lastly, what error message is thrown if the respective user doesn't have permissions to access the interface? We should definitely also catch that in the isAvailable method.

So the problem here is that, depending on the system configuration, there are several different errors that could be returned. The list of possible errors is:

- `org.freedesktop.DBus.Error.AccessDenied`
- `org.freedesktop.DBus.Error.AuthFailed`
- `org.freedesktop.DBus.Error.InteractiveAuthorizationRequired`

We could look for all three of those, I suppose.

**Comment by elyscape** [comment]
I just did some digging and checking for those error messages is going to be complicated because `dbus-native` doesn't currently expose the `ERROR_NAME` when a method call fails, instead exposing only the error message body, which is an optional human-readable error message.

**Comment by Supereg** [comment]
> I don't have permissions to edit it directly, but I'll write a blurb and post it in a comment here so that you or someone else can add it in.

Yeah, we recently took the Wiki pages collaborators-only for an unspecified time frame. So, just write the markdown into this issue or the referenced PR and I will update the Wiki page for you. Thanks a lot 🚀 

> So the problem here is that, depending on the system configuration, there are several different errors that could be returned. The list of possible errors is: [...]

Thanks a lot for the research! 🚀

> I just did some digging and checking for those error messages is going to be complicated because `dbus-native` doesn't currently expose the `ERROR_NAME` when a method call fails, instead exposing only the error message body, which is an optional human-readable error message.

We maintain a fork of `dbus-native` here: [homebridge/dbus-native](https://github.com/homebridge/dbus-native).
How much work would be required to adapt the `dbus-native` implementation? Is this easy to so, is it worth it? We are currently the only one actively using that fork. However, we can do a `major` version increment and properly announce the breaking change within the release notes.
Consequentially, we could look into trying to get this change into the upstream as well once it works with our implementation.

**Comment by elyscape** [comment]
> How much work would be required to adapt the dbus-native implementation? Is this easy to so, is it worth it?

It's pretty easy to change. The message handler code [currently looks like this][handler]:
```javascript
if (handler) {
  delete self.cookies[msg.replySerial];
  var props = {
    connection: self.connection,
    bus: self,
    message: msg,
    signature: msg.signature
  };
  var args = msg.body || [];
  if (msg.type === constants.messageType.methodReturn) {
    args = [null].concat(args); // first argument - no errors, null
    handler.apply(props, args); // body as array of arguments
  } else {
    handler.call(props, args); // body as first argument
  }
}
```
We could change the call to `handler.call()` to something like:
```javascript
handler.call(props, {name: msg.errorName, message: args});
```
This would result in the callback passed to `MessageBus.invoke()` having the following shape:
```typescript
function invokeCallback(err: (null | {name: string, message: any}), message: any) : void;
```
Is it worth it? I dunno. Do we use this library anywhere else, or just in the mDNS advertiser code?

[handler]: https://github.com/homebridge/dbus-native/blob/65b75c22257b435720b85ee923cdda036a2afa8d/lib/bus.js#L127-L142

**Comment by Supereg** [comment]
> Is it worth it? I dunno. Do we use this library anywhere else, or just in the mDNS advertiser code?

I feel like your proposed change is a sensible solution to the problem. I think there isn't really a solution without breaking the current interface. The library is currently only used within the mDNS advertiser code.

So I would propose the following next steps:
1. Open a PR at the [`dbus-native` fork](https://github.com/homebridge/dbus-native) to change the callback signature. Once merged, I push an `major` increment release to signal the breaking change.
2. Once release release, update to the latest version and adapt the type declaration inside HAP-NodeJS (https://github.com/homebridge/HAP-NodeJS/blob/deeb8d1eb00113828dc2b698f4826ad14e13fabf/src/types/dbus-native.d.ts#L11) to accommodate for the updated signature. You can just include that in the #982 PR.

**Comment by elyscape** [comment]
> Open a PR at the [dbus-native fork](https://github.com/homebridge/dbus-native) to change the callback signature.

On it.

> Once merged, I push an major increment release to signal the breaking change.

Since `dbus-native` is pre-1.0.0, you could probably just bump the minor version number (i.e. bump from v0.4.2 to v0.5.0).

**Comment by Supereg** [comment]
Issue is resolved in the latest beta release `0.11.0-beta.11`.

**Comment by elyscape** [comment]
Here's the info for the wiki page:

    ### systemd-resolved (Linux only, experimental)

    As of Homebridge VERSION, Linux users can choose the `resolved` advertiser, which uses systemd-resolved via D-Bus. If your system already uses systemd-resolved for mDNS support, this will likely provide the best experience. You can check this by running `resolvectl mdns`; if the first line is `Global: yes`, you should use this advertiser.

    The user that runs Homebridge must have permission to register and unregister DNS-SD services with systemd-resolved. If you installed Homebridge using the official `apt` package, this should be handled for you automatically. Otherwise, you'll need to create a file in `/etc/polkit-1/localauthority/30-site.d` named `homebridge.pkla` with the following contents:

    ```
    [Homebridge RegisterService]
    Identity=unix-user:homebridge
    Action=org.freedesktop.resolve1.register-service
    ResultAny=yes

    [Homebridge UnregisterService]
    Identity=unix-user:homebridge
    Action=org.freedesktop.resolve1.unregister-service
    ResultAny=yes
    ```

    If you run Homebridge as a different user, you'll need to adjust the `Identity` line accordingly.

I opened homebridge/homebridge-apt-pkg#2 for the apt package. If that doesn't get merged, the second paragraph should be adjusted.

**Comment by Supereg** [comment]
Thanks, I updated the Wiki page
