### ISSUE TITLE
How to run HAP-NodeJS inside Docker container

### ISSUE THREAD

**Issue by buschco** [homebridge/HAP-NodeJS#990]
### Current Situation

I created a simple Accessory with a nodejs http server. Running it from the command line with `node` works as expected.

However if I try to run the same file inside a Docker image I can not find the Accessory inside the Home app.

### Logs

```markdown
2022-12-03T20:15:55.204Z HAP-NodeJS:Advertiser Initializing HAP-NodeJS v0.11.0 ...
2022-12-03T20:15:55.220Z HAP-NodeJS:Accessory [esp-air 762D] Creating new AccessoryInfo for our HAP server
2022-12-03T20:15:55.281Z HAP-NodeJS:Accessory [esp-air 762D] Creating new IdentifierCache
2022-12-03T20:15:55.289Z HAP-NodeJS:Advertiser Preparing Advertiser for 'esp-air 762D' using bonjour-hap backend!
http on 3000, homekit on 51826
2022-12-03T20:15:55.296Z HAP-NodeJS:EventedHTTPServer Server listening on [::]:51826
2022-12-03T20:15:55.297Z HAP-NodeJS:Advertiser Starting to advertise 'esp-air 762D' using bonjour-hap backend!
2022-12-03T20:16:55.256Z HAP-NodeJS:EventedHTTPServer Currently 0 hap connections open:
```

### Configuration

```json
bridge.publish({
  username: "0C:4E:19:2C:A3:82",
  pincode: "210-21-998",
  port: 51827,
});
```

### Environment

- OS: Mac/Linux
- Software: hap-nodejs
- Node: 18
- npm: idk latest u guess

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

Dockerfile:
```
FROM node:18-alpine AS builder

COPY package.json .
COPY index.ts .
COPY yarn.lock .

RUN yarn install --frozen-lockfile
RUN yarn build

FROM node:18-alpine AS runner

COPY --from=builder out/index.js . 

EXPOSE 3000 51826

ENV DEBUG=HAP-NodeJS:*
CMD [ "node", "index.js", "3000", "51826"]
```

**Comment by Shaquu** [comment]
I believe you need to run it in the host mode.

**Comment by Supereg** [comment]
It might be able to have a look at the official homebridge docker image as an inspiration https://github.com/oznu/docker-homebridge.

The primary problem, most likely, is to make sure that the mDNS advertisements reach the „outside“ of the container. That’s the reason to use the container in host mode as of right now.

**Comment by buschco** [comment]
Thanks for the replies!

In my `docker-compose` file I added ` network_mode: host` and removed any other `network`, `ports` and `expose` entries. 

To access the container from another service, this might help https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

```
extra_hosts:
      - "host.docker.internal:host-gateway"
```

and access via `host.docker.internal:<port>`

**Comment by guilhermelirio** [comment]
> 

Hi @buschco 

Could you share how your dockerfile or docker-compose turned out, please?

I'm facing the same problem.

**Comment by buschco** [comment]
@guilhermelirio 

```yaml
  air:
    tty: true
    stdin_open: true
    image: buschco/esp-air-reporter
    restart: always
    network_mode: host
    volumes:
      - persist:/persist
```
