### ISSUE TITLE
How to update the device status from the Socket.io-client

### ISSUE THREAD

**Issue by mandyHoga** [homebridge/HAP-NodeJS#991]
### Current Situation

Hey, Currently we are using socket.io-client to get the device status when its controlled manually. How can we update the device status in HomeKit using the socket.io-client message.
Are there any Events in module that we need to use/listen/emit in the application for real time device status updation?

We have created accessories they are working one way - from Homekit ,but we also need to update the device status in realtime when controlled manually.

### Logs

```markdown
NA
```

### Configuration

```json
socket.on("status", (data) => {
    let messageResponse = data.payload.objects[0].data[0];
//How to use this message response to update the status of device in Homekit
}
```

### Environment

- Windows 10
- Hap nodejs latest
- Node: 16.13.0
- npm: 8.1.0

### Process Supervisor

not applicable

**Comment by Supereg** [comment]
Here are the respective parts from the hap-nodejs technical documentation.

Either Characteristic.updateValue(…)
https://developers.homebridge.io/HAP-NodeJS/classes/Characteristic.html#updateValue

Or Service.updateCharacteristic(…) which is basically the same
https://developers.homebridge.io/HAP-NodeJS/classes/Service.html#updateCharacteristic

**Comment by mandyHoga** [comment]
Hi Supereg,

Thanks for sharing the technical document links.

const onCharacteristic = lightService.getCharacteristic(Characteristic.On);

I'm newbie and little confused. Do we need to change the above code as below.

const onCharacteristic = lightService.updateCharacteristic(Characteristic.On);

or do we need to make changes here.

// with the 'on' function we can add event handlers for different events, mainly the 'get' and 'set' event
onCharacteristic.on(CharacteristicEventTypes.GET, callback => {
  console.log("Queried current light state: " + currentLightState);
  callback(undefined, currentLightState);
});

**Comment by mandyHoga** [comment]
Hi, We have checked the Service.updateCharacteristic(…).

updateCharacteristic(name,value). Here the name is the UUID of the device and the value will be the new value?

We have defined the service as below.

`switch (device.type) {
    case 'SWITCH': {
      const onCharacteristic = service.getCharacteristic(Characteristic.On)

      onCharacteristic.on(CharacteristicEventTypes.GET, callback => {

        console.log("Getting current state of ",device.name ," : " + currentLightState);
        callback(undefined, currentLightState);
      });

      onCharacteristic.on(CharacteristicEventTypes.SET, (value, callback) => {
        console.log("Setting current state of ",device.name ," : " + value);
        currentLightState = value;
        deviceControl(device_ID,value) // calling API to control the device
        callback();
      });
      break;
    }
}`
//=======================

Here do we need to add -  const onCharacteristic = service.updateCharacteristic(Characteristic.On,newValue);

We have the device UUID and the updated state of device from socket.io-client . Now, how can we pass the values to updateCharacteristic.

Can anyone please share any reference link or explain us which makes it clear to understand.

  Can anyone please explain me in detail.  I'm sorry if I'm asking too basic questions but I really wanted to understand the flow so that I can write the logic better.

**Comment by mandy-Tony** [comment]
`
// To inform HomeKit about changes occurred outside of HomeKit (like user physically turn on the light)
// Please use Characteristic.updateValue
//
// lightAccessory
//   .getService(Service.Lightbulb)
//   .getCharacteristic(Characteristic.On)
//   .updateValue(true);
`

I have checked this for reference but still, I'm not sure how the latest value and device UUID is being sent to update the device status.

**Comment by NorthernMan54** [comment]
I think what’s missing in this, is that service.updateCharacteristic is an object which is an instance of the created accessory.

You need to wrap this in logic to map the socketio message to the appropriate accessory instance that was created and published.  Am thinking looking a working example of this may be helpful, and taking a look at a homebridge plugin may be the best option.

For example in my homebridge-Tasmota plugin, I use nodejs events to do the mapping.  Where the message listener ( mqtt ), emit’s an event message with the topic being the device identifier.  And the accessory object is subscribing to events for its device identifier.  It then updates the device status.

A less elegant approach is to maintain an array of accessory objects, with a key being the device identifier, so you can gain access to the appropriate accessory object.
