### ISSUE TITLE
VOC Density characteristic incorrectly set as a float and limited to 1000

### ISSUE THREAD

**Issue by benwebbbenwebb** [homebridge/HAP-NodeJS#995]
### Analysis

The constructor for 'VOC Density', within CharacteristicDefinitions.ts, uses a Float type and has a max vale of 1000.

When I look at the [Apple documentation for this characteristic](https://developer.apple.com/documentation/homekit/hmcharacteristictypevolatileorganiccompounddensity) I believe that this is incorrect and that it should now be a string type and that there should not be an upper limit (or a lower one?).

### Expected Behavior

Change data type

and/or

Remove maxValue limit

### Steps To Reproduce

1. Open code https://github.com/homebridge/HAP-NodeJS/blob/v0.11.0/src/lib/definitions/CharacteristicDefinitions.ts#L4959-L4974
2. Open Apple documentation https://developer.apple.com/documentation/homekit/hmcharacteristictypevolatileorganiccompounddensity
3. Compare types and settings / limits

### Logs

```markdown
No specific log available from HAP-NodeJS

However have seen Homebridge plugins throw warnings:

This plugin generated a warning from the characteristic 'VOC Density': characteristic was supplied illegal value: number 1141 exceeded maximum of 1000.
```

### Configuration

```json
Not specifically applicable

Plugin is homebridge-sensibo-ac

Temporary artificial max of 1000 has been implemented to suppress warning
```

### Environment

- OS: RaspPi
- Software: Homebridge v1.6.0
- Node: v16.18.1
- npm: 8.19.2

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
@benwebbbenwebb That file is generated from the HomeKit Simulator files supplied by Apple as part of the HomeKit development environment, so we can not change it.  

https://github.com/homebridge/HAP-NodeJS/blob/e39faf0358909e2525bd91a2746fceb68fa0274d/src/lib/definitions/CharacteristicDefinitions.ts#L1
