### ISSUE TITLE
Interpreting Siri Commands

### ISSUE THREAD

**Issue by ahnyerkeester** [homebridge/HAP-NodeJS#999]
### Current Situation

I have a project, a fan, that I created a few years ago under the previous version of HAP-NodeJS and it works. For example, I can say "Set the fan to high" and it just does it. I have an accessory execute a Python script I wrote with an argument for the fan speed.

I decided to reconstitute the project with everything updated, including HAP-NodeJS. The biggest part of that update was pretty much rewriting my fan accessory from scratch. I based it on the Lightbulb example provided. It works when I use the tile in the Home app but Siri seems to be confused. When I say "Set the fan to high" it sometimes just sends the on command and sometimes set it to low or just does do anything. I've been over the code repeatedly and I can't see anything I've missed. Any insights would be appreciated

There are no errors produced, it just doesn't work with Siri. Here's the accessory:

```
var cmd = require('node-cmd');

const hap = require("hap-nodejs");

const Accessory = hap.Accessory;
const Characteristic = hap.Characteristic;
const CharacteristicEventTypes = hap.CharacteristicEventTypes;
const Service = hap.Service;

// optionally set a different storage location with code below
// hap.HAPStorage.setCustomStoragePath("...");

const accessoryUuid = hap.uuid.generate("hap.swamp.cooler");
const accessory = new Accessory("Swamp Cooler", accessoryUuid);

const fanService = new Service.Fan("Swamp Cooler");
let currentFanState = false; // on or off
//let currentFanState = 0; // on or off
let currentSpeed = 0;

// 'On' characteristic is required for the fan service

const onCharacteristic = fanService.getCharacteristic(Characteristic.On);

// 'RotationSpeed' characteristic is optional for the fan service;
// 'getCharacteristic' will automatically add it to the service!

const speedCharacteristic = fanService.getCharacteristic(Characteristic.RotationSpeed);

// with the 'on' function we can add event handlers for different
// events, mainly the 'get' and 'set' event
// The 'get' is called whenever a HomeKit controller request the
// current value of the characteristic.

onCharacteristic.on(CharacteristicEventTypes.GET, callback => {
  console.log("Queried current fan state: " + currentFanState);
  callback(undefined, currentFanState);
});

onCharacteristic.on(CharacteristicEventTypes.SET, (value, callback) => {
  console.log("Setting fan state to: " + value);
  currentFanState = value;
  callback();
});

speedCharacteristic.on(CharacteristicEventTypes.GET, (callback) => {
  console.log("Queried current speed level: " + currentSpeed);
  callback(undefined, currentSpeed);
});

speedCharacteristic.on(CharacteristicEventTypes.SET, (value, callback) => {
      console.log("speedCharacteristic.on(CharacteristicEventTypes.SET, (value =" + value);
      if (value >= 1 && value <= 33) {
      // First third is low
      speedtxt = "low";}

      else if (value > 33 && value <= 66) {
      // Second third is medium
      speedtxt = "med";}

      else if (value > 66 && value <= 100) {
      // Top third is high
      speedtxt="hi";}

      else {
      // < 1 or > 100 is off
      speedtxt="off";}

  thecmd = 'sudo python /home/pi/python/HAPSpeed.py '+speedtxt
  console.log("Sending: " + thecmd);
  cmd.run(thecmd);
  currentSpeed = value;
  callback();
});

 // adding the service to the accessory
accessory.addService(fanService);

// once everything is set up, we publish the accessory.
// Publish should always be the last step!

accessory.publish({
  username: "1A:2B:CC:17:01:FF",
  pincode: "031-45-154",
//  port: 47129,
  category: hap.Categories.FAN, // value here defines the symbol shown in the pairing screen
});

console.log("Accessory setup finished! Listening now...");
```

### Logs

```markdown
Here's a typical log output of a test run:

Accessory setup finished! Listening now...
Queried current fan state: 0
Queried current speed level: 0
Queried current fan state: 0
Setting fan state to: true
Setting fan state to: false
Queried current fan state: false
Queried current speed level: 0
speedCharacteristic.on(CharacteristicEventTypes.SET, (value =53
Sending: sudo python /home/pi/python/HAPSpeed.py med
Setting fan state to: true
speedCharacteristic.on(CharacteristicEventTypes.SET, (value =52
Sending: sudo python /home/pi/python/HAPSpeed.py med
Queried current fan state: true
Queried current speed level: 52
Queried current fan state: true
Queried current speed level: 52
Queried current speed level: 52
Queried current fan state: true
Queried current speed level: 52
Queried current fan state: true
Queried current fan state: true
```

### Configuration

```json
hap-nodejs package.json:

{
  "name": "hap-nodejs",
  "version": "0.11.0",
  "description": "HAP-NodeJS is a Node.js implementation of HomeKit Accessory Server.",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "maintainers": [
    "Andreas Bauer <mail@anderl-bauer.de>"
  ],
  "author": "Khaos Tian <khaos.tian@gmail.com> (https://tz.is/)",
  "homepage": "https://github.com/homebridge/HAP-NodeJS",
  "license": "Apache-2.0",
  "scripts": {
    "clean": "rimraf dist && rimraf coverage",
    "lint": "eslint 'src/**/*.{js,ts,json}'",
    "build": "rimraf dist && tsc && node .github/node-persist-ignore.js",
    "prepublishOnly": "npm run build",
    "postpublish": "npm run clean",
    "test": "jest",
    "test-coverage": "jest --coverage",
    "start": "node dist/BridgedCore.js",
    "docs": "typedoc",
    "lint-docs": "typedoc --emit none --treatWarningsAsErrors"
  },
  "keywords": [
    "hap-nodejs",
    "hap",
    "homekit",
    "homekit-accessory-protocol",
    "homekit-server",
    "homekit-protocol",
    "homekit-device",
    "homekit-accessory",
    "hap-server",
    "homekit-support",
    "siri"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/homebridge/HAP-NodeJS.git"
  },
  "bugs": {
    "url": "https://github.com/homebridge/HAP-NodeJS/issues"
  },
  "engines": {
    "node": ">=10.17.0"
  },
  "files": [
    "README.md",
    "LICENSE",
    "dist",
    "@types"
  ],
  "dependencies": {
    "@homebridge/ciao": "^1.1.5",
    "@homebridge/dbus-native": "^0.5.0",
    "bonjour-hap": "~3.6.4",
    "debug": "^4.3.4",
    "fast-srp-hap": "~2.0.4",
    "futoin-hkdf": "~1.4.3",
    "node-persist": "^0.0.11",
    "source-map-support": "^0.5.21",
    "tslib": "^2.4.0",
    "tweetnacl": "^1.0.3"
  },
  "devDependencies": {
    "@types/debug": "^4.1.7",
    "@types/escape-html": "^1.0.2",
    "@types/jest": "^27.4.1",
    "@types/node": "^10.17.60",
    "@typescript-eslint/eslint-plugin": "^5.21.0",
    "@typescript-eslint/parser": "^5.21.0",
    "commander": "^6.2.1",
    "escape-html": "^1.0.3",
    "http-parser-js": "^0.5.8",
    "eslint": "^8.14.0",
    "jest": "^27.5.1",
    "rimraf": "^3.0.2",
    "semver": "^7.3.7",
    "simple-plist": "1.1.1",
    "ts-jest": "^27.1.4",
    "ts-node": "^10.7.0",
    "typedoc": "^0.23.21",
    "typescript": "~4.9.3",
    "axios": "^0.27.2"
  }
}
```

### Environment

- OS: Raspbian GNU/Linux 11 (bullseye)
- Software:
- Node: v12.22.12
- npm: 7.5.2

### Process Supervisor

init-d

**Comment by NorthernMan54** [comment]
If you enable debug ie `DEBUG=* node  yourprogram.js` you can see what was passed into HAP-NodeJS.  And use this to further determine if the issue is with Siri, or your program.

**Comment by ahnyerkeester** [comment]
Aren't I kind of doing that with statements in the code like:
`console.log("speedCharacteristic.on(CharacteristicEventTypes.SET, (value =" + value);`
and
`console.log("Sending: " + thecmd);`?

Running DEBUG gives a lot more info but none of it really helpful.
When I say "Set the fan to medium" it works.
When I say "Set the fan to high" it says "the fan failed to respond" and I get no commands
When I say "Set the fan to low" it either turns if off or says "OK. To which value?" or occasionally it works.
If I say "set the fan speed to 100" it works, it sets it to high.

I can see what Siri is sending but I'm not sure why she can't understand "Set the fan to high". Did I define the service incorrectly or something? Did HomeKit change something important?

**Comment by NorthernMan54** [comment]
> Did I define the service incorrectly or something?

Your code looks appropriate

>  Did HomeKit change something important?

The API used by HAP-NodeJS has not been changed by Apple in a long time.

Take some time and get familiar with the DEBUG options, and how to tune the amount of detail logged.

Take this use case for example, and look and see what is being sent in the DEBUG log from Siri.   Is your python program too slow, and maybe remove it from the equation

> When I say "Set the fan to high" it says "the fan failed to respond" and I get no commands

**Comment by ahnyerkeester** [comment]
> Is your python program too slow, and maybe remove it from the equation

Good question, no the python code HAP-NodeJS runs is very short. It just gathers the incoming command and then sends it to the main code running the fan.

> > Did I define the service incorrectly or something?
> 
> Your code looks appropriate
> 
> > Did HomeKit change something important?
> 
> The API used by HAP-NodeJS has not been changed by Apple in a long time.

Thanks, that's helpful. I felt blind in that area like I might be missing something.

> Take some time and get familiar with the DEBUG options, and how to tune the amount of detail logged.
> 
> Take this use case for example, and look and see what is being sent in the DEBUG log from Siri.

I will do that. The more information the better so I can try to find the problem.

**Comment by NorthernMan54** [comment]
BTW, I just tested Siri with my fans and the wording

Hey Siri, turn east bedroom fan to high

and it worked correctly

Please keep in mind that you will receive two almost simultaneous events for each command, one to turn on, and one for the speed.

**Comment by ahnyerkeester** [comment]
Yes, I see the two commands. I might change the name of the accessory from "swamp cooler" and see if that makes a difference.

Currently looking very closely at the debug output. I might fire up the old one and see what that debug output looks like.

**Comment by ahnyerkeester** [comment]
Just booted up the old version which used to work fine and it is doing the same thing. So I think my implementation is good, something changed on my network that is causing problems.

Thanks again for your help. You gave me enough confidence to fire up the old one and that explained a lot.
